1516X High Stakes: Miscellaneous C++ API
Miscellaneous C++ API
Classes
class pros::v5::Controller
Functions
pros::v5::Controller::Controller (controller_id_e_t id)
std::int32_t pros::v5::Controller::is_connected (void)
std::int32_t pros::v5::Controller::get_analog (controller_analog_e_t channel)
std::int32_t pros::v5::Controller::get_battery_capacity (void)
std::int32_t pros::v5::Controller::get_battery_level (void)
std::int32_t pros::v5::Controller::get_digital (controller_digital_e_t button)
std::int32_t pros::v5::Controller::get_digital_new_press (controller_digital_e_t button)
template<typename T >
T pros::v5::Controller::convert_args (T arg)
const char * pros::v5::Controller::convert_args (const std::string &arg)
template<typename... Params>
std::int32_t pros::v5::Controller::print (std::uint8_t line, std::uint8_t col, const char *fmt, Params... args)
std::int32_t pros::v5::Controller::set_text (std::uint8_t line, std::uint8_t col, const char *str)
std::int32_t pros::v5::Controller::set_text (std::uint8_t line, std::uint8_t col, const std::string &str)
std::int32_t pros::v5::Controller::clear_line (std::uint8_t line)
std::int32_t pros::v5::Controller::rumble (const char *rumble_pattern)
std::int32_t pros::v5::Controller::clear (void)
double pros::battery::get_capacity (void)
int32_t pros::battery::get_current (void)
double pros::battery::get_temperature (void)
int32_t pros::battery::get_voltage (void)
Variables
controller_id_e_t pros::v5::Controller::_id
Detailed Description
Note
Additional example code for this module can be found in its Tutorial.
///
///
Function Documentation
Controller()
pros::v5::Controller::Controller (controller_id_e_t id) explicit
#include <include/pros/misc.hpp>
Creates a controller object for the given controller id.
Parameters
id The ID of the controller (e.g. the master or partner controller). Must be one of CONTROLLER_MASTER or CONTROLLER_PARTNER
clear()
std::int32_t pros::v5::Controller::clear (void)
#include <include/pros/misc.hpp>
Clears all of the lines on the controller screen.
Note
Controller text setting is currently in beta, so continuous, fast updates will not work well. On vexOS version 1.0.0 this function will block for 110ms.
This function uses the following values of errno when an error state is reached: EACCES - Another resource is currently trying to access the controller port.
Returns
1 if the operation was successful or PROS_ERR if the operation failed, setting errno.
Example
void opcontrol() {
    pros::Controller master(pros::E_CONTROLLER_MASTER);
  master.set_text(0, 0, "Example");
  delay(100);
  master.clear();
}
clear_line()
std::int32_t pros::v5::Controller::clear_line (std::uint8_t line)
#include <include/pros/misc.hpp>
Clears an individual line of the controller screen.
Note
Controller text setting is currently in beta, so continuous, fast updates will not work well.
This function uses the following values of errno when an error state is reached: EACCES - Another resource is currently trying to access the controller port.
Parameters
line The line number to clear [0-2]
Returns
1 if the operation was successful or PROS_ERR if the operation failed, setting errno.
Example
void opcontrol() {
  pros::Controller master(pros::E_CONTROLLER_MASTER);
  master.set_text(0, 0, "Example");
  delay(100);
  master.clear_line(0);
}
convert_args() [1/2]
const char * pros::v5::Controller::convert_args (const std::string & arg) inline
#include <include/pros/misc.hpp>
Definition at line 220 of file misc.hpp.
{
      return arg.c_str();
   }
convert_args() [2/2]
template<typename T > T pros::v5::Controller::convert_args (T arg) inline
#include <include/pros/misc.hpp>
Definition at line 217 of file misc.hpp.
{
      return arg;
   }
Referenced by pros::v5::Controller::print().
get_analog()
std::int32_t pros::v5::Controller::get_analog (controller_analog_e_t channel)
#include <include/pros/misc.hpp>
Gets the value of an analog channel (joystick) on a controller.
This function uses the following values of errno when an error state is reached: EACCES - Another resource is currently trying to access the controller port.
Parameters
channel The analog channel to get. Must be one of ANALOG_LEFT_X, ANALOG_LEFT_Y, ANALOG_RIGHT_X, ANALOG_RIGHT_Y
Returns
The current reading of the analog channel: [-127, 127]. If the controller was not connected, then 0 is returned
Example
void opcontrol() {
  pros::Controller master(pros::E_CONTROLLER_MASTER);
  while (true) {
    motor_move(1, master.get_analog(E_CONTROLLER_ANALOG_LEFT_Y));
    delay(2);
  }
}
Referenced by Robot::Drivetrain::ArcadeDrive(), Robot::Drivetrain::CurvatureDrive(), Robot::Drivetrain::CurveDrive(), and Robot::Drivetrain::TankDrive().
get_battery_capacity()
std::int32_t pros::v5::Controller::get_battery_capacity (void)
#include <include/pros/misc.hpp>
Gets the battery capacity of the controller.
This function uses the following values of errno when an error state is reached: EACCES - Another resource is currently trying to access the controller port.
Returns
The controller's battery capacity
Example
void initialize() {
  pros::Controller master(pros::E_CONTROLLER_MASTER);
  printf("Battery Capacity: %d\n", master.get_battery_capacity());
}
get_battery_level()
std::int32_t pros::v5::Controller::get_battery_level (void)
#include <include/pros/misc.hpp>
Gets the battery level of the controller.
This function uses the following values of errno when an error state is reached: EACCES - Another resource is currently trying to access the controller port.
Returns
The controller's battery level
Example
void initialize() {
    pros::Controller master(pros::E_CONTROLLER_MASTER);
  printf("Battery Level: %d\n", master.get_battery_level());
}
get_capacity()
double pros::battery::get_capacity (void)
#include <include/pros/misc.hpp>
Gets the current voltage of the battery, as reported by VEXos.
This function uses the following values of errno when an error state is reached: EACCES - Another resource is currently trying to access the battery port.
Returns
The current voltage of the battery
Example
void initialize() {
  printf("Battery Level: %.2f\n", get_capacity());
}
get_current()
int32_t pros::battery::get_current (void)
#include <include/pros/misc.hpp>
Gets the current current of the battery in milliamps, as reported by VEXos.
This function uses the following values of errno when an error state is reached: EACCES - Another resource is currently trying to access the battery port.
Returns
The current current of the battery
Example
void initialize() {
  printf("Battery Current: %d\n", get_current());
}
get_digital()
std::int32_t pros::v5::Controller::get_digital (controller_digital_e_t button)
#include <include/pros/misc.hpp>
Checks if a digital channel (button) on the controller is currently pressed.
This function uses the following values of errno when an error state is reached: EACCES - Another resource is currently trying to access the controller port.
Parameters
button The button to read. Must be one of DIGITAL_{RIGHT,DOWN,LEFT,UP,A,B,Y,X,R1,R2,L1,L2}
Returns
1 if the button on the controller is pressed. If the controller was not connected, then 0 is returned
Example
void opcontrol() {
  pros::Controller master(pros::E_CONTROLLER_MASTER);
  while (true) {
  if (master.get_digital(pros::E_CONTROLLER_DIGITAL_A)) {
    motor_set(1, 100);
  }
  else {
    motor_set(1, 0);
  }
    delay(2);
  }
}
Referenced by Robot::Intake::run().
get_digital_new_press()
std::int32_t pros::v5::Controller::get_digital_new_press (controller_digital_e_t button)
#include <include/pros/misc.hpp>
Returns a rising-edge case for a controller button press.
This function is not thread-safe. Multiple tasks polling a single button may return different results under the same circumstances, so only one task should call this function for any given button. E.g., Task A calls this function for buttons 1 and 2. Task B may call this function for button 3, but should not for buttons 1 or 2. A typical use-case for this function is to call inside opcontrol to detect new button presses, and not in any other tasks.
This function uses the following values of errno when an error state is reached: EACCES - Another resource is currently trying to access the controller port.
Parameters
button The button to read. Must be one of DIGITAL_{RIGHT,DOWN,LEFT,UP,A,B,Y,X,R1,R2,L1,L2}
Returns
1 if the button on the controller is pressed and had not been pressed the last time this function was called, 0 otherwise.
Example
void opcontrol() {
   pros::Controller master(pros::E_CONTROLLER_MASTER);
   while (true) {
  if (master.get_digital_new_press(pros::E_CONTROLLER_DIGITAL_A)) {
    // Toggle pneumatics or other similar actions
  }
  delay(2);
  }
}
Referenced by opcontrol(), Robot::Latch::run(), and toggles().
get_temperature()
double pros::battery::get_temperature (void)
#include <include/pros/misc.hpp>
Gets the current temperature of the battery, as reported by VEXos.
This function uses the following values of errno when an error state is reached: EACCES - Another resource is currently trying to access the battery port.
Returns
The current temperature of the battery
Example
void initialize() {
  printf("Battery's Temperature: %.2f\n", get_temperature());
}
get_voltage()
int32_t pros::battery::get_voltage (void)
#include <include/pros/misc.hpp>
Gets the current capacity of the battery in millivolts, as reported by VEXos.
This function uses the following values of errno when an error state is reached: EACCES - Another resource is currently trying to access the battery port.
Returns
The current capacity of the battery
Example
void initialize() {
  printf("Battery's Voltage: %d\n", get_voltage());
}
is_connected()
std::int32_t pros::v5::Controller::is_connected (void)
#include <include/pros/misc.hpp>
Checks if the controller is connected.
This function uses the following values of errno when an error state is reached: EACCES - Another resource is currently trying to access the controller port.
Returns
1 if the controller is connected, 0 otherwise
Example
void status_display_controller(){
  pros::Controller master(pros::E_CONTROLLER_MASTER);
  if(!master.is_connected()) {
      pros::lcd::print(0, "Main controller is not connected!");
  }
}
print()
template<typename... Params> std::int32_t pros::v5::Controller::print (std::uint8_t line, std::uint8_t col, const char * fmt, Params... args) inline
#include <include/pros/misc.hpp>
Sets text to the controller LCD screen.
Note
Controller text setting is currently in beta, so continuous, fast updates will not work well.
This function uses the following values of errno when an error state is reached: EACCES - Another resource is currently trying to access the controller port.
Parameters
line The line number at which the text will be displayed [0-2]
col The column number at which the text will be displayed [0-14]
fmt The format string to print to the controller
... The argument list for the format string
Returns
1 if the operation was successful or PROS_ERR if the operation failed, setting errno.
Example
void opcontrol() {
  int count = 0;
    pros::Controller master(pros::E_CONTROLLER_MASTER);
  while (true) {
  if (!(count % 25)) {
    // Only print every 50ms, the controller text update rate is slow
    master.print(0, 0, "Counter: %d", count);
  }
    count++;
    delay(2);
  }
}
Definition at line 265 of file misc.hpp.
{
      return pros::c::controller_print(_id, line, col, fmt, convert_args(args)...);
   }
References pros::v5::Controller::_id, and pros::v5::Controller::convert_args().
Referenced by opcontrol().
rumble()
std::int32_t pros::v5::Controller::rumble (const char * rumble_pattern)
#include <include/pros/misc.hpp>
Rumble the controller.
Note
Controller rumble activation is currently in beta, so continuous, fast updates will not work well.
This function uses the following values of errno when an error state is reached: EACCES - Another resource is currently trying to access the controller port.
Parameters
rumble_pattern A string consisting of the characters '.', '-', and ' ', where dots are short rumbles, dashes are long rumbles, and spaces are pauses. Maximum supported length is 8 characters.
Returns
1 if the operation was successful or PROS_ERR if the operation failed, setting errno.
Example
void opcontrol() {
  int count = 0;
  pros::Controller master(pros::E_CONTROLLER_MASTER);
  while (true) {
  if (!(count % 25)) {
    // Only send every 50ms, the controller update rate is slow
    master.rumble(". - . -");
  }
  count++;
  delay(2);
  }
}
set_text() [1/2]
std::int32_t pros::v5::Controller::set_text (std::uint8_t line, std::uint8_t col, const char * str)
#include <include/pros/misc.hpp>
Sets text to the controller LCD screen.
Note
Controller text setting is currently in beta, so continuous, fast updates will not work well.
This function uses the following values of errno when an error state is reached: EACCES - Another resource is currently trying to access the controller port.
Parameters
line The line number at which the text will be displayed [0-2]
col The column number at which the text will be displayed [0-14]
str The pre-formatted string to print to the controller
Returns
1 if the operation was successful or PROS_ERR if the operation failed, setting errno.
Example
void opcontrol() {
  int count = 0;
  pros::Controller master(pros::E_CONTROLLER_MASTER);
  while (true) {
    if (!(count % 25)) {
      // Only print every 50ms, the controller text update rate is slow
      master.set_text(0, 0, "Example text");
    }
  count++;
  delay(2);
  }
}
set_text() [2/2]
std::int32_t pros::v5::Controller::set_text (std::uint8_t line, std::uint8_t col, const std::string & str)
#include <include/pros/misc.hpp>
Variable Documentation
_id
controller_id_e_t pros::v5::Controller::_id private
Definition at line 403 of file misc.hpp.
Referenced by pros::v5::Controller::print().