1516X High Stakes: fmt::v10::detail::arg_mapper< Context > Struct Template Reference
fmt::v10::detail::arg_mapper< Context > Struct Template Reference
#include <core.h>
Classes
struct formattable
Public Types
using char_type = typename Context::char_type
Public Member Functions
auto map (signed char val) -> int
auto map (unsigned char val) -> unsigned
auto map (short val) -> int
auto map (unsigned short val) -> unsigned
auto map (int val) -> int
auto map (unsigned val) -> unsigned
auto map (long val) -> long_type
auto map (unsigned long val) -> ulong_type
auto map (long long val) -> long long
auto map (unsigned long long val) -> unsigned long long
auto map (int128_opt val) -> int128_opt
auto map (uint128_opt val) -> uint128_opt
auto map (bool val) -> bool
template<typename T , fmt::enable_if_t<(std::is_same< T, char >::value||std::is_same< T, char_type >::value), int > = 0>
auto map (T val) -> char_type
template<typename T , enable_if_t<(std::is_same< T, wchar_t >::value||std::is_same< T, char16_t >::value||std::is_same< T, char32_t >::value) &&!std::is_same< T, char_type >::value, int > = 0>
auto map (T) -> unformattable_char
auto map (float val) -> float
auto map (double val) -> double
auto map (long double val) -> long double
auto map (char_type *val) -> const char_type *
auto map (const char_type *val) -> const char_type *
template<typename T , fmt::enable_if_t<(is_string< T >::value &&!std::is_pointer< T >::value &&std::is_same< char_type, char_t< T > >::value), int > = 0>
auto map (const T &val) -> basic_string_view< char_type >
template<typename T , fmt::enable_if_t<(is_string< T >::value &&!std::is_pointer< T >::value &&!std::is_same< char_type, char_t< T > >::value), int > = 0>
auto map (const T &) -> unformattable_char
auto map (void *val) -> const void *
auto map (const void *val) -> const void *
auto map (std::nullptr_t val) -> const void *
template<typename T , fmt::enable_if_t<(std::is_pointer< T >::value||std::is_member_pointer< T >::value||std::is_function< typename std::remove_pointer< T >::type >::value||(std::is_array< T >::value &&!std::is_convertible< T, const char_type * >::value)), int > = 0>
auto map (const T &) -> unformattable_pointer
template<typename T , std::size_t N, fmt::enable_if_t<(!std::is_same< T, wchar_t >::value), int > = 0>
auto map (const T(&values)[N]) -> const T(&)[N]
template<typename T , typename U = format_as_t<T>, fmt::enable_if_t<(std::is_arithmetic< U >::value), int > = 0>
auto map (const T &val) -> decltype(this->map(U()))
template<typename T , fmt::enable_if_t<(formattable< T >::value), int > = 0>
auto do_map (T &val) -> T &
template<typename T , fmt::enable_if_t<(!formattable< T >::value), int > = 0>
auto do_map (T &) -> unformattable
template<typename T , typename U = remove_const_t<T>, fmt::enable_if_t<((std::is_class< U >::value||std::is_enum< U >::value||std::is_union< U >::value) &&!is_string< U >::value &&!is_char< U >::value &&!is_named_arg< U >::value &&!std::is_arithmetic< format_as_t< U > >::value), int > = 0>
auto map (T &val) -> decltype(this->do_map(val))
template<typename T , fmt::enable_if_t<(is_named_arg< T >::value), int > = 0>
auto map (const T &named_arg) -> decltype(this->map(named_arg.value))
auto map (...) -> unformattable
Detailed Description
template<typename Context>
struct fmt::v10::detail::arg_mapper< Context >
Definition at line 1260 of file core.h.
Member Typedef Documentation
char_type
template<typename Context > using fmt::v10::detail::arg_mapper< Context >::char_type = typename Context::char_type
Definition at line 1261 of file core.h.
Member Function Documentation
do_map() [1/2]
template<typename Context > template<typename T , fmt::enable_if_t<(!formattable< T >::value), int > = 0> auto fmt::v10::detail::arg_mapper< Context >::do_map (T &) -> unformattable inline
Definition at line 1362 of file core.h.
{
            return {};
        }
do_map() [2/2]
template<typename Context > template<typename T , fmt::enable_if_t<(formattable< T >::value), int > = 0> auto fmt::v10::detail::arg_mapper< Context >::do_map (T & val) -> T& inline
Definition at line 1358 of file core.h.
{
            return val;
        }
map() [1/31]
template<typename Context > auto fmt::v10::detail::arg_mapper< Context >::map (...) -> unformattable inline
Definition at line 1380 of file core.h.
{ return {}; }
map() [2/31]
template<typename Context > auto fmt::v10::detail::arg_mapper< Context >::map (bool val) -> bool inline
Definition at line 1287 of file core.h.
{ return val; }
map() [3/31]
template<typename Context > auto fmt::v10::detail::arg_mapper< Context >::map (char_type * val) -> const char_type* inline
Definition at line 1311 of file core.h.
{ return val; }
map() [4/31]
template<typename Context > auto fmt::v10::detail::arg_mapper< Context >::map (const char_type * val) -> const char_type* inline
Definition at line 1313 of file core.h.
{ return val; }
map() [5/31]
template<typename Context > template<typename T , fmt::enable_if_t<(is_string< T >::value &&!std::is_pointer< T >::value &&!std::is_same< char_type, char_t< T > >::value), int > = 0> auto fmt::v10::detail::arg_mapper< Context >::map (const T &) -> unformattable_char inline
Definition at line 1323 of file core.h.
{
            return {};
        }
map() [6/31]
template<typename Context > template<typename T , fmt::enable_if_t<(std::is_pointer< T >::value||std::is_member_pointer< T >::value||std::is_function< typename std::remove_pointer< T >::type >::value||(std::is_array< T >::value &&!std::is_convertible< T, const char_type * >::value)), int > = 0> auto fmt::v10::detail::arg_mapper< Context >::map (const T &) -> unformattable_pointer inline
Definition at line 1339 of file core.h.
{
            return {};
        }
map() [7/31]
template<typename Context > template<typename T , fmt::enable_if_t<(is_named_arg< T >::value), int > = 0> auto fmt::v10::detail::arg_mapper< Context >::map (const T & named_arg) -> decltype(this->map(named_arg.value)) inline
Definition at line 1376 of file core.h.
{
            return map(named_arg.value);
        }
References fmt::v10::detail::named_arg< Char, T >::value.
map() [8/31]
template<typename Context > template<typename T , fmt::enable_if_t<(is_string< T >::value &&!std::is_pointer< T >::value &&std::is_same< char_type, char_t< T > >::value), int > = 0> auto fmt::v10::detail::arg_mapper< Context >::map (const T & val) -> basic_string_view<char_type> inline
Definition at line 1317 of file core.h.
{
            return to_string_view(val);
        }
References fmt::v10::detail::to_string_view().
map() [9/31]
template<typename Context > template<typename T , typename U = format_as_t<T>, fmt::enable_if_t<(std::is_arithmetic< U >::value), int > = 0> auto fmt::v10::detail::arg_mapper< Context >::map (const T & val) -> decltype(this->map(U())) inline
Definition at line 1350 of file core.h.
{
            return map(format_as(val));
        }
map() [10/31]
template<typename Context > template<typename T , std::size_t N, fmt::enable_if_t<(!std::is_same< T, wchar_t >::value), int > = 0> auto fmt::v10::detail::arg_mapper< Context >::map (const T(&) values[N]) -> const T (&)[N] inline
Definition at line 1344 of file core.h.
{
            return values;
        }
map() [11/31]
template<typename Context > auto fmt::v10::detail::arg_mapper< Context >::map (const void * val) -> const void* inline
Definition at line 1329 of file core.h.
{ return val; }
map() [12/31]
template<typename Context > auto fmt::v10::detail::arg_mapper< Context >::map (double val) -> double inline
Definition at line 1307 of file core.h.
{ return val; }
map() [13/31]
template<typename Context > auto fmt::v10::detail::arg_mapper< Context >::map (float val) -> float inline
Definition at line 1305 of file core.h.
{ return val; }
map() [14/31]
template<typename Context > auto fmt::v10::detail::arg_mapper< Context >::map (int val) -> int inline
Definition at line 1271 of file core.h.
{ return val; }
map() [15/31]
template<typename Context > auto fmt::v10::detail::arg_mapper< Context >::map (int128_opt val) -> int128_opt inline
Definition at line 1283 of file core.h.
{ return val; }
map() [16/31]
template<typename Context > auto fmt::v10::detail::arg_mapper< Context >::map (long double val) -> long double inline
Definition at line 1309 of file core.h.
{ return val; }
map() [17/31]
template<typename Context > auto fmt::v10::detail::arg_mapper< Context >::map (long long val) -> long long inline
Definition at line 1279 of file core.h.
{ return val; }
map() [18/31]
template<typename Context > auto fmt::v10::detail::arg_mapper< Context >::map (long val) -> long_type inline
Definition at line 1275 of file core.h.
{ return val; }
map() [19/31]
template<typename Context > auto fmt::v10::detail::arg_mapper< Context >::map (short val) -> int inline
Definition at line 1267 of file core.h.
{ return val; }
map() [20/31]
template<typename Context > auto fmt::v10::detail::arg_mapper< Context >::map (signed char val) -> int inline
Definition at line 1263 of file core.h.
{ return val; }
Referenced by fmt::v10::detail::make_arg(), and fmt::v10::detail::parse_format_specs().
map() [21/31]
template<typename Context > auto fmt::v10::detail::arg_mapper< Context >::map (std::nullptr_t val) -> const void* inline
Definition at line 1331 of file core.h.
{ return val; }
map() [22/31]
template<typename Context > template<typename T , typename U = remove_const_t<T>, fmt::enable_if_t<((std::is_class< U >::value||std::is_enum< U >::value||std::is_union< U >::value) &&!is_string< U >::value &&!is_char< U >::value &&!is_named_arg< U >::value &&!std::is_arithmetic< format_as_t< U > >::value), int > = 0> auto fmt::v10::detail::arg_mapper< Context >::map (T & val) -> decltype(this->do_map(val)) inline
Definition at line 1371 of file core.h.
{
            return do_map(val);
        }
map() [23/31]
template<typename Context > template<typename T , fmt::enable_if_t<(std::is_same< T, char >::value||std::is_same< T, char_type >::value), int > = 0> auto fmt::v10::detail::arg_mapper< Context >::map (T val) -> char_type inline
Definition at line 1290 of file core.h.
{
            return val;
        }
map() [24/31]
template<typename Context > template<typename T , enable_if_t<(std::is_same< T, wchar_t >::value||std::is_same< T, char16_t >::value||std::is_same< T, char32_t >::value) &&!std::is_same< T, char_type >::value, int > = 0> auto fmt::v10::detail::arg_mapper< Context >::map (T) -> unformattable_char inline
Definition at line 1301 of file core.h.
{
            return {};
        }
map() [25/31]
template<typename Context > auto fmt::v10::detail::arg_mapper< Context >::map (uint128_opt val) -> uint128_opt inline
Definition at line 1285 of file core.h.
{ return val; }
map() [26/31]
template<typename Context > auto fmt::v10::detail::arg_mapper< Context >::map (unsigned char val) -> unsigned inline
Definition at line 1265 of file core.h.
{ return val; }
map() [27/31]
template<typename Context > auto fmt::v10::detail::arg_mapper< Context >::map (unsigned long long val) -> unsigned long long inline
Definition at line 1281 of file core.h.
{ return val; }
map() [28/31]
template<typename Context > auto fmt::v10::detail::arg_mapper< Context >::map (unsigned long val) -> ulong_type inline
Definition at line 1277 of file core.h.
{ return val; }
map() [29/31]
template<typename Context > auto fmt::v10::detail::arg_mapper< Context >::map (unsigned short val) -> unsigned inline
Definition at line 1269 of file core.h.
{ return val; }
map() [30/31]
template<typename Context > auto fmt::v10::detail::arg_mapper< Context >::map (unsigned val) -> unsigned inline
Definition at line 1273 of file core.h.
{ return val; }
map() [31/31]
template<typename Context > auto fmt::v10::detail::arg_mapper< Context >::map (void * val) -> const void* inline
Definition at line 1327 of file core.h.
{ return val; }
The documentation for this struct was generated from the following file:
include/fmt/core.h