1516X High Stakes: Robot::Drivetrain Class Reference
Robot::Drivetrain Class Reference
Represents the drivetrain of the robot.
#include <drivetrain.h>
Public Member Functions
void run ()
Runs the drivetrain.
void setdeadzone (int newDeadZone)
Sets the joystick deadzone.
int getdeadzone ()
Returns the current deadzone value.
std::string toggleDrive ()
Drivetrain ()
Initializes the Drivetrain object.
Static Public Member Functions
static std::string SwitchDrive (int drive)
Switches the DriveTrain mode between arcade and tank drive.
Static Public Attributes
static int driveNum = 0
Private Member Functions
void ArcadeDrive ()
Drives the robot using arcade drive.
void CurvatureDrive ()
Drives the robot using curvature drive.
void TankDrive ()
Drives the robot using tank drive.
void CurveDrive ()
Drives the robot using curve drive.
int CheckDeadzone (int entry)
Checks if the controller input is inside the deadzone range.
Private Attributes
int deadzone
The deadzone value for the joystick.
Detailed Description
Represents the drivetrain of the robot.
The Drivetrain class is responsible for controlling the movement of the robot's drivetrain. It provides functions to interpret joystick inputs and convert them into appropriate drivetrain movements. The drivetrain can be controlled using different drive modes, such as tank drive or arcade drive.
The Drivetrain class also allows setting and retrieving the deadzone value for the joystick. The deadzone is a range around the joystick's resting position where no movement is registered. By adjusting the deadzone value, the sensitivity of the joystick inputs can be fine-tuned.
Definition at line 24 of file drivetrain.h.
Constructor & Destructor Documentation
Drivetrain()
Drivetrain::Drivetrain ()
Initializes the Drivetrain object.
This constructor is responsible for initializing the Drivetrain object and setting default values.
Definition at line 42 of file drivetrain.cpp.
{}
Member Function Documentation
ArcadeDrive()
void Drivetrain::ArcadeDrive () private
Drives the robot using arcade drive.
Arcade drive uses the left joystick for forward and backward movement, and the right joystick for left and right movement.
Definition at line 29 of file drivetrain.cpp.
{
  Drivetrain::deadzone = 5;
  // Arcade Measurements
  int left = controller.get_analog(pros::E_CONTROLLER_ANALOG_LEFT_Y);
  int right = controller.get_analog(pros::E_CONTROLLER_ANALOG_RIGHT_X);
  // std::abs takes the absolute value of whatever it is called on.
  // Thus, any values in range (-5,5) are discarded as 0.
  chassis.arcade(left, right, false, 0.6);
  pros::delay(15);
}
References Robot::Globals::chassis, Robot::Globals::controller, and deadzone.
Referenced by run().
CheckDeadzone()
int Drivetrain::CheckDeadzone (int entry) private
Checks if the controller input is inside the deadzone range.
Parameters
entry The controller input to check.
Returns
The input value if it is outside the deadzone range, otherwise 0.
Definition at line 9 of file drivetrain.cpp.
{
  if (std::abs(ControllerInput) < Drivetrain::deadzone) {
    return 0;
  } else {
    return ControllerInput;
  }
}
References deadzone.
Referenced by CurvatureDrive().
CurvatureDrive()
void Drivetrain::CurvatureDrive () private
Drives the robot using curvature drive.
Curvature drive applies curvature to turns and a negative inertia accumulator.
Definition at line 17 of file drivetrain.cpp.
{
  Drivetrain::deadzone = 5;
  int left = controller.get_analog(pros::E_CONTROLLER_ANALOG_LEFT_Y);
  int right = controller.get_analog(pros::E_CONTROLLER_ANALOG_RIGHT_X);
  left = CheckDeadzone(left);
  right = CheckDeadzone(right);
  chassis.curvature(left, right);
}
References Robot::Globals::chassis, CheckDeadzone(), Robot::Globals::controller, and deadzone.
Referenced by run().
CurveDrive()
void Drivetrain::CurveDrive () private
Drives the robot using curve drive.
Curve drive uses the left joystick for forward and backward movement, and the right joystick for steering.
Definition at line 57 of file drivetrain.cpp.
{
  Drivetrain::deadzone = 5;
  int left = controller.get_analog(pros::E_CONTROLLER_ANALOG_LEFT_Y);
  int right = controller.get_analog(pros::E_CONTROLLER_ANALOG_RIGHT_X);
  // std::abs takes the absolute value of whatever it is called on.
  // Thus, any values in range (-5,5) are discarded as 0.
  chassis.curvature(left, right);
  pros::delay(15);
}
References Robot::Globals::chassis, Robot::Globals::controller, and deadzone.
getdeadzone()
int Robot::Drivetrain::getdeadzone ()
Returns the current deadzone value.
Returns
The deadzone value.
The deadzone is a range around the joystick's resting position where no movement is registered. This function returns the current deadzone value that is being used by the drivetrain.
The deadzone value can be used to fine-tune the drivetrain's responsiveness to joystick inputs. By retrieving the current deadzone value, you can adjust other parts of your code to take it into account.
run()
void Drivetrain::run ()
Runs the drivetrain.
This function is responsible for controlling the movement of the robot's drivetrain. It executes the necessary actions to make the robot move according to the current drive mode.
The drivetrain can be controlled using different drive modes, such as tank drive or arcade drive. This function implements the logic to interpret the joystick inputs and convert them into appropriate drivetrain movements.
Definition at line 77 of file drivetrain.cpp.
                     {
  if (Drivetrain::driveNum == 0) {
    Drivetrain::CurvatureDrive();
  }
  if (Drivetrain::driveNum == 1) {
    Drivetrain::ArcadeDrive();
  }
  if (Drivetrain::driveNum == 2) {
    Drivetrain::TankDrive();
  }
}
References ArcadeDrive(), CurvatureDrive(), driveNum, and TankDrive().
Referenced by opcontrol().
setdeadzone()
void Robot::Drivetrain::setdeadzone (int newDeadZone)
Sets the joystick deadzone.
Parameters
newDeadZone The new deadzone value.
The deadzone is a range around the joystick's resting position where no movement is registered. This function allows you to set the deadzone value to filter out small joystick movements.
The deadzone value determines the sensitivity of the joystick inputs. A higher deadzone value will require larger joystick movements to register any movement in the drivetrain. Conversely, a lower deadzone value will make the drivetrain more responsive to small joystick movements.
SwitchDrive()
std::string Drivetrain::SwitchDrive (int drive) static
Switches the DriveTrain mode between arcade and tank drive.
The drive mode determines how the drivetrain interprets the joystick inputs. Arcade drive uses the left joystick for forward and backward movement, and the right joystick for left and right movement. Tank drive uses the left and right joysticks for controlling the left and right sides of the robot. < The current drive train mode, between arcade (0) and tank (1).
Switches the drive mode of the robot.
This function takes an integer parameter drive representing the desired drive mode and returns a string. The drive mode determines how the robot's drivetrain operates.
Parameters
drive The desired drive mode.
Returns
A string indicating the name of the drive mode switch.
Definition at line 99 of file drivetrain.cpp.
{
  Drivetrain::driveNum = drive;
  // Return the name of the drive mode
  if (Drivetrain::driveNum == 0) {
    std::cout << "Curvature Drive" << std::endl;
    return "Curvature Drive";
  }
  if (Drivetrain::driveNum == 1) {
    std::cout << "Arcade Drive" << std::endl;
    return "Arcade Drive";
  }
  if (Drivetrain::driveNum == 2) {
    std::cout << "Tank Drive" << std::endl;
    return "Tank Drive";
  } else {
    return "Error";
  }
}
References driveNum.
Referenced by drive_update(), and toggleDrive().
TankDrive()
void Drivetrain::TankDrive () private
Drives the robot using tank drive.
Tank drive uses the left and right joysticks for controlling the left and right sides of the robot.
Definition at line 44 of file drivetrain.cpp.
{
  Drivetrain::deadzone = 5;
  int left = controller.get_analog(pros::E_CONTROLLER_ANALOG_LEFT_Y);
  int right = controller.get_analog(pros::E_CONTROLLER_ANALOG_RIGHT_Y);
  // std::abs takes the absolute value of whatever it is called on.
  // Thus, any values in range (-5,5) are discarded as 0.
  chassis.tank(left, right);
  pros::delay(15);
}
References Robot::Globals::chassis, Robot::Globals::controller, and deadzone.
Referenced by run().
toggleDrive()
std::string Drivetrain::toggleDrive ()
Toggles the drive mode of the robot.
Returns
The new drive mode as a string.
Definition at line 89 of file drivetrain.cpp.
{
  Drivetrain::driveNum += 1;
  if (Drivetrain::driveNum > 2) {
    Drivetrain::driveNum = 0;
  }
  return SwitchDrive(Drivetrain::driveNum);
}
References driveNum, and SwitchDrive().
Referenced by opcontrol().
Member Data Documentation
deadzone
int Robot::Drivetrain::deadzone private
The deadzone value for the joystick.
Definition at line 140 of file drivetrain.h.
Referenced by ArcadeDrive(), CheckDeadzone(), CurvatureDrive(), CurveDrive(), and TankDrive().
driveNum
int Drivetrain::driveNum = 0 static
Definition at line 94 of file drivetrain.h.
Referenced by run(), SwitchDrive(), and toggleDrive().
The documentation for this class was generated from the following files:
include/robot/drivetrain.h
src/subsystems/drivetrain.cpp