1516X High Stakes: include/liblvgl/misc/lv_style.h File Reference
lv_style.h File Reference
#include <stdbool.h>
#include <stdint.h>
#include "liblvgl/font/lv_font.h"
#include "lv_color.h"
#include "lv_area.h"
#include "lv_anim.h"
#include "lv_txt.h"
#include "lv_types.h"
#include "lv_assert.h"
#include "lv_bidi.h"
#include "lv_style_gen.h"
Classes
struct lv_gradient_stop_t
struct lv_grad_dsc_t
union lv_style_value_t
struct lv_style_transition_dsc_t
struct lv_style_const_prop_t
struct lv_style_t
Macros
#define LV_STYLE_SENTINEL_VALUE 0xAABBCCDD
#define LV_STYLE_PROP_FLAG_NONE (0)
#define LV_STYLE_PROP_INHERIT (1 << 0) /*Inherited*/
#define LV_STYLE_PROP_EXT_DRAW (1 << 1) /*Requires ext. draw size update when changed*/
#define LV_STYLE_PROP_LAYOUT_REFR (1 << 2) /*Requires layout update when changed*/
#define LV_STYLE_PROP_PARENT_LAYOUT_REFR (1 << 3) /*Requires layout update on parent when changed*/
#define LV_STYLE_PROP_LAYER_REFR (1 << 4) /*Affects layer handling*/
#define LV_STYLE_PROP_ALL (0x1F) /*Indicating all flags*/
#define LV_IMG_ZOOM_NONE 256 /*Value for not zooming the image*/
#define LV_STYLE_CONST_INIT(var_name, prop_array)
#define LV_STYLE_PROP_META_INHERIT 0x8000
#define LV_STYLE_PROP_META_INITIAL 0x4000
#define LV_STYLE_PROP_META_MASK (LV_STYLE_PROP_META_INHERIT | LV_STYLE_PROP_META_INITIAL)
#define LV_STYLE_PROP_ID_MASK(prop) ((lv_style_prop_t)((prop) & ~LV_STYLE_PROP_META_MASK))
#define LV_ASSERT_STYLE(p) do{}while(0)
Typedefs
typedef uint8_t lv_blend_mode_t
typedef uint8_t lv_text_decor_t
typedef uint8_t lv_border_side_t
typedef uint8_t lv_grad_dir_t
typedef uint8_t lv_dither_mode_t
typedef uint8_t lv_style_res_t
Enumerations
enum {
LV_BLEND_MODE_NORMAL , LV_BLEND_MODE_ADDITIVE , LV_BLEND_MODE_SUBTRACTIVE , LV_BLEND_MODE_MULTIPLY ,
LV_BLEND_MODE_REPLACE
}
enum { LV_TEXT_DECOR_NONE = 0x00 , LV_TEXT_DECOR_UNDERLINE = 0x01 , LV_TEXT_DECOR_STRIKETHROUGH = 0x02 }
enum {
LV_BORDER_SIDE_NONE = 0x00 , LV_BORDER_SIDE_BOTTOM = 0x01 , LV_BORDER_SIDE_TOP = 0x02 , LV_BORDER_SIDE_LEFT = 0x04 ,
LV_BORDER_SIDE_RIGHT = 0x08 , LV_BORDER_SIDE_FULL = 0x0F , LV_BORDER_SIDE_INTERNAL = 0x10
}
enum { LV_GRAD_DIR_NONE , LV_GRAD_DIR_VER , LV_GRAD_DIR_HOR }
enum { LV_DITHER_NONE , LV_DITHER_ORDERED , LV_DITHER_ERR_DIFF }
enum lv_style_prop_t {
LV_STYLE_PROP_INV = 0 , LV_STYLE_WIDTH = 1 , LV_STYLE_MIN_WIDTH = 2 , LV_STYLE_MAX_WIDTH = 3 ,
LV_STYLE_HEIGHT = 4 , LV_STYLE_MIN_HEIGHT = 5 , LV_STYLE_MAX_HEIGHT = 6 , LV_STYLE_X = 7 ,
LV_STYLE_Y = 8 , LV_STYLE_ALIGN = 9 , LV_STYLE_LAYOUT = 10 , LV_STYLE_RADIUS = 11 ,
LV_STYLE_PAD_TOP = 16 , LV_STYLE_PAD_BOTTOM = 17 , LV_STYLE_PAD_LEFT = 18 , LV_STYLE_PAD_RIGHT = 19 ,
LV_STYLE_PAD_ROW = 20 , LV_STYLE_PAD_COLUMN = 21 , LV_STYLE_BASE_DIR = 22 , LV_STYLE_CLIP_CORNER = 23 ,
LV_STYLE_BG_COLOR = 32 , LV_STYLE_BG_OPA = 33 , LV_STYLE_BG_GRAD_COLOR = 34 , LV_STYLE_BG_GRAD_DIR = 35 ,
LV_STYLE_BG_MAIN_STOP = 36 , LV_STYLE_BG_GRAD_STOP = 37 , LV_STYLE_BG_GRAD = 38 , LV_STYLE_BG_DITHER_MODE = 39 ,
LV_STYLE_BG_IMG_SRC = 40 , LV_STYLE_BG_IMG_OPA = 41 , LV_STYLE_BG_IMG_RECOLOR = 42 , LV_STYLE_BG_IMG_RECOLOR_OPA = 43 ,
LV_STYLE_BG_IMG_TILED = 44 , LV_STYLE_BORDER_COLOR = 48 , LV_STYLE_BORDER_OPA = 49 , LV_STYLE_BORDER_WIDTH = 50 ,
LV_STYLE_BORDER_SIDE = 51 , LV_STYLE_BORDER_POST = 52 , LV_STYLE_OUTLINE_WIDTH = 53 , LV_STYLE_OUTLINE_COLOR = 54 ,
LV_STYLE_OUTLINE_OPA = 55 , LV_STYLE_OUTLINE_PAD = 56 , LV_STYLE_SHADOW_WIDTH = 64 , LV_STYLE_SHADOW_OFS_X = 65 ,
LV_STYLE_SHADOW_OFS_Y = 66 , LV_STYLE_SHADOW_SPREAD = 67 , LV_STYLE_SHADOW_COLOR = 68 , LV_STYLE_SHADOW_OPA = 69 ,
LV_STYLE_IMG_OPA = 70 , LV_STYLE_IMG_RECOLOR = 71 , LV_STYLE_IMG_RECOLOR_OPA = 72 , LV_STYLE_LINE_WIDTH = 73 ,
LV_STYLE_LINE_DASH_WIDTH = 74 , LV_STYLE_LINE_DASH_GAP = 75 , LV_STYLE_LINE_ROUNDED = 76 , LV_STYLE_LINE_COLOR = 77 ,
LV_STYLE_LINE_OPA = 78 , LV_STYLE_ARC_WIDTH = 80 , LV_STYLE_ARC_ROUNDED = 81 , LV_STYLE_ARC_COLOR = 82 ,
LV_STYLE_ARC_OPA = 83 , LV_STYLE_ARC_IMG_SRC = 84 , LV_STYLE_TEXT_COLOR = 85 , LV_STYLE_TEXT_OPA = 86 ,
LV_STYLE_TEXT_FONT = 87 , LV_STYLE_TEXT_LETTER_SPACE = 88 , LV_STYLE_TEXT_LINE_SPACE = 89 , LV_STYLE_TEXT_DECOR = 90 ,
LV_STYLE_TEXT_ALIGN = 91 , LV_STYLE_OPA = 96 , LV_STYLE_COLOR_FILTER_DSC = 97 , LV_STYLE_COLOR_FILTER_OPA = 98 ,
LV_STYLE_ANIM = 99 , LV_STYLE_ANIM_TIME = 100 , LV_STYLE_ANIM_SPEED = 101 , LV_STYLE_TRANSITION = 102 ,
LV_STYLE_BLEND_MODE = 103 , LV_STYLE_TRANSFORM_WIDTH = 104 , LV_STYLE_TRANSFORM_HEIGHT = 105 , LV_STYLE_TRANSLATE_X = 106 ,
LV_STYLE_TRANSLATE_Y = 107 , LV_STYLE_TRANSFORM_ZOOM = 108 , LV_STYLE_TRANSFORM_ANGLE = 109 , LV_STYLE_TRANSFORM_PIVOT_X = 110 ,
LV_STYLE_TRANSFORM_PIVOT_Y = 111 , _LV_STYLE_LAST_BUILT_IN_PROP = 111 , _LV_STYLE_NUM_BUILT_IN_PROPS = _LV_STYLE_LAST_BUILT_IN_PROP + 1 , LV_STYLE_PROP_ANY = 0xFFFF ,
_LV_STYLE_PROP_CONST = 0xFFFF
}
enum { LV_STYLE_RES_NOT_FOUND , LV_STYLE_RES_FOUND , LV_STYLE_RES_INHERIT }
Functions
void lv_style_init (lv_style_t *style)
void lv_style_reset (lv_style_t *style)
lv_style_prop_t lv_style_register_prop (uint8_t flag)
lv_style_prop_t lv_style_get_num_custom_props (void)
bool lv_style_remove_prop (lv_style_t *style, lv_style_prop_t prop)
void lv_style_set_prop (lv_style_t *style, lv_style_prop_t prop, lv_style_value_t value)
void lv_style_set_prop_meta (lv_style_t *style, lv_style_prop_t prop, uint16_t meta)
lv_style_res_t lv_style_get_prop (const lv_style_t *style, lv_style_prop_t prop, lv_style_value_t *value)
void lv_style_transition_dsc_init (lv_style_transition_dsc_t *tr, const lv_style_prop_t props[], lv_anim_path_cb_t path_cb, uint32_t time, uint32_t delay, void *user_data)
lv_style_value_t lv_style_prop_get_default (lv_style_prop_t prop)
static lv_style_res_t lv_style_get_prop_inlined (const lv_style_t *style, lv_style_prop_t prop, lv_style_value_t *value)
bool lv_style_is_empty (const lv_style_t *style)
uint8_t _lv_style_get_prop_group (lv_style_prop_t prop)
uint8_t _lv_style_prop_lookup_flags (lv_style_prop_t prop)
static void lv_style_set_size (lv_style_t *style, lv_coord_t value)
static void lv_style_set_pad_all (lv_style_t *style, lv_coord_t value)
static void lv_style_set_pad_hor (lv_style_t *style, lv_coord_t value)
static void lv_style_set_pad_ver (lv_style_t *style, lv_coord_t value)
static void lv_style_set_pad_gap (lv_style_t *style, lv_coord_t value)
static bool lv_style_prop_has_flag (lv_style_prop_t prop, uint8_t flag)
Check if the style property has a specified behavioral flag.
Macro Definition Documentation
LV_ASSERT_STYLE
#define LV_ASSERT_STYLE (p) do{}while(0)
Definition at line 585 of file lv_style.h.
LV_IMG_ZOOM_NONE
#define LV_IMG_ZOOM_NONE 256 /*Value for not zooming the image*/
Other constants
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/misc/lv_style.h.
Definition at line 49 of file lv_style.h.
LV_STYLE_CONST_INIT
#define LV_STYLE_CONST_INIT (var_name, prop_array)
Value:
    const lv_style_t var_name = {                                       \
        .v_p = { .const_props = prop_array },                           \
        .has_group = 0xFF,                                              \
        .prop1 = LV_STYLE_PROP_ANY,                                     \
        .prop_cnt = (sizeof(prop_array) / sizeof((prop_array)[0])),     \
    }
Definition at line 63 of file lv_style.h.
#define LV_STYLE_CONST_INIT(var_name, prop_array)                       \
    const lv_style_t var_name = {                                       \
        .v_p = { .const_props = prop_array },                           \
        .has_group = 0xFF,                                              \
        .prop1 = LV_STYLE_PROP_ANY,                                     \
        .prop_cnt = (sizeof(prop_array) / sizeof((prop_array)[0])),     \
    }
LV_STYLE_PROP_ALL
#define LV_STYLE_PROP_ALL (0x1F) /*Indicating all flags*/
Definition at line 44 of file lv_style.h.
LV_STYLE_PROP_EXT_DRAW
#define LV_STYLE_PROP_EXT_DRAW (1 << 1) /*Requires ext. draw size update when changed*/
Definition at line 40 of file lv_style.h.
LV_STYLE_PROP_FLAG_NONE
#define LV_STYLE_PROP_FLAG_NONE (0)
Flags for style behavior
The rest of the flags will have _FLAG added to their name in v9.
Definition at line 38 of file lv_style.h.
LV_STYLE_PROP_ID_MASK
#define LV_STYLE_PROP_ID_MASK (prop) ((lv_style_prop_t)((prop) & ~LV_STYLE_PROP_META_MASK))
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/misc/lv_style.h.
Definition at line 77 of file lv_style.h.
Referenced by lv_style_get_prop_inlined().
LV_STYLE_PROP_INHERIT
#define LV_STYLE_PROP_INHERIT (1 << 0) /*Inherited*/
Definition at line 39 of file lv_style.h.
LV_STYLE_PROP_LAYER_REFR
#define LV_STYLE_PROP_LAYER_REFR (1 << 4) /*Affects layer handling*/
Definition at line 43 of file lv_style.h.
LV_STYLE_PROP_LAYOUT_REFR
#define LV_STYLE_PROP_LAYOUT_REFR (1 << 2) /*Requires layout update when changed*/
Definition at line 41 of file lv_style.h.
LV_STYLE_PROP_META_INHERIT
#define LV_STYLE_PROP_META_INHERIT 0x8000
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/misc/lv_style.h.
Definition at line 73 of file lv_style.h.
Referenced by lv_style_get_prop_inlined().
LV_STYLE_PROP_META_INITIAL
#define LV_STYLE_PROP_META_INITIAL 0x4000
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/misc/lv_style.h.
Definition at line 74 of file lv_style.h.
Referenced by lv_style_get_prop_inlined().
LV_STYLE_PROP_META_MASK
#define LV_STYLE_PROP_META_MASK (LV_STYLE_PROP_META_INHERIT | LV_STYLE_PROP_META_INITIAL)
Definition at line 75 of file lv_style.h.
LV_STYLE_PROP_PARENT_LAYOUT_REFR
#define LV_STYLE_PROP_PARENT_LAYOUT_REFR (1 << 3) /*Requires layout update on parent when changed*/
Definition at line 42 of file lv_style.h.
LV_STYLE_SENTINEL_VALUE
#define LV_STYLE_SENTINEL_VALUE 0xAABBCCDD
Definition at line 31 of file lv_style.h.
Typedef Documentation
lv_blend_mode_t
typedef uint8_t lv_blend_mode_t
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/misc/lv_style.h.
Definition at line 94 of file lv_style.h.
lv_border_side_t
typedef uint8_t lv_border_side_t
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/misc/lv_style.h.
Definition at line 121 of file lv_style.h.
lv_dither_mode_t
typedef uint8_t lv_dither_mode_t
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/misc/lv_style.h.
Definition at line 144 of file lv_style.h.
lv_grad_dir_t
typedef uint8_t lv_grad_dir_t
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/misc/lv_style.h.
Definition at line 132 of file lv_style.h.
lv_style_res_t
typedef uint8_t lv_style_res_t
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/misc/lv_style.h.
Definition at line 292 of file lv_style.h.
lv_text_decor_t
typedef uint8_t lv_text_decor_t
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/misc/lv_style.h.
Definition at line 106 of file lv_style.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Possible options how to blend opaque drawings
Enumerator
LV_BLEND_MODE_NORMAL
Simply mix according to the opacity value
LV_BLEND_MODE_ADDITIVE
Add the respective color channels
LV_BLEND_MODE_SUBTRACTIVE
Subtract the foreground from the background
LV_BLEND_MODE_MULTIPLY
Multiply the foreground and background
LV_BLEND_MODE_REPLACE
Replace background with foreground in the area
Definition at line 86 of file lv_style.h.
     {
    LV_BLEND_MODE_NORMAL,
    LV_BLEND_MODE_ADDITIVE,
    LV_BLEND_MODE_SUBTRACTIVE,
    LV_BLEND_MODE_MULTIPLY,
    LV_BLEND_MODE_REPLACE,
};
anonymous enum
anonymous enum
Some options to apply decorations on texts. 'OR'ed values can be used.
Enumerator
LV_TEXT_DECOR_NONE
LV_TEXT_DECOR_UNDERLINE
LV_TEXT_DECOR_STRIKETHROUGH
Definition at line 100 of file lv_style.h.
     {
    LV_TEXT_DECOR_NONE          = 0x00,
    LV_TEXT_DECOR_UNDERLINE     = 0x01,
    LV_TEXT_DECOR_STRIKETHROUGH = 0x02,
};
anonymous enum
anonymous enum
Selects on which sides border should be drawn 'OR'ed values can be used.
Enumerator
LV_BORDER_SIDE_NONE
LV_BORDER_SIDE_BOTTOM
LV_BORDER_SIDE_TOP
LV_BORDER_SIDE_LEFT
LV_BORDER_SIDE_RIGHT
LV_BORDER_SIDE_FULL
LV_BORDER_SIDE_INTERNAL
FOR matrix-like objects (e.g. Button matrix)
Definition at line 112 of file lv_style.h.
     {
    LV_BORDER_SIDE_NONE     = 0x00,
    LV_BORDER_SIDE_BOTTOM   = 0x01,
    LV_BORDER_SIDE_TOP      = 0x02,
    LV_BORDER_SIDE_LEFT     = 0x04,
    LV_BORDER_SIDE_RIGHT    = 0x08,
    LV_BORDER_SIDE_FULL     = 0x0F,
    LV_BORDER_SIDE_INTERNAL = 0x10,
};
anonymous enum
anonymous enum
The direction of the gradient.
Enumerator
LV_GRAD_DIR_NONE
No gradient (the grad_color property is ignored)
LV_GRAD_DIR_VER
Vertical (top to bottom) gradient
LV_GRAD_DIR_HOR
Horizontal (left to right) gradient
Definition at line 126 of file lv_style.h.
     {
    LV_GRAD_DIR_NONE,
    LV_GRAD_DIR_VER,
    LV_GRAD_DIR_HOR,
};
anonymous enum
anonymous enum
The dithering algorithm for the gradient Depends on LV_DITHER_GRADIENT
Enumerator
LV_DITHER_NONE
No dithering, colors are just quantized to the output resolution
LV_DITHER_ORDERED
Ordered dithering. Faster to compute and use less memory but lower quality
LV_DITHER_ERR_DIFF
Error diffusion mode. Slower to compute and use more memory but give highest dither quality
Definition at line 138 of file lv_style.h.
     {
    LV_DITHER_NONE,
    LV_DITHER_ORDERED,
    LV_DITHER_ERR_DIFF,
};
anonymous enum
anonymous enum
Enumerator
LV_STYLE_RES_NOT_FOUND
LV_STYLE_RES_FOUND
LV_STYLE_RES_INHERIT
Definition at line 286 of file lv_style.h.
     {
    LV_STYLE_RES_NOT_FOUND,
    LV_STYLE_RES_FOUND,
    LV_STYLE_RES_INHERIT
};
lv_style_prop_t
enum lv_style_prop_t
Enumeration of all built in style properties
Props are split into groups of 16. When adding a new prop to a group, ensure it does not overflow into the next one.
Enumerator
LV_STYLE_PROP_INV
LV_STYLE_WIDTH
LV_STYLE_MIN_WIDTH
LV_STYLE_MAX_WIDTH
LV_STYLE_HEIGHT
LV_STYLE_MIN_HEIGHT
LV_STYLE_MAX_HEIGHT
LV_STYLE_X
LV_STYLE_Y
LV_STYLE_ALIGN
LV_STYLE_LAYOUT
LV_STYLE_RADIUS
LV_STYLE_PAD_TOP
LV_STYLE_PAD_BOTTOM
LV_STYLE_PAD_LEFT
LV_STYLE_PAD_RIGHT
LV_STYLE_PAD_ROW
LV_STYLE_PAD_COLUMN
LV_STYLE_BASE_DIR
LV_STYLE_CLIP_CORNER
LV_STYLE_BG_COLOR
LV_STYLE_BG_OPA
LV_STYLE_BG_GRAD_COLOR
LV_STYLE_BG_GRAD_DIR
LV_STYLE_BG_MAIN_STOP
LV_STYLE_BG_GRAD_STOP
LV_STYLE_BG_GRAD
LV_STYLE_BG_DITHER_MODE
LV_STYLE_BG_IMG_SRC
LV_STYLE_BG_IMG_OPA
LV_STYLE_BG_IMG_RECOLOR
LV_STYLE_BG_IMG_RECOLOR_OPA
LV_STYLE_BG_IMG_TILED
LV_STYLE_BORDER_COLOR
LV_STYLE_BORDER_OPA
LV_STYLE_BORDER_WIDTH
LV_STYLE_BORDER_SIDE
LV_STYLE_BORDER_POST
LV_STYLE_OUTLINE_WIDTH
LV_STYLE_OUTLINE_COLOR
LV_STYLE_OUTLINE_OPA
LV_STYLE_OUTLINE_PAD
LV_STYLE_SHADOW_WIDTH
LV_STYLE_SHADOW_OFS_X
LV_STYLE_SHADOW_OFS_Y
LV_STYLE_SHADOW_SPREAD
LV_STYLE_SHADOW_COLOR
LV_STYLE_SHADOW_OPA
LV_STYLE_IMG_OPA
LV_STYLE_IMG_RECOLOR
LV_STYLE_IMG_RECOLOR_OPA
LV_STYLE_LINE_WIDTH
LV_STYLE_LINE_DASH_WIDTH
LV_STYLE_LINE_DASH_GAP
LV_STYLE_LINE_ROUNDED
LV_STYLE_LINE_COLOR
LV_STYLE_LINE_OPA
LV_STYLE_ARC_WIDTH
LV_STYLE_ARC_ROUNDED
LV_STYLE_ARC_COLOR
LV_STYLE_ARC_OPA
LV_STYLE_ARC_IMG_SRC
LV_STYLE_TEXT_COLOR
LV_STYLE_TEXT_OPA
LV_STYLE_TEXT_FONT
LV_STYLE_TEXT_LETTER_SPACE
LV_STYLE_TEXT_LINE_SPACE
LV_STYLE_TEXT_DECOR
LV_STYLE_TEXT_ALIGN
LV_STYLE_OPA
LV_STYLE_COLOR_FILTER_DSC
LV_STYLE_COLOR_FILTER_OPA
LV_STYLE_ANIM
LV_STYLE_ANIM_TIME
LV_STYLE_ANIM_SPEED
LV_STYLE_TRANSITION
LV_STYLE_BLEND_MODE
LV_STYLE_TRANSFORM_WIDTH
LV_STYLE_TRANSFORM_HEIGHT
LV_STYLE_TRANSLATE_X
LV_STYLE_TRANSLATE_Y
LV_STYLE_TRANSFORM_ZOOM
LV_STYLE_TRANSFORM_ANGLE
LV_STYLE_TRANSFORM_PIVOT_X
LV_STYLE_TRANSFORM_PIVOT_Y
_LV_STYLE_LAST_BUILT_IN_PROP
_LV_STYLE_NUM_BUILT_IN_PROPS
LV_STYLE_PROP_ANY
_LV_STYLE_PROP_CONST
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/misc/lv_style.h.
Definition at line 178 of file lv_style.h.
             {
    LV_STYLE_PROP_INV               = 0,
    /*Group 0*/
    LV_STYLE_WIDTH                  = 1,
    LV_STYLE_MIN_WIDTH              = 2,
    LV_STYLE_MAX_WIDTH              = 3,
    LV_STYLE_HEIGHT                 = 4,
    LV_STYLE_MIN_HEIGHT             = 5,
    LV_STYLE_MAX_HEIGHT             = 6,
    LV_STYLE_X                      = 7,
    LV_STYLE_Y                      = 8,
    LV_STYLE_ALIGN                  = 9,
    LV_STYLE_LAYOUT                 = 10,
    LV_STYLE_RADIUS                 = 11,
    /*Group 1*/
    LV_STYLE_PAD_TOP                = 16,
    LV_STYLE_PAD_BOTTOM             = 17,
    LV_STYLE_PAD_LEFT               = 18,
    LV_STYLE_PAD_RIGHT              = 19,
    LV_STYLE_PAD_ROW                = 20,
    LV_STYLE_PAD_COLUMN             = 21,
    LV_STYLE_BASE_DIR               = 22,
    LV_STYLE_CLIP_CORNER            = 23,
    /*Group 2*/
    LV_STYLE_BG_COLOR               = 32,
    LV_STYLE_BG_OPA                 = 33,
    LV_STYLE_BG_GRAD_COLOR          = 34,
    LV_STYLE_BG_GRAD_DIR            = 35,
    LV_STYLE_BG_MAIN_STOP           = 36,
    LV_STYLE_BG_GRAD_STOP           = 37,
    LV_STYLE_BG_GRAD                = 38,
    LV_STYLE_BG_DITHER_MODE         = 39,
    LV_STYLE_BG_IMG_SRC             = 40,
    LV_STYLE_BG_IMG_OPA             = 41,
    LV_STYLE_BG_IMG_RECOLOR         = 42,
    LV_STYLE_BG_IMG_RECOLOR_OPA     = 43,
    LV_STYLE_BG_IMG_TILED           = 44,
    /*Group 3*/
    LV_STYLE_BORDER_COLOR           = 48,
    LV_STYLE_BORDER_OPA             = 49,
    LV_STYLE_BORDER_WIDTH           = 50,
    LV_STYLE_BORDER_SIDE            = 51,
    LV_STYLE_BORDER_POST            = 52,
    LV_STYLE_OUTLINE_WIDTH          = 53,
    LV_STYLE_OUTLINE_COLOR          = 54,
    LV_STYLE_OUTLINE_OPA            = 55,
    LV_STYLE_OUTLINE_PAD            = 56,
    /*Group 4*/
    LV_STYLE_SHADOW_WIDTH           = 64,
    LV_STYLE_SHADOW_OFS_X           = 65,
    LV_STYLE_SHADOW_OFS_Y           = 66,
    LV_STYLE_SHADOW_SPREAD          = 67,
    LV_STYLE_SHADOW_COLOR           = 68,
    LV_STYLE_SHADOW_OPA             = 69,
    LV_STYLE_IMG_OPA                = 70,
    LV_STYLE_IMG_RECOLOR            = 71,
    LV_STYLE_IMG_RECOLOR_OPA        = 72,
    LV_STYLE_LINE_WIDTH             = 73,
    LV_STYLE_LINE_DASH_WIDTH        = 74,
    LV_STYLE_LINE_DASH_GAP          = 75,
    LV_STYLE_LINE_ROUNDED           = 76,
    LV_STYLE_LINE_COLOR             = 77,
    LV_STYLE_LINE_OPA               = 78,
    /*Group 5*/
    LV_STYLE_ARC_WIDTH              = 80,
    LV_STYLE_ARC_ROUNDED            = 81,
    LV_STYLE_ARC_COLOR              = 82,
    LV_STYLE_ARC_OPA                = 83,
    LV_STYLE_ARC_IMG_SRC            = 84,
    LV_STYLE_TEXT_COLOR             = 85,
    LV_STYLE_TEXT_OPA               = 86,
    LV_STYLE_TEXT_FONT              = 87,
    LV_STYLE_TEXT_LETTER_SPACE      = 88,
    LV_STYLE_TEXT_LINE_SPACE        = 89,
    LV_STYLE_TEXT_DECOR             = 90,
    LV_STYLE_TEXT_ALIGN             = 91,
    /*Group 6*/
    LV_STYLE_OPA                    = 96,
    LV_STYLE_COLOR_FILTER_DSC       = 97,
    LV_STYLE_COLOR_FILTER_OPA       = 98,
    LV_STYLE_ANIM                   = 99,
    LV_STYLE_ANIM_TIME              = 100,
    LV_STYLE_ANIM_SPEED             = 101,
    LV_STYLE_TRANSITION             = 102,
    LV_STYLE_BLEND_MODE             = 103,
    LV_STYLE_TRANSFORM_WIDTH        = 104,
    LV_STYLE_TRANSFORM_HEIGHT       = 105,
    LV_STYLE_TRANSLATE_X            = 106,
    LV_STYLE_TRANSLATE_Y            = 107,
    LV_STYLE_TRANSFORM_ZOOM         = 108,
    LV_STYLE_TRANSFORM_ANGLE        = 109,
    LV_STYLE_TRANSFORM_PIVOT_X      = 110,
    LV_STYLE_TRANSFORM_PIVOT_Y      = 111,
    _LV_STYLE_LAST_BUILT_IN_PROP     = 111,
    _LV_STYLE_NUM_BUILT_IN_PROPS     = _LV_STYLE_LAST_BUILT_IN_PROP + 1,
    LV_STYLE_PROP_ANY                = 0xFFFF,
    _LV_STYLE_PROP_CONST             = 0xFFFF /* magic value for const styles */
} lv_style_prop_t;
Function Documentation
_lv_style_get_prop_group()
uint8_t _lv_style_get_prop_group (lv_style_prop_t prop)
Tell the group of a property. If the a property from a group is set in a style the (1 << group) bit of style->has_group is set. It allows early skipping the style if the property is not exists in the style at all.
Parameters
prop a style property
Returns
the group [0..7] 7 means all the custom properties with index > 112
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/misc/lv_style.h.
_lv_style_prop_lookup_flags()
uint8_t _lv_style_prop_lookup_flags (lv_style_prop_t prop)
Get the flags of a built-in or custom property.
Parameters
prop a style property
Returns
the flags of the property
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/misc/lv_style.h.
Referenced by lv_style_prop_has_flag().
lv_style_get_num_custom_props()
lv_style_prop_t lv_style_get_num_custom_props (void)
Get the number of custom properties that have been registered thus far.
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/misc/lv_style.h.
lv_style_get_prop()
lv_style_res_t lv_style_get_prop (const lv_style_t * style, lv_style_prop_t prop, lv_style_value_t * value)
Get the value of a property
Parameters
style pointer to a style
prop the ID of a property
value pointer to a lv_style_value_t variable to store the value
Returns
LV_RES_INV: the property wasn't found in the style (value is unchanged) LV_RES_OK: the property was fond, and value is set accordingly
Note
For performance reasons there are no sanity check on style
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/misc/lv_style.h.
lv_style_get_prop_inlined()
static lv_style_res_t lv_style_get_prop_inlined (const lv_style_t * style, lv_style_prop_t prop, lv_style_value_t * value) inline static
Get the value of a property
Parameters
style pointer to a style
prop the ID of a property
value pointer to a lv_style_value_t variable to store the value
Returns
LV_RES_INV: the property wasn't found in the style (value is unchanged) LV_RES_OK: the property was fond, and value is set accordingly
Note
For performance reasons there are no sanity check on style
This function is the same as lv_style_get_prop but inlined. Use it only on performance critical places
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/misc/lv_style.h.
Definition at line 448 of file lv_style.h.
{
    if(style->prop1 == LV_STYLE_PROP_ANY) {
        const lv_style_const_prop_t * const_prop;
        uint32_t i;
        for(i = 0; i < style->prop_cnt; i++) {
            const_prop = style->v_p.const_props + i;
            lv_style_prop_t prop_id = LV_STYLE_PROP_ID_MASK(const_prop->prop);
            if(prop_id == prop) {
                if(const_prop->prop & LV_STYLE_PROP_META_INHERIT)
                    return LV_STYLE_RES_INHERIT;
                *value = (const_prop->prop & LV_STYLE_PROP_META_INITIAL) ? lv_style_prop_get_default(prop_id) : const_prop->value;
                return LV_STYLE_RES_FOUND;
            }
        }
        return LV_STYLE_RES_NOT_FOUND;
    }
    if(style->prop_cnt == 0) return LV_STYLE_RES_NOT_FOUND;
    if(style->prop_cnt > 1) {
        uint8_t * tmp = style->v_p.values_and_props + style->prop_cnt * sizeof(lv_style_value_t);
        uint16_t * props = (uint16_t *)tmp;
        uint32_t i;
        for(i = 0; i < style->prop_cnt; i++) {
            lv_style_prop_t prop_id = LV_STYLE_PROP_ID_MASK(props[i]);
            if(prop_id == prop) {
                if(props[i] & LV_STYLE_PROP_META_INHERIT)
                    return LV_STYLE_RES_INHERIT;
                if(props[i] & LV_STYLE_PROP_META_INITIAL)
                    *value = lv_style_prop_get_default(prop_id);
                else {
                    lv_style_value_t * values = (lv_style_value_t *)style->v_p.values_and_props;
                    *value = values[i];
                }
                return LV_STYLE_RES_FOUND;
            }
        }
    }
    else if(LV_STYLE_PROP_ID_MASK(style->prop1) == prop) {
        if(style->prop1 & LV_STYLE_PROP_META_INHERIT)
            return LV_STYLE_RES_INHERIT;
        *value = (style->prop1 & LV_STYLE_PROP_META_INITIAL) ? lv_style_prop_get_default(LV_STYLE_PROP_ID_MASK(
                                                                                             style->prop1)) : style->v_p.value1;
        return LV_STYLE_RES_FOUND;
    }
    return LV_STYLE_RES_NOT_FOUND;
}
References lv_style_t::const_props, LV_STYLE_PROP_ANY, lv_style_prop_get_default(), LV_STYLE_PROP_ID_MASK, LV_STYLE_PROP_META_INHERIT, LV_STYLE_PROP_META_INITIAL, LV_STYLE_RES_FOUND, LV_STYLE_RES_INHERIT, LV_STYLE_RES_NOT_FOUND, lv_style_const_prop_t::prop, lv_style_t::prop1, lv_style_t::prop_cnt, lv_style_t::v_p, lv_style_const_prop_t::value, lv_style_t::value1, and lv_style_t::values_and_props.
lv_style_init()
void lv_style_init (lv_style_t * style)
Initialize a style
Parameters
style pointer to a style to initialize
Note
Do not call lv_style_init on styles that already have some properties because this function won't free the used memory, just sets a default state for the style. In other words be sure to initialize styles only once!
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/misc/lv_style.h.
lv_style_is_empty()
bool lv_style_is_empty (const lv_style_t * style)
Checks if a style is empty (has no properties)
Parameters
style pointer to a style
Returns
true if the style is empty
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/misc/lv_style.h.
lv_style_prop_get_default()
lv_style_value_t lv_style_prop_get_default (lv_style_prop_t prop)
Get the default value of a property
Parameters
prop the ID of a property
Returns
the default value
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/misc/lv_style.h.
Referenced by lv_style_get_prop_inlined().
lv_style_prop_has_flag()
static bool lv_style_prop_has_flag (lv_style_prop_t prop, uint8_t flag) inline static
Check if the style property has a specified behavioral flag.
Do not pass multiple flags to this function as backwards-compatibility is not guaranteed for that.
Parameters
prop Property ID
flag Flag
Returns
true if the flag is set for this property
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/misc/lv_style.h.
Definition at line 565 of file lv_style.h.
{
    return _lv_style_prop_lookup_flags(prop) & flag;
}
References _lv_style_prop_lookup_flags().
lv_style_register_prop()
lv_style_prop_t lv_style_register_prop (uint8_t flag)
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/misc/lv_style.h.
lv_style_remove_prop()
bool lv_style_remove_prop (lv_style_t * style, lv_style_prop_t prop)
Remove a property from a style
Parameters
style pointer to a style
prop a style property ORed with a state.
Returns
true: the property was found and removed; false: the property wasn't found
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/misc/lv_style.h.
lv_style_reset()
void lv_style_reset (lv_style_t * style)
Clear all properties from a style and free all allocated memories.
Parameters
style pointer to a style
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/misc/lv_style.h.
lv_style_set_pad_all()
static void lv_style_set_pad_all (lv_style_t * style, lv_coord_t value) inline static
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/misc/lv_style.h.
Definition at line 529 of file lv_style.h.
{
    lv_style_set_pad_left(style, value);
    lv_style_set_pad_right(style, value);
    lv_style_set_pad_top(style, value);
    lv_style_set_pad_bottom(style, value);
}
References lv_style_set_pad_bottom(), lv_style_set_pad_left(), lv_style_set_pad_right(), and lv_style_set_pad_top().
lv_style_set_pad_gap()
static void lv_style_set_pad_gap (lv_style_t * style, lv_coord_t value) inline static
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/misc/lv_style.h.
Definition at line 549 of file lv_style.h.
{
    lv_style_set_pad_row(style, value);
    lv_style_set_pad_column(style, value);
}
References lv_style_set_pad_column(), and lv_style_set_pad_row().
lv_style_set_pad_hor()
static void lv_style_set_pad_hor (lv_style_t * style, lv_coord_t value) inline static
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/misc/lv_style.h.
Definition at line 537 of file lv_style.h.
{
    lv_style_set_pad_left(style, value);
    lv_style_set_pad_right(style, value);
}
References lv_style_set_pad_left(), and lv_style_set_pad_right().
lv_style_set_pad_ver()
static void lv_style_set_pad_ver (lv_style_t * style, lv_coord_t value) inline static
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/misc/lv_style.h.
Definition at line 543 of file lv_style.h.
{
    lv_style_set_pad_top(style, value);
    lv_style_set_pad_bottom(style, value);
}
References lv_style_set_pad_bottom(), and lv_style_set_pad_top().
lv_style_set_prop()
void lv_style_set_prop (lv_style_t * style, lv_style_prop_t prop, lv_style_value_t value)
Set the value of property in a style. This function shouldn't be used directly by the user. Instead use lv_style_set_<prop_name>(). E.g. lv_style_set_bg_color()
Parameters
style pointer to style
prop the ID of a property (e.g. LV_STYLE_BG_COLOR)
value lv_style_value_t variable in which a field is set according to the type of prop
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/misc/lv_style.h.
lv_style_set_prop_meta()
void lv_style_set_prop_meta (lv_style_t * style, lv_style_prop_t prop, uint16_t meta)
Set a special meta state for a property in a style. This function shouldn't be used directly by the user.
Parameters
style pointer to style
prop the ID of a property (e.g. LV_STYLE_BG_COLOR)
meta the meta value to attach to the property in the style
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/misc/lv_style.h.
lv_style_set_size()
static void lv_style_set_size (lv_style_t * style, lv_coord_t value) inline static
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/misc/lv_style.h.
Definition at line 523 of file lv_style.h.
{
    lv_style_set_width(style, value);
    lv_style_set_height(style, value);
}
References lv_style_set_height(), and lv_style_set_width().
lv_style_transition_dsc_init()
void lv_style_transition_dsc_init (lv_style_transition_dsc_t * tr, const lv_style_prop_t props[], lv_anim_path_cb_t path_cb, uint32_t time, uint32_t delay, void * user_data)
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/misc/lv_style.h.