1516X High Stakes: fmt::v10::detail::formatbuf< Streambuf > Class Template Reference
fmt::v10::detail::formatbuf< Streambuf > Class Template Reference
#include <format.h>
Public Member Functions
formatbuf (buffer< char_type > &buf)
Protected Member Functions
auto overflow (int_type ch) -> int_type override
auto xsputn (const char_type *s, streamsize count) -> streamsize override
Private Types
using char_type = typename Streambuf::char_type
using streamsize = decltype(std::declval<Streambuf>().sputn(nullptr, 0))
using int_type = typename Streambuf::int_type
using traits_type = typename Streambuf::traits_type
Private Attributes
buffer< char_type > & buffer_
Detailed Description
template<typename Streambuf>
class fmt::v10::detail::formatbuf< Streambuf >
Definition at line 311 of file format.h.
Member Typedef Documentation
char_type
template<typename Streambuf > using fmt::v10::detail::formatbuf< Streambuf >::char_type = typename Streambuf::char_type private
Definition at line 313 of file format.h.
int_type
template<typename Streambuf > using fmt::v10::detail::formatbuf< Streambuf >::int_type = typename Streambuf::int_type private
Definition at line 315 of file format.h.
streamsize
template<typename Streambuf > using fmt::v10::detail::formatbuf< Streambuf >::streamsize = decltype(std::declval<Streambuf>().sputn(nullptr, 0)) private
Definition at line 314 of file format.h.
traits_type
template<typename Streambuf > using fmt::v10::detail::formatbuf< Streambuf >::traits_type = typename Streambuf::traits_type private
Definition at line 316 of file format.h.
Constructor & Destructor Documentation
formatbuf()
template<typename Streambuf > fmt::v10::detail::formatbuf< Streambuf >::formatbuf (buffer< char_type > & buf) inline explicit
Definition at line 320 of file format.h.
: buffer_(buf) {}
Member Function Documentation
overflow()
template<typename Streambuf > auto fmt::v10::detail::formatbuf< Streambuf >::overflow (int_type ch) -> int_type inline override protected
Definition at line 328 of file format.h.
{
            if (!traits_type::eq_int_type(ch, traits_type::eof())) buffer_.push_back(static_cast<char_type>(ch));
            return ch;
        }
References fmt::v10::detail::buffer< T >::push_back().
xsputn()
template<typename Streambuf > auto fmt::v10::detail::formatbuf< Streambuf >::xsputn (const char_type * s, streamsize count) -> streamsize inline override protected
Definition at line 333 of file format.h.
{
            buffer_.append(s, s + count);
            return count;
        }
References fmt::v10::detail::buffer< T >::append(), and fmt::v10::detail::count().
Member Data Documentation
buffer_
template<typename Streambuf > buffer<char_type>& fmt::v10::detail::formatbuf< Streambuf >::buffer_ private
Definition at line 318 of file format.h.
The documentation for this class was generated from the following file:
include/fmt/format.h