1516X High Stakes: fmt::v10::detail::buffer< T > Class Template Reference
fmt::v10::detail::buffer< T > Class Template Reference abstract
#include <core.h>
Public Types
using value_type = T
using const_reference = const T&
Public Member Functions
buffer (const buffer &)=delete
void operator= (const buffer &)=delete
auto begin () noexcept -> T *
auto end () noexcept -> T *
auto begin () const noexcept -> const T *
auto end () const noexcept -> const T *
constexpr auto size () const noexcept -> size_t
constexpr auto capacity () const noexcept -> size_t
auto data () noexcept -> T *
auto data () const noexcept -> const T *
void clear ()
void try_resize (size_t count)
void try_reserve (size_t new_capacity)
void push_back (const T &value)
template<typename U >
void append (const U *begin, const U *end)
template<typename Idx >
auto operator[] (Idx index) -> T &
template<typename Idx >
auto operator[] (Idx index) const -> const T &
Protected Member Functions
buffer (size_t sz) noexcept
buffer (T *p=nullptr, size_t sz=0, size_t cap=0) noexcept
~buffer ()=default
buffer (buffer &&)=default
void set (T *buf_data, size_t buf_capacity) noexcept
virtual void grow (size_t capacity)=0
Private Attributes
T * ptr_
size_t size_
size_t capacity_
Detailed Description
template<typename T>
class fmt::v10::detail::buffer< T >
\rst A contiguous memory buffer with an optional growing ability. It is an internal class and shouldn't be used directly, only via ~fmtbasic_memory_buffer. \endrst
Definition at line 738 of file core.h.
Member Typedef Documentation
const_reference
template<typename T > using fmt::v10::detail::buffer< T >::const_reference = const T&
Definition at line 765 of file core.h.
value_type
template<typename T > using fmt::v10::detail::buffer< T >::value_type = T
Definition at line 764 of file core.h.
Constructor & Destructor Documentation
buffer() [1/4]
template<typename T > fmt::v10::detail::buffer< T >::buffer (size_t sz) inline protected noexcept
Definition at line 747 of file core.h.
: size_(sz), capacity_(sz) {}
buffer() [2/4]
template<typename T > fmt::v10::detail::buffer< T >::buffer (T * p = nullptr, size_t sz = 0, size_t cap = 0) inline protected noexcept
Definition at line 749 of file core.h.
            : ptr_(p), size_(sz), capacity_(cap) {}
~buffer()
template<typename T > fmt::v10::detail::buffer< T >::~buffer () protected default
buffer() [3/4]
template<typename T > fmt::v10::detail::buffer< T >::buffer (buffer< T > &&) protected default
buffer() [4/4]
template<typename T > fmt::v10::detail::buffer< T >::buffer (const buffer< T > &) delete
Member Function Documentation
append()
template<typename T > template<typename U > void fmt::v10::detail::buffer< T >::append (const U * begin, const U * end)
Appends data to the end of the buffer.
Referenced by fmt::v10::detail::format_hexfloat(), and fmt::v10::detail::formatbuf< Streambuf >::xsputn().
begin() [1/2]
template<typename T > auto fmt::v10::detail::buffer< T >::begin () const -> const T* inline noexcept
Definition at line 774 of file core.h.
{ return ptr_; }
begin() [2/2]
template<typename T > auto fmt::v10::detail::buffer< T >::begin () -> T* inline noexcept
Definition at line 770 of file core.h.
{ return ptr_; }
capacity()
template<typename T > auto fmt::v10::detail::buffer< T >::capacity () const -> size_t inline constexpr noexcept
Returns the capacity of this buffer.
Definition at line 782 of file core.h.
{ return capacity_; }
Referenced by fmt::v10::basic_memory_buffer< T, SIZE, Allocator >::move(), and fmt::v10::detail::to_pointer().
clear()
template<typename T > void fmt::v10::detail::buffer< T >::clear () inline
Clears this buffer.
Definition at line 790 of file core.h.
{ size_ = 0; }
Referenced by fmt::v10::basic_memory_buffer< T, SIZE, Allocator >::move().
data() [1/2]
template<typename T > auto fmt::v10::detail::buffer< T >::data () const -> const T* inline noexcept
Definition at line 787 of file core.h.
{ return ptr_; }
data() [2/2]
template<typename T > auto fmt::v10::detail::buffer< T >::data () -> T* inline noexcept
Returns a pointer to the buffer data (not null-terminated).
Definition at line 785 of file core.h.
{ return ptr_; }
Referenced by fmt::v10::detail::bigint::align(), fmt::v10::detail::bigint::assign(), fmt::v10::detail::format_dragon(), fmt::v10::basic_memory_buffer< T, SIZE, Allocator >::move(), fmt::v10::detail::report_error(), fmt::v10::detail::to_pointer(), fmt::v10::detail::write_float(), fmt::v10::detail::write_significand(), and fmt::v10::detail::write_significand().
end() [1/2]
template<typename T > auto fmt::v10::detail::buffer< T >::end () const -> const T* inline noexcept
Definition at line 776 of file core.h.
{ return ptr_ + size_; }
end() [2/2]
template<typename T > auto fmt::v10::detail::buffer< T >::end () -> T* inline noexcept
Definition at line 772 of file core.h.
{ return ptr_ + size_; }
Referenced by fmt::v10::detail::write_significand().
grow()
template<typename T > virtual void fmt::v10::detail::buffer< T >::grow (size_t capacity) protected pure virtual
Increases the buffer capacity to hold at least capacity elements.
Implemented in fmt::v10::basic_memory_buffer< T, SIZE, Allocator >, fmt::v10::basic_memory_buffer< bigit, bigits_capacity >, fmt::v10::basic_memory_buffer< bigit, bigits_capacity >, fmt::v10::basic_memory_buffer< wchar_t >, fmt::v10::basic_memory_buffer< wchar_t >, fmt::v10::detail::counting_buffer< T >, fmt::v10::detail::iterator_buffer< OutputIt, T, Traits >, fmt::v10::detail::iterator_buffer< std::back_insert_iterator< Container >, enable_if_t< is_contiguous< Container >::value, typename Container::value_type > >, fmt::v10::detail::iterator_buffer< T *, T >, and fmt::v10::detail::iterator_buffer< T *, T, fixed_buffer_traits >.
operator=()
template<typename T > void fmt::v10::detail::buffer< T >::operator= (const buffer< T > &) delete
operator[]() [1/2]
template<typename T > template<typename Idx > auto fmt::v10::detail::buffer< T >::operator[] (Idx index) -> T& inline
Definition at line 815 of file core.h.
{ return ptr_[index]; }
References fmt::v10::detail::index.
operator[]() [2/2]
template<typename T > template<typename Idx > auto fmt::v10::detail::buffer< T >::operator[] (Idx index) const -> const T& inline
Definition at line 817 of file core.h.
{ return ptr_[index]; }
References fmt::v10::detail::index.
push_back()
template<typename T > void fmt::v10::detail::buffer< T >::push_back (const T & value) inline
Definition at line 807 of file core.h.
{
            try_reserve(size_ + 1);
            ptr_[size_++] = value;
        }
Referenced by fmt::v10::detail::utf8_to_utf16::utf8_to_utf16(), fmt::v10::detail::format_dragon(), fmt::v10::detail::format_hexfloat(), fmt::v10::detail::bigint::multiply(), fmt::v10::detail::bigint::multiply(), fmt::v10::detail::bigint::operator<<=(), fmt::v10::detail::formatbuf< Streambuf >::overflow(), and fmt::v10::detail::write_float().
set()
template<typename T > void fmt::v10::detail::buffer< T >::set (T * buf_data, size_t buf_capacity) inline protected noexcept
Sets the buffer data and capacity.
Definition at line 756 of file core.h.
{
            ptr_ = buf_data;
            capacity_ = buf_capacity;
        }
Referenced by fmt::v10::basic_memory_buffer< T, SIZE, Allocator >::move().
size()
template<typename T > auto fmt::v10::detail::buffer< T >::size () const -> size_t inline constexpr noexcept
Returns the size of this buffer.
Definition at line 779 of file core.h.
{ return size_; }
Referenced by fmt::v10::detail::bigint::align(), fmt::v10::detail::bigint::assign(), fmt::v10::basic_memory_buffer< T, SIZE, Allocator >::move(), fmt::v10::detail::bigint::multiply(), fmt::v10::detail::bigint::multiply(), fmt::v10::detail::bigint::num_bigits(), fmt::v10::detail::bigint::operator<<=(), fmt::v10::detail::bigint::remove_leading_zeros(), fmt::v10::detail::report_error(), fmt::v10::detail::reserve(), fmt::v10::detail::utf8_to_utf16::size(), fmt::v10::detail::bigint::square(), fmt::v10::detail::bigint::subtract_aligned(), fmt::v10::detail::to_pointer(), fmt::v10::detail::write_float(), and fmt::v10::detail::write_significand().
try_reserve()
template<typename T > void fmt::v10::detail::buffer< T >::try_reserve (size_t new_capacity) inline
Definition at line 803 of file core.h.
{
            if (new_capacity > capacity_) grow(new_capacity);
        }
Referenced by fmt::v10::detail::reserve().
try_resize()
template<typename T > void fmt::v10::detail::buffer< T >::try_resize (size_t count) inline
Definition at line 794 of file core.h.
{
            try_reserve(count);
            size_ = count <= capacity_ ? count : capacity_;
        }
References fmt::v10::detail::count().
Referenced by fmt::v10::detail::format_dragon(), and fmt::v10::detail::to_pointer().
Member Data Documentation
capacity_
template<typename T > size_t fmt::v10::detail::buffer< T >::capacity_ private
Definition at line 742 of file core.h.
ptr_
template<typename T > T* fmt::v10::detail::buffer< T >::ptr_ private
Definition at line 740 of file core.h.
size_
template<typename T > size_t fmt::v10::detail::buffer< T >::size_ private
Definition at line 741 of file core.h.
The documentation for this class was generated from the following file:
include/fmt/core.h