1516X High Stakes: fmt::v10::detail::format_string_checker< Char, Args > Class Template Reference
fmt::v10::detail::format_string_checker< Char, Args > Class Template Reference
#include <core.h>
Public Member Functions
format_string_checker (basic_string_view< Char > fmt)
void on_text (const Char *, const Char *)
auto on_arg_id () -> int
auto on_arg_id (int id) -> int
auto on_arg_id (basic_string_view< Char > id) -> int
void on_replacement_field (int id, const Char *begin)
auto on_format_specs (int id, const Char *begin, const Char *) -> const Char *
void on_error (const char *message)
Private Types
using parse_context_type = compile_parse_context<Char>
using parse_func = const Char* (*)(parse_context_type&)
Private Attributes
type types_ [num_args > 0 ? static_cast< size_t >(num_args) :1]
parse_context_type context_
parse_func parse_funcs_ [num_args > 0 ? static_cast< size_t >(num_args) :1]
Static Private Attributes
static constexpr int num_args = sizeof...(Args)
Detailed Description
template<typename Char, typename... Args>
class fmt::v10::detail::format_string_checker< Char, Args >
Definition at line 2368 of file core.h.
Member Typedef Documentation
parse_context_type
template<typename Char , typename... Args> using fmt::v10::detail::format_string_checker< Char, Args >::parse_context_type = compile_parse_context<Char> private
Definition at line 2370 of file core.h.
parse_func
template<typename Char , typename... Args> using fmt::v10::detail::format_string_checker< Char, Args >::parse_func = const Char* (*)(parse_context_type&) private
Definition at line 2377 of file core.h.
Constructor & Destructor Documentation
format_string_checker()
template<typename Char , typename... Args> fmt::v10::detail::format_string_checker< Char, Args >::format_string_checker (basic_string_view< Char > fmt) inline explicit
Definition at line 2383 of file core.h.
            : types_ {mapped_type_constant<Args, buffer_context<Char>>::value...}, context_(fmt, num_args, types_),
              parse_funcs_ {&parse_format_specs<Args, parse_context_type>...} {}
References fmt::v10::detail::parse_format_specs().
Member Function Documentation
on_arg_id() [1/3]
template<typename Char , typename... Args> auto fmt::v10::detail::format_string_checker< Char, Args >::on_arg_id () -> int inline
Definition at line 2389 of file core.h.
{ return context_.next_arg_id(); }
References fmt::v10::detail::compile_parse_context< Char >::next_arg_id().
on_arg_id() [2/3]
template<typename Char , typename... Args> auto fmt::v10::detail::format_string_checker< Char, Args >::on_arg_id (basic_string_view< Char > id) -> int inline
Definition at line 2393 of file core.h.
{
#if FMT_USE_NONTYPE_TEMPLATE_ARGS
            auto index = get_arg_index_by_name<Args...>(id);
            if (index < 0) on_error("named argument is not found");
            return index;
#else
            (void)id;
            on_error("compile-time checks for named arguments require C++20 support");
            return 0;
#endif
        }
References fmt::v10::detail::get_arg_index_by_name(), and fmt::v10::detail::index.
on_arg_id() [3/3]
template<typename Char , typename... Args> auto fmt::v10::detail::format_string_checker< Char, Args >::on_arg_id (int id) -> int inline
Definition at line 2391 of file core.h.
{ return context_.check_arg_id(id), id; }
References fmt::v10::detail::compile_parse_context< Char >::check_arg_id().
on_error()
template<typename Char , typename... Args> void fmt::v10::detail::format_string_checker< Char, Args >::on_error (const char * message) inline
Definition at line 2415 of file core.h.
{ throw_format_error(message); }
on_format_specs()
template<typename Char , typename... Args> auto fmt::v10::detail::format_string_checker< Char, Args >::on_format_specs (int id, const Char * begin, const Char *) -> const Char* inline
Definition at line 2409 of file core.h.
{
            context_.advance_to(begin);
            // id >= 0 check is a workaround for gcc 10 bug (#2065).
            return id >= 0 && id < num_args ? parse_funcs_[id](context_) : begin;
        }
References fmt::v10::basic_format_parse_context< Char >::advance_to().
on_replacement_field()
template<typename Char , typename... Args> void fmt::v10::detail::format_string_checker< Char, Args >::on_replacement_field (int id, const Char * begin) inline
Definition at line 2405 of file core.h.
{
            on_format_specs(id, begin, begin); // Call parse() on empty specs.
        }
on_text()
template<typename Char , typename... Args> void fmt::v10::detail::format_string_checker< Char, Args >::on_text (const Char * , const Char *) inline
Definition at line 2387 of file core.h.
{}
Member Data Documentation
context_
template<typename Char , typename... Args> parse_context_type fmt::v10::detail::format_string_checker< Char, Args >::context_ private
Definition at line 2380 of file core.h.
num_args
template<typename Char , typename... Args> constexpr int fmt::v10::detail::format_string_checker< Char, Args >::num_args = sizeof...(Args) static constexpr private
Definition at line 2371 of file core.h.
parse_funcs_
template<typename Char , typename... Args> parse_func fmt::v10::detail::format_string_checker< Char, Args >::parse_funcs_[num_args > 0 ? static_cast< size_t >(num_args) :1] private
Definition at line 2381 of file core.h.
types_
template<typename Char , typename... Args> type fmt::v10::detail::format_string_checker< Char, Args >::types_[num_args > 0 ? static_cast< size_t >(num_args) :1] private
Definition at line 2379 of file core.h.
The documentation for this class was generated from the following file:
include/fmt/core.h