1516X High Stakes: pros::rtos::MutexVar< Var > Class Template Reference
pros::rtos::MutexVar< Var > Class Template Reference
#include <rtos.hpp>
Public Member Functions
template<typename... Args>
MutexVar (Args &&... args)
std::optional< MutexVarLock< Var > > try_lock (std::uint32_t timeout)
template<typename Rep , typename Period >
std::optional< MutexVarLock< Var > > try_lock (const std::chrono::duration< Rep, Period > &rel_time)
MutexVarLock< Var > lock ()
Private Attributes
Mutex mutex
Var var
Detailed Description
template<typename Var>
class pros::rtos::MutexVar< Var >
Definition at line 1385 of file rtos.hpp.
Constructor & Destructor Documentation
MutexVar()
template<typename Var > template<typename... Args> pros::rtos::MutexVar< Var >::MutexVar (Args &&... args) inline
Creates a mutex-protected variable which is initialized with the given constructor arguments.
Parameters
args The arguments to provide to the Var constructor.
Example
// We create a pose class to contain all our odometry data in a single
// variable that can be protected by a MutexVar. Otherwise, we would have
// three seperate variables which could not be protected in a single
// MutexVar
struct Pose {
  double x;
  double y;
  double heading;
}
pros::MutexVar<Pose> odom_pose(0.0, 0.0, 0.0);
void odom_task(void* param) {
   while(true) {
    Pose old_pose = *odom_pose.lock();
    Pose new_pose{0.0, 0.0, 0.0};
     // --- Calculate new pose for the robot here ---
     // Now that we have the new pose, we can update the global variables
    *odom_pose.take() = new_pose;
    delay(10);
  }
}
 void chassis_task(void* param) {
   while(true) {
    Pose cur_pose = *odom_pose.take();
     // ---- Move the robot using the current locations goes here ----
     delay(10);
   }
 }
 void initialize() {
  odom_mutex = pros::Mutex();
  pros::Task odom_task(odom_task, "Odometry Task");
  pros::Task chassis_task(odom_task, "Chassis Control Task");
 }
Definition at line 1448 of file rtos.hpp.
: mutex(), var(std::forward<Args>(args)...) {}
Member Function Documentation
lock()
template<typename Var > MutexVarLock< Var > pros::rtos::MutexVar< Var >::lock () inline
Lock the mutex-protected variable, waiting indefinitely.
Returns
A MutexVarLock providing access to the protected variable.
Example
pros::MutexVar<Pose> odom_pose;
void my_task(void* param) {
  while(true) {
    pros::delay(10);
    pros::MutexVarLock<Pose> cur_pose = odom_pose.lock();
    Pose cur_pose = *cur_pose;
    // do stuff with cur_pose
  }
}
Definition at line 1545 of file rtos.hpp.
{
      while (!mutex.take(TIMEOUT_MAX))
         ;
      return {mutex, var};
   }
References pros::rtos::MutexVar< Var >::mutex, pros::rtos::Mutex::take(), TIMEOUT_MAX, and pros::rtos::MutexVar< Var >::var.
try_lock() [1/2]
template<typename Var > template<typename Rep , typename Period > std::optional< MutexVarLock< Var > > pros::rtos::MutexVar< Var >::try_lock (const std::chrono::duration< Rep, Period > & rel_time) inline
Try to lock the mutex-protected variable.
Parameters
timeout Time to wait before the mutex becomes available. A timeout of 0 can be used to poll the mutex.
Returns
A std::optional which contains a MutexVarLock providing access to the protected variable if locking is successful.
Example
pros::MutexVar<Pose> odom_pose;
void my_task(void* param) {
  while(true) {
    std::chrono::duration<int, std::milli> timeout(100);
    std::optional<pros::MutexVar<Pose>> cur_pose_opt = odom_pose.try_lock(timeout);
    if(cur_pose_opt.has_value()) {
      Pose* cur_pose = **cur_pose_opt;
    }
    else {
      printf("Could not lock the mutex var!");
    }
    pros::delay(10);
  }
}
Definition at line 1520 of file rtos.hpp.
{
      try_lock(std::chrono::duration_cast<Clock::duration>(rel_time).count());
   }
References pros::rtos::MutexVar< Var >::try_lock().
try_lock() [2/2]
template<typename Var > std::optional< MutexVarLock< Var > > pros::rtos::MutexVar< Var >::try_lock (std::uint32_t timeout) inline
Try to lock the mutex-protected variable.
Parameters
timeout Time to wait before the mutex becomes available, in milliseconds. A timeout of 0 can be used to poll the mutex.
Returns
A std::optional which contains a MutexVarLock providing access to the protected variable if locking is successful.
Example
pros::MutexVar<Pose> odom_pose;
void my_task(void* param) {
  while(true) {
    std::optional<pros::MutexVar<Pose>> cur_pose_opt = odom_pose.try_lock(100);
    if(cur_pose_opt.has_value()) {
      Pose* cur_pose = **cur_pose_opt;
    }
    else {
      printf("Could not lock the mutex var!");
    }
    pros::delay(10);
  }
}
Definition at line 1480 of file rtos.hpp.
{
      if (mutex.take(timeout)) {
         return {{mutex, var}};
      } else {
         return {};
      }
   }
References pros::rtos::MutexVar< Var >::mutex, pros::rtos::Mutex::take(), and pros::rtos::MutexVar< Var >::var.
Referenced by pros::rtos::MutexVar< Var >::try_lock().
Member Data Documentation
mutex
template<typename Var > Mutex pros::rtos::MutexVar< Var >::mutex private
Definition at line 1386 of file rtos.hpp.
Referenced by pros::rtos::MutexVar< Var >::lock(), and pros::rtos::MutexVar< Var >::try_lock().
var
template<typename Var > Var pros::rtos::MutexVar< Var >::var private
Definition at line 1387 of file rtos.hpp.
Referenced by pros::rtos::MutexVar< Var >::lock(), and pros::rtos::MutexVar< Var >::try_lock().
The documentation for this class was generated from the following file:
include/pros/rtos.hpp