1516X High Stakes: fmt::v10::detail::utf8_to_utf16 Class Reference
fmt::v10::detail::utf8_to_utf16 Class Reference
#include <format.h>
Public Member Functions
utf8_to_utf16 (string_view s)
operator basic_string_view< wchar_t > () const
auto size () const -> size_t
auto c_str () const -> const wchar_t *
auto str () const -> std::wstring
Private Attributes
basic_memory_buffer< wchar_t > buffer_
Detailed Description
Definition at line 1311 of file format.h.
Constructor & Destructor Documentation
utf8_to_utf16()
fmt::v10::detail::utf8_to_utf16::utf8_to_utf16 (string_view s) explicit
Definition at line 1311 of file format-inl.h.
{
    for_each_codepoint(s, [this](uint32_t cp, string_view) {
        if (cp == invalid_code_point) FMT_THROW(std::runtime_error("invalid utf8"));
        if (cp <= 0xFFFF) {
            buffer_.push_back(static_cast<wchar_t>(cp));
        } else {
            cp -= 0x10000;
            buffer_.push_back(static_cast<wchar_t>(0xD800 + (cp >> 10)));
            buffer_.push_back(static_cast<wchar_t>(0xDC00 + (cp & 0x3FF)));
        }
        return true;
    });
    buffer_.push_back(0);
}
References buffer_, FMT_THROW, fmt::v10::detail::for_each_codepoint(), fmt::v10::detail::invalid_code_point, and fmt::v10::detail::buffer< T >::push_back().
Member Function Documentation
c_str()
auto fmt::v10::detail::utf8_to_utf16::c_str () const -> const wchar_t* inline
Definition at line 1321 of file format.h.
{ return &buffer_[0]; }
operator basic_string_view< wchar_t >()
fmt::v10::detail::utf8_to_utf16::operator basic_string_view< wchar_t > () const inline
Definition at line 1317 of file format.h.
{ return {&buffer_[0], size()}; }
size()
auto fmt::v10::detail::utf8_to_utf16::size () const -> size_t inline
Definition at line 1319 of file format.h.
{ return buffer_.size() - 1; }
References fmt::v10::detail::buffer< T >::size().
str()
auto fmt::v10::detail::utf8_to_utf16::str () const -> std::wstring inline
Definition at line 1323 of file format.h.
{ return {&buffer_[0], size()}; }
Member Data Documentation
buffer_
basic_memory_buffer<wchar_t> fmt::v10::detail::utf8_to_utf16::buffer_ private
Definition at line 1313 of file format.h.
Referenced by utf8_to_utf16().
The documentation for this class was generated from the following files:
include/fmt/format.h
include/fmt/format-inl.h