1516X High Stakes: Robot::Globals Namespace Reference
Robot::Globals Namespace Reference
Contains global variables and type definitions for the Robot namespace.
Functions
pros::Controller controller (pros::E_CONTROLLER_MASTER)
pros::Motor RightFront (6, pros::E_MOTOR_GEARSET_18, false, pros::E_MOTOR_ENCODER_DEGREES)
pros::Motor LeftFront (-5, pros::E_MOTOR_GEARSET_18, false, pros::E_MOTOR_ENCODER_DEGREES)
pros::Motor LeftBack (-7, pros::E_MOTOR_GEARSET_18, false, pros::E_MOTOR_ENCODER_DEGREES)
pros::Motor RightBack (8, pros::E_MOTOR_GEARSET_18, false, pros::E_MOTOR_ENCODER_DEGREES)
pros::Motor LeftMid (-2, pros::E_MOTOR_GEARSET_18, false, pros::E_MOTOR_ENCODER_DEGREES)
pros::Motor PuncherMotor (19, pros::E_MOTOR_GEARSET_18, false, pros::E_MOTOR_ENCODER_DEGREES)
pros::Motor PuncherMotor2 (-20, pros::E_MOTOR_GEARSET_18, false, pros::E_MOTOR_ENCODER_DEGREES)
pros::Motor RightMid (3, pros::E_MOTOR_GEARSET_18, false, pros::E_MOTOR_ENCODER_DEGREES)
pros::Motor IntakeMotor (-9, pros::E_MOTOR_GEARSET_18, false, pros::E_MOTOR_ENCODER_DEGREES)
pros::Imu inertial_sensor (15)
pros::Distance distance (18)
pros::ADIDigitalOut FrontWing ('A')
pros::ADIDigitalOut BackWing1 ('B')
pros::ADIDigitalOut BackWing2 ('C')
pros::ADIDigitalOut Elevator ('D')
pros::ADIDigitalIn puncherToggleSwitch ('E')
pros::ADIDigitalIn autonToggleSwitch ('F')
pros::ADIDigitalIn drivetrainToggleSwitch ('G')
pros::Motor_Group punchers ({PuncherMotor, PuncherMotor2})
pros::Motor_Group drive_left ({LeftFront, LeftMid, LeftBack})
pros::Motor_Group drive_right ({RightFront, RightMid, RightBack})
pros::Motor_Group drive_ ({LeftFront, RightFront, LeftMid, RightMid, LeftBack, RightBack})
lemlib::Chassis chassis (drivetrain, lateralController, angularController, sensors)
Variables
pros::Controller controller
Robot::Wings robotWings
pros::Motor RightFront
pros::Motor LeftFront
pros::Motor LeftBack
pros::Motor RightBack
pros::Motor LeftMid
pros::Motor PuncherMotor
pros::Motor PuncherMotor2
pros::Motor RightMid
pros::Motor IntakeMotor
pros::Imu inertial_sensor
pros::Distance distance
pros::ADIDigitalOut FrontWing
pros::ADIDigitalOut BackWing1
pros::ADIDigitalOut BackWing2
pros::ADIDigitalOut Elevator
pros::Motor_Group punchers
pros::Motor_Group drive_left
pros::Motor_Group drive_right
pros::Motor_Group drive_
lemlib::Drivetrain_t drivetrain
lemlib::OdomSensors_t sensors
lemlib::ChassisController_t lateralController
lemlib::ChassisController_t angularController
lemlib::Chassis chassis
pros::ADIDigitalIn puncherToggleSwitch
pros::ADIDigitalIn autonToggleSwitch
pros::ADIDigitalIn drivetrainToggleSwitch
Detailed Description
Contains global variables and type definitions for the Robot namespace.
The majority of the global variables are defined in the Globals namespace. This is to allow for easy access to the variables from any file in the project. The Globals namespace is also used to hold lemlib objects that are used to control the autonomous functions of the robot. It contains parameters that are used to control the PID that lemlib uses, additionally.
Function Documentation
autonToggleSwitch()
pros::ADIDigitalIn Robot::Globals::autonToggleSwitch ('F')
BackWing1()
pros::ADIDigitalOut Robot::Globals::BackWing1 ('B')
BackWing2()
pros::ADIDigitalOut Robot::Globals::BackWing2 ('C')
chassis()
lemlib::Chassis Robot::Globals::chassis (drivetrain , lateralController , angularController , sensors)
controller()
pros::Controller Robot::Globals::controller (pros::E_CONTROLLER_MASTER)
distance()
pros::Distance Robot::Globals::distance (18)
drive_()
pros::Motor_Group Robot::Globals::drive_ ({LeftFront, RightFront, LeftMid, RightMid, LeftBack, RightBack})
References LeftBack, LeftFront, LeftMid, RightBack, RightFront, and RightMid.
drive_left()
pros::Motor_Group Robot::Globals::drive_left ({LeftFront, LeftMid, LeftBack})
References LeftBack, LeftFront, and LeftMid.
drive_right()
pros::Motor_Group Robot::Globals::drive_right ({RightFront, RightMid, RightBack})
References RightBack, RightFront, and RightMid.
drivetrainToggleSwitch()
pros::ADIDigitalIn Robot::Globals::drivetrainToggleSwitch ('G')
Elevator()
pros::ADIDigitalOut Robot::Globals::Elevator ('D')
FrontWing()
pros::ADIDigitalOut Robot::Globals::FrontWing ('A')
inertial_sensor()
pros::Imu Robot::Globals::inertial_sensor (15)
IntakeMotor()
pros::Motor Robot::Globals::IntakeMotor (- 9, pros::E_MOTOR_GEARSET_18 , false , pros::E_MOTOR_ENCODER_DEGREES)
LeftBack()
pros::Motor Robot::Globals::LeftBack (- 7, pros::E_MOTOR_GEARSET_18 , false , pros::E_MOTOR_ENCODER_DEGREES)
LeftFront()
pros::Motor Robot::Globals::LeftFront (- 5, pros::E_MOTOR_GEARSET_18 , false , pros::E_MOTOR_ENCODER_DEGREES)
LeftMid()
pros::Motor Robot::Globals::LeftMid (- 2, pros::E_MOTOR_GEARSET_18 , false , pros::E_MOTOR_ENCODER_DEGREES)
PuncherMotor()
pros::Motor Robot::Globals::PuncherMotor (19 , pros::E_MOTOR_GEARSET_18 , false , pros::E_MOTOR_ENCODER_DEGREES)
PuncherMotor2()
pros::Motor Robot::Globals::PuncherMotor2 (- 20, pros::E_MOTOR_GEARSET_18 , false , pros::E_MOTOR_ENCODER_DEGREES)
punchers()
pros::Motor_Group Robot::Globals::punchers ({PuncherMotor, PuncherMotor2})
References PuncherMotor, and PuncherMotor2.
puncherToggleSwitch()
pros::ADIDigitalIn Robot::Globals::puncherToggleSwitch ('E')
RightBack()
pros::Motor Robot::Globals::RightBack (8 , pros::E_MOTOR_GEARSET_18 , false , pros::E_MOTOR_ENCODER_DEGREES)
RightFront()
pros::Motor Robot::Globals::RightFront (6 , pros::E_MOTOR_GEARSET_18 , false , pros::E_MOTOR_ENCODER_DEGREES)
RightMid()
pros::Motor Robot::Globals::RightMid (3 , pros::E_MOTOR_GEARSET_18 , false , pros::E_MOTOR_ENCODER_DEGREES)
Variable Documentation
angularController
lemlib::ChassisController_t Robot::Globals::angularController
Initial value:
{
    6,
    47,
    1,
    100,
    3,
    500,
    0.5
}
Definition at line 79 of file globals.cpp.
{
    6, // kP
    47, // kD
    1, // smallErrorRange
    100, // smallErrorTimeout
    3, // largeErrorRange
    500, // largeErrorTimeout
    0.5 // slew rate
};
autonToggleSwitch
pros::ADIDigitalIn Robot::Globals::autonToggleSwitch extern
Referenced by Robot::Autonomous::AutonSwitcher().
BackWing1
pros::ADIDigitalOut Robot::Globals::BackWing1 extern
Referenced by Robot::Wings::Wings(), Robot::Autonomous::Auton4(), and Robot::Wings::BackWings().
BackWing2
pros::ADIDigitalOut Robot::Globals::BackWing2 extern
Referenced by Robot::Wings::Wings(), Robot::Autonomous::Auton4(), and Robot::Wings::BackWings().
chassis
lemlib::Chassis Robot::Globals::chassis(drivetrain, lateralController, angularController, sensors)
Referenced by Robot::Autonomous::Auton1(), Robot::Autonomous::Auton2(), Robot::Autonomous::Auton4(), and Robot::Utility::displayLocation().
controller
pros::Controller Robot::Globals::controller(pros::E_CONTROLLER_MASTER)
Referenced by Robot::Drivetrain::ArcadeDrive(), Robot::Wings::BackWings(), Robot::Wings::FrontWings(), Robot::Puncher::ManualOverride(), Robot::Elevation::run(), Robot::Intake::run(), Robot::Drivetrain::TankDrive(), and Robot::Puncher::UserRun().
distance
pros::Distance Robot::Globals::distance(18)
Referenced by Robot::Puncher::DistanceRun(), and Robot::Puncher::toShoot().
drive_
pros::Motor_Group Robot::Globals::drive_ extern
Referenced by Robot::Autonomous::Auton1(), Robot::Autonomous::Auton2(), Robot::Autonomous::Auton3(), and Robot::Autonomous::Auton4().
drive_left
pros::Motor_Group Robot::Globals::drive_left extern
Referenced by Robot::Drivetrain::ArcadeDrive(), Robot::Autonomous::Auton3(), and Robot::Drivetrain::TankDrive().
drive_right
pros::Motor_Group Robot::Globals::drive_right extern
Referenced by Robot::Drivetrain::ArcadeDrive(), Robot::Autonomous::Auton2(), and Robot::Drivetrain::TankDrive().
drivetrain
lemlib::Drivetrain_t Robot::Globals::drivetrain
Initial value:
{
    &drive_left,
    &drive_right,
    10,
    3.25,
   450
}
Definition at line 50 of file globals.cpp.
{
    &drive_left, // left drivetrain motors
    &drive_right, // right drivetrain motors
    10, // track width
    3.25, // wheel diameter - 3.25 on competition bot, 4 on test drivetrain
   450 // wheel rpm - 360 rpm for competition bot, 200 for test drivetrain
};
drivetrainToggleSwitch
pros::ADIDigitalIn Robot::Globals::drivetrainToggleSwitch extern
Referenced by Robot::Drivetrain::SwitchDrive().
Elevator
pros::ADIDigitalOut Robot::Globals::Elevator extern
Referenced by Robot::Elevation::run().
FrontWing
pros::ADIDigitalOut Robot::Globals::FrontWing extern
Referenced by Robot::Wings::Wings(), Robot::Autonomous::Auton3(), and Robot::Wings::FrontWings().
inertial_sensor
pros::Imu Robot::Globals::inertial_sensor(15)
IntakeMotor
pros::Motor Robot::Globals::IntakeMotor(-9, pros::E_MOTOR_GEARSET_18, false, pros::E_MOTOR_ENCODER_DEGREES)
Referenced by Robot::Autonomous::Auton4(), and Robot::Intake::run().
lateralController
lemlib::ChassisController_t Robot::Globals::lateralController
Initial value:
{
    33,
    300,
    1,
    100,
    3,
    500,
    10
}
Definition at line 68 of file globals.cpp.
{
    33, // kP
    300, // kD
    1, // smallErrorRange
    100, // smallErrorTimeout
    3, // largeErrorRange
    500, // largeErrorTimeout
    10 // slew rate
};
LeftBack
pros::Motor Robot::Globals::LeftBack(-7, pros::E_MOTOR_GEARSET_18, false, pros::E_MOTOR_ENCODER_DEGREES)
Referenced by Robot::Utility::displayMotorVel(), drive_(), and drive_left().
LeftFront
pros::Motor Robot::Globals::LeftFront(-5, pros::E_MOTOR_GEARSET_18, false, pros::E_MOTOR_ENCODER_DEGREES)
Referenced by Robot::Utility::displayMotorVel(), drive_(), and drive_left().
LeftMid
pros::Motor Robot::Globals::LeftMid(-2, pros::E_MOTOR_GEARSET_18, false, pros::E_MOTOR_ENCODER_DEGREES)
Referenced by Robot::Utility::displayMotorVel(), drive_(), and drive_left().
PuncherMotor
pros::Motor Robot::Globals::PuncherMotor(19, pros::E_MOTOR_GEARSET_18, false, pros::E_MOTOR_ENCODER_DEGREES)
Referenced by punchers().
PuncherMotor2
pros::Motor Robot::Globals::PuncherMotor2(-20, pros::E_MOTOR_GEARSET_18, false, pros::E_MOTOR_ENCODER_DEGREES)
Referenced by punchers().
punchers
pros::Motor_Group Robot::Globals::punchers extern
Referenced by Robot::Puncher::DistanceRun(), and Robot::Puncher::UserRun().
puncherToggleSwitch
pros::ADIDigitalIn Robot::Globals::puncherToggleSwitch extern
Referenced by Robot::Puncher::PuncherSwitch().
RightBack
pros::Motor Robot::Globals::RightBack(8, pros::E_MOTOR_GEARSET_18, false, pros::E_MOTOR_ENCODER_DEGREES)
Referenced by Robot::Utility::displayMotorVel(), drive_(), and drive_right().
RightFront
pros::Motor Robot::Globals::RightFront(6, pros::E_MOTOR_GEARSET_18, false, pros::E_MOTOR_ENCODER_DEGREES)
Referenced by Robot::Utility::displayMotorVel(), drive_(), and drive_right().
RightMid
pros::Motor Robot::Globals::RightMid(3, pros::E_MOTOR_GEARSET_18, false, pros::E_MOTOR_ENCODER_DEGREES)
Referenced by Robot::Utility::displayMotorVel(), drive_(), and drive_right().
robotWings
Robot::Wings Robot::Globals::robotWings extern
sensors
lemlib::OdomSensors_t Robot::Globals::sensors
Initial value:
{
    nullptr,
    nullptr,
    nullptr,
    nullptr,
    &inertial_sensor
}
Definition at line 58 of file globals.cpp.
{
    nullptr, // vertical tracking wheel 1
    nullptr, // vertical tracking wheel 2
    nullptr, // horizontal tracking wheel 1
    nullptr, // we don't have a second tracking wheel, so we set it to nullptr
    &inertial_sensor // inertial sensor
};