1516X High Stakes: pros::adi::Motor Class Reference
pros::adi::Motor Class Reference
#include <adi.hpp>
Public Member Functions
Motor (std::uint8_t adi_port)
Motor (ext_adi_port_pair_t port_pair)
std::int32_t stop () const
std::int32_t set_value (std::int32_t value) const
std::int32_t get_value () const
virtual ext_adi_port_tuple_t get_port () const
Additional Inherited Members
Private Member Functions inherited from pros::adi::Port
Port (std::uint8_t adi_port, adi_port_config_e_t type=E_ADI_TYPE_UNDEFINED)
Port (ext_adi_port_pair_t port_pair, adi_port_config_e_t type=E_ADI_TYPE_UNDEFINED)
std::int32_t get_config () const
std::int32_t get_value () const
std::int32_t set_config (adi_port_config_e_t type) const
std::int32_t set_value (std::int32_t value) const
Private Attributes inherited from pros::adi::Port
std::uint8_t _smart_port
std::uint8_t _adi_port
Detailed Description
Definition at line 776 of file adi.hpp.
Member Function Documentation
get_port()
virtual ext_adi_port_tuple_t pros::adi::Port::get_port () const virtual
Gets the port of the sensor.
Returns
returns a tuple of integer ports.
Note
The parts of the tuple are {smart port, adi port, second adi port (when applicable)}.
Example
#define DIGITAL_SENSOR_PORT 1 // 'A'
void initialize() {
  pros::adi::AnalogIn sensor (DIGITAL_SENSOR_PORT);
    // Getting values from the tuple using std::get<index>
    int sensorSmartPort = std::get<0>(sensor.get_port()); // First value
  int sensorAdiPort = std::get<1>(sensor.get_port()); // Second value
    // Prints the first and second value from the port tuple (The Adi Port. The first value is the Smart Port)
  printf("Sensor Smart Port: %d\n", sensorSmartPort);
  printf("Sensor Adi Port: %d\n", sensorAdiPort);
}
Reimplemented from pros::adi::Port.
Referenced by Robot::Globals::drive_(), Robot::Globals::drive_left(), and Robot::Globals::drive_right().
get_value()
std::int32_t pros::adi::Port::get_value () const
Gets the last set speed of the motor on the given port.
This function uses the following values of errno when an error state is reached: ENODEV - The port is not configured as a motor
Returns
The last set speed of the motor on the given
Example
#define MOTOR_PORT 1
void opcontrol() {
  pros::adi::Motor motor (MOTOR_PORT);
  motor.set_value(127); // Go full speed forward
  std::cout << "Commanded Motor Power: " << motor.get_value(); // Will display 127
  delay(1000);
  motor.set_value(0); // Stop the motor
}
set_value()
std::int32_t pros::adi::Port::set_value (std::int32_t value) const
Sets the speed of the motor on the given port.
This function uses the following values of errno when an error state is reached: ENODEV - The port is not configured as a motor
Parameters
value The new signed speed; -127 is full reverse and 127 is full forward, with 0 being off
Returns
1 if the operation was successful or PROS_ERR if the operation failed, setting errno.
Example
#define MOTOR_PORT 1
void opcontrol() {
  pros::adi::Motor motor (MOTOR_PORT);
  motor.set_value(127); // Go full speed forward
  std::cout << "Commanded Motor Power: " << motor.get_value(); // Will display 127
  delay(1000);
  motor.set_value(0); // Stop the motor
}
The documentation for this class was generated from the following file:
include/pros/adi.hpp