1516X High Stakes: Robot::Autonomous Class Reference
Robot::Autonomous Class Reference
The Autonomous class contains classes and functions related to the robot's autonomous behavior.
#include <auton.h>
Public Member Functions
void AutoDrive (Puncher &puncher, bool autono)
Drives the robot autonomously.
void AutonSwitcher ()
Switches the autonomous program.
Static Public Attributes
static int auton = 4
Sets the number of the autonomous program to use.
Private Member Functions
void Auton1 ()
Runs the autonomous path for the far side defensive game strategy.
void Auton2 ()
Runs the autonomous path for the near side offensive game strategy.
void Auton3 (Puncher &puncher)
Runs the puncher routine for the Skills Challenge.
void Auton4 ()
Private Attributes
std::string autonName
Detailed Description
The Autonomous class contains classes and functions related to the robot's autonomous behavior.
We use Lemlib extensively for our documentation. You can find the documentation for Lemlib at Lemlib documentation.
Definition at line 11 of file auton.h.
Member Function Documentation
AutoDrive()
void Autonomous::AutoDrive (Puncher & puncher, bool autono = false)
Drives the robot autonomously.
This function drives the robot autonomously based on the selected autonomous program. It takes a reference to a Puncher object and a boolean value indicating whether to use autonomous mode.
Parameters
puncher A reference to the Puncher object.
autono A boolean value indicating whether to use autonomous mode.
Definition at line 191 of file auton.cpp.
{
   // Keep the switcher running while the controller down button has not been pressed and the time period is not autonomous
   // Compare the current auton value to run the auton routine
    if(Autonomous::auton == 1){
        Auton1();
    }
    if(Autonomous::auton == 2){
        Auton2();
    }
    if(Autonomous::auton == 3){
        Auton3(puncher);
    }
   if(Autonomous::auton == 4){
        Auton4();
    }
}
References auton, Auton1(), Auton2(), Auton3(), and Auton4().
Auton1()
void Autonomous::Auton1 () private
Runs the autonomous path for the far side defensive game strategy.
This function executes the autonomous path for the far side defensive game strategy. It contains the specific actions and movements required for this strategy.
Definition at line 11 of file auton.cpp.
{
if(Autonomous::auton == 1){
   // Autonomous for Far side defensive zone.
   int imuOn = 0;
   if (imuOn == 1) {
      // 36.994 -58.128 0
      chassis.setPose(36.994, -58.128, 0);
      chassis.follow("home_side_auton_path_1.txt", 2000, 15);
      chassis.follow("home_side_auton_path_2.txt", 2000, 15);
      chassis.follow("home_side_auton_path_3.txt", 2000, 15);
      chassis.follow("home_side_auton_path_4.txt", 2000, 15);
      chassis.follow("home_side_auton_path_5.txt", 2000, 15);
      chassis.follow("home_side_auton_path_6.txt", 2000, 15);
   }
   else {
      drive_.move(-127);
      pros::delay(1900);
      // drive_left.move(100);
      // pros::delay(200);
      drive_.brake();
      drive_.move(65);
      pros::delay(500);
      drive_.brake();
      drive_.move(-127);
      pros::delay(1000);
      drive_.brake();
      drive_.move(65);
      pros::delay(200);
      drive_.brake();
   }
}
}
References auton, Robot::Globals::chassis, Robot::Globals::drive_, lemlib::Chassis::follow(), and lemlib::Chassis::setPose().
Referenced by AutoDrive().
Auton2()
void Autonomous::Auton2 () private
Runs the autonomous path for the near side offensive game strategy.
This function executes the autonomous path for the near side offensive game strategy. It contains the specific actions and movements required for this strategy.
Definition at line 46 of file auton.cpp.
{
   if(Autonomous::auton == 2){
      // Autonomous for near side offensive zone.
      int imuOn = 1;
      if (imuOn == 1) {
         // -36.851 -58.638 0
         chassis.setPose(-36.851, -58.638, 0);
         chassis.follow("far_side_auton_path_1.txt", 2000, 15);
         chassis.follow("far_side_auton_path_2.txt", 2000, 15);
         chassis.follow("far_side_auton_path_3.txt", 2000, 15);
         chassis.follow("far_side_auton_path_4.txt", 2000, 15);
      }
      else {
         drive_.move(-100);
         pros::delay(1700);
         drive_right.move(100);
         pros::delay(200);
         drive_.brake();
         drive_.move(-85);
         pros::delay(600);
         drive_.brake();
         drive_.move(85);
         pros::delay(150);
         drive_.brake();
      }
   }
}
References auton, Robot::Globals::chassis, Robot::Globals::drive_, Robot::Globals::drive_right, lemlib::Chassis::follow(), and lemlib::Chassis::setPose().
Referenced by AutoDrive().
Auton3()
void Autonomous::Auton3 (Puncher & puncher) private
Runs the puncher routine for the Skills Challenge.
This function executes the puncher routine for the Skills Challenge. It takes a reference to a Puncher object and performs the necessary actions for the challenge.
Parameters
puncher A reference to the Puncher object.
Definition at line 76 of file auton.cpp.
{
    // Autonomous routine for the Skills challenge
   for (int i=0; i < 30000; i++) {
      puncher.DistanceRun();
      pros::delay(1);
   }
   FrontWing.set_value(true);
   drive_.move(100);
   pros::delay(1700);
   drive_.brake();
   drive_left.move(75);
   pros::delay(75);
   drive_.brake();
   drive_.move(100);
   pros::delay(2000);
   drive_.brake();
   // else {
   //    for (int i=0; i < 30000; i++) {
   //       punchers.move(105);
   //       pros::delay(1);
   //    }
   // }
   // //movement
   // if (pros::c::registry_get_plugged_type(15) == pros::c::E_DEVICE_IMU) {
   //    chassis.setPose(-55.174, -55.383, 45);
   //    chassis.follow("auton_skills_1.txt", 5000, 15);
   //    chassis.follow("auton_skills_2.txt", 10000, 15);
   // }
}
References Robot::Puncher::DistanceRun(), Robot::Globals::drive_, Robot::Globals::drive_left, and Robot::Globals::FrontWing.
Referenced by AutoDrive().
Auton4()
void Autonomous::Auton4 () private
Definition at line 109 of file auton.cpp.
{
    // Autonomous routine for the Skills challenge
   // lemlib::Pose pose = chassis.getPose();
   // chassis.moveTo(0, 4, 2000);
   // IntakeMotor.move(88);
   // pros::delay(1400);
   // chassis.setPose(0, 0, 180);
   // chassis.moveTo(0, 37, 4000,65);
   // chassis.setPose(0, 0, 180);
   // chassis.turnTo(-22, 15, 2000);
   // chassis.setPose(0, 0, 0);
   // FrontWing.set_value(true);
   // chassis.moveTo(-20, 20, 2000, 120);
   // chassis.setPose(0, 0, 0);
   // chassis.turnTo(-25, -29, 2000, 70);
   // chassis.setPose(0, 0, 0);
   // IntakeMotor.move(-127);
   // chassis.moveTo(0, 10, 4000);
   // IntakeMotor.brake();
   // drive_.move(-70);
   // pros::delay(350);
   // drive_.brake();
   lemlib::Pose pose = chassis.getPose();
   chassis.moveTo(0, 4, 2000);
   IntakeMotor.move(88);
   pros::delay(600);
   chassis.setPose(0, 0, 180);
   chassis.moveTo(0, 37, 4000, 65);
   chassis.setPose(0, 0, 180);
   chassis.turnTo(22, -15, 2000);
   chassis.setPose(0, 0, 180);
   BackWing1.set_value(true);
   BackWing2.set_value(true);
   chassis.moveTo(-20, 20, 2000, 120);
   chassis.setPose(0, 0, 180);
   chassis.turnTo(-25, -29, 2000, 70);
   chassis.setPose(0, 0, 180);
   // IntakeMotor.move(-127);
   chassis.moveTo(0, 10, 4000);
   pros::delay(1000);
   BackWing1.set_value(false);
   BackWing2.set_value(false);
   drive_.move(80);
   pros::delay(500);
   drive_.brake();
   chassis.setPose(0, 0, 180);
   chassis.turnTo(-6, 40, 2000, 70);
   chassis.setPose(0, 0, 0);
   IntakeMotor.move(-127);
   chassis.moveTo(0, 10, 4000);
   pros::delay(750);
   drive_.move(-80);
   pros::delay(400);
   IntakeMotor.brake();
   drive_.move(-80);
   pros::delay(300);
   drive_.move(110);
   pros::delay(700);
   drive_.move(-80);
   pros::delay(400);
   drive_.brake();
   // else {
   //    for (int i=0; i < 30000; i++) {
   //       punchers.move(105);
   //       pros::delay(1);
   //    }
   // }
   // //movement
   // if (pros::c::registry_get_plugged_type(15) == pros::c::E_DEVICE_IMU) {
   //    chassis.setPose(-55.174, -55.383, 45);
   //    chassis.follow("auton_skills_1.txt", 5000, 15);
   //    chassis.follow("auton_skills_2.txt", 10000, 15);
   // }
}
References Robot::Globals::BackWing1, Robot::Globals::BackWing2, Robot::Globals::chassis, Robot::Globals::drive_, lemlib::Chassis::getPose(), Robot::Globals::IntakeMotor, and lemlib::Chassis::setPose().
Referenced by AutoDrive().
AutonSwitcher()
void Autonomous::AutonSwitcher ()
Switches the autonomous program.
Make sure to pass in a reference to the Puncher object with .
This function switches the autonomous program to the next available program. It allows the user to cycle through different autonomous programs during runtime.
Definition at line 213 of file auton.cpp.
{
    if(autonToggleSwitch.get_new_press()) {
         pros::lcd::clear_line(3);
         Autonomous::auton = auton + 1;
         // Checks if the toggler goes out of bounds.
         if (Autonomous::auton == 5) {
            Autonomous::auton = 1;
         }
         if (auton == 1) {
            autonName = "Far side defensive";
         }
         if (auton == 2) {
            autonName = "Home side offensive";
         }
         if (auton == 3) {
            autonName = "Skills Challenge";
         }
         if (auton == 4) {
            autonName = "Autonomous tuning";
         }
         // Set the controllet text to the current autonomous routine value
         pros::lcd::print(3, "Autonomous prog: %s", autonName);
   }
}
References auton, autonName, Robot::Globals::autonToggleSwitch, pros::lcd::clear_line(), and pros::lcd::print().
Referenced by Robot::Utility::toggleSubsystemOptions().
Member Data Documentation
auton
int Autonomous::auton = 4 static
Sets the number of the autonomous program to use.
This function allows the user to specify the autonomous program to be executed by the robot. The autonomous program number determines the specific actions and movements the robot will perform.
Parameters
auton The number of the autonomous program to use.
Definition at line 22 of file auton.h.
Referenced by AutoDrive(), Auton1(), Auton2(), and AutonSwitcher().
autonName
std::string Robot::Autonomous::autonName private
Definition at line 74 of file auton.h.
Referenced by AutonSwitcher().
The documentation for this class was generated from the following files:
include/robot/auton.h
src/routines/auton.cpp