1516X High Stakes: Robot::Puncher Class Reference
Robot::Puncher Class Reference
Represents a Puncher mechanism for a robot.
#include <puncher.h>
Public Member Functions
void UserRun ()
Runs the puncher based on the given autonomous value.
void DistanceRun ()
void ManualOverride ()
Puncher ()
void setDistancePuncher (int punch)
Sets the distancePuncher variable based on the punch parameter.
void PuncherSwitch ()
Toggles whether the distance sensor is activated or not and prints it out.
void run ()
Private Member Functions
int toShoot ()
Checks if the distance sensor is connected and whether to shoot.
Private Attributes
int distancePuncherBool
Determines whether to use the distance sensor or not.
Detailed Description
Represents a Puncher mechanism for a robot.
The Puncher class provides functionality to control a puncher mechanism on a robot. It allows running the puncher based on an autonomous value, setting the distancePuncher variable, toggling the distance sensor activation, and checking whether to shoot or not.
Definition at line 12 of file puncher.h.
Constructor & Destructor Documentation
Puncher()
Puncher::Puncher ()
Definition at line 68 of file puncher.cpp.
                 {
    Puncher::distancePuncherBool = 0;
}
References distancePuncherBool.
Member Function Documentation
DistanceRun()
void Puncher::DistanceRun ()
Definition at line 26 of file puncher.cpp.
{
    if (Puncher::toShoot() == 2) {
        Puncher::distancePuncherBool = 1;
    }
    if (Puncher::distancePuncherBool == 0) {
    // Distance Puncher Control
        if (distance.get() <= 20) {
            // if (Puncher::toShoot() == 1) {
            punchers.move(-127);
            }
        else {
            punchers.brake();
        }
    }
    else {
        Puncher::UserRun();
    }
}
References Robot::Globals::distance, distancePuncherBool, pros::v5::Distance::get(), Robot::Globals::punchers, toShoot(), and UserRun().
Referenced by Robot::Autonomous::Auton3(), and run().
ManualOverride()
void Puncher::ManualOverride ()
Definition at line 95 of file puncher.cpp.
{
    if(controller.get_digital_new_press(pros::E_CONTROLLER_DIGITAL_RIGHT)) {
        Puncher::distancePuncherBool = Puncher::distancePuncherBool + 1;
        if (Puncher::distancePuncherBool == 2) {
            Puncher::distancePuncherBool = 0;
        }
        std::printf("Puncher: %d\n", Puncher::distancePuncherBool);
        if (Puncher::distancePuncherBool == 0) {
            controller.print(0, 0, "Dist. punch on");
        }
        if (Puncher::distancePuncherBool == 1) {
            controller.print(0, 0, "Dist. punch off");
        }
    }
}
References Robot::Globals::controller, distancePuncherBool, pros::v5::Controller::get_digital_new_press(), and pros::v5::Controller::print().
PuncherSwitch()
void Puncher::PuncherSwitch ()
Toggles whether the distance sensor is activated or not and prints it out.
This function toggles the distance sensor activation by flipping the value of the distancePuncher variable. It then prints out the current state of the distancePuncher variable.
Definition at line 72 of file puncher.cpp.
{
    if(puncherToggleSwitch.get_new_press()) {
        pros::lcd::clear_line(1);
        Puncher::distancePuncherBool = Puncher::distancePuncherBool + 1;
        if (Puncher::distancePuncherBool == 2) {
            Puncher::distancePuncherBool = 0;
        }
        std::printf("Puncher: %d\n", Puncher::distancePuncherBool);
        if (Puncher::distancePuncherBool == 0) {
            pros::lcd::set_text(1, "Distance puncher on!");
        }
        if (Puncher::distancePuncherBool == 1) {
            pros::lcd::set_text(1, "Distance puncher off!");
        }
    }
}
References pros::lcd::clear_line(), distancePuncherBool, Robot::Globals::puncherToggleSwitch, and pros::lcd::set_text().
Referenced by Robot::Utility::toggleSubsystemOptions().
run()
void Puncher::run ()
Definition at line 48 of file puncher.cpp.
                  {
    if (Puncher::distancePuncherBool == 0) {
        Puncher::DistanceRun();
    }
    else {
        Puncher::UserRun();
    }
}
References distancePuncherBool, DistanceRun(), and UserRun().
setDistancePuncher()
void Robot::Puncher::setDistancePuncher (int punch)
Sets the distancePuncher variable based on the punch parameter.
This function sets the distancePuncher variable based on the provided punch parameter. The distancePuncher variable determines the behavior of the puncher mechanism.
Parameters
punch The value to set the distancePuncher variable to.
toShoot()
int Puncher::toShoot () private
Checks if the distance sensor is connected and whether to shoot.
This function checks if the distance sensor is connected and retrieves the distance from the triball. It uses the distance to determine whether to shoot or not.
Returns
The value returned of whether to shoot or not.
Definition at line 58 of file puncher.cpp.
                     {
    if (distance.get() <= 28) {
        return 1;
    }
    if (distance.get() > 28) {
        return 0;
    }
    return 0;
}
References Robot::Globals::distance, and pros::v5::Distance::get().
Referenced by DistanceRun(), and UserRun().
UserRun()
void Puncher::UserRun ()
Runs the puncher based on the given autonomous value.
This function executes the puncher mechanism based on the provided autonomous value. It contains conditionals that determine the behavior of the puncher.
Note
Make sure to have the Puncher object initialized before calling this function.
Parameters
autonVal The autonomous value to determine the puncher behavior.
Definition at line 11 of file puncher.cpp.
                      {
    if (toShoot() == 2) {
        Puncher::distancePuncherBool = 1;
    }
    // Manual Puncher Control
    if (Puncher::distancePuncherBool == 1) {
        if(controller.get_digital(pros::E_CONTROLLER_DIGITAL_R2)) {
            punchers.move(-127);
        }
        else {
            punchers.brake();
        }
    }
}
References Robot::Globals::controller, distancePuncherBool, pros::v5::Controller::get_digital(), Robot::Globals::punchers, and toShoot().
Referenced by DistanceRun(), and run().
Member Data Documentation
distancePuncherBool
int Robot::Puncher::distancePuncherBool private
Determines whether to use the distance sensor or not.
The distancePuncher variable decides whether to use the distance sensor or not. If distancePuncher is true, the distance sensor is used. If it is false, the distance sensor is not used.
Definition at line 71 of file puncher.h.
Referenced by Puncher(), DistanceRun(), ManualOverride(), PuncherSwitch(), run(), and UserRun().
The documentation for this class was generated from the following files:
include/robot/puncher.h
src/subsystems/puncher.cpp