1516X High Stakes: include/liblvgl/misc/lv_anim.h File Reference
lv_anim.h File Reference
#include "liblvgl/lv_conf_internal.h"
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>
Classes
struct _lv_anim_t
Macros
#define LV_ANIM_REPEAT_INFINITE 0xFFFF
#define LV_ANIM_PLAYTIME_INFINITE 0xFFFFFFFF
Typedefs
typedef int32_t(* lv_anim_path_cb_t) (const struct _lv_anim_t *)
typedef void(* lv_anim_exec_xcb_t) (void *, int32_t)
typedef void(* lv_anim_custom_exec_cb_t) (struct _lv_anim_t *, int32_t)
typedef void(* lv_anim_ready_cb_t) (struct _lv_anim_t *)
typedef void(* lv_anim_start_cb_t) (struct _lv_anim_t *)
typedef int32_t(* lv_anim_get_value_cb_t) (struct _lv_anim_t *)
typedef void(* lv_anim_deleted_cb_t) (struct _lv_anim_t *)
typedef struct _lv_anim_t lv_anim_t
Enumerations
enum lv_anim_enable_t { LV_ANIM_OFF , LV_ANIM_ON }
Functions
LV_EXPORT_CONST_INT (0xFFFF)
LV_EXPORT_CONST_INT (0xFFFFFFFF)
void _lv_anim_core_init (void)
void lv_anim_init (lv_anim_t *a)
static void lv_anim_set_var (lv_anim_t *a, void *var)
static void lv_anim_set_exec_cb (lv_anim_t *a, lv_anim_exec_xcb_t exec_cb)
static void lv_anim_set_time (lv_anim_t *a, uint32_t duration)
static void lv_anim_set_delay (lv_anim_t *a, uint32_t delay)
static void lv_anim_set_values (lv_anim_t *a, int32_t start, int32_t end)
static void lv_anim_set_custom_exec_cb (lv_anim_t *a, lv_anim_custom_exec_cb_t exec_cb)
static void lv_anim_set_path_cb (lv_anim_t *a, lv_anim_path_cb_t path_cb)
static void lv_anim_set_start_cb (lv_anim_t *a, lv_anim_start_cb_t start_cb)
static void lv_anim_set_get_value_cb (lv_anim_t *a, lv_anim_get_value_cb_t get_value_cb)
static void lv_anim_set_ready_cb (lv_anim_t *a, lv_anim_ready_cb_t ready_cb)
static void lv_anim_set_deleted_cb (lv_anim_t *a, lv_anim_deleted_cb_t deleted_cb)
static void lv_anim_set_playback_time (lv_anim_t *a, uint32_t time)
static void lv_anim_set_playback_delay (lv_anim_t *a, uint32_t delay)
static void lv_anim_set_repeat_count (lv_anim_t *a, uint16_t cnt)
static void lv_anim_set_repeat_delay (lv_anim_t *a, uint32_t delay)
static void lv_anim_set_early_apply (lv_anim_t *a, bool en)
lv_anim_t * lv_anim_start (const lv_anim_t *a)
static uint32_t lv_anim_get_delay (lv_anim_t *a)
uint32_t lv_anim_get_playtime (lv_anim_t *a)
bool lv_anim_del (void *var, lv_anim_exec_xcb_t exec_cb)
void lv_anim_del_all (void)
lv_anim_t * lv_anim_get (void *var, lv_anim_exec_xcb_t exec_cb)
struct _lv_timer_t * lv_anim_get_timer (void)
static bool lv_anim_custom_del (lv_anim_t *a, lv_anim_custom_exec_cb_t exec_cb)
static lv_anim_t * lv_anim_custom_get (lv_anim_t *a, lv_anim_custom_exec_cb_t exec_cb)
uint16_t lv_anim_count_running (void)
uint32_t lv_anim_speed_to_time (uint32_t speed, int32_t start, int32_t end)
void lv_anim_refr_now (void)
int32_t lv_anim_path_linear (const lv_anim_t *a)
int32_t lv_anim_path_ease_in (const lv_anim_t *a)
int32_t lv_anim_path_ease_out (const lv_anim_t *a)
int32_t lv_anim_path_ease_in_out (const lv_anim_t *a)
int32_t lv_anim_path_overshoot (const lv_anim_t *a)
int32_t lv_anim_path_bounce (const lv_anim_t *a)
int32_t lv_anim_path_step (const lv_anim_t *a)
Macro Definition Documentation
LV_ANIM_PLAYTIME_INFINITE
#define LV_ANIM_PLAYTIME_INFINITE 0xFFFFFFFF
Definition at line 27 of file lv_anim.h.
LV_ANIM_REPEAT_INFINITE
#define LV_ANIM_REPEAT_INFINITE 0xFFFF
Definition at line 26 of file lv_anim.h.
Typedef Documentation
lv_anim_custom_exec_cb_t
typedef void(* lv_anim_custom_exec_cb_t) (struct _lv_anim_t *, int32_t)
Same as lv_anim_exec_xcb_t but receives lv_anim_t * as the first parameter. It's more consistent but less convenient. Might be used by binding generator functions.
Definition at line 58 of file lv_anim.h.
lv_anim_deleted_cb_t
typedef void(* lv_anim_deleted_cb_t) (struct _lv_anim_t *)
Callback used when the animation is deleted
Definition at line 70 of file lv_anim.h.
lv_anim_exec_xcb_t
typedef void(* lv_anim_exec_xcb_t) (void *, int32_t)
Generic prototype of "animator" functions. First parameter is the variable to animate. Second parameter is the value to set. Compatible with lv_xxx_set_yyy(obj, value) functions The x in _xcb_t means it's not a fully generic prototype because it doesn't receive lv_anim_t * as its first argument
Definition at line 54 of file lv_anim.h.
lv_anim_get_value_cb_t
typedef int32_t(* lv_anim_get_value_cb_t) (struct _lv_anim_t *)
Callback used when the animation values are relative to get the current value
Definition at line 67 of file lv_anim.h.
lv_anim_path_cb_t
typedef int32_t(* lv_anim_path_cb_t) (const struct _lv_anim_t *)
Get the current value during an animation
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/misc/lv_style.h.
Definition at line 46 of file lv_anim.h.
lv_anim_ready_cb_t
typedef void(* lv_anim_ready_cb_t) (struct _lv_anim_t *)
Callback to call when the animation is ready
Definition at line 61 of file lv_anim.h.
lv_anim_start_cb_t
typedef void(* lv_anim_start_cb_t) (struct _lv_anim_t *)
Callback to call when the animation really stars (considering delay)
Definition at line 64 of file lv_anim.h.
lv_anim_t
typedef struct _lv_anim_t lv_anim_t
Describes an animation
Enumeration Type Documentation
lv_anim_enable_t
enum lv_anim_enable_t
Can be used to indicate if animations are enabled or disabled in a case
Enumerator
LV_ANIM_OFF
LV_ANIM_ON
Definition at line 37 of file lv_anim.h.
             {
    LV_ANIM_OFF,
    LV_ANIM_ON,
} lv_anim_enable_t;
Function Documentation
_lv_anim_core_init()
void _lv_anim_core_init (void)
Init. the animation module
lv_anim_count_running()
uint16_t lv_anim_count_running (void)
Get the number of currently running animations
Returns
the number of running animations
lv_anim_custom_del()
static bool lv_anim_custom_del (lv_anim_t * a, lv_anim_custom_exec_cb_t exec_cb) inline static
Delete an animation by getting the animated variable from a. Only animations with exec_cb will be deleted. This function exists because it's logical that all anim. functions receives an lv_anim_t as their first parameter. It's not practical in C but might make the API more consequent and makes easier to generate bindings.
Parameters
a pointer to an animation.
exec_cb a function pointer which is animating 'var', or NULL to ignore it and delete all the animations of 'var
Returns
true: at least 1 animation is deleted, false: no animation is deleted
Definition at line 380 of file lv_anim.h.
{
    return lv_anim_del(a ? a->var : NULL, (lv_anim_exec_xcb_t)exec_cb);
}
References lv_anim_del(), and _lv_anim_t::var.
lv_anim_custom_get()
static lv_anim_t * lv_anim_custom_get (lv_anim_t * a, lv_anim_custom_exec_cb_t exec_cb) inline static
Get the animation of a variable and its exec_cb. This function exists because it's logical that all anim. functions receives an lv_anim_t as their first parameter. It's not practical in C but might make the API more consequent and makes easier to generate bindings.
Parameters
a pointer to an animation.
exec_cb a function pointer which is animating 'var', or NULL to return first matching 'var'
Returns
pointer to the animation.
Definition at line 394 of file lv_anim.h.
{
    return lv_anim_get(a ? a->var : NULL, (lv_anim_exec_xcb_t)exec_cb);
}
References lv_anim_get(), and _lv_anim_t::var.
lv_anim_del()
bool lv_anim_del (void * var, lv_anim_exec_xcb_t exec_cb)
Get the user_data field of the animation
Parameters
a pointer to an initialized lv_anim_t variable
Returns
the pointer to the custom user_data of the animation Delete an animation of a variable with a given animator function
Parameters
var pointer to variable
exec_cb a function pointer which is animating 'var', or NULL to ignore it and delete all the animations of 'var
Returns
true: at least 1 animation is deleted, false: no animation is deleted
Referenced by lv_anim_custom_del().
lv_anim_del_all()
void lv_anim_del_all (void)
Delete all the animations
lv_anim_get()
lv_anim_t * lv_anim_get (void * var, lv_anim_exec_xcb_t exec_cb)
Get the animation of a variable and its exec_cb.
Parameters
var pointer to variable
exec_cb a function pointer which is animating 'var', or NULL to return first matching 'var'
Returns
pointer to the animation.
Referenced by lv_anim_custom_get().
lv_anim_get_delay()
static uint32_t lv_anim_get_delay (lv_anim_t * a) inline static
Get a delay before starting the animation
Parameters
a pointer to an initialized lv_anim_t variable
Returns
delay before the animation in milliseconds
Definition at line 317 of file lv_anim.h.
{
    return -a->act_time;
}
References _lv_anim_t::act_time.
lv_anim_get_playtime()
uint32_t lv_anim_get_playtime (lv_anim_t * a)
Get the time used to play the animation.
Parameters
a pointer to an animation.
Returns
the play time in milliseconds.
lv_anim_get_timer()
struct _lv_timer_t * lv_anim_get_timer (void)
Get global animation refresher timer.
Returns
pointer to the animation refresher timer.
lv_anim_init()
void lv_anim_init (lv_anim_t * a)
Initialize an animation variable. E.g.: lv_anim_t a; lv_anim_init(&a); lv_anim_set_...(&a); lv_anim_start(&a);
Parameters
a pointer to an lv_anim_t variable to initialize
lv_anim_path_bounce()
int32_t lv_anim_path_bounce (const lv_anim_t * a)
Calculate the current value of an animation with 3 bounces
Parameters
a pointer to an animation
Returns
the current value to set
lv_anim_path_ease_in()
int32_t lv_anim_path_ease_in (const lv_anim_t * a)
Calculate the current value of an animation slowing down the start phase
Parameters
a pointer to an animation
Returns
the current value to set
lv_anim_path_ease_in_out()
int32_t lv_anim_path_ease_in_out (const lv_anim_t * a)
Calculate the current value of an animation applying an "S" characteristic (cosine)
Parameters
a pointer to an animation
Returns
the current value to set
lv_anim_path_ease_out()
int32_t lv_anim_path_ease_out (const lv_anim_t * a)
Calculate the current value of an animation slowing down the end phase
Parameters
a pointer to an animation
Returns
the current value to set
lv_anim_path_linear()
int32_t lv_anim_path_linear (const lv_anim_t * a)
Calculate the current value of an animation applying linear characteristic
Parameters
a pointer to an animation
Returns
the current value to set
lv_anim_path_overshoot()
int32_t lv_anim_path_overshoot (const lv_anim_t * a)
Calculate the current value of an animation with overshoot at the end
Parameters
a pointer to an animation
Returns
the current value to set
lv_anim_path_step()
int32_t lv_anim_path_step (const lv_anim_t * a)
Calculate the current value of an animation applying step characteristic. (Set end value on the end of the animation)
Parameters
a pointer to an animation
Returns
the current value to set
lv_anim_refr_now()
void lv_anim_refr_now (void)
Manually refresh the state of the animations. Useful to make the animations running in a blocking process where lv_timer_handler can't run for a while. Shouldn't be used directly because it is called in lv_refr_now().
lv_anim_set_custom_exec_cb()
static void lv_anim_set_custom_exec_cb (lv_anim_t * a, lv_anim_custom_exec_cb_t exec_cb) inline static
Similar to lv_anim_set_exec_cb but lv_anim_custom_exec_cb_t receives lv_anim_t * as its first parameter instead of void *. This function might be used when LVGL is bound to other languages because it's more consistent to have lv_anim_t * as first parameter. The variable to animate can be stored in the animation's user_data
Parameters
a pointer to an initialized lv_anim_t variable
exec_cb a function to execute.
Definition at line 185 of file lv_anim.h.
{
    a->var     = a;
    a->exec_cb = (lv_anim_exec_xcb_t)exec_cb;
}
References _lv_anim_t::exec_cb, and _lv_anim_t::var.
lv_anim_set_delay()
static void lv_anim_set_delay (lv_anim_t * a, uint32_t delay) inline static
Set a delay before starting the animation
Parameters
a pointer to an initialized lv_anim_t variable
delay delay before the animation in milliseconds
Definition at line 158 of file lv_anim.h.
{
    a->act_time = -(int32_t)(delay);
}
References _lv_anim_t::act_time.
lv_anim_set_deleted_cb()
static void lv_anim_set_deleted_cb (lv_anim_t * a, lv_anim_deleted_cb_t deleted_cb) inline static
Set a function call when the animation is deleted.
Parameters
a pointer to an initialized lv_anim_t variable
deleted_cb a function call when the animation is deleted
Definition at line 237 of file lv_anim.h.
{
    a->deleted_cb = deleted_cb;
}
References _lv_anim_t::deleted_cb.
lv_anim_set_early_apply()
static void lv_anim_set_early_apply (lv_anim_t * a, bool en) inline static
Set a whether the animation's should be applied immediately or only when the delay expired.
Parameters
a pointer to an initialized lv_anim_t variable
en true: apply the start value immediately in lv_anim_start; false: apply the start value only when delay ms is elapsed and the animations really starts
Definition at line 288 of file lv_anim.h.
{
    a->early_apply = en;
}
References _lv_anim_t::early_apply.
lv_anim_set_exec_cb()
static void lv_anim_set_exec_cb (lv_anim_t * a, lv_anim_exec_xcb_t exec_cb) inline static
Set a function to animate var
Parameters
a pointer to an initialized lv_anim_t variable
exec_cb a function to execute during animation LVGL's built-in functions can be used. E.g. lv_obj_set_x
Definition at line 138 of file lv_anim.h.
{
    a->exec_cb = exec_cb;
}
References _lv_anim_t::exec_cb.
lv_anim_set_get_value_cb()
static void lv_anim_set_get_value_cb (lv_anim_t * a, lv_anim_get_value_cb_t get_value_cb) inline static
Set a function to use the current value of the variable and make start and end value relative to the returned current value.
Parameters
a pointer to an initialized lv_anim_t variable
get_value_cb a function call when the animation starts
Definition at line 217 of file lv_anim.h.
{
    a->get_value_cb = get_value_cb;
}
References _lv_anim_t::get_value_cb.
lv_anim_set_path_cb()
static void lv_anim_set_path_cb (lv_anim_t * a, lv_anim_path_cb_t path_cb) inline static
Set the path (curve) of the animation.
Parameters
a pointer to an initialized lv_anim_t variable
path_cb a function to set the current value of the animation.
Definition at line 196 of file lv_anim.h.
{
    a->path_cb = path_cb;
}
References _lv_anim_t::path_cb.
lv_anim_set_playback_delay()
static void lv_anim_set_playback_delay (lv_anim_t * a, uint32_t delay) inline static
Make the animation to play back to when the forward direction is ready
Parameters
a pointer to an initialized lv_anim_t variable
delay delay in milliseconds before starting the playback animation.
Definition at line 257 of file lv_anim.h.
{
    a->playback_delay = delay;
}
References delay(), and _lv_anim_t::playback_delay.
lv_anim_set_playback_time()
static void lv_anim_set_playback_time (lv_anim_t * a, uint32_t time) inline static
Make the animation to play back to when the forward direction is ready
Parameters
a pointer to an initialized lv_anim_t variable
time the duration of the playback animation in milliseconds. 0: disable playback
Definition at line 247 of file lv_anim.h.
{
    a->playback_time = time;
}
References _lv_anim_t::playback_time.
lv_anim_set_ready_cb()
static void lv_anim_set_ready_cb (lv_anim_t * a, lv_anim_ready_cb_t ready_cb) inline static
Set a function call when the animation is ready
Parameters
a pointer to an initialized lv_anim_t variable
ready_cb a function call when the animation is ready
Definition at line 227 of file lv_anim.h.
{
    a->ready_cb = ready_cb;
}
References _lv_anim_t::ready_cb.
lv_anim_set_repeat_count()
static void lv_anim_set_repeat_count (lv_anim_t * a, uint16_t cnt) inline static
Make the animation repeat itself.
Parameters
a pointer to an initialized lv_anim_t variable
cnt repeat count or LV_ANIM_REPEAT_INFINITE for infinite repetition. 0: to disable repetition.
Definition at line 267 of file lv_anim.h.
{
    a->repeat_cnt = cnt;
}
References _lv_anim_t::repeat_cnt.
lv_anim_set_repeat_delay()
static void lv_anim_set_repeat_delay (lv_anim_t * a, uint32_t delay) inline static
Set a delay before repeating the animation.
Parameters
a pointer to an initialized lv_anim_t variable
delay delay in milliseconds before repeating the animation.
Definition at line 277 of file lv_anim.h.
{
    a->repeat_delay = delay;
}
References delay(), and _lv_anim_t::repeat_delay.
lv_anim_set_start_cb()
static void lv_anim_set_start_cb (lv_anim_t * a, lv_anim_start_cb_t start_cb) inline static
Set a function call when the animation really starts (considering delay)
Parameters
a pointer to an initialized lv_anim_t variable
start_cb a function call when the animation starts
Definition at line 206 of file lv_anim.h.
{
    a->start_cb = start_cb;
}
References _lv_anim_t::start_cb.
lv_anim_set_time()
static void lv_anim_set_time (lv_anim_t * a, uint32_t duration) inline static
Set the duration of an animation
Parameters
a pointer to an initialized lv_anim_t variable
duration duration of the animation in milliseconds
Definition at line 148 of file lv_anim.h.
{
    a->time = duration;
}
References _lv_anim_t::time.
lv_anim_set_values()
static void lv_anim_set_values (lv_anim_t * a, int32_t start, int32_t end) inline static
Set the start and end values of an animation
Parameters
a pointer to an initialized lv_anim_t variable
start the start value
end the end value
Definition at line 169 of file lv_anim.h.
{
    a->start_value = start;
    a->current_value = start;
    a->end_value = end;
}
References _lv_anim_t::current_value, _lv_anim_t::end_value, and _lv_anim_t::start_value.
lv_anim_set_var()
static void lv_anim_set_var (lv_anim_t * a, void * var) inline static
Set a variable to animate
Parameters
a pointer to an initialized lv_anim_t variable
var pointer to a variable to animate
Definition at line 126 of file lv_anim.h.
{
    a->var = var;
}
References _lv_anim_t::var.
lv_anim_speed_to_time()
uint32_t lv_anim_speed_to_time (uint32_t speed, int32_t start, int32_t end)
Calculate the time of an animation with a given speed and the start and end values
Parameters
speed speed of animation in unit/sec
start start value of the animation
end end value of the animation
Returns
the required time [ms] for the animation with the given parameters
lv_anim_start()
lv_anim_t * lv_anim_start (const lv_anim_t * a)
Set the custom user data field of the animation.
Parameters
a pointer to an initialized lv_anim_t variable
user_data pointer to the new user_data. Create an animation
a an initialized 'anim_t' variable. Not required after call.
Returns
pointer to the created animation (different from the a parameter)
LV_EXPORT_CONST_INT() [1/2]
LV_EXPORT_CONST_INT (0xFFFF)
LV_EXPORT_CONST_INT() [2/2]
LV_EXPORT_CONST_INT (0xFFFFFFFF)