1516X High Stakes: include/liblvgl/widgets/lv_label.h File Reference
lv_label.h File Reference
#include "../lv_conf_internal.h"
#include <stdarg.h>
#include "liblvgl/core/lv_obj.h"
#include "liblvgl/font/lv_font.h"
#include "liblvgl/font/lv_symbol_def.h"
#include "liblvgl/misc/lv_txt.h"
#include "liblvgl/draw/lv_draw.h"
Classes
struct lv_label_t
Macros
#define LV_LABEL_WAIT_CHAR_COUNT 3
#define LV_LABEL_DOT_NUM 3
#define LV_LABEL_POS_LAST 0xFFFF
#define LV_LABEL_TEXT_SELECTION_OFF LV_DRAW_LABEL_NO_TXT_SEL
Typedefs
typedef uint8_t lv_label_long_mode_t
Enumerations
enum {
LV_LABEL_LONG_WRAP , LV_LABEL_LONG_DOT , LV_LABEL_LONG_SCROLL , LV_LABEL_LONG_SCROLL_CIRCULAR ,
LV_LABEL_LONG_CLIP
}
Functions
lv_obj_t * lv_label_create (lv_obj_t *parent)
void lv_label_set_text (lv_obj_t *obj, const char *text)
void lv_label_set_text_fmt (lv_obj_t *obj, const char *fmt,...) LV_FORMAT_ATTRIBUTE(2
void void lv_label_set_text_static (lv_obj_t *obj, const char *text)
void lv_label_set_long_mode (lv_obj_t *obj, lv_label_long_mode_t long_mode)
void lv_label_set_recolor (lv_obj_t *obj, bool en)
void lv_label_set_text_sel_start (lv_obj_t *obj, uint32_t index)
void lv_label_set_text_sel_end (lv_obj_t *obj, uint32_t index)
char * lv_label_get_text (const lv_obj_t *obj)
lv_label_long_mode_t lv_label_get_long_mode (const lv_obj_t *obj)
bool lv_label_get_recolor (const lv_obj_t *obj)
void lv_label_get_letter_pos (const lv_obj_t *obj, uint32_t char_id, lv_point_t *pos)
uint32_t lv_label_get_letter_on (const lv_obj_t *obj, lv_point_t *pos_in)
bool lv_label_is_char_under_pos (const lv_obj_t *obj, lv_point_t *pos)
uint32_t lv_label_get_text_selection_start (const lv_obj_t *obj)
Get the selection start index.
uint32_t lv_label_get_text_selection_end (const lv_obj_t *obj)
Get the selection end index.
void lv_label_ins_text (lv_obj_t *obj, uint32_t pos, const char *txt)
void lv_label_cut_text (lv_obj_t *obj, uint32_t pos, uint32_t cnt)
Variables
const lv_obj_class_t lv_label_class
Macro Definition Documentation
LV_LABEL_DOT_NUM
#define LV_LABEL_DOT_NUM 3
Definition at line 31 of file lv_label.h.
LV_LABEL_POS_LAST
#define LV_LABEL_POS_LAST 0xFFFF
Definition at line 32 of file lv_label.h.
LV_LABEL_TEXT_SELECTION_OFF
#define LV_LABEL_TEXT_SELECTION_OFF LV_DRAW_LABEL_NO_TXT_SEL
Definition at line 33 of file lv_label.h.
LV_LABEL_WAIT_CHAR_COUNT
#define LV_LABEL_WAIT_CHAR_COUNT 3
Definition at line 30 of file lv_label.h.
Typedef Documentation
lv_label_long_mode_t
typedef uint8_t lv_label_long_mode_t
Definition at line 51 of file lv_label.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Long mode behaviors. Used in 'lv_label_ext_t'
Enumerator
LV_LABEL_LONG_WRAP
Keep the object width, wrap the too long lines and expand the object height
LV_LABEL_LONG_DOT
Keep the size and write dots at the end if the text is too long
LV_LABEL_LONG_SCROLL
Keep the size and roll the text back and forth
LV_LABEL_LONG_SCROLL_CIRCULAR
Keep the size and roll the text circularly
LV_LABEL_LONG_CLIP
Keep the size and clip the text out of it
Definition at line 44 of file lv_label.h.
     {
    LV_LABEL_LONG_WRAP,
    LV_LABEL_LONG_DOT,
    LV_LABEL_LONG_SCROLL,
    LV_LABEL_LONG_SCROLL_CIRCULAR,
    LV_LABEL_LONG_CLIP,
};
Function Documentation
lv_label_create()
lv_obj_t * lv_label_create (lv_obj_t * parent)
Create a label object
Parameters
parent pointer to an object, it will be the parent of the new label.
Returns
pointer to the created button
Referenced by Robot::selector_screen::selector().
lv_label_cut_text()
void lv_label_cut_text (lv_obj_t * obj, uint32_t pos, uint32_t cnt)
Delete characters from a label. The label text can not be static.
Parameters
obj pointer to a label object
pos character index from where to cut. Expressed in character index and not byte index. 0: start in from of the first character
cnt number of characters to cut
lv_label_get_letter_on()
uint32_t lv_label_get_letter_on (const lv_obj_t * obj, lv_point_t * pos_in)
Get the index of letter on a relative point of a label.
Parameters
obj pointer to label object
pos pointer to point with coordinates on a the label
Returns
The index of the letter on the 'pos_p' point (E.g. on 0;0 is the 0. letter if aligned to the left) Expressed in character index and not byte index (different in UTF-8)
lv_label_get_letter_pos()
void lv_label_get_letter_pos (const lv_obj_t * obj, uint32_t char_id, lv_point_t * pos)
Get the relative x and y coordinates of a letter
Parameters
obj pointer to a label object
index index of the character [0 ... text length - 1]. Expressed in character index, not byte index (different in UTF-8)
pos store the result here (E.g. index = 0 gives 0;0 coordinates if the text if aligned to the left)
lv_label_get_long_mode()
lv_label_long_mode_t lv_label_get_long_mode (const lv_obj_t * obj)
Get the long mode of a label
Parameters
obj pointer to a label object
Returns
the current long mode
lv_label_get_recolor()
bool lv_label_get_recolor (const lv_obj_t * obj)
Get the recoloring attribute
Parameters
obj pointer to a label object
Returns
true: recoloring is enabled, false: disable
lv_label_get_text()
char * lv_label_get_text (const lv_obj_t * obj)
Get the text of a label
Parameters
obj pointer to a label object
Returns
the text of the label
lv_label_get_text_selection_end()
uint32_t lv_label_get_text_selection_end (const lv_obj_t * obj)
Get the selection end index.
Parameters
obj pointer to a label object.
Returns
selection end index. LV_LABEL_TXT_SEL_OFF if nothing is selected.
lv_label_get_text_selection_start()
uint32_t lv_label_get_text_selection_start (const lv_obj_t * obj)
Get the selection start index.
Parameters
obj pointer to a label object.
Returns
selection start index. LV_LABEL_TEXT_SELECTION_OFF if nothing is selected.
lv_label_ins_text()
void lv_label_ins_text (lv_obj_t * obj, uint32_t pos, const char * txt)
Insert a text to a label. The label text can not be static.
Parameters
obj pointer to a label object
pos character index to insert. Expressed in character index and not byte index. 0: before first char. LV_LABEL_POS_LAST: after last char.
txt pointer to the text to insert
lv_label_is_char_under_pos()
bool lv_label_is_char_under_pos (const lv_obj_t * obj, lv_point_t * pos)
Check if a character is drawn under a point.
Parameters
obj pointer to a label object
pos Point to check for character under
Returns
whether a character is drawn under the point
lv_label_set_long_mode()
void lv_label_set_long_mode (lv_obj_t * obj, lv_label_long_mode_t long_mode)
Set the behavior of the label with longer text then the object size
Parameters
obj pointer to a label object
long_mode the new mode from 'lv_label_long_mode' enum. In LV_LONG_WRAP/DOT/SCROLL/SCROLL_CIRC the size of the label should be set AFTER this function
lv_label_set_recolor()
void lv_label_set_recolor (lv_obj_t * obj, bool en)
lv_label_set_text()
void lv_label_set_text (lv_obj_t * obj, const char * text)
Set a new text for a label. Memory will be allocated to store the text by the label.
Parameters
obj pointer to a label object
text '\0' terminated character string. NULL to refresh with the current text.
Referenced by Robot::selector_screen::selector().
lv_label_set_text_fmt()
void lv_label_set_text_fmt (lv_obj_t * obj, const char * fmt, ...)
Referenced by Robot::selector_screen::auton_ui_update(), drive_update(), and Robot::selector_screen::selector().
lv_label_set_text_sel_end()
void lv_label_set_text_sel_end (lv_obj_t * obj, uint32_t index)
Set where text selection should end
Parameters
obj pointer to a label object
index character index where selection should end. LV_LABEL_TEXT_SELECTION_OFF for no selection
lv_label_set_text_sel_start()
void lv_label_set_text_sel_start (lv_obj_t * obj, uint32_t index)
Set where text selection should start
Parameters
obj pointer to a label object
index character index from where selection should start. LV_LABEL_TEXT_SELECTION_OFF for no selection
lv_label_set_text_static()
void void lv_label_set_text_static (lv_obj_t * obj, const char * text)
Set a static text. It will not be saved by the label so the 'text' variable has to be 'alive' while the label exists.
Parameters
obj pointer to a label object
text pointer to a text. NULL to refresh with the current text.
Variable Documentation
lv_label_class
const lv_obj_class_t lv_label_class extern