1516X High Stakes: fmt::v10::basic_format_context< OutputIt, Char > Class Template Reference
fmt::v10::basic_format_context< OutputIt, Char > Class Template Reference
#include <core.h>
Public Types
using iterator = OutputIt
using format_arg = basic_format_arg<basic_format_context>
using format_args = basic_format_args<basic_format_context>
using parse_context_type = basic_format_parse_context<Char>
template<typename T >
using formatter_type = formatter<T, Char>
using char_type = Char
Public Member Functions
basic_format_context (basic_format_context &&)=default
basic_format_context (const basic_format_context &)=delete
void operator= (const basic_format_context &)=delete
constexpr basic_format_context (OutputIt out, format_args ctx_args, detail::locale_ref loc={})
constexpr auto arg (int id) const -> format_arg
auto arg (basic_string_view< Char > name) -> format_arg
auto arg_id (basic_string_view< Char > name) -> int
auto args () const -> const format_args &
auto error_handler () -> detail::error_handler
void on_error (const char *message)
auto out () -> iterator
void advance_to (iterator it)
auto locale () -> detail::locale_ref
Private Attributes
OutputIt out_
basic_format_args< basic_format_context > args_
detail::locale_ref loc_
Detailed Description
template<typename OutputIt, typename Char>
class fmt::v10::basic_format_context< OutputIt, Char >
Definition at line 1576 of file core.h.
Member Typedef Documentation
char_type
template<typename OutputIt , typename Char > using fmt::v10::basic_format_context< OutputIt, Char >::char_type = Char
The character type for the output.
Definition at line 1589 of file core.h.
format_arg
template<typename OutputIt , typename Char > using fmt::v10::basic_format_context< OutputIt, Char >::format_arg = basic_format_arg<basic_format_context>
Definition at line 1583 of file core.h.
format_args
template<typename OutputIt , typename Char > using fmt::v10::basic_format_context< OutputIt, Char >::format_args = basic_format_args<basic_format_context>
Definition at line 1584 of file core.h.
formatter_type
template<typename OutputIt , typename Char > template<typename T > using fmt::v10::basic_format_context< OutputIt, Char >::formatter_type = formatter<T, Char>
Definition at line 1586 of file core.h.
iterator
template<typename OutputIt , typename Char > using fmt::v10::basic_format_context< OutputIt, Char >::iterator = OutputIt
Definition at line 1582 of file core.h.
parse_context_type
template<typename OutputIt , typename Char > using fmt::v10::basic_format_context< OutputIt, Char >::parse_context_type = basic_format_parse_context<Char>
Definition at line 1585 of file core.h.
Constructor & Destructor Documentation
basic_format_context() [1/3]
template<typename OutputIt , typename Char > fmt::v10::basic_format_context< OutputIt, Char >::basic_format_context (basic_format_context< OutputIt, Char > &&) default
basic_format_context() [2/3]
template<typename OutputIt , typename Char > fmt::v10::basic_format_context< OutputIt, Char >::basic_format_context (const basic_format_context< OutputIt, Char > &) delete
basic_format_context() [3/3]
template<typename OutputIt , typename Char > fmt::v10::basic_format_context< OutputIt, Char >::basic_format_context (OutputIt out, format_args ctx_args, detail::locale_ref loc = {}) inline constexpr
Constructs a basic_format_context object. References to the arguments are stored in the object so make sure they have appropriate lifetimes.
Definition at line 1599 of file core.h.
                                                                                                  {})
            : out_(out), args_(ctx_args), loc_(loc) {}
Member Function Documentation
advance_to()
template<typename OutputIt , typename Char > void fmt::v10::basic_format_context< OutputIt, Char >::advance_to (iterator it) inline
Definition at line 1618 of file core.h.
{
            if (!detail::is_back_insert_iterator<iterator>()) out_ = it;
        }
Referenced by fmt::v10::detail::vformat_to().
arg() [1/2]
template<typename OutputIt , typename Char > auto fmt::v10::basic_format_context< OutputIt, Char >::arg (basic_string_view< Char > name) -> format_arg inline
Definition at line 1604 of file core.h.
{ return args_.get(name); }
References fmt::v10::basic_format_args< Context >::get().
arg() [2/2]
template<typename OutputIt , typename Char > auto fmt::v10::basic_format_context< OutputIt, Char >::arg (int id) const -> format_arg inline constexpr
Definition at line 1602 of file core.h.
{ return args_.get(id); }
References fmt::v10::basic_format_args< Context >::get().
arg_id()
template<typename OutputIt , typename Char > auto fmt::v10::basic_format_context< OutputIt, Char >::arg_id (basic_string_view< Char > name) -> int inline
Definition at line 1606 of file core.h.
{ return args_.get_id(name); }
References fmt::v10::basic_format_args< Context >::get_id().
Referenced by fmt::v10::detail::vformat_to().
args()
template<typename OutputIt , typename Char > auto fmt::v10::basic_format_context< OutputIt, Char >::args () const -> const format_args& inline
Definition at line 1608 of file core.h.
{ return args_; }
Referenced by fmt::v10::detail::vformat_to().
error_handler()
template<typename OutputIt , typename Char > auto fmt::v10::basic_format_context< OutputIt, Char >::error_handler () -> detail::error_handler inline
Definition at line 1610 of file core.h.
{ return {}; }
locale()
template<typename OutputIt , typename Char > auto fmt::v10::basic_format_context< OutputIt, Char >::locale () -> detail::locale_ref inline
Definition at line 1622 of file core.h.
{ return loc_; }
Referenced by fmt::v10::detail::vformat_to().
on_error()
template<typename OutputIt , typename Char > void fmt::v10::basic_format_context< OutputIt, Char >::on_error (const char * message) inline
Definition at line 1612 of file core.h.
{ error_handler().on_error(message); }
Referenced by fmt::v10::detail::parse_format_string(), and fmt::v10::detail::parse_replacement_field().
operator=()
template<typename OutputIt , typename Char > void fmt::v10::basic_format_context< OutputIt, Char >::operator= (const basic_format_context< OutputIt, Char > &) delete
out()
template<typename OutputIt , typename Char > auto fmt::v10::basic_format_context< OutputIt, Char >::out () -> iterator inline
Definition at line 1615 of file core.h.
{ return out_; }
Referenced by fmt::v10::detail::vformat_to().
Member Data Documentation
args_
template<typename OutputIt , typename Char > basic_format_args<basic_format_context> fmt::v10::basic_format_context< OutputIt, Char >::args_ private
Definition at line 1579 of file core.h.
loc_
template<typename OutputIt , typename Char > detail::locale_ref fmt::v10::basic_format_context< OutputIt, Char >::loc_ private
Definition at line 1580 of file core.h.
out_
template<typename OutputIt , typename Char > OutputIt fmt::v10::basic_format_context< OutputIt, Char >::out_ private
Definition at line 1578 of file core.h.
The documentation for this class was generated from the following file:
include/fmt/core.h