1516X High Stakes: fmt::v10::detail::dynamic_spec_id_handler< Char > Struct Template Reference
fmt::v10::detail::dynamic_spec_id_handler< Char > Struct Template Reference
#include <core.h>
Public Member Functions
void on_auto ()
void on_index (int id)
void on_name (basic_string_view< Char > id)
Public Attributes
basic_format_parse_context< Char > & ctx
arg_ref< Char > & ref
Detailed Description
template<typename Char>
struct fmt::v10::detail::dynamic_spec_id_handler< Char >
Definition at line 2035 of file core.h.
Member Function Documentation
on_auto()
template<typename Char > void fmt::v10::detail::dynamic_spec_id_handler< Char >::on_auto () inline
Definition at line 2039 of file core.h.
{
            int id = ctx.next_arg_id();
            ref = arg_ref<Char>(id);
            ctx.check_dynamic_spec(id);
        }
References fmt::v10::basic_format_parse_context< Char >::check_dynamic_spec(), and fmt::v10::basic_format_parse_context< Char >::next_arg_id().
on_index()
template<typename Char > void fmt::v10::detail::dynamic_spec_id_handler< Char >::on_index (int id) inline
Definition at line 2045 of file core.h.
{
            ref = arg_ref<Char>(id);
            ctx.check_arg_id(id);
            ctx.check_dynamic_spec(id);
        }
References fmt::v10::basic_format_parse_context< Char >::check_arg_id(), and fmt::v10::basic_format_parse_context< Char >::check_dynamic_spec().
on_name()
template<typename Char > void fmt::v10::detail::dynamic_spec_id_handler< Char >::on_name (basic_string_view< Char > id) inline
Definition at line 2051 of file core.h.
{
            ref = arg_ref<Char>(id);
            ctx.check_arg_id(id);
        }
References fmt::v10::basic_format_parse_context< Char >::check_arg_id().
Member Data Documentation
ctx
template<typename Char > basic_format_parse_context<Char>& fmt::v10::detail::dynamic_spec_id_handler< Char >::ctx
Definition at line 2036 of file core.h.
ref
template<typename Char > arg_ref<Char>& fmt::v10::detail::dynamic_spec_id_handler< Char >::ref
Definition at line 2037 of file core.h.
The documentation for this struct was generated from the following file:
include/fmt/core.h