1516X High Stakes: include/liblvgl/hal/lv_hal_disp.h File Reference
lv_hal_disp.h File Reference
#include <stdint.h>
#include <stdbool.h>
#include "lv_hal.h"
#include "liblvgl/draw/lv_draw.h"
#include "liblvgl/misc/lv_color.h"
#include "liblvgl/misc/lv_area.h"
#include "liblvgl/misc/lv_ll.h"
#include "liblvgl/misc/lv_timer.h"
Classes
struct _lv_disp_draw_buf_t
struct _lv_disp_drv_t
struct _lv_disp_t
Typedefs
typedef struct _lv_disp_draw_buf_t lv_disp_draw_buf_t
typedef struct _lv_disp_drv_t lv_disp_drv_t
typedef struct _lv_disp_t lv_disp_t
Enumerations
enum lv_disp_rot_t { LV_DISP_ROT_NONE = 0 , LV_DISP_ROT_90 , LV_DISP_ROT_180 , LV_DISP_ROT_270 }
Functions
void lv_disp_drv_init (lv_disp_drv_t *driver)
void lv_disp_draw_buf_init (lv_disp_draw_buf_t *draw_buf, void *buf1, void *buf2, uint32_t size_in_px_cnt)
lv_disp_t * lv_disp_drv_register (lv_disp_drv_t *driver)
void lv_disp_drv_update (lv_disp_t *disp, lv_disp_drv_t *new_drv)
void lv_disp_remove (lv_disp_t *disp)
void lv_disp_set_default (lv_disp_t *disp)
lv_disp_t * lv_disp_get_default (void)
lv_coord_t lv_disp_get_hor_res (lv_disp_t *disp)
lv_coord_t lv_disp_get_ver_res (lv_disp_t *disp)
lv_coord_t lv_disp_get_physical_hor_res (lv_disp_t *disp)
lv_coord_t lv_disp_get_physical_ver_res (lv_disp_t *disp)
lv_coord_t lv_disp_get_offset_x (lv_disp_t *disp)
lv_coord_t lv_disp_get_offset_y (lv_disp_t *disp)
bool lv_disp_get_antialiasing (lv_disp_t *disp)
lv_coord_t lv_disp_get_dpi (const lv_disp_t *disp)
void lv_disp_set_rotation (lv_disp_t *disp, lv_disp_rot_t rotation)
lv_disp_rot_t lv_disp_get_rotation (lv_disp_t *disp)
lv_disp_t * lv_disp_get_next (lv_disp_t *disp)
lv_disp_draw_buf_t * lv_disp_get_draw_buf (lv_disp_t *disp)
void lv_disp_drv_use_generic_set_px_cb (lv_disp_drv_t *disp_drv, lv_img_cf_t cf)
Detailed Description
@description Display Driver HAL interface header file
Definition in file lv_hal_disp.h.
Typedef Documentation
lv_disp_draw_buf_t
typedef struct _lv_disp_draw_buf_t lv_disp_draw_buf_t
Structure for holding display buffer information.
lv_disp_drv_t
typedef struct _lv_disp_drv_t lv_disp_drv_t
Display Driver structure to be registered by HAL. Only its pointer will be saved in lv_disp_t so it should be declared as static lv_disp_drv_t my_drv or allocated dynamically.
lv_disp_t
typedef struct _lv_disp_t lv_disp_t
Display structure.
Note
lv_disp_drv_t should be the first member of the structure.
Enumeration Type Documentation
lv_disp_rot_t
enum lv_disp_rot_t
Enumerator
LV_DISP_ROT_NONE
LV_DISP_ROT_90
LV_DISP_ROT_180
LV_DISP_ROT_270
Definition at line 65 of file lv_hal_disp.h.
             {
    LV_DISP_ROT_NONE = 0,
    LV_DISP_ROT_90,
    LV_DISP_ROT_180,
    LV_DISP_ROT_270
} lv_disp_rot_t;
Function Documentation
lv_disp_draw_buf_init()
void lv_disp_draw_buf_init (lv_disp_draw_buf_t * draw_buf, void * buf1, void * buf2, uint32_t size_in_px_cnt)
Initialize a display buffer
Parameters
draw_buf pointer lv_disp_draw_buf_t variable to initialize
buf1 A buffer to be used by LVGL to draw the image. Always has to specified and can't be NULL. Can be an array allocated by the user. E.g. static lv_color_t disp_buf1[1024 * 10] Or a memory address e.g. in external SRAM
buf2 Optionally specify a second buffer to make image rendering and image flushing (sending to the display) parallel. In the disp_drv->flush you should use DMA or similar hardware to send the image to the display in the background. It lets LVGL to render next frame into the other buffer while previous is being sent. Set to NULL if unused.
size_in_px_cnt size of the buf1 and buf2 in pixel count.
lv_disp_drv_init()
void lv_disp_drv_init (lv_disp_drv_t * driver)
Initialize a display driver with default values. It is used to have known values in the fields and not junk in memory. After it you can safely set only the fields you need.
Parameters
driver pointer to driver variable to initialize
lv_disp_drv_register()
lv_disp_t * lv_disp_drv_register (lv_disp_drv_t * driver)
Register an initialized display driver. Automatically set the first display as active.
Parameters
driver pointer to an initialized 'lv_disp_drv_t' variable. Only its pointer is saved!
Returns
pointer to the new display or NULL on error
lv_disp_drv_update()
void lv_disp_drv_update (lv_disp_t * disp, lv_disp_drv_t * new_drv)
Update the driver in run time.
Parameters
disp pointer to a display. (return value of lv_disp_drv_register)
new_drv pointer to the new driver
lv_disp_drv_use_generic_set_px_cb()
void lv_disp_drv_use_generic_set_px_cb (lv_disp_drv_t * disp_drv, lv_img_cf_t cf)
lv_disp_get_antialiasing()
bool lv_disp_get_antialiasing (lv_disp_t * disp)
Get if anti-aliasing is enabled for a display or not
Parameters
disp pointer to a display (NULL to use the default display)
Returns
true: anti-aliasing is enabled; false: disabled
lv_disp_get_default()
lv_disp_t * lv_disp_get_default (void)
Get the default display
Returns
pointer to the default display
Referenced by lv_layer_sys(), lv_layer_top(), and lv_scr_act().
lv_disp_get_dpi()
lv_coord_t lv_disp_get_dpi (const lv_disp_t * disp)
Get the DPI of the display
Parameters
disp pointer to a display (NULL to use the default display)
Returns
dpi of the display
Referenced by lv_disp_dpx(), and lv_obj_dpx().
lv_disp_get_draw_buf()
lv_disp_draw_buf_t * lv_disp_get_draw_buf (lv_disp_t * disp)
Get the internal buffer of a display
Parameters
disp pointer to a display
Returns
pointer to the internal buffers
lv_disp_get_hor_res()
lv_coord_t lv_disp_get_hor_res (lv_disp_t * disp)
Get the horizontal resolution of a display
Parameters
disp pointer to a display (NULL to use the default display)
Returns
the horizontal resolution of the display
lv_disp_get_next()
lv_disp_t * lv_disp_get_next (lv_disp_t * disp)
Get the next display.
Parameters
disp pointer to the current display. NULL to initialize.
Returns
the next display or NULL if no more. Give the first display when the parameter is NULL
lv_disp_get_offset_x()
lv_coord_t lv_disp_get_offset_x (lv_disp_t * disp)
Get the horizontal offset from the full / physical display
Parameters
disp pointer to a display (NULL to use the default display)
Returns
the horizontal offset from the full / physical display
lv_disp_get_offset_y()
lv_coord_t lv_disp_get_offset_y (lv_disp_t * disp)
Get the vertical offset from the full / physical display
Parameters
disp pointer to a display (NULL to use the default display)
Returns
the horizontal offset from the full / physical display
lv_disp_get_physical_hor_res()
lv_coord_t lv_disp_get_physical_hor_res (lv_disp_t * disp)
Get the full / physical horizontal resolution of a display
Parameters
disp pointer to a display (NULL to use the default display)
Returns
the full / physical horizontal resolution of the display
lv_disp_get_physical_ver_res()
lv_coord_t lv_disp_get_physical_ver_res (lv_disp_t * disp)
Get the full / physical vertical resolution of a display
Parameters
disp pointer to a display (NULL to use the default display)
Returns
the full / physical vertical resolution of the display
lv_disp_get_rotation()
lv_disp_rot_t lv_disp_get_rotation (lv_disp_t * disp)
Get the current rotation of this display.
Parameters
disp pointer to a display (NULL to use the default display)
Returns
rotation angle
lv_disp_get_ver_res()
lv_coord_t lv_disp_get_ver_res (lv_disp_t * disp)
Get the vertical resolution of a display
Parameters
disp pointer to a display (NULL to use the default display)
Returns
the vertical resolution of the display
lv_disp_remove()
void lv_disp_remove (lv_disp_t * disp)
Remove a display
Parameters
disp pointer to display
lv_disp_set_default()
void lv_disp_set_default (lv_disp_t * disp)
Set a default display. The new screens will be created on it by default.
Parameters
disp pointer to a display
lv_disp_set_rotation()
void lv_disp_set_rotation (lv_disp_t * disp, lv_disp_rot_t rotation)
Set the rotation of this display.
Parameters
disp pointer to a display (NULL to use the default display)
rotation rotation angle