1516X High Stakes: include/liblvgl/core/lv_obj_tree.h File Reference
lv_obj_tree.h File Reference
#include <stddef.h>
#include <stdbool.h>
Typedefs
typedef lv_obj_tree_walk_res_t(* lv_obj_tree_walk_cb_t) (struct _lv_obj_t *, void *)
Enumerations
enum lv_obj_tree_walk_res_t { LV_OBJ_TREE_WALK_NEXT , LV_OBJ_TREE_WALK_SKIP_CHILDREN , LV_OBJ_TREE_WALK_END }
Functions
void lv_obj_del (struct _lv_obj_t *obj)
void lv_obj_clean (struct _lv_obj_t *obj)
void lv_obj_del_delayed (struct _lv_obj_t *obj, uint32_t delay_ms)
void lv_obj_del_anim_ready_cb (lv_anim_t *a)
void lv_obj_del_async (struct _lv_obj_t *obj)
void lv_obj_set_parent (struct _lv_obj_t *obj, struct _lv_obj_t *parent)
void lv_obj_swap (struct _lv_obj_t *obj1, struct _lv_obj_t *obj2)
void lv_obj_move_to_index (struct _lv_obj_t *obj, int32_t index)
struct _lv_obj_t * lv_obj_get_screen (const struct _lv_obj_t *obj)
lv_disp_t * lv_obj_get_disp (const struct _lv_obj_t *obj)
struct _lv_obj_t * lv_obj_get_parent (const struct _lv_obj_t *obj)
struct _lv_obj_t * lv_obj_get_child (const struct _lv_obj_t *obj, int32_t id)
uint32_t lv_obj_get_child_cnt (const struct _lv_obj_t *obj)
uint32_t lv_obj_get_index (const struct _lv_obj_t *obj)
void lv_obj_tree_walk (struct _lv_obj_t *start_obj, lv_obj_tree_walk_cb_t cb, void *user_data)
Typedef Documentation
lv_obj_tree_walk_cb_t
typedef lv_obj_tree_walk_res_t(* lv_obj_tree_walk_cb_t) (struct _lv_obj_t *, void *)
Definition at line 37 of file lv_obj_tree.h.
Enumeration Type Documentation
lv_obj_tree_walk_res_t
enum lv_obj_tree_walk_res_t
Enumerator
LV_OBJ_TREE_WALK_NEXT
LV_OBJ_TREE_WALK_SKIP_CHILDREN
LV_OBJ_TREE_WALK_END
Definition at line 31 of file lv_obj_tree.h.
             {
    LV_OBJ_TREE_WALK_NEXT,
    LV_OBJ_TREE_WALK_SKIP_CHILDREN,
    LV_OBJ_TREE_WALK_END,
} lv_obj_tree_walk_res_t;
Function Documentation
lv_obj_clean()
void lv_obj_clean (struct _lv_obj_t * obj)
Delete all children of an object. Also remove the objects from their group and remove all animations (if any). Send LV_EVENT_DELETED to deleted objects.
Parameters
obj pointer to an object
lv_obj_del()
void lv_obj_del (struct _lv_obj_t * obj)
Delete an object and all of its children. Also remove the objects from their group and remove all animations (if any). Send LV_EVENT_DELETED to deleted objects.
Parameters
obj pointer to an object
lv_obj_del_anim_ready_cb()
void lv_obj_del_anim_ready_cb (lv_anim_t * a)
A function to be easily used in animation ready callback to delete an object when the animation is ready
Parameters
a pointer to the animation
lv_obj_del_async()
void lv_obj_del_async (struct _lv_obj_t * obj)
Helper function for asynchronously deleting objects. Useful for cases where you can't delete an object directly in an LV_EVENT_DELETE handler (i.e. parent).
Parameters
obj object to delete
See also
lv_async_call
lv_obj_del_delayed()
void lv_obj_del_delayed (struct _lv_obj_t * obj, uint32_t delay_ms)
Delete an object after some delay
Parameters
obj pointer to an object
delay_ms time to wait before delete in milliseconds
lv_obj_get_child()
struct _lv_obj_t * lv_obj_get_child (const struct _lv_obj_t * obj, int32_t id)
Get the child of an object by the child's index.
Parameters
obj pointer to an object whose child should be get
id the index of the child. 0: the oldest (firstly created) child 1: the second oldest child count-1: the youngest -1: the youngest -2: the second youngest
Returns
pointer to the child or NULL if the index was invalid
Referenced by Robot::selector_screen::auton_update(), and Robot::selector_screen::drive_update().
lv_obj_get_child_cnt()
uint32_t lv_obj_get_child_cnt (const struct _lv_obj_t * obj)
Get the number of children
Parameters
obj pointer to an object
Returns
the number of children
Referenced by lv_obj_move_foreground().
lv_obj_get_disp()
lv_disp_t * lv_obj_get_disp (const struct _lv_obj_t * obj)
Get the display of the object
Parameters
obj pointer to an object
Returns
pointer to the object's display
Referenced by lv_obj_dpx().
lv_obj_get_index()
uint32_t lv_obj_get_index (const struct _lv_obj_t * obj)
Get the index of a child.
Parameters
obj pointer to an object
Returns
the child index of the object. E.g. 0: the oldest (firstly created child)
Referenced by lv_obj_get_child_id().
lv_obj_get_parent()
struct _lv_obj_t * lv_obj_get_parent (const struct _lv_obj_t * obj)
Get the parent of an object
Parameters
obj pointer to an object
Returns
the parent of the object. (NULL if obj was a screen)
Referenced by lv_obj_move_foreground().
lv_obj_get_screen()
struct _lv_obj_t * lv_obj_get_screen (const struct _lv_obj_t * obj)
Get the screen of an object
Parameters
obj pointer to an object
Returns
pointer to the object's screen
lv_obj_move_to_index()
void lv_obj_move_to_index (struct _lv_obj_t * obj, int32_t index)
moves the object to the given index in its parent. When used in listboxes, it can be used to sort the listbox items.
Parameters
obj pointer to the object to be moved.
index new index in parent. -1 to count from the back
Note
to move to the background: lv_obj_move_to_index(obj, 0)
to move forward (up): lv_obj_move_to_index(obj, lv_obj_get_index(obj) - 1)
Referenced by lv_obj_move_background(), and lv_obj_move_foreground().
lv_obj_set_parent()
void lv_obj_set_parent (struct _lv_obj_t * obj, struct _lv_obj_t * parent)
Move the parent of an object. The relative coordinates will be kept.
Parameters
obj pointer to an object whose parent needs to be changed
parent pointer to the new parent
lv_obj_swap()
void lv_obj_swap (struct _lv_obj_t * obj1, struct _lv_obj_t * obj2)
Swap the positions of two objects. When used in listboxes, it can be used to sort the listbox items.
Parameters
obj1 pointer to the first object
obj2 pointer to the second object
lv_obj_tree_walk()
void lv_obj_tree_walk (struct _lv_obj_t * start_obj, lv_obj_tree_walk_cb_t cb, void * user_data)
Iterate through all children of any object.
Parameters
start_obj start integrating from this object
cb call this callback on the objects
user_data pointer to any user related data (will be passed to cb)