1516X High Stakes: src/screen/status.cpp File Reference
status.cpp File Reference
#include "main.h"
#include "pros/apix.h"
#include "robot/drivetrain.h"
Functions
static void slider_event_cb (lv_event_t *e)
Variables
static lv_obj_t * label
Function Documentation
slider_event_cb()
static void slider_event_cb (lv_event_t * e) static
Definition at line 9 of file status.cpp.
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * obj = lv_event_get_current_target(e);
    if(code == LV_EVENT_VALUE_CHANGED) {
        lv_calendar_date_t date;
        if(lv_calendar_get_pressed_date(obj, &date)) {
            LV_LOG_USER("Clicked date: %02d.%02d.%d", date.day, date.month, date.year);
        }
    }
}
References lv_event_get_code(), lv_event_get_current_target(), LV_EVENT_VALUE_CHANGED, and LV_LOG_USER.
Referenced by Robot::status_screen::status().
Variable Documentation
label
lv_obj_t* label static
Definition at line 7 of file status.cpp.