1516X High Stakes: fmt::v10::detail::uint128_fallback Class Reference
fmt::v10::detail::uint128_fallback Class Reference
#include <format.h>
Public Member Functions
constexpr uint128_fallback (uint64_t hi, uint64_t lo)
constexpr uint128_fallback (uint64_t value=0)
constexpr uint64_t high () const noexcept
constexpr uint64_t low () const noexcept
template<typename T , fmt::enable_if_t<(std::is_integral< T >::value), int > = 0>
constexpr operator T () const
auto operator>> (int shift) const -> uint128_fallback
auto operator<< (int shift) const -> uint128_fallback
auto operator>>= (int shift) -> uint128_fallback &
void operator+= (uint128_fallback n)
void operator&= (uint128_fallback n)
uint128_fallback & operator+= (uint64_t n) noexcept
Private Attributes
uint64_t lo_
uint64_t hi_
Friends
constexpr auto operator== (const uint128_fallback &lhs, const uint128_fallback &rhs) -> bool
constexpr auto operator!= (const uint128_fallback &lhs, const uint128_fallback &rhs) -> bool
constexpr auto operator> (const uint128_fallback &lhs, const uint128_fallback &rhs) -> bool
constexpr auto operator| (const uint128_fallback &lhs, const uint128_fallback &rhs) -> uint128_fallback
constexpr auto operator& (const uint128_fallback &lhs, const uint128_fallback &rhs) -> uint128_fallback
constexpr auto operator~ (const uint128_fallback &n) -> uint128_fallback
auto operator+ (const uint128_fallback &lhs, const uint128_fallback &rhs) -> uint128_fallback
auto operator* (const uint128_fallback &lhs, uint32_t rhs) -> uint128_fallback
auto operator- (const uint128_fallback &lhs, uint64_t rhs) -> uint128_fallback
Detailed Description
Definition at line 367 of file format.h.
Constructor & Destructor Documentation
uint128_fallback() [1/2]
constexpr fmt::v10::detail::uint128_fallback::uint128_fallback (uint64_t hi, uint64_t lo) inline constexpr
Definition at line 371 of file format.h.
: lo_(lo), hi_(hi) {}
uint128_fallback() [2/2]
constexpr fmt::v10::detail::uint128_fallback::uint128_fallback (uint64_t value = 0) inline constexpr
Definition at line 373 of file format.h.
: lo_(value), hi_(0) {}
Member Function Documentation
high()
constexpr uint64_t fmt::v10::detail::uint128_fallback::high () const inline constexpr noexcept
Definition at line 375 of file format.h.
{ return hi_; }
Referenced by fmt::v10::detail::dragonbox::cache_accessor< double >::get_cached_power(), fmt::v10::detail::dragonbox::umul128_upper64(), and fmt::v10::detail::dragonbox::umul192_lower128().
low()
constexpr uint64_t fmt::v10::detail::uint128_fallback::low () const inline constexpr noexcept
Definition at line 377 of file format.h.
{ return lo_; }
Referenced by fmt::v10::detail::dragonbox::cache_accessor< double >::get_cached_power(), and fmt::v10::detail::dragonbox::umul192_lower128().
operator T()
template<typename T , fmt::enable_if_t<(std::is_integral< T >::value), int > = 0> constexpr fmt::v10::detail::uint128_fallback::operator T () const inline explicit constexpr
Definition at line 379 of file format.h.
{
            return static_cast<T>(lo_);
        }
operator&=()
void fmt::v10::detail::uint128_fallback::operator&= (uint128_fallback n) inline
Definition at line 445 of file format.h.
{
            lo_ &= n.lo_;
            hi_ &= n.hi_;
        }
References hi_, and lo_.
operator+=() [1/2]
void fmt::v10::detail::uint128_fallback::operator+= (uint128_fallback n) inline
Definition at line 437 of file format.h.
{
            uint64_t new_lo = lo_ + n.lo_;
            uint64_t new_hi = hi_ + n.hi_ + (new_lo < lo_ ? 1 : 0);
            FMT_ASSERT(new_hi >= hi_, "");
            lo_ = new_lo;
            hi_ = new_hi;
        }
References FMT_ASSERT, hi_, and lo_.
operator+=() [2/2]
uint128_fallback & fmt::v10::detail::uint128_fallback::operator+= (uint64_t n) inline noexcept
Definition at line 450 of file format.h.
{
            if (is_constant_evaluated()) {
                lo_ += n;
                hi_ += (lo_ < n ? 1 : 0);
                return *this;
            }
#if FMT_HAS_BUILTIN(__builtin_addcll) && !defined(__ibmxl__)
            unsigned long long carry;
            lo_ = __builtin_addcll(lo_, n, 0, &carry);
            hi_ += carry;
#elif FMT_HAS_BUILTIN(__builtin_ia32_addcarryx_u64) && !defined(__ibmxl__)
            unsigned long long result;
            auto carry = __builtin_ia32_addcarryx_u64(0, lo_, n, &result);
            lo_ = result;
            hi_ += carry;
#elif defined(_MSC_VER) && defined(_M_X64)
            auto carry = _addcarry_u64(0, lo_, n, &lo_);
            _addcarry_u64(carry, hi_, 0, &hi_);
#else
            lo_ += n;
            hi_ += (lo_ < n ? 1 : 0);
#endif
            return *this;
        }
References fmt::v10::detail::is_constant_evaluated().
operator<<()
auto fmt::v10::detail::uint128_fallback::operator<< (int shift) const -> uint128_fallback inline
Definition at line 429 of file format.h.
{
            if (shift == 64) return {lo_, 0};
            if (shift > 64) return uint128_fallback(lo_, 0) << (shift - 64);
            return {hi_ << shift | (lo_ >> (64 - shift)), (lo_ << shift)};
        }
operator>>()
auto fmt::v10::detail::uint128_fallback::operator>> (int shift) const -> uint128_fallback inline
Definition at line 423 of file format.h.
{
            if (shift == 64) return {0, hi_};
            if (shift > 64) return uint128_fallback(0, hi_) >> (shift - 64);
            return {hi_ >> shift, (hi_ << (64 - shift)) | (lo_ >> shift)};
        }
operator>>=()
auto fmt::v10::detail::uint128_fallback::operator>>= (int shift) -> uint128_fallback& inline
Definition at line 435 of file format.h.
{ return *this = *this >> shift; }
Friends And Related Symbol Documentation
operator!=
constexpr auto operator!= (const uint128_fallback & lhs, const uint128_fallback & rhs) -> bool friend
Definition at line 387 of file format.h.
{
            return !(lhs == rhs);
        }
operator&
constexpr auto operator& (const uint128_fallback & lhs, const uint128_fallback & rhs) -> uint128_fallback friend
Definition at line 399 of file format.h.
{
            return {lhs.hi_ & rhs.hi_, lhs.lo_ & rhs.lo_};
        }
operator*
auto operator* (const uint128_fallback & lhs, uint32_t rhs) -> uint128_fallback friend
Definition at line 411 of file format.h.
{
            FMT_ASSERT(lhs.hi_ == 0, "");
            uint64_t hi = (lhs.lo_ >> 32) * rhs;
            uint64_t lo = (lhs.lo_ & ~uint32_t()) * rhs;
            uint64_t new_lo = (hi << 32) + lo;
            return {(hi >> 32) + (new_lo < lo ? 1 : 0), new_lo};
        }
operator+
auto operator+ (const uint128_fallback & lhs, const uint128_fallback & rhs) -> uint128_fallback friend
Definition at line 405 of file format.h.
{
            auto result = uint128_fallback(lhs);
            result += rhs;
            return result;
        }
operator-
auto operator- (const uint128_fallback & lhs, uint64_t rhs) -> uint128_fallback friend
Definition at line 419 of file format.h.
{
            return {lhs.hi_ - (lhs.lo_ < rhs ? 1 : 0), lhs.lo_ - rhs};
        }
operator==
constexpr auto operator== (const uint128_fallback & lhs, const uint128_fallback & rhs) -> bool friend
Definition at line 383 of file format.h.
{
            return lhs.hi_ == rhs.hi_ && lhs.lo_ == rhs.lo_;
        }
operator>
constexpr auto operator> (const uint128_fallback & lhs, const uint128_fallback & rhs) -> bool friend
Definition at line 391 of file format.h.
{
            return lhs.hi_ != rhs.hi_ ? lhs.hi_ > rhs.hi_ : lhs.lo_ > rhs.lo_;
        }
operator|
constexpr auto operator| (const uint128_fallback & lhs, const uint128_fallback & rhs) -> uint128_fallback friend
Definition at line 395 of file format.h.
{
            return {lhs.hi_ | rhs.hi_, lhs.lo_ | rhs.lo_};
        }
operator~
constexpr auto operator~ (const uint128_fallback & n) -> uint128_fallback friend
Definition at line 403 of file format.h.
{ return {~n.hi_, ~n.lo_}; }
Member Data Documentation
hi_
uint64_t fmt::v10::detail::uint128_fallback::hi_ private
Definition at line 369 of file format.h.
Referenced by operator&=(), and operator+=().
lo_
uint64_t fmt::v10::detail::uint128_fallback::lo_ private
Definition at line 369 of file format.h.
Referenced by operator&=(), and operator+=().
The documentation for this class was generated from the following file:
include/fmt/format.h