1516X High Stakes: fmt::v10::detail::value< Context > Class Template Reference
fmt::v10::detail::value< Context > Class Template Reference
#include <core.h>
Public Types
using char_type = typename Context::char_type
Public Member Functions
constexpr value ()
constexpr value (int val)
constexpr value (unsigned val)
constexpr value (long long val)
constexpr value (unsigned long long val)
value (int128_opt val)
value (uint128_opt val)
constexpr value (float val)
constexpr value (double val)
value (long double val)
constexpr value (bool val)
constexpr value (char_type val)
value (const char_type *val)
value (basic_string_view< char_type > val)
value (const void *val)
value (const named_arg_info< char_type > *args, size_t size)
template<typename T >
value (T &val)
value (unformattable)
value (unformattable_char)
value (unformattable_pointer)
Public Attributes
union {
monostate no_value
int int_value
unsigned uint_value
long long long_long_value
unsigned long long ulong_long_value
int128_opt int128_value
uint128_opt uint128_value
bool bool_value
char_type char_value
float float_value
double double_value
long double long_double_value
const void * pointer
string_value< char_type > string
custom_value< Context > custom
named_arg_value< char_type > named_args
};
Static Private Member Functions
template<typename T , typename Formatter >
static void format_custom_arg (void *arg, typename Context::parse_context_type &parse_ctx, Context &ctx)
Detailed Description
template<typename Context>
class fmt::v10::detail::value< Context >
Definition at line 1154 of file core.h.
Member Typedef Documentation
char_type
template<typename Context > using fmt::v10::detail::value< Context >::char_type = typename Context::char_type
Definition at line 1156 of file core.h.
Constructor & Destructor Documentation
value() [1/20]
template<typename Context > constexpr fmt::v10::detail::value< Context >::value () inline constexpr
Definition at line 1177 of file core.h.
: no_value() {}
value() [2/20]
template<typename Context > constexpr fmt::v10::detail::value< Context >::value (int val) inline constexpr
Definition at line 1179 of file core.h.
: int_value(val) {}
value() [3/20]
template<typename Context > constexpr fmt::v10::detail::value< Context >::value (unsigned val) inline constexpr
Definition at line 1181 of file core.h.
: uint_value(val) {}
value() [4/20]
template<typename Context > constexpr fmt::v10::detail::value< Context >::value (long long val) inline constexpr
Definition at line 1183 of file core.h.
: long_long_value(val) {}
value() [5/20]
template<typename Context > constexpr fmt::v10::detail::value< Context >::value (unsigned long long val) inline constexpr
Definition at line 1185 of file core.h.
: ulong_long_value(val) {}
value() [6/20]
template<typename Context > fmt::v10::detail::value< Context >::value (int128_opt val) inline
Definition at line 1187 of file core.h.
: int128_value(val) {}
value() [7/20]
template<typename Context > fmt::v10::detail::value< Context >::value (uint128_opt val) inline
Definition at line 1189 of file core.h.
: uint128_value(val) {}
value() [8/20]
template<typename Context > constexpr fmt::v10::detail::value< Context >::value (float val) inline constexpr
Definition at line 1191 of file core.h.
: float_value(val) {}
value() [9/20]
template<typename Context > constexpr fmt::v10::detail::value< Context >::value (double val) inline constexpr
Definition at line 1193 of file core.h.
: double_value(val) {}
value() [10/20]
template<typename Context > fmt::v10::detail::value< Context >::value (long double val) inline
Definition at line 1195 of file core.h.
: long_double_value(val) {}
value() [11/20]
template<typename Context > constexpr fmt::v10::detail::value< Context >::value (bool val) inline constexpr
Definition at line 1197 of file core.h.
: bool_value(val) {}
value() [12/20]
template<typename Context > constexpr fmt::v10::detail::value< Context >::value (char_type val) inline constexpr
Definition at line 1199 of file core.h.
: char_value(val) {}
value() [13/20]
template<typename Context > fmt::v10::detail::value< Context >::value (const char_type * val) inline
Definition at line 1201 of file core.h.
{
            string.data = val;
            if (is_constant_evaluated()) string.size = {};
        }
References fmt::v10::detail::is_constant_evaluated().
value() [14/20]
template<typename Context > fmt::v10::detail::value< Context >::value (basic_string_view< char_type > val) inline
Definition at line 1206 of file core.h.
{
            string.data = val.data();
            string.size = val.size();
        }
References fmt::v10::basic_string_view< Char >::data(), and fmt::v10::basic_string_view< Char >::size().
value() [15/20]
template<typename Context > fmt::v10::detail::value< Context >::value (const void * val) inline
Definition at line 1211 of file core.h.
: pointer(val) {}
References fmt::v10::pointer.
value() [16/20]
template<typename Context > fmt::v10::detail::value< Context >::value (const named_arg_info< char_type > * args, size_t size) inline
Definition at line 1213 of file core.h.
: named_args {args, size} {}
value() [17/20]
template<typename Context > template<typename T > fmt::v10::detail::value< Context >::value (T & val) inline
Definition at line 1215 of file core.h.
{
            using value_type = remove_const_t<T>;
            custom.value = const_cast<value_type*>(std::addressof(val));
            // Get the formatter type through the context to allow different contexts
            // have different extension points, e.g. `formatter<T>` for `format` and
            // `printf_formatter<T>` for `printf`.
            custom.format = format_custom_arg<value_type, typename Context::template formatter_type<value_type>>;
        }
value() [18/20]
template<typename Context > fmt::v10::detail::value< Context >::value (unformattable)
value() [19/20]
template<typename Context > fmt::v10::detail::value< Context >::value (unformattable_char)
value() [20/20]
template<typename Context > fmt::v10::detail::value< Context >::value (unformattable_pointer)
Member Function Documentation
format_custom_arg()
template<typename Context > template<typename T , typename Formatter > static void fmt::v10::detail::value< Context >::format_custom_arg (void * arg, typename Context::parse_context_type & parse_ctx, Context & ctx) inline static private
Definition at line 1230 of file core.h.
{
            auto f = Formatter();
            parse_ctx.advance_to(f.parse(parse_ctx));
            using qualified_type = conditional_t<has_const_formatter<T, Context>(), const T, T>;
            ctx.advance_to(f.format(*static_cast<qualified_type*>(arg), ctx));
        }
Member Data Documentation
[union]
union { ... } fmt::v10::detail::value< Context >
bool_value
template<typename Context > bool fmt::v10::detail::value< Context >::bool_value
Definition at line 1166 of file core.h.
char_value
template<typename Context > char_type fmt::v10::detail::value< Context >::char_value
Definition at line 1167 of file core.h.
custom
template<typename Context > custom_value<Context> fmt::v10::detail::value< Context >::custom
Definition at line 1173 of file core.h.
double_value
template<typename Context > double fmt::v10::detail::value< Context >::double_value
Definition at line 1169 of file core.h.
float_value
template<typename Context > float fmt::v10::detail::value< Context >::float_value
Definition at line 1168 of file core.h.
int128_value
template<typename Context > int128_opt fmt::v10::detail::value< Context >::int128_value
Definition at line 1164 of file core.h.
int_value
template<typename Context > int fmt::v10::detail::value< Context >::int_value
Definition at line 1160 of file core.h.
long_double_value
template<typename Context > long double fmt::v10::detail::value< Context >::long_double_value
Definition at line 1170 of file core.h.
long_long_value
template<typename Context > long long fmt::v10::detail::value< Context >::long_long_value
Definition at line 1162 of file core.h.
named_args
template<typename Context > named_arg_value<char_type> fmt::v10::detail::value< Context >::named_args
Definition at line 1174 of file core.h.
no_value
template<typename Context > monostate fmt::v10::detail::value< Context >::no_value
Definition at line 1159 of file core.h.
pointer
template<typename Context > const void* fmt::v10::detail::value< Context >::pointer
Definition at line 1171 of file core.h.
string
template<typename Context > string_value<char_type> fmt::v10::detail::value< Context >::string
Definition at line 1172 of file core.h.
uint128_value
template<typename Context > uint128_opt fmt::v10::detail::value< Context >::uint128_value
Definition at line 1165 of file core.h.
uint_value
template<typename Context > unsigned fmt::v10::detail::value< Context >::uint_value
Definition at line 1161 of file core.h.
ulong_long_value
template<typename Context > unsigned long long fmt::v10::detail::value< Context >::ulong_long_value
Definition at line 1163 of file core.h.
The documentation for this class was generated from the following file:
include/fmt/core.h