1516X High Stakes: src/screen/selector.cpp File Reference
selector.cpp File Reference
#include "main.h"
#include "pros/apix.h"
#include "robot/auton.h"
#include "robot/drivetrain.h"
Functions
void auton_state_update (lv_event_code_t code, lv_obj_t *dropdown, lv_obj_t *label, lv_obj_t *skillSwitch, lv_obj_t *autonSwitch)
function to update the autonomous routine based on the updates made to the dropdown list and skills switch in the UI (See auton_ui_update)
static void auton_ui_update (lv_event_t *e)
Updates the user interface for autonomous selection.
static void drive_update (lv_event_t *e)
Updates the drive mode based on the selected option in the drive roller.
Function Documentation
auton_state_update()
void auton_state_update (lv_event_code_t code, lv_obj_t * dropdown, lv_obj_t * label, lv_obj_t * skillSwitch, lv_obj_t * autonSwitch)
function to update the autonomous routine based on the updates made to the dropdown list and skills switch in the UI (See auton_ui_update)
Definition at line 13 of file selector.cpp.
{
    // Checks if the dropdown list has been updated, and updates the autonomous routine
    if(code == LV_EVENT_VALUE_CHANGED) {
         char * opt = new char[15];
         std::string auton;
         lv_dropdown_get_selected_str(dropdown, opt, 15);
        if (lv_obj_has_state(skillSwitch, LV_STATE_CHECKED)) {
            Autonomous::AutonSwitcher(5);
        }
        else {
            if(strcmp(opt, "Red Left") == 0) {
                Autonomous::AutonSwitcher(1);
            }
            else if(strcmp(opt, "Red Right") == 0) {
                Autonomous::AutonSwitcher(2);
            }
            else if(strcmp(opt, "Blue Left") == 0) {
                Autonomous::AutonSwitcher(3);
            }
            else if(strcmp(opt, "Blue Right") == 0) {
                Autonomous::AutonSwitcher(4);
            }
            else {
            }
        }
        lv_label_set_text_fmt(label, "Current Auton: %s", Autonomous::autonName.c_str());
    }
}
References Robot::Autonomous::autonName, Robot::Autonomous::AutonSwitcher(), label, LV_EVENT_VALUE_CHANGED, lv_label_set_text_fmt(), lv_obj_has_state(), and LV_STATE_CHECKED.
Referenced by auton_ui_update().
auton_ui_update()
static void auton_ui_update (lv_event_t * e) static
Updates the user interface for autonomous selection.
This function is responsible for updating the content of the dropdown list based on the alliance color. It also handles the state of the skill switch and updates the autonomous routine accordingly.
Parameters
e Pointer to the event object.
Definition at line 53 of file selector.cpp.
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * tab1 = lv_event_get_current_target(e);
    lv_obj_t * auton_dd = lv_obj_get_child(tab1, -1);
    lv_obj_t * skillSwitch = lv_obj_get_child(tab1, -2);
    lv_obj_t * autonSwitch = lv_obj_get_child(tab1, -3);
    lv_obj_t * autonLabel = lv_obj_get_child(tab1, -4);
    /* Updates content of the dropdown list based on the alliance color, using
    * the state of the alliance color switch, which is detected through "bubbling"
    */
    if (code == LV_EVENT_VALUE_CHANGED) {
        if(lv_obj_has_state(autonSwitch, LV_STATE_CHECKED)) {
            lv_dropdown_clear_options(auton_dd);
            lv_dropdown_add_option(auton_dd, "Blue Left",0);
            lv_dropdown_add_option(auton_dd, "Blue Right",1);
            lv_obj_set_style_border_color(auton_dd, lv_color_hex(0x0077c8), 0);
        }
        else {
            lv_dropdown_clear_options(auton_dd);
            lv_dropdown_add_option(auton_dd, "Red Left",0);
            lv_dropdown_add_option(auton_dd, "Red Right",1);
            lv_obj_set_style_border_color(auton_dd, lv_color_hex(0xd22730), 0);
        }
    }
    if (lv_obj_has_state(skillSwitch, LV_STATE_CHECKED)) {
        lv_obj_add_state(autonSwitch, LV_STATE_DISABLED);
        lv_obj_add_state(auton_dd, LV_STATE_DISABLED);
        lv_obj_set_style_border_color(auton_dd, lv_color_hex(0x7a7a7a), 0);
    }
    else {
        lv_obj_clear_state(autonSwitch, LV_STATE_DISABLED);
        lv_obj_clear_state(auton_dd, LV_STATE_DISABLED);
    }
    auton_state_update(code, auton_dd, autonLabel, skillSwitch, autonSwitch);
    //Updates the Autonomous routine based on the dropdown list and skills
}
References auton_state_update(), lv_color_hex(), lv_event_get_code(), lv_event_get_current_target(), LV_EVENT_VALUE_CHANGED, lv_obj_add_state(), lv_obj_clear_state(), lv_obj_get_child(), lv_obj_has_state(), lv_obj_set_style_border_color(), LV_STATE_CHECKED, and LV_STATE_DISABLED.
Referenced by Robot::selector_screen::selector().
drive_update()
static void drive_update (lv_event_t * e) static
Updates the drive mode based on the selected option in the drive roller.
This function is called when the value of the drive roller is changed. It retrieves the selected option from the drive roller and updates the drive mode accordingly. The updated drive mode is then displayed on the drive label.
Parameters
e The event object associated with the drive roller.
Definition at line 104 of file selector.cpp.
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_obj_t * tab1 = lv_event_get_current_target(e);
    lv_obj_t * drive_roller = lv_obj_get_child(tab1, -1);
    lv_obj_t * driveLabel = lv_obj_get_child(tab1, -2);
    if (code == LV_EVENT_VALUE_CHANGED) {
        std::string driveMode;
        char * opt = new char[18];
        lv_roller_get_selected_str(drive_roller, opt, 18);
        if(strcmp(opt, "Curvature Drive") == 0) {
            driveMode = Drivetrain::SwitchDrive(0);
        }
        else if(strcmp(opt, "Arcade Drive") == 0) {
            driveMode = Drivetrain::SwitchDrive(1);
        }
        else if(strcmp(opt, "Tank Drive") == 0) {
            driveMode = Drivetrain::SwitchDrive(2);
        }
        else {
            driveMode = "error";
        }
        lv_label_set_text_fmt(driveLabel, "Current drive mode: %s", driveMode.c_str());
    }
}
References lv_event_get_code(), lv_event_get_current_target(), LV_EVENT_VALUE_CHANGED, lv_label_set_text_fmt(), lv_obj_get_child(), and Robot::Drivetrain::SwitchDrive().
Referenced by Robot::selector_screen::selector().