1516X High Stakes: Robot::Intake Class Reference
Robot::Intake Class Reference
The Intake class represents a robot intake system.
#include <intake.h>
Public Member Functions
void run ()
Runs the main function of the intake system.
void score ()
Outakes rings and scores them inside of latched mobile goal.
Intake ()
void interval (const uint32_t time)
Runs intake for a certain interval of time.
void toggle ()
Toggles intake elevation.
Private Attributes
bool elevated
Detailed Description
The Intake class represents a robot intake system.
Definition at line 9 of file intake.h.
Constructor & Destructor Documentation
Intake()
Intake::Intake ()
Definition at line 8 of file intake.cpp.
               {
    elevated = false;
}
References elevated.
Member Function Documentation
interval()
void Intake::interval (const uint32_t time)
Runs intake for a certain interval of time.
Definition at line 12 of file intake.cpp.
{
    IntakeMotor.move(127);
    pros::delay(time);
}
References Robot::Globals::IntakeMotor.
Referenced by Robot::Autonomous::Auton1().
run()
void Intake::run ()
Runs the main function of the intake system.
Takes optional user input to control the direction of the intake system in autonomous.
Definition at line 24 of file intake.cpp.
                {
    if (controller.get_digital(pros::E_CONTROLLER_DIGITAL_L1)) {
      IntakeMotor.move(127);
    }
    else if (controller.get_digital(pros::E_CONTROLLER_DIGITAL_R1)) {
        IntakeMotor.move(-127);
    }
    else {
        IntakeMotor.brake();
    }
}
References Robot::Globals::controller, pros::v5::Controller::get_digital(), and Robot::Globals::IntakeMotor.
Referenced by opcontrol().
score()
void Intake::score ()
Outakes rings and scores them inside of latched mobile goal.
Definition at line 18 of file intake.cpp.
                   {
    IntakeMotor.move(127);
    pros::delay(3000); // will modify later, will run until color sensor doesn't detect a ring
}
References Robot::Globals::IntakeMotor.
Referenced by Robot::Autonomous::Auton1().
toggle()
void Intake::toggle ()
Toggles intake elevation.
Definition at line 36 of file intake.cpp.
                    {
    if (elevated) {
        IntakeToggle.retract();
        elevated = false;
    }
    else {
        IntakeToggle.extend();
        elevated = true;
    }
}
References elevated, pros::adi::Pneumatics::extend(), Robot::Globals::IntakeToggle, and pros::adi::Pneumatics::retract().
Referenced by Robot::Autonomous::Auton1().
Member Data Documentation
elevated
bool Robot::Intake::elevated private
Definition at line 36 of file intake.h.
Referenced by Intake(), and toggle().
The documentation for this class was generated from the following files:
include/robot/intake.h
src/subsystems/intake.cpp