1516X High Stakes: include/liblvgl/lv_api_map.h File Reference
lv_api_map.h File Reference
#include "liblvgl/lvgl.h"
Macros
#define LV_NO_TASK_READY LV_NO_TIMER_READY
#define LV_INDEV_STATE_REL LV_INDEV_STATE_RELEASED
#define LV_INDEV_STATE_PR LV_INDEV_STATE_PRESSED
#define LV_OBJ_FLAG_SNAPABLE LV_OBJ_FLAG_SNAPPABLE /*Fixed typo*/
Functions
static LV_ATTRIBUTE_TIMER_HANDLER uint32_t lv_task_handler (void)
static void lv_obj_move_foreground (lv_obj_t *obj)
static void lv_obj_move_background (lv_obj_t *obj)
static uint32_t lv_obj_get_child_id (const struct _lv_obj_t *obj)
Macro Definition Documentation
LV_INDEV_STATE_PR
#define LV_INDEV_STATE_PR LV_INDEV_STATE_PRESSED
Definition at line 24 of file lv_api_map.h.
LV_INDEV_STATE_REL
#define LV_INDEV_STATE_REL LV_INDEV_STATE_RELEASED
Definition at line 23 of file lv_api_map.h.
LV_NO_TASK_READY
#define LV_NO_TASK_READY LV_NO_TIMER_READY
Definition at line 22 of file lv_api_map.h.
LV_OBJ_FLAG_SNAPABLE
#define LV_OBJ_FLAG_SNAPABLE LV_OBJ_FLAG_SNAPPABLE /*Fixed typo*/
Definition at line 25 of file lv_api_map.h.
Function Documentation
lv_obj_get_child_id()
static uint32_t lv_obj_get_child_id (const struct _lv_obj_t * obj) inline static
Definition at line 78 of file lv_api_map.h.
{
    LV_LOG_WARN("lv_obj_get_child_id(obj) is deprecated, please use lv_obj_get_index(obj).");
    return lv_obj_get_index(obj);
}
References LV_LOG_WARN, and lv_obj_get_index().
lv_obj_move_background()
static void lv_obj_move_background (lv_obj_t * obj) inline static
Move the object to the background. It will look like if it was created as the first child of its parent. It also means any of the siblings can cover the object.
Parameters
obj pointer to an object
Definition at line 67 of file lv_api_map.h.
{
    lv_obj_move_to_index(obj, 0);
}
References lv_obj_move_to_index().
lv_obj_move_foreground()
static void lv_obj_move_foreground (lv_obj_t * obj) inline static
Move the object to the foreground. It will look like if it was created as the last child of its parent. It also means it can cover any of the siblings.
Parameters
obj pointer to an object
Definition at line 55 of file lv_api_map.h.
{
    lv_obj_t * parent = lv_obj_get_parent(obj);
    lv_obj_move_to_index(obj, lv_obj_get_child_cnt(parent) - 1);
}
References lv_obj_get_child_cnt(), lv_obj_get_parent(), and lv_obj_move_to_index().
lv_task_handler()
static LV_ATTRIBUTE_TIMER_HANDLER uint32_t lv_task_handler (void) inline static
Definition at line 35 of file lv_api_map.h.
{
    return lv_timer_handler();
}