1516X High Stakes: fmt::v10::detail::dragonbox Namespace Reference
fmt::v10::detail::dragonbox Namespace Reference
Classes
struct cache_accessor
struct cache_accessor< double >
struct cache_accessor< float >
struct decimal_fp
struct float_info
struct float_info< double >
struct float_info< float >
struct float_info< T, enable_if_t< is_double_double< T >::value > >
struct float_info< T, enable_if_t< std::numeric_limits< T >::digits==64||std::numeric_limits< T >::digits==113||is_float128< T >::value > >
Functions
uint64_t umul96_upper64 (uint32_t x, uint64_t y) noexcept
uint128_fallback umul192_lower128 (uint64_t x, uint128_fallback y) noexcept
uint64_t umul96_lower64 (uint32_t x, uint64_t y) noexcept
int floor_log10_pow2_minus_log10_4_over_3 (int e) noexcept
template<int N>
bool check_divisibility_and_divide_by_pow10 (uint32_t &n) noexcept
template<int N>
uint32_t small_division_by_pow10 (uint32_t n) noexcept
uint32_t divide_by_10_to_kappa_plus_1 (uint32_t n) noexcept
uint64_t divide_by_10_to_kappa_plus_1 (uint64_t n) noexcept
uint128_fallback get_cached_power (int k) noexcept
template<typename T >
bool is_left_endpoint_integer_shorter_interval (int exponent) noexcept
int remove_trailing_zeros (uint32_t &n, int s=0) noexcept
int remove_trailing_zeros (uint64_t &n) noexcept
template<typename T >
decimal_fp< T > shorter_interval_case (int exponent) noexcept
template<typename T >
decimal_fp< T > to_decimal (T x) noexcept
int floor_log10_pow2 (int e) noexcept
int floor_log2_pow10 (int e) noexcept
uint64_t umul128_upper64 (uint64_t x, uint64_t y) noexcept
uint128_fallback umul192_upper128 (uint64_t x, uint128_fallback y) noexcept
template<typename T >
auto to_decimal (T x) noexcept -> decimal_fp< T >
Variables
struct {
uint32_t fmt::v10::detail::dragonbox::divisor
int fmt::v10::detail::dragonbox::shift_amount
} div_small_pow10_infos [] = {{10, 16}, {100, 16}}
Function Documentation
check_divisibility_and_divide_by_pow10()
template<int N> bool fmt::v10::detail::dragonbox::check_divisibility_and_divide_by_pow10 (uint32_t & n) noexcept
Definition at line 186 of file format-inl.h.
{
    // The numbers below are chosen such that:
    //   1. floor(n/d) = floor(nm / 2^k) where d=10 or d=100,
    //   2. nm mod 2^k < m if and only if n is divisible by d,
    // where m is magic_number, k is shift_amount
    // and d is divisor.
    //
    // Item 1 is a common technique of replacing division by a constant with
    // multiplication, see e.g. "Division by Invariant Integers Using
    // Multiplication" by Granlund and Montgomery (1994). magic_number (m) is set
    // to ceil(2^k/d) for large enough k.
    // The idea for item 2 originates from Schubfach.
    constexpr auto info = div_small_pow10_infos[N - 1];
    FMT_ASSERT(n <= info.divisor * 10, "n is too large");
    constexpr uint32_t magic_number = (1u << info.shift_amount) / info.divisor + 1;
    n *= magic_number;
    const uint32_t comparison_mask = (1u << info.shift_amount) - 1;
    bool result = (n & comparison_mask) < magic_number;
    n >>= info.shift_amount;
    return result;
}
References div_small_pow10_infos, and FMT_ASSERT.
divide_by_10_to_kappa_plus_1() [1/2]
uint32_t fmt::v10::detail::dragonbox::divide_by_10_to_kappa_plus_1 (uint32_t n) inline noexcept
Definition at line 218 of file format-inl.h.
{
    // 1374389535 = ceil(2^37/100)
    return static_cast<uint32_t>((static_cast<uint64_t>(n) * 1374389535) >> 37);
}
Referenced by to_decimal().
divide_by_10_to_kappa_plus_1() [2/2]
uint64_t fmt::v10::detail::dragonbox::divide_by_10_to_kappa_plus_1 (uint64_t n) inline noexcept
Definition at line 224 of file format-inl.h.
{
    // 2361183241434822607 = ceil(2^(64+7)/1000)
    return umul128_upper64(n, 2361183241434822607ull) >> 7;
}
References umul128_upper64().
floor_log10_pow2()
int fmt::v10::detail::dragonbox::floor_log10_pow2 (int e) inline noexcept
Definition at line 1425 of file format.h.
{
    FMT_ASSERT(e <= 2620 && e >= -2620, "too large exponent");
    static_assert((-1 >> 1) == -1, "right shift is not arithmetic");
    return (e * 315653) >> 20;
}
References floor_log10_pow2(), and FMT_ASSERT.
Referenced by floor_log10_pow2(), and to_decimal().
floor_log10_pow2_minus_log10_4_over_3()
int fmt::v10::detail::dragonbox::floor_log10_pow2_minus_log10_4_over_3 (int e) inline noexcept
Definition at line 173 of file format-inl.h.
{
    FMT_ASSERT(e <= 2936 && e >= -2985, "too large exponent");
    return (e * 631305 - 261663) >> 21;
}
References FMT_ASSERT.
Referenced by shorter_interval_case().
floor_log2_pow10()
int fmt::v10::detail::dragonbox::floor_log2_pow10 (int e) inline noexcept
Definition at line 1431 of file format.h.
{
    FMT_ASSERT(e <= 1233 && e >= -1233, "too large exponent");
    return (e * 1741647) >> 19;
}
References floor_log2_pow10(), and FMT_ASSERT.
Referenced by floor_log2_pow10(), fmt::v10::detail::dragonbox::cache_accessor< double >::get_cached_power(), shorter_interval_case(), and to_decimal().
get_cached_power()
uint128_fallback fmt::v10::detail::dragonbox::get_cached_power (int k) noexcept
Definition at line 1064 of file format-inl.h.
{ return cache_accessor<double>::get_cached_power(k); }
is_left_endpoint_integer_shorter_interval()
template<typename T > bool fmt::v10::detail::dragonbox::is_left_endpoint_integer_shorter_interval (int exponent) noexcept
Definition at line 1067 of file format-inl.h.
{
    const int case_shorter_interval_left_endpoint_lower_threshold = 2;
    const int case_shorter_interval_left_endpoint_upper_threshold = 3;
    return exponent >= case_shorter_interval_left_endpoint_lower_threshold &&
           exponent <= case_shorter_interval_left_endpoint_upper_threshold;
}
Referenced by shorter_interval_case().
remove_trailing_zeros() [1/2]
int fmt::v10::detail::dragonbox::remove_trailing_zeros (uint32_t & n, int s = 0) inline noexcept
Definition at line 1075 of file format-inl.h.
{
    FMT_ASSERT(n != 0, "");
    // Modular inverse of 5 (mod 2^32): (mod_inv_5 * 5) mod 2^32 = 1.
    constexpr uint32_t mod_inv_5 = 0xcccccccd;
    constexpr uint32_t mod_inv_25 = 0xc28f5c29; // = mod_inv_5 * mod_inv_5
    while (true) {
        auto q = rotr(n * mod_inv_25, 2);
        if (q > max_value<uint32_t>() / 100) break;
        n = q;
        s += 2;
    }
    auto q = rotr(n * mod_inv_5, 1);
    if (q <= max_value<uint32_t>() / 10) {
        n = q;
        s |= 1;
    }
    return s;
}
References FMT_ASSERT, fmt::v10::detail::max_value(), and fmt::v10::detail::rotr().
Referenced by remove_trailing_zeros(), shorter_interval_case(), and to_decimal().
remove_trailing_zeros() [2/2]
int fmt::v10::detail::dragonbox::remove_trailing_zeros (uint64_t & n) inline noexcept
Definition at line 1096 of file format-inl.h.
{
    FMT_ASSERT(n != 0, "");
    // This magic number is ceil(2^90 / 10^8).
    constexpr uint64_t magic_number = 12379400392853802749ull;
    auto nm = umul128(n, magic_number);
    // Is n is divisible by 10^8?
    if ((nm.high() & ((1ull << (90 - 64)) - 1)) == 0 && nm.low() < magic_number) {
        // If yes, work with the quotient...
        auto n32 = static_cast<uint32_t>(nm.high() >> (90 - 64));
        // ... and use the 32 bit variant of the function
        int s = remove_trailing_zeros(n32, 8);
        n = n32;
        return s;
    }
    // If n is not divisible by 10^8, work with n itself.
    constexpr uint64_t mod_inv_5 = 0xcccccccccccccccd;
    constexpr uint64_t mod_inv_25 = 0x8f5c28f5c28f5c29; // = mod_inv_5 * mod_inv_5
    int s = 0;
    while (true) {
        auto q = rotr(n * mod_inv_25, 2);
        if (q > max_value<uint64_t>() / 100) break;
        n = q;
        s += 2;
    }
    auto q = rotr(n * mod_inv_5, 1);
    if (q <= max_value<uint64_t>() / 10) {
        n = q;
        s |= 1;
    }
    return s;
}
References FMT_ASSERT, fmt::v10::detail::max_value(), remove_trailing_zeros(), fmt::v10::detail::rotr(), and fmt::v10::detail::umul128().
shorter_interval_case()
template<typename T > decimal_fp< T > fmt::v10::detail::dragonbox::shorter_interval_case (int exponent) inline noexcept
Definition at line 1134 of file format-inl.h.
{
    decimal_fp<T> ret_value;
    // Compute k and beta
    const int minus_k = floor_log10_pow2_minus_log10_4_over_3(exponent);
    const int beta = exponent + floor_log2_pow10(-minus_k);
    // Compute xi and zi
    using cache_entry_type = typename cache_accessor<T>::cache_entry_type;
    const cache_entry_type cache = cache_accessor<T>::get_cached_power(-minus_k);
    auto xi = cache_accessor<T>::compute_left_endpoint_for_shorter_interval_case(cache, beta);
    auto zi = cache_accessor<T>::compute_right_endpoint_for_shorter_interval_case(cache, beta);
    // If the left endpoint is not an integer, increase it
    if (!is_left_endpoint_integer_shorter_interval<T>(exponent)) ++xi;
    // Try bigger divisor
    ret_value.significand = zi / 10;
    // If succeed, remove trailing zeros if necessary and return
    if (ret_value.significand * 10 >= xi) {
        ret_value.exponent = minus_k + 1;
        ret_value.exponent += remove_trailing_zeros(ret_value.significand);
        return ret_value;
    }
    // Otherwise, compute the round-up of y
    ret_value.significand = cache_accessor<T>::compute_round_up_for_shorter_interval_case(cache, beta);
    ret_value.exponent = minus_k;
    // When tie occurs, choose one of them according to the rule
    if (exponent >= float_info<T>::shorter_interval_tie_lower_threshold &&
        exponent <= float_info<T>::shorter_interval_tie_upper_threshold) {
        ret_value.significand = ret_value.significand % 2 == 0 ? ret_value.significand : ret_value.significand - 1;
    } else if (ret_value.significand < xi) {
        ++ret_value.significand;
    }
    return ret_value;
}
References fmt::v10::detail::dragonbox::decimal_fp< T >::exponent, floor_log10_pow2_minus_log10_4_over_3(), floor_log2_pow10(), is_left_endpoint_integer_shorter_interval(), remove_trailing_zeros(), and fmt::v10::detail::dragonbox::decimal_fp< T >::significand.
Referenced by to_decimal().
small_division_by_pow10()
template<int N> uint32_t fmt::v10::detail::dragonbox::small_division_by_pow10 (uint32_t n) noexcept
Definition at line 210 of file format-inl.h.
{
    constexpr auto info = div_small_pow10_infos[N - 1];
    FMT_ASSERT(n <= info.divisor * 10, "n is too large");
    constexpr uint32_t magic_number = (1u << info.shift_amount) / info.divisor + 1;
    return (n * magic_number) >> info.shift_amount;
}
References div_small_pow10_infos, and FMT_ASSERT.
to_decimal() [1/2]
template<typename T > decimal_fp< T > fmt::v10::detail::dragonbox::to_decimal (T x) noexcept
Definition at line 1174 of file format-inl.h.
{
    // Step 1: integer promotion & Schubfach multiplier calculation.
    using carrier_uint = typename float_info<T>::carrier_uint;
    using cache_entry_type = typename cache_accessor<T>::cache_entry_type;
    auto br = bit_cast<carrier_uint>(x);
    // Extract significand bits and exponent bits.
    const carrier_uint significand_mask = (static_cast<carrier_uint>(1) << num_significand_bits<T>()) - 1;
    carrier_uint significand = (br & significand_mask);
    int exponent = static_cast<int>((br & exponent_mask<T>()) >> num_significand_bits<T>());
    if (exponent != 0) { // Check if normal.
        exponent -= exponent_bias<T>() + num_significand_bits<T>();
        // Shorter interval case; proceed like Schubfach.
        // In fact, when exponent == 1 and significand == 0, the interval is
        // regular. However, it can be shown that the end-results are anyway same.
        if (significand == 0) return shorter_interval_case<T>(exponent);
        significand |= (static_cast<carrier_uint>(1) << num_significand_bits<T>());
    } else {
        // Subnormal case; the interval is always regular.
        if (significand == 0) return {0, 0};
        exponent = std::numeric_limits<T>::min_exponent - num_significand_bits<T>() - 1;
    }
    const bool include_left_endpoint = (significand % 2 == 0);
    const bool include_right_endpoint = include_left_endpoint;
    // Compute k and beta.
    const int minus_k = floor_log10_pow2(exponent) - float_info<T>::kappa;
    const cache_entry_type cache = cache_accessor<T>::get_cached_power(-minus_k);
    const int beta = exponent + floor_log2_pow10(-minus_k);
    // Compute zi and deltai.
    // 10^kappa <= deltai < 10^(kappa + 1)
    const uint32_t deltai = cache_accessor<T>::compute_delta(cache, beta);
    const carrier_uint two_fc = significand << 1;
    // For the case of binary32, the result of integer check is not correct for
    // 29711844 * 2^-82
    // = 6.1442653300000000008655037797566933477355632930994033813476... * 10^-18
    // and 29711844 * 2^-81
    // = 1.2288530660000000001731007559513386695471126586198806762695... * 10^-17,
    // and they are the unique counterexamples. However, since 29711844 is even,
    // this does not cause any problem for the endpoints calculations; it can only
    // cause a problem when we need to perform integer check for the center.
    // Fortunately, with these inputs, that branch is never executed, so we are
    // fine.
    const typename cache_accessor<T>::compute_mul_result z_mul =
        cache_accessor<T>::compute_mul((two_fc | 1) << beta, cache);
    // Step 2: Try larger divisor; remove trailing zeros if necessary.
    // Using an upper bound on zi, we might be able to optimize the division
    // better than the compiler; we are computing zi / big_divisor here.
    decimal_fp<T> ret_value;
    ret_value.significand = divide_by_10_to_kappa_plus_1(z_mul.result);
    uint32_t r = static_cast<uint32_t>(z_mul.result - float_info<T>::big_divisor * ret_value.significand);
    if (r < deltai) {
        // Exclude the right endpoint if necessary.
        if (r == 0 && (z_mul.is_integer & !include_right_endpoint)) {
            --ret_value.significand;
            r = float_info<T>::big_divisor;
            goto small_divisor_case_label;
        }
    } else if (r > deltai) {
        goto small_divisor_case_label;
    } else {
        // r == deltai; compare fractional parts.
        const typename cache_accessor<T>::compute_mul_parity_result x_mul =
            cache_accessor<T>::compute_mul_parity(two_fc - 1, cache, beta);
        if (!(x_mul.parity | (x_mul.is_integer & include_left_endpoint))) goto small_divisor_case_label;
    }
    ret_value.exponent = minus_k + float_info<T>::kappa + 1;
    // We may need to remove trailing zeros.
    ret_value.exponent += remove_trailing_zeros(ret_value.significand);
    return ret_value;
    // Step 3: Find the significand with the smaller divisor.
small_divisor_case_label:
    ret_value.significand *= 10;
    ret_value.exponent = minus_k + float_info<T>::kappa;
    uint32_t dist = r - (deltai / 2) + (float_info<T>::small_divisor / 2);
    const bool approx_y_parity = ((dist ^ (float_info<T>::small_divisor / 2)) & 1) != 0;
    // Is dist divisible by 10^kappa?
    const bool divisible_by_small_divisor = check_divisibility_and_divide_by_pow10<float_info<T>::kappa>(dist);
    // Add dist / 10^kappa to the significand.
    ret_value.significand += dist;
    if (!divisible_by_small_divisor) return ret_value;
    // Check z^(f) >= epsilon^(f).
    // We have either yi == zi - epsiloni or yi == (zi - epsiloni) - 1,
    // where yi == zi - epsiloni if and only if z^(f) >= epsilon^(f).
    // Since there are only 2 possibilities, we only need to care about the
    // parity. Also, zi and r should have the same parity since the divisor
    // is an even number.
    const auto y_mul = cache_accessor<T>::compute_mul_parity(two_fc, cache, beta);
    // If z^(f) >= epsilon^(f), we might have a tie when z^(f) == epsilon^(f),
    // or equivalently, when y is an integer.
    if (y_mul.parity != approx_y_parity) --ret_value.significand;
    else if (y_mul.is_integer & (ret_value.significand % 2 != 0)) --ret_value.significand;
    return ret_value;
}
References fmt::v10::detail::bit_cast(), divide_by_10_to_kappa_plus_1(), fmt::v10::detail::dragonbox::decimal_fp< T >::exponent, fmt::v10::detail::exponent_bias(), fmt::v10::detail::exponent_mask(), floor_log10_pow2(), floor_log2_pow10(), fmt::v10::detail::num_significand_bits(), remove_trailing_zeros(), shorter_interval_case(), and fmt::v10::detail::dragonbox::decimal_fp< T >::significand.
to_decimal() [2/2]
template<typename T > auto fmt::v10::detail::dragonbox::to_decimal (T x) -> decimal_fp< T > noexcept
Definition at line 1174 of file format-inl.h.
{
    // Step 1: integer promotion & Schubfach multiplier calculation.
    using carrier_uint = typename float_info<T>::carrier_uint;
    using cache_entry_type = typename cache_accessor<T>::cache_entry_type;
    auto br = bit_cast<carrier_uint>(x);
    // Extract significand bits and exponent bits.
    const carrier_uint significand_mask = (static_cast<carrier_uint>(1) << num_significand_bits<T>()) - 1;
    carrier_uint significand = (br & significand_mask);
    int exponent = static_cast<int>((br & exponent_mask<T>()) >> num_significand_bits<T>());
    if (exponent != 0) { // Check if normal.
        exponent -= exponent_bias<T>() + num_significand_bits<T>();
        // Shorter interval case; proceed like Schubfach.
        // In fact, when exponent == 1 and significand == 0, the interval is
        // regular. However, it can be shown that the end-results are anyway same.
        if (significand == 0) return shorter_interval_case<T>(exponent);
        significand |= (static_cast<carrier_uint>(1) << num_significand_bits<T>());
    } else {
        // Subnormal case; the interval is always regular.
        if (significand == 0) return {0, 0};
        exponent = std::numeric_limits<T>::min_exponent - num_significand_bits<T>() - 1;
    }
    const bool include_left_endpoint = (significand % 2 == 0);
    const bool include_right_endpoint = include_left_endpoint;
    // Compute k and beta.
    const int minus_k = floor_log10_pow2(exponent) - float_info<T>::kappa;
    const cache_entry_type cache = cache_accessor<T>::get_cached_power(-minus_k);
    const int beta = exponent + floor_log2_pow10(-minus_k);
    // Compute zi and deltai.
    // 10^kappa <= deltai < 10^(kappa + 1)
    const uint32_t deltai = cache_accessor<T>::compute_delta(cache, beta);
    const carrier_uint two_fc = significand << 1;
    // For the case of binary32, the result of integer check is not correct for
    // 29711844 * 2^-82
    // = 6.1442653300000000008655037797566933477355632930994033813476... * 10^-18
    // and 29711844 * 2^-81
    // = 1.2288530660000000001731007559513386695471126586198806762695... * 10^-17,
    // and they are the unique counterexamples. However, since 29711844 is even,
    // this does not cause any problem for the endpoints calculations; it can only
    // cause a problem when we need to perform integer check for the center.
    // Fortunately, with these inputs, that branch is never executed, so we are
    // fine.
    const typename cache_accessor<T>::compute_mul_result z_mul =
        cache_accessor<T>::compute_mul((two_fc | 1) << beta, cache);
    // Step 2: Try larger divisor; remove trailing zeros if necessary.
    // Using an upper bound on zi, we might be able to optimize the division
    // better than the compiler; we are computing zi / big_divisor here.
    decimal_fp<T> ret_value;
    ret_value.significand = divide_by_10_to_kappa_plus_1(z_mul.result);
    uint32_t r = static_cast<uint32_t>(z_mul.result - float_info<T>::big_divisor * ret_value.significand);
    if (r < deltai) {
        // Exclude the right endpoint if necessary.
        if (r == 0 && (z_mul.is_integer & !include_right_endpoint)) {
            --ret_value.significand;
            r = float_info<T>::big_divisor;
            goto small_divisor_case_label;
        }
    } else if (r > deltai) {
        goto small_divisor_case_label;
    } else {
        // r == deltai; compare fractional parts.
        const typename cache_accessor<T>::compute_mul_parity_result x_mul =
            cache_accessor<T>::compute_mul_parity(two_fc - 1, cache, beta);
        if (!(x_mul.parity | (x_mul.is_integer & include_left_endpoint))) goto small_divisor_case_label;
    }
    ret_value.exponent = minus_k + float_info<T>::kappa + 1;
    // We may need to remove trailing zeros.
    ret_value.exponent += remove_trailing_zeros(ret_value.significand);
    return ret_value;
    // Step 3: Find the significand with the smaller divisor.
small_divisor_case_label:
    ret_value.significand *= 10;
    ret_value.exponent = minus_k + float_info<T>::kappa;
    uint32_t dist = r - (deltai / 2) + (float_info<T>::small_divisor / 2);
    const bool approx_y_parity = ((dist ^ (float_info<T>::small_divisor / 2)) & 1) != 0;
    // Is dist divisible by 10^kappa?
    const bool divisible_by_small_divisor = check_divisibility_and_divide_by_pow10<float_info<T>::kappa>(dist);
    // Add dist / 10^kappa to the significand.
    ret_value.significand += dist;
    if (!divisible_by_small_divisor) return ret_value;
    // Check z^(f) >= epsilon^(f).
    // We have either yi == zi - epsiloni or yi == (zi - epsiloni) - 1,
    // where yi == zi - epsiloni if and only if z^(f) >= epsilon^(f).
    // Since there are only 2 possibilities, we only need to care about the
    // parity. Also, zi and r should have the same parity since the divisor
    // is an even number.
    const auto y_mul = cache_accessor<T>::compute_mul_parity(two_fc, cache, beta);
    // If z^(f) >= epsilon^(f), we might have a tie when z^(f) == epsilon^(f),
    // or equivalently, when y is an integer.
    if (y_mul.parity != approx_y_parity) --ret_value.significand;
    else if (y_mul.is_integer & (ret_value.significand % 2 != 0)) --ret_value.significand;
    return ret_value;
}
References fmt::v10::detail::bit_cast(), divide_by_10_to_kappa_plus_1(), fmt::v10::detail::dragonbox::decimal_fp< T >::exponent, fmt::v10::detail::exponent_bias(), fmt::v10::detail::exponent_mask(), floor_log10_pow2(), floor_log2_pow10(), fmt::v10::detail::num_significand_bits(), remove_trailing_zeros(), shorter_interval_case(), and fmt::v10::detail::dragonbox::decimal_fp< T >::significand.
umul128_upper64()
uint64_t fmt::v10::detail::dragonbox::umul128_upper64 (uint64_t x, uint64_t y) inline noexcept
Definition at line 1437 of file format.h.
{
#if FMT_USE_INT128
    auto p = static_cast<uint128_opt>(x) * static_cast<uint128_opt>(y);
    return static_cast<uint64_t>(p >> 64);
#elif defined(_MSC_VER) && defined(_M_X64)
    return __umulh(x, y);
#else
    return umul128(x, y).high();
#endif
}
References fmt::v10::detail::uint128_fallback::high(), fmt::v10::detail::umul128(), and umul128_upper64().
Referenced by divide_by_10_to_kappa_plus_1(), umul128_upper64(), umul192_upper128(), and umul96_upper64().
umul192_lower128()
uint128_fallback fmt::v10::detail::dragonbox::umul192_lower128 (uint64_t x, uint128_fallback y) inline noexcept
Definition at line 162 of file format-inl.h.
{
    uint64_t high = x * y.high();
    uint128_fallback high_low = umul128(x, y.low());
    return {high + high_low.high(), high_low.low()};
}
References fmt::v10::detail::uint128_fallback::high(), fmt::v10::detail::uint128_fallback::low(), and fmt::v10::detail::umul128().
Referenced by fmt::v10::detail::dragonbox::cache_accessor< double >::compute_mul_parity().
umul192_upper128()
uint128_fallback fmt::v10::detail::dragonbox::umul192_upper128 (uint64_t x, uint128_fallback y) inline noexcept
Definition at line 1450 of file format.h.
{
    uint128_fallback r = umul128(x, y.high());
    r += umul128_upper64(x, y.low());
    return r;
}
References fmt::v10::detail::umul128(), umul128_upper64(), and umul192_upper128().
Referenced by fmt::v10::detail::dragonbox::cache_accessor< double >::compute_mul(), and umul192_upper128().
umul96_lower64()
uint64_t fmt::v10::detail::dragonbox::umul96_lower64 (uint32_t x, uint64_t y) inline noexcept
Definition at line 170 of file format-inl.h.
{ return x * y; }
Referenced by fmt::v10::detail::dragonbox::cache_accessor< float >::compute_mul_parity().
umul96_upper64()
uint64_t fmt::v10::detail::dragonbox::umul96_upper64 (uint32_t x, uint64_t y) inline noexcept
Definition at line 156 of file format-inl.h.
{
    return umul128_upper64(static_cast<uint64_t>(x) << 32, y);
}
References umul128_upper64().
Referenced by fmt::v10::detail::dragonbox::cache_accessor< float >::compute_mul().
Variable Documentation
[struct]
struct { ... } fmt::v10::detail::dragonbox::div_small_pow10_infos[]
Referenced by check_divisibility_and_divide_by_pow10(), and small_division_by_pow10().
divisor
uint32_t fmt::v10::detail::dragonbox::divisor
Definition at line 179 of file format-inl.h.
shift_amount
int fmt::v10::detail::dragonbox::shift_amount
Definition at line 180 of file format-inl.h.