1516b Over Under: Robot::Autonomous::AutoDrive
AutoDrive()
void Autonomous::AutoDrive (Puncher & puncher, bool autono = false)
Drives the robot autonomously.
This function drives the robot autonomously based on the selected autonomous program. It takes a reference to a Puncher object and a boolean value indicating whether to use autonomous mode.
Parameters
puncher A reference to the Puncher object.
autono A boolean value indicating whether to use autonomous mode.
Definition at line 60 of file auton.cpp.
{
   // Keep the switcher running while the controller down button has not been pressed and the time period is not autonomous
   if (autono == false) {
      AutonSwitcher();
   }
   // Compare the current auton value to run the auton routine
    if(Autonomous::auton == 1){
        Auton1();
    }
    if(Autonomous::auton == 2){
        Auton2();
    }
    if(Autonomous::auton == 3){
        Auton3(puncher);
    }
}
References auton, Auton1(), Auton2(), Auton3(), and AutonSwitcher().
Referenced by autonomous().