1516X High Stakes: lemlib::Chassis Class Reference
lemlib::Chassis Class Reference
Chassis class.
#include <chassis.hpp>
Public Member Functions
Chassis (Drivetrain drivetrain, ControllerSettings linearSettings, ControllerSettings angularSettings, OdomSensors sensors, DriveCurve *throttleCurve=&defaultDriveCurve, DriveCurve *steerCurve=&defaultDriveCurve)
void calibrate (bool calibrateIMU=true)
Calibrate the chassis sensors. THis should be called in the initialize function.
void setPose (float x, float y, float theta, bool radians=false)
Set the pose of the chassis.
void setPose (Pose pose, bool radians=false)
Set the pose of the chassis.
Pose getPose (bool radians=false, bool standardPos=false)
Get the pose of the chassis.
void waitUntil (float dist)
Wait until the robot has traveled a certain distance along the path.
void waitUntilDone ()
Wait until the robot has completed the path.
void setBrakeMode (pros::motor_brake_mode_e mode)
Sets the brake mode of the drivetrain motors.
void turnToPoint (float x, float y, int timeout, TurnToPointParams params={}, bool async=true)
Turn the chassis so it is facing the target point.
void turnToHeading (float theta, int timeout, TurnToHeadingParams params={}, bool async=true)
Turn the chassis so it is facing the target heading.
void swingToHeading (float theta, DriveSide lockedSide, int timeout, SwingToHeadingParams params={}, bool async=true)
Turn the chassis so it is facing the target heading, but only by moving one half of the drivetrain.
void swingToPoint (float x, float y, DriveSide lockedSide, int timeout, SwingToPointParams params={}, bool async=true)
Turn the chassis so it is facing the target point, but only by moving one half of the drivetrain.
void moveToPose (float x, float y, float theta, int timeout, MoveToPoseParams params={}, bool async=true)
Move the chassis towards the target pose.
void moveToPoint (float x, float y, int timeout, MoveToPointParams params={}, bool async=true)
Move the chassis towards a target point.
void follow (const asset &path, float lookahead, int timeout, bool forwards=true, bool async=true)
Move the chassis along a path.
void tank (int left, int right, bool disableDriveCurve=false)
Control the robot during the driver using the arcade drive control scheme. In this control scheme one joystick axis controls the forwards and backwards movement of the robot, while the other joystick axis.
void arcade (int throttle, int turn, bool disableDriveCurve=false, float desaturateBias=0.5)
Control the robot during the driver using the arcade drive control scheme. In this control scheme one joystick axis controls the forwards and backwards movement of the robot, while the other joystick axis controls the robot's turning.
void curvature (int throttle, int turn, bool disableDriveCurve=false)
Control the robot during the driver using the curvature drive control scheme. This control scheme is very similar to arcade drive, except the second joystick axis controls the radius of the curve that the drivetrain makes, rather than the speed. This means that the driver can accelerate in a turn without changing the radius of that turn. This control scheme defaults to arcade when forward is zero.
void cancelMotion ()
Cancels the currently running motion. If there is a queued motion, then that queued motion will run.
void cancelAllMotions ()
Cancels all motions, even those that are queued. After this, the chassis will not be in motion.
bool isInMotion () const
void resetLocalPosition ()
Resets the x and y position of the robot without interfering with the heading.
Public Attributes
PID lateralPID
PID angularPID
Protected Member Functions
void requestMotionStart ()
Indicates that this motion is queued and blocks current task until this motion reaches front of queue.
void endMotion ()
Dequeues this motion and permits queued task to run.
Protected Attributes
bool motionRunning = false
bool motionQueued = false
float distTraveled = 0
ControllerSettings lateralSettings
ControllerSettings angularSettings
Drivetrain drivetrain
OdomSensors sensors
DriveCurve * throttleCurve
DriveCurve * steerCurve
ExitCondition lateralLargeExit
ExitCondition lateralSmallExit
ExitCondition angularLargeExit
ExitCondition angularSmallExit
Private Attributes
pros::Mutex mutex
Detailed Description
Chassis class.
Definition at line 332 of file chassis.hpp.
Constructor & Destructor Documentation
Chassis()
lemlib::Chassis::Chassis (Drivetrain drivetrain, ControllerSettings linearSettings, ControllerSettings angularSettings, OdomSensors sensors, DriveCurve * throttleCurve = &defaultDriveCurve, DriveCurve * steerCurve = &defaultDriveCurve)
Member Function Documentation
arcade()
void lemlib::Chassis::arcade (int throttle, int turn, bool disableDriveCurve = false, float desaturateBias = 0.5)
Control the robot during the driver using the arcade drive control scheme. In this control scheme one joystick axis controls the forwards and backwards movement of the robot, while the other joystick axis controls the robot's turning.
Parameters
throttle speed to move forward or backward. Takes an input from -127 to 127.
turn speed to turn. Takes an input from -127 to 127.
disableDriveCurve whether to disable the drive curve or not. If disabled, uses a linear curve with no deadzone or minimum power
desaturateBias how much to favor angular motion over lateral motion or vice versa when motors are saturated. A value of 0 fully prioritizes lateral motion, a value of 1 fully prioritizes angular motion
Example
// opcontrol function in your project. The function that runs during the driver control period
void opcontrol() {
    // controller
    pros::Controller controller(pros::E_CONTROLLER_MASTER);
    // loop to continuously update motors
    while (true) {
        // get joystick positions
        int leftY = controller.get_analog(pros::E_CONTROLLER_ANALOG_LEFT_Y);
        int rightX = controller.get_analog(pros::E_CONTROLLER_ANALOG_RIGHT_X);
        // move the chassis with arcade controls
        chassis.arcade(leftY, // throttle
                       rightX, // steer
                       false, // enable drive curves
                       0.75 // slightly prioritize steering
        );
        // delay to save resources
        pros::delay(25);
    }
}
Referenced by Robot::Drivetrain::ArcadeDrive().
calibrate()
void lemlib::Chassis::calibrate (bool calibrateIMU = true)
Calibrate the chassis sensors. THis should be called in the initialize function.
Parameters
calibrateIMU whether the IMU should be calibrated. true by default
Example
// initialize function in your project. The first function that runs when the program is started
void initialize() {
    chassis.calibrate();
}
// initialize function in your project. The first function that runs when the program is started
void initialize() {
    // don't calibrate the IMU
    // this should only be necessary if you are using a different library that calibrates the IMU
    chassis.calibrate(false);
}
cancelAllMotions()
void lemlib::Chassis::cancelAllMotions ()
Cancels all motions, even those that are queued. After this, the chassis will not be in motion.
Example
// move the robot to x = 20, y = 20 with a timeout of 4000ms
chassis.moveToPoint(20, 20, 4000);
// wait 500 milliseconds
pros::delay(500);
// cancel all motions. The robot will stop immediately
chassis.cancelAllMotions();
Example (advanced)
// this example shows how the cancelMotion function behaves when a motion is queued
// this is an advanced example since we will be using tasks here
// move the robot to x = 20, y = 20 with a timeout of 4000ms
chassis.moveToPoint(20, 20, 4000);
// start a lambda task that will be used to cancel all motions after 500ms
pros::Task task([] {
    // wait 500 milliseconds
    pros::delay(500);
    // cancels both motions
    chassis.cancelAllMotions();
});
// queue a motion to x = 10, y = 10 with a timeout of 4000ms
// this will never run because cancelAllMotions will be called while this motion is in the queue
chassis.moveToPoint(10, 10, 4000);
cancelMotion()
void lemlib::Chassis::cancelMotion ()
Cancels the currently running motion. If there is a queued motion, then that queued motion will run.
Example
// move the robot to x = 20, y = 20 with a timeout of 4000ms
chassis.moveToPoint(20, 20, 4000);
// wait 500 milliseconds
pros::delay(500);
// cancel the current motion. This stops it immediately
chassis.cancelMotion();
Example (advanced)
// this example shows how the cancelMotion function behaves when a motion is queued
// this is an advanced example since we will be using tasks here
// move the robot to x = 20, y = 20 with a timeout of 4000ms
chassis.moveToPoint(20, 20, 4000);
// start a lambda task that will be used to cancel the motion after 500ms
pros::Task task([] {
    // wait 500 milliseconds
    pros::delay(500);
    // cancel the current motion. This stops it immediately
    chassis.cancelMotion();
});
// queue a motion to x = 10, y = 10 with a timeout of 4000ms
// this will run after the first motion is cancelled
chassis.moveToPoint(10, 10, 4000);
curvature()
void lemlib::Chassis::curvature (int throttle, int turn, bool disableDriveCurve = false)
Control the robot during the driver using the curvature drive control scheme. This control scheme is very similar to arcade drive, except the second joystick axis controls the radius of the curve that the drivetrain makes, rather than the speed. This means that the driver can accelerate in a turn without changing the radius of that turn. This control scheme defaults to arcade when forward is zero.
Parameters
throttle speed to move forward or backward. Takes an input from -127 to 127.
turn speed to turn. Takes an input from -127 to 127.
disableDriveCurve whether to disable the drive curve or not. If disabled, uses a linear curve with no deadzone or minimum power
Example
// opcontrol function in your project. The function that runs during the driver control period
void opcontrol() {
    // controller
    pros::Controller controller(pros::E_CONTROLLER_MASTER);
    // loop to continuously update motors
    while (true) {
        // get joystick positions
        int leftY = controller.get_analog(pros::E_CONTROLLER_ANALOG_LEFT_Y);
        int rightX = controller.get_analog(pros::E_CONTROLLER_ANALOG_RIGHT_X);
        // move the chassis with curvature controls
        chassis.curvature(leftY, rightX);
        // delay to save resources
        pros::delay(25);
    }
}
Referenced by Robot::Drivetrain::CurvatureDrive(), and Robot::Drivetrain::CurveDrive().
endMotion()
void lemlib::Chassis::endMotion () protected
Dequeues this motion and permits queued task to run.
follow()
void lemlib::Chassis::follow (const asset & path, float lookahead, int timeout, bool forwards = true, bool async = true)
Move the chassis along a path.
Parameters
path the path asset to follow
lookahead the lookahead distance. Units in inches. Larger values will make the robot move faster but will follow the path less accurately
timeout the maximum time the robot can spend moving
forwards whether the robot should follow the path going forwards. true by default
async whether the function should be run asynchronously. true by default
Example
// load "myPath.txt"
// the file should be in the "static" folder in the project root directory
// this should also be done outside of any functions, otherwise it won't compile
ASSET(myPath_txt); // we replace "." with "_" to make the asset name valid
// autonomous function in your project. The function that runs during the autonomous period
void autonomous() {
    // follow the path in "myPath.txt" with a lookahead of 10 inches and a timeout of 4000ms
    chassis.follow(myPath_txt, 10, 4000);
    // follow the path in "myPath.txt" with a lookahead of 10 inches and a timeout of 4000ms
    // but follow the path backwards
    chassis.follow(myPath_txt, 10, 4000, false);
}
Referenced by Robot::Autonomous::Auton1(), and Robot::Autonomous::Auton2().
getPose()
Pose lemlib::Chassis::getPose (bool radians = false, bool standardPos = false)
Get the pose of the chassis.
Parameters
radians whether theta should be in radians (true) or degrees (false). false by default
Returns
Pose
Example
// get the pose of the chassis
lemlib::Pose pose = chassis.getPose();
// print the x, y, and theta values of the pose
printf("X: %f, Y: %f, Theta: %f\n", pose.x, pose.y, pose.theta);
// get the pose of the chassis in radians
lemlib::Pose poseRad = chassis.getPose(true);
// print the x, y, and theta values of the pose
printf("X: %f, Y: %f, Theta: %f\n", poseRad.x, poseRad.y, poseRad.theta);
// get the pose of the chassis in radians and standard position
lemlib::Pose poseRadStandard = chassis.getPose(true, true);
// print the x, y, and theta values of the pose
printf("X: %f, Y: %f, Theta: %f\n", poseRadStandard.x, poseRadStandard.y, poseRadStandard.theta);
Referenced by Robot::Utility::displayLocation().
isInMotion()
bool lemlib::Chassis::isInMotion () const
Returns
whether a motion is currently running
Example
// move the robot to x = 20, y = 15, and face heading 90
chassis.moveToPose(20, 15, 90, 4000);
// delay for 500ms
// this returns true, since the robot is still in motion
chassis.isInMotion();
moveToPoint()
void lemlib::Chassis::moveToPoint (float x, float y, int timeout, MoveToPointParams params = {}, bool async = true)
Move the chassis towards a target point.
Parameters
x x location
y y location
timeout longest time the robot can spend moving
params struct to simulate named parameters
async whether the function should be run asynchronously. true by default
Example
// move the robot to x = 20, y = 15 with a timeout of 4000ms
chassis.moveToPoint(20, 15, 4000);
// move the robot to x = 20, y = 15 with a timeout of 4000ms
// but face the point with the back of the robot
chassis.moveToPoint(20, 15, 4000, {.forwards = false});
// move the robot to x = -20, 32.5 with a timeout of 4000ms
// with a maxSpeed of 60
chassis.moveToPoint(-20, 32.5, 4000, {.maxSpeed = 60});
// move the robot to x = 10, y = 10 with a timeout of 4000ms
// with a minSpeed of 20 and a maxSpeed of 60
chassis.moveToPoint(10, 10, 4000, {.maxSpeed = 60, .minSpeed = 20});
// move the robot to x = 7.5, y = 7.5 with a timeout of 4000ms
// with a minSpeed of 60, and exit the movement if the robot is within 5 inches of the target
chassis.moveToPoint(7.5, 7.5, 4000, {.minSpeed = 60, .earlyExitRange = 5});
Referenced by Robot::Autonomous::Auton4().
moveToPose()
void lemlib::Chassis::moveToPose (float x, float y, float theta, int timeout, MoveToPoseParams params = {}, bool async = true)
Move the chassis towards the target pose.
Uses the boomerang controller
Parameters
x x location
y y location
theta target heading in degrees.
timeout longest time the robot can spend moving
params struct to simulate named parameters
async whether the function should be run asynchronously. true by default
Example
// move the robot to x = 20, y = 15, and face heading 90 with a timeout of 4000ms
chassis.moveToPose(20, 15, 90, 4000);
// move the robot to x = 20, y = 15, and face heading 90 with a timeout of 4000ms
// but face the point with the back of the robot
chassis.moveToPose(20, 15, 90, 4000, {.forwards = false});
// move the robot to x = -20, 32.5 and face heading 90 with a timeout of 4000ms
// with a maxSpeed of 60
chassis.moveToPose(-20, 32.5, 90, 4000, {.maxSpeed = 60});
// move the robot to x = 10, y = 10 and face heading 90
// with a minSpeed of 20 and a maxSpeed of 60
chassis.moveToPose(10, 10, 90, 4000, {.maxSpeed = 60, .minSpeed = 20});
// move the robot to x = 7.5, y = 7.5 and face heading 90 with a timeout of 4000ms
// with a minSpeed of 60, and exit the movement if the robot is within 5 inches of the target
chassis.moveToPose(7.5, 7.5, 90, 4000, {.minSpeed = 60, .earlyExitRange = 5});
// move the robot to 0, 0, and facing heading 0 with a timeout of 4000ms
// this motion should not be as curved as the others, so we set lead to a smaller value (0.3)
chassis.moveToPose(0, 0, 0, 4000, {.lead = 0.3});
requestMotionStart()
void lemlib::Chassis::requestMotionStart () protected
Indicates that this motion is queued and blocks current task until this motion reaches front of queue.
resetLocalPosition()
void lemlib::Chassis::resetLocalPosition ()
Resets the x and y position of the robot without interfering with the heading.
Example
// set robot position to x = 10, y = 15, and heading 90
chassis.setPose(10, 15, 90);
// reset the robot's x and y position
chassis.resetLocalPosition();
// the robot's position is now x = 0, y = 0, and heading 90
setBrakeMode()
void lemlib::Chassis::setBrakeMode (pros::motor_brake_mode_e mode)
Sets the brake mode of the drivetrain motors.
Parameters
mode Mode to set the drivetrain motors to
Example
// set the brake mode of the drivetrain motors to hold
chassis.setBrakeMode(pros::E_MOTOR_BRAKE_HOLD);
// set the brake mode of the drivetrain motors to coast
chassis.setBrakeMode(pros::E_MOTOR_BRAKE_COAST);
// set the brake mode of the drivetrain motors to brake
chassis.setBrakeMode(pros::E_MOTOR_BRAKE_BRAKE);
Referenced by Robot::Autonomous::Auton4().
setPose() [1/2]
void lemlib::Chassis::setPose (float x, float y, float theta, bool radians = false)
Set the pose of the chassis.
Parameters
x new x value
y new y value
theta new theta value
radians true if theta is in radians, false if not. False by default
Example
// set the pose of the chassis to x = 0, y = 0, theta = 0
chassis.setPose(0, 0, 0);
// set the pose of the chassis to x = 5.3, y = 12.2, theta = 3.14
// this time with theta in radians
chassis.setPose(5.3, 12.2, 3.14, true);
Referenced by Robot::Autonomous::Auton1(), Robot::Autonomous::Auton2(), Robot::Autonomous::Auton4(), and initialize().
setPose() [2/2]
void lemlib::Chassis::setPose (Pose pose, bool radians = false)
Set the pose of the chassis.
Parameters
pose the new pose
radians whether pose theta is in radians (true) or not (false). false by default
Example
// set the pose of the chassis to x = 0, y = 0, theta = 0
lemlib::Pose poseA(0, 0, 0);
chassis.setPose(poseA);
// set the pose of the chassis to x = 5.3, y = 12.2, theta = 3.14
// this time with theta in radians
lemlib::Pose poseB(5.3, 12.2, 3.14);
chassis.setPose(poseB, true);
swingToHeading()
void lemlib::Chassis::swingToHeading (float theta, DriveSide lockedSide, int timeout, SwingToHeadingParams params = {}, bool async = true)
Turn the chassis so it is facing the target heading, but only by moving one half of the drivetrain.
Parameters
theta heading location
lockedSide side of the drivetrain that is locked
timeout longest time the robot can spend moving
params struct to simulate named parameters
async whether the function should be run asynchronously. true by default
Example
chassis.setPose(0, 0, 0); // set the pose of the chassis to x = 0, y = 0, theta = 0
// turn the robot to face heading 135, with a timeout of 1000ms
// and lock the left side of the drivetrain
chassis.swingToHeading(135, DriveSide::LEFT, 1000);
// turn the robot to face heading 230.5 with a timeout of 2000ms
// and a maximum speed of 60
// and lock the right side of the drivetrain
chassis.swingToHeading(230.5, DriveSide::RIGHT, 2000, {.maxSpeed = 60});
// turn the robot to face heading -90 with a timeout of 1500ms
// and turn counterclockwise
// and lock the left side of the drivetrain
chassis.swingToHeading(-90, DriveSide::LEFT, 1500, {.direction = AngularDirection::CCW_COUNTERCLOCKWISE});
// turn the robot to face heading 90 with a timeout of 500ms
// with a minSpeed of 20 and a maxSpeed of 60
// and lock the right side of the drivetrain
chassis.swingToHeading(90, DriveSide::RIGHT, 500, {.maxSpeed = 60, .minSpeed = 20});
// turn the robot to face heading 45 with a timeout of 2000ms
// and a minSpeed of 60, and exit the movement if the robot is within 5 degrees of the target
// and lock the left side of the drivetrain
chassis.swingToHeading(45, DriveSide::LEFT, 2000, {.minSpeed = 60, .earlyExitRange = 5});
swingToPoint()
void lemlib::Chassis::swingToPoint (float x, float y, DriveSide lockedSide, int timeout, SwingToPointParams params = {}, bool async = true)
Turn the chassis so it is facing the target point, but only by moving one half of the drivetrain.
Parameters
x x location
y y location
lockedSide side of the drivetrain that is locked
timeout longest time the robot can spend moving
params struct to simulate named parameters
async whether the function should be run asynchronously. true by default
Example
chassis.setPose(0, 0, 0); // set the pose of the chassis to x = 0, y = 0, theta = 0
// turn the robot to face the point x = 45, y = -45, with a timeout of 1000ms
// and lock the left side of the drivetrain
chassis.swingToPoint(45, -45, DriveSide::LEFT, 1000);
// turn the robot to face the point x = 45, y = -45, with a timeout of 1000ms
// but face the point with the back of the robot
// and lock the right side of the drivetrain
chassis.swingToPoint(45, -45, DriveSide::RIGHT, 1000, {.forwards = false});
// turn the robot to face the point x = -20, 32.5 with a timeout of 2000ms
// and a maximum speed of 60
// and lock the left side of the drivetrain
chassis.swingToPoint(-20, 32.5, DriveSide::LEFT, 2000, {.maxSpeed = 60});
// turn the robot to face the point x = -30, y = 22.5 with a timeout of 1500ms
// and turn counterclockwise
// and lock the right side of the drivetrain
chassis.swingToPoint(-30, 22.5, DriveSide::RIGHT, 1500, {.direction =
AngularDirection::CCW_COUNTERCLOCKWISE});
// turn the robot to face the point x = 10, y = 10 with a timeout of 500ms
// with a minSpeed of 20 and a maxSpeed of 60
// and lock the left side of the drivetrain
chassis.swingToPoint(10, 10, DriveSide::LEFT, 500, {.maxSpeed = 60, .minSpeed = 20});
// turn the robot to face the point x = 7.5, y = 7.5 with a timeout of 2000ms
// and a minSpeed of 60, and exit the movement if the robot is within 5 degrees of the target
// and lock the right side of the drivetrain
chassis.swingToPoint(7.5, 7.5, DriveSide::RIGHT, 2000, {.minSpeed = 60, .earlyExitRange = 5});
tank()
void lemlib::Chassis::tank (int left, int right, bool disableDriveCurve = false)
Control the robot during the driver using the arcade drive control scheme. In this control scheme one joystick axis controls the forwards and backwards movement of the robot, while the other joystick axis.
controls the robot's turning
Parameters
throttle speed to move forward or backward. Takes an input from -127 to 127.
turn speed to turn. Takes an input from -127 to 127.
disableDriveCurve whether to disable the drive curve or not. If disabled, uses a linear curve with no deadzone or minimum power
Example
// opcontrol function in your project. The function that runs during the driver control period
void opcontrol() {
    // controller
    pros::Controller controller(pros::E_CONTROLLER_MASTER);
    // loop to continuously update motors
    while (true) {
        // get joystick positions
        int leftY = controller.get_analog(pros::E_CONTROLLER_ANALOG_LEFT_Y);
        int rightY = controller.get_analog(pros::E_CONTROLLER_ANALOG_RIGHT_Y);
        // move the chassis with tank controls
        chassis.tank(leftY, rightY);
        // delay to save resources
        pros::delay(25);
    }
}
Referenced by Robot::Drivetrain::TankDrive().
turnToHeading()
void lemlib::Chassis::turnToHeading (float theta, int timeout, TurnToHeadingParams params = {}, bool async = true)
Turn the chassis so it is facing the target heading.
Parameters
theta heading location
timeout longest time the robot can spend moving
params struct to simulate named parameters
async whether the function should be run asynchronously. true by default
Example
chassis.setPose(0, 0, 0); // set the pose of the chassis to x = 0, y = 0, theta = 0
// turn the robot to face heading 135, with a timeout of 1000ms
chassis.turnToHeading(135, 1000);
// turn the robot to face heading 230.5 with a timeout of 2000ms
// and a maximum speed of 60
chassis.turnToHeading(230.5, 2000, {.maxSpeed = 60});
// turn the robot to face heading -90 with a timeout of 1500ms
// and turn counterclockwise
chassis.turnToHeading(-90, 1500, {.direction = AngularDirection::CCW_COUNTERCLOCKWISE});
// turn the robot to face heading 90 with a timeout of 500ms
// with a minSpeed of 20 and a maxSpeed of 60
chassis.turnToHeading(90, 500, {.maxSpeed = 60, .minSpeed = 20});
// turn the robot to face heading 45 with a timeout of 2000ms
// and a minSpeed of 60, and exit the movement if the robot is within 5 degrees of the target
chassis.turnToHeading(45, 2000, {.minSpeed = 60, .earlyExitRange = 5});
Referenced by Robot::Autonomous::Auton4().
turnToPoint()
void lemlib::Chassis::turnToPoint (float x, float y, int timeout, TurnToPointParams params = {}, bool async = true)
Turn the chassis so it is facing the target point.
Parameters
x x location
y y location
timeout longest time the robot can spend moving
params struct to simulate named parameters
async whether the function should be run asynchronously. true by default
Example
chassis.setPose(0, 0, 0); // set the pose of the chassis to x = 0, y = 0, theta = 0
// turn the robot to face the point x = 45, y = -45, with a timeout of 1000ms
chassis.turnToPoint(45, -45, 1000);
// turn the robot to face the point x = 45, y = -45, with a timeout of 1000ms
// but face the point with the back of the robot
chassis.turnToPoint(45, -45, 1000, {.forwards = false});
// turn the robot to face the point x = -20, 32.5 with a timeout of 2000ms
// and a maximum speed of 60
chassis.turnToPoint(-20, 32.5, 2000, {.maxSpeed = 60});
// turn the robot to face the point x = -30, y = 22.5 with a timeout of 1500ms
// and turn counterclockwise
chassis.turnToPoint(-30, 22.5, 1500, {.direction = AngularDirection::CCW_COUNTERCLOCKWISE});
// turn the robot to face the point x = 10, y = 10 with a timeout of 500ms
// with a minSpeed of 20 and a maxSpeed of 60
chassis.turnToPoint(10, 10, 500, {.maxSpeed = 60, .minSpeed = 20});
// turn the robot to face the point x = 7.5, y = 7.5 with a timeout of 2000ms
// and a minSpeed of 60, and exit the movement if the robot is within 5 degrees of the target
chassis.turnToPoint(7.5, 7.5, 2000, {.minSpeed = 60, .earlyExitRange = 5});
waitUntil()
void lemlib::Chassis::waitUntil (float dist)
Wait until the robot has traveled a certain distance along the path.
Note
Units are in inches if current motion is moveToPoint, moveToPose or follow, degrees for everything else
Parameters
dist the distance the robot needs to travel before returning
Example
// move the robot to x = 20, y = 15, and face heading 90
chassis.moveToPose(20, 15, 90, 4000);
// wait until the robot has traveled 10 inches
chassis.waitUntil(10);
// output "traveled 10 inches" to the console
std::cout << "traveled 10 inches" << std::endl;
// turn the robot to face 270 degrees
// this will wait for the last motion to complete before running
chassis.turnToHeading(270, 4000);
// wait until the robot has traveled 45 degrees
chassis.waitUntil(45);
// output "traveled 45 degrees" to the console
std::cout << "traveled 45 degrees" << std::endl;
waitUntilDone()
void lemlib::Chassis::waitUntilDone ()
Wait until the robot has completed the path.
Example
// move the robot to x = 20, y = 15, and face heading 90
chassis.moveToPose(20, 15, 90, 4000);
// wait until the robot has completed the motion
chassis.waitUntilDone();
// output "motion completed" to the console
std::cout << "motion completed" << std::endl;
Member Data Documentation
angularLargeExit
ExitCondition lemlib::Chassis::angularLargeExit protected
Definition at line 937 of file chassis.hpp.
angularPID
PID lemlib::Chassis::angularPID
PIDs are exposed so advanced users can implement things like gain scheduling Changes are immediate and will affect a motion in progress
Warning
Do not interact with these unless you know what you are doing
Definition at line 912 of file chassis.hpp.
angularSettings
ControllerSettings lemlib::Chassis::angularSettings protected
Definition at line 929 of file chassis.hpp.
angularSmallExit
ExitCondition lemlib::Chassis::angularSmallExit protected
Definition at line 938 of file chassis.hpp.
distTraveled
float lemlib::Chassis::distTraveled = 0 protected
Definition at line 926 of file chassis.hpp.
drivetrain
Drivetrain lemlib::Chassis::drivetrain protected
Definition at line 930 of file chassis.hpp.
lateralLargeExit
ExitCondition lemlib::Chassis::lateralLargeExit protected
Definition at line 935 of file chassis.hpp.
lateralPID
PID lemlib::Chassis::lateralPID
PIDs are exposed so advanced users can implement things like gain scheduling Changes are immediate and will affect a motion in progress
Warning
Do not interact with these unless you know what you are doing
Definition at line 905 of file chassis.hpp.
lateralSettings
ControllerSettings lemlib::Chassis::lateralSettings protected
Definition at line 928 of file chassis.hpp.
lateralSmallExit
ExitCondition lemlib::Chassis::lateralSmallExit protected
Definition at line 936 of file chassis.hpp.
motionQueued
bool lemlib::Chassis::motionQueued = false protected
Definition at line 924 of file chassis.hpp.
motionRunning
bool lemlib::Chassis::motionRunning = false protected
Definition at line 923 of file chassis.hpp.
mutex
pros::Mutex lemlib::Chassis::mutex private
Definition at line 940 of file chassis.hpp.
sensors
OdomSensors lemlib::Chassis::sensors protected
Definition at line 931 of file chassis.hpp.
steerCurve
DriveCurve* lemlib::Chassis::steerCurve protected
Definition at line 933 of file chassis.hpp.
throttleCurve
DriveCurve* lemlib::Chassis::throttleCurve protected
Definition at line 932 of file chassis.hpp.
The documentation for this class was generated from the following file:
include/lemlib/chassis/chassis.hpp