1516X High Stakes: fmt::v10::basic_string_view< Char > Class Template Reference
fmt::v10::basic_string_view< Char > Class Template Reference
#include <core.h>
Public Types
using value_type = Char
using iterator = const Char*
Public Member Functions
constexpr basic_string_view () noexcept
constexpr basic_string_view (const Char *s, size_t count) noexcept
basic_string_view (const Char *s)
template<typename Traits , typename Alloc >
basic_string_view (const std::basic_string< Char, Traits, Alloc > &s) noexcept
template<typename S , fmt::enable_if_t<(std::is_same< S, detail::std_string_view< Char > >::value), int > = 0>
basic_string_view (S s) noexcept
constexpr auto data () const noexcept -> const Char *
constexpr auto size () const noexcept -> size_t
constexpr auto begin () const noexcept -> iterator
constexpr auto end () const noexcept -> iterator
constexpr auto operator[] (size_t pos) const noexcept -> const Char &
void remove_prefix (size_t n) noexcept
bool starts_with (basic_string_view< Char > sv) const noexcept
bool starts_with (Char c) const noexcept
bool starts_with (const Char *s) const
auto compare (basic_string_view other) const -> int
Private Attributes
const Char * data_
size_t size_
Friends
auto operator== (basic_string_view lhs, basic_string_view rhs) -> bool
auto operator!= (basic_string_view lhs, basic_string_view rhs) -> bool
auto operator< (basic_string_view lhs, basic_string_view rhs) -> bool
auto operator<= (basic_string_view lhs, basic_string_view rhs) -> bool
auto operator> (basic_string_view lhs, basic_string_view rhs) -> bool
auto operator>= (basic_string_view lhs, basic_string_view rhs) -> bool
Detailed Description
template<typename Char>
class fmt::v10::basic_string_view< Char >
An implementation of std::basic_string_view for pre-C++17. It provides a subset of the API. fmt::basic_string_view is used for format strings even if std::string_view is available to prevent issues when a library is compiled with a different -std option than the client code (which is not recommended).
Definition at line 371 of file core.h.
Member Typedef Documentation
iterator
template<typename Char > using fmt::v10::basic_string_view< Char >::iterator = const Char*
Definition at line 377 of file core.h.
value_type
template<typename Char > using fmt::v10::basic_string_view< Char >::value_type = Char
Definition at line 376 of file core.h.
Constructor & Destructor Documentation
basic_string_view() [1/5]
template<typename Char > fmt::v10::basic_string_view< Char >::basic_string_view () inline constexpr noexcept
Definition at line 379 of file core.h.
: data_(nullptr), size_(0) {}
basic_string_view() [2/5]
template<typename Char > fmt::v10::basic_string_view< Char >::basic_string_view (const Char * s, size_t count) inline constexpr noexcept
Constructs a string reference object from a C string and a size.
Definition at line 382 of file core.h.
: data_(s), size_(count) {}
basic_string_view() [3/5]
template<typename Char > fmt::v10::basic_string_view< Char >::basic_string_view (const Char * s) inline
\rst Constructs a string reference object from a C string computing the size with std::char_traits<Char>::length. \endrst
Definition at line 393 of file core.h.
            : data_(s),
              size_(detail::const_check(std::is_same<Char, char>::value && !detail::is_constant_evaluated(true))
                        ? std::strlen(reinterpret_cast<const char*>(s))
                        : std::char_traits<Char>::length(s)) {}
basic_string_view() [4/5]
template<typename Char > template<typename Traits , typename Alloc > fmt::v10::basic_string_view< Char >::basic_string_view (const std::basic_string< Char, Traits, Alloc > & s) inline noexcept
Constructs a string reference from a std::basic_string object.
Definition at line 401 of file core.h.
            : data_(s.data()), size_(s.size()) {}
basic_string_view() [5/5]
template<typename Char > template<typename S , fmt::enable_if_t<(std::is_same< S, detail::std_string_view< Char > >::value), int > = 0> fmt::v10::basic_string_view< Char >::basic_string_view (S s) inline noexcept
Definition at line 405 of file core.h.
: data_(s.data()), size_(s.size()) {}
Member Function Documentation
begin()
template<typename Char > auto fmt::v10::basic_string_view< Char >::begin () const -> iterator inline constexpr noexcept
Definition at line 413 of file core.h.
{ return data_; }
Referenced by fmt::v10::basic_format_parse_context< Char >::begin(), fmt::v10::detail::to_utf8< WChar, Buffer >::convert(), and fmt::v10::detail::find_escape().
compare()
template<typename Char > auto fmt::v10::basic_string_view< Char >::compare (basic_string_view< Char > other) const -> int inline
Definition at line 437 of file core.h.
{
            size_t str_size = size_ < other.size_ ? size_ : other.size_;
            int result = std::char_traits<Char>::compare(data_, other.data_, str_size);
            if (result == 0) result = size_ == other.size_ ? 0 : (size_ < other.size_ ? -1 : 1);
            return result;
        }
data()
template<typename Char > auto fmt::v10::basic_string_view< Char >::data () const -> const Char* inline constexpr noexcept
Returns a pointer to the string data.
Definition at line 408 of file core.h.
{ return data_; }
Referenced by fmt::v10::detail::value< Context >::value(), fmt::v10::detail_exported::compile_string_to_view(), fmt::v10::detail::for_each_codepoint(), fmt::v10::detail::parse_format_string(), and fmt::v10::detail::print().
end()
template<typename Char > auto fmt::v10::basic_string_view< Char >::end () const -> iterator inline constexpr noexcept
Definition at line 415 of file core.h.
{ return data_ + size_; }
Referenced by fmt::v10::detail::to_utf8< WChar, Buffer >::convert(), fmt::v10::basic_format_parse_context< Char >::end(), and fmt::v10::detail::find_escape().
operator[]()
template<typename Char > auto fmt::v10::basic_string_view< Char >::operator[] (size_t pos) const -> const Char& inline constexpr noexcept
Definition at line 417 of file core.h.
{ return data_[pos]; }
remove_prefix()
template<typename Char > void fmt::v10::basic_string_view< Char >::remove_prefix (size_t n) inline noexcept
Definition at line 419 of file core.h.
{
            data_ += n;
            size_ -= n;
        }
Referenced by fmt::v10::basic_format_parse_context< Char >::advance_to().
size()
template<typename Char > auto fmt::v10::basic_string_view< Char >::size () const -> size_t inline constexpr noexcept
Returns the string size.
Definition at line 411 of file core.h.
{ return size_; }
Referenced by fmt::v10::detail::value< Context >::value(), fmt::v10::detail::digit_grouping< Char >::apply(), fmt::v10::detail::for_each_codepoint(), fmt::v10::detail::fill_t< Char >::operator=(), fmt::v10::detail::parse_format_string(), and fmt::v10::detail::print().
starts_with() [1/3]
template<typename Char > bool fmt::v10::basic_string_view< Char >::starts_with (basic_string_view< Char > sv) const inline noexcept
Definition at line 424 of file core.h.
{
            return size_ >= sv.size_ && std::char_traits<Char>::compare(data_, sv.data_, sv.size_) == 0;
        }
starts_with() [2/3]
template<typename Char > bool fmt::v10::basic_string_view< Char >::starts_with (Char c) const inline noexcept
Definition at line 428 of file core.h.
{
            return size_ >= 1 && std::char_traits<Char>::eq(*data_, c);
        }
starts_with() [3/3]
template<typename Char > bool fmt::v10::basic_string_view< Char >::starts_with (const Char * s) const inline
Definition at line 432 of file core.h.
{
            return starts_with(basic_string_view<Char>(s));
        }
Friends And Related Symbol Documentation
operator!=
template<typename Char > auto operator!= (basic_string_view< Char > lhs, basic_string_view< Char > rhs) -> bool friend
Definition at line 448 of file core.h.
{ return lhs.compare(rhs) != 0; }
operator<
template<typename Char > auto operator< (basic_string_view< Char > lhs, basic_string_view< Char > rhs) -> bool friend
Definition at line 450 of file core.h.
{ return lhs.compare(rhs) < 0; }
operator<=
template<typename Char > auto operator<= (basic_string_view< Char > lhs, basic_string_view< Char > rhs) -> bool friend
Definition at line 452 of file core.h.
{ return lhs.compare(rhs) <= 0; }
operator==
template<typename Char > auto operator== (basic_string_view< Char > lhs, basic_string_view< Char > rhs) -> bool friend
Definition at line 444 of file core.h.
{
            return lhs.compare(rhs) == 0;
        }
operator>
template<typename Char > auto operator> (basic_string_view< Char > lhs, basic_string_view< Char > rhs) -> bool friend
Definition at line 454 of file core.h.
{ return lhs.compare(rhs) > 0; }
operator>=
template<typename Char > auto operator>= (basic_string_view< Char > lhs, basic_string_view< Char > rhs) -> bool friend
Definition at line 456 of file core.h.
{ return lhs.compare(rhs) >= 0; }
Member Data Documentation
data_
template<typename Char > const Char* fmt::v10::basic_string_view< Char >::data_ private
Definition at line 373 of file core.h.
size_
template<typename Char > size_t fmt::v10::basic_string_view< Char >::size_ private
Definition at line 374 of file core.h.
The documentation for this class was generated from the following file:
include/fmt/core.h