1516b Over Under: opcontrol
opcontrol()
void opcontrol (void)
Runs the operator control code. This function will be started in its own task with the default priority and stack size whenever the robot is enabled via the Field Management System or the VEX Competition Switch in the operator control mode.
If no competition control is connected, this function will run immediately following initialize().
If the robot is disabled or communications is lost, the operator control task will be stopped. Re-enabling the robot will restart the task, not resume it from where it left off.
Definition at line 144 of file main.cpp.
                 {
    while (true) {
        subsystem.drivetrain.run();
      subsystem.puncher.run(0);
      // Catapult controller, uses the X button holded down to push the elevation up.
      subsystem.intake.run();
      // Intake controller, moves the left and right intakes and stops them if nothing is pressed.
      subsystem.wings.run();
        pros::delay(2); // Small delay to reduce CPU usage
    }
}
References Robot::RobotSubsystems::drivetrain, Robot::RobotSubsystems::intake, Robot::RobotSubsystems::puncher, Robot::Drivetrain::run(), Robot::Intake::run(), Robot::Wings::run(), Robot::Puncher::run(), and Robot::RobotSubsystems::wings.