1516b Over Under: src/main.cpp File Reference
main.cpp File Reference
This file contains the main code for the robot's operation.
#include "main.h"
#include <ostream>
#include "api.h"
#include "pros/apix.h"
#include "pros/serial.h"
Classes
struct Robot::RobotSubsystems
Structure that holds instances of all robot subsystems.
Namespaces
namespace Robot
Contains all objects generated by the 1516B team - Contains all of the subsystems, methods, and global objects.
Functions
void toggles ()
void initialize ()
void disabled ()
void competition_initialize ()
void autonomous ()
void opcontrol ()
Variables
struct Robot::RobotSubsystems Robot::subsystem
Detailed Description
This file contains the main code for the robot's operation.
Definition in file main.cpp.
Function Documentation
autonomous()
void autonomous (void)
Runs the user autonomous code. This function will be started in its own task with the default priority and stack size whenever the robot is enabled via the Field Management System or the VEX Competition Switch in the autonomous mode. Alternatively, this function may be called in initialize or opcontrol for non-competition testing purposes.
If the robot is disabled or communications is lost, the autonomous task will be stopped. Re-enabling the robot will restart the task, not re-start it from where it left off.
Definition at line 121 of file main.cpp.
                  {
   subsystem.autonomous.AutoDrive(subsystem.puncher, true);
}
References Robot::Autonomous::AutoDrive(), Robot::RobotSubsystems::autonomous, and Robot::RobotSubsystems::puncher.
competition_initialize()
void competition_initialize (void)
Runs after initialize(), and before autonomous when connected to the Field Management System or the VEX Competition Switch. This is intended for competition-specific initialization routines, such as an autonomous selector on the LCD.
This task will exit when the robot is enabled and autonomous or opcontrol starts.<asd></asd>
Definition at line 95 of file main.cpp.
{
   // Allows the user to select the autonomous routine, drive control type as well as whether the distance puncher is enabled.
   // The user can select the auton routine by pressing the right buttons on the controller.
   // The user can select the drive control type by pressing the down button on the controller.
   // The user can select the distance puncher by pressing the left button on the controller.
   // The state of each subsystem is displayed on the controller screen.
}
disabled()
void disabled (void)
Runs while the robot is in the disabled state of Field Management System or the VEX Competition Switch, following either autonomous or opcontrol. When the robot is enabled, this task will exit.
Definition at line 84 of file main.cpp.
{}
initialize()
void initialize (void)
Runs initialization code. This occurs as soon as the program is started.
All other competition modes are blocked by initialize; it is recommended to keep execution time for this mode under a few seconds.
Definition at line 59 of file main.cpp.
                  {
   pros::lcd::initialize();
   pros::Task toggler(toggles);
   if (pros::c::registry_get_plugged_type(13) == pros::c::E_DEVICE_IMU) {
      chassis.calibrate();
      chassis.setPose(0, 0, 90); // X: 0, Y: 0, Heading: 0
      // Setting an example start location for the robot so it is all relatativistic
      pros::Task screenTask(Robot::Utility::displayLocation);
   }
   else {
      pros::Task screenTask(Robot::Utility::displayMotorVel);
   }
}
References Robot::Globals::chassis, Robot::Utility::displayLocation(), Robot::Utility::displayMotorVel(), and toggles().
opcontrol()
void opcontrol (void)
Runs the operator control code. This function will be started in its own task with the default priority and stack size whenever the robot is enabled via the Field Management System or the VEX Competition Switch in the operator control mode.
If no competition control is connected, this function will run immediately following initialize().
If the robot is disabled or communications is lost, the operator control task will be stopped. Re-enabling the robot will restart the task, not resume it from where it left off.
Definition at line 144 of file main.cpp.
                 {
    while (true) {
        subsystem.drivetrain.run();
      subsystem.puncher.run(0);
      // Catapult controller, uses the X button holded down to push the elevation up.
      subsystem.intake.run();
      // Intake controller, moves the left and right intakes and stops them if nothing is pressed.
      subsystem.wings.run();
        pros::delay(2); // Small delay to reduce CPU usage
    }
}
References Robot::RobotSubsystems::drivetrain, Robot::RobotSubsystems::intake, Robot::RobotSubsystems::puncher, Robot::Drivetrain::run(), Robot::Intake::run(), Robot::Wings::run(), Robot::Puncher::run(), and Robot::RobotSubsystems::wings.
toggles()
void toggles ()
A callback function for LLEMU's center button.
When this callback is fired, it will toggle line 2 of the LCD text between "I was pressed!" and nothing.
Definition at line 48 of file main.cpp.
               {
   Robot::Utility::toggleSubsystemOptions(subsystem.autonomous, subsystem.drivetrain, subsystem.puncher);
}
References Robot::RobotSubsystems::autonomous, Robot::RobotSubsystems::drivetrain, Robot::RobotSubsystems::puncher, and Robot::Utility::toggleSubsystemOptions().
Referenced by initialize().