1516X High Stakes: fmt::v10::detail::digit_grouping< Char > Class Template Reference
fmt::v10::detail::digit_grouping< Char > Class Template Reference
#include <format.h>
Classes
struct next_state
Public Member Functions
digit_grouping (locale_ref loc, bool localized=true)
digit_grouping (std::string grouping, std::basic_string< Char > sep)
bool has_separator () const
int count_separators (int num_digits) const
template<typename Out , typename C >
Out apply (Out out, basic_string_view< C > digits) const
Private Member Functions
next_state initial_state () const
int next (next_state &state) const
Private Attributes
std::string grouping_
std::basic_string< Char > thousands_sep_
Detailed Description
template<typename Char>
class fmt::v10::detail::digit_grouping< Char >
Definition at line 1909 of file format.h.
Constructor & Destructor Documentation
digit_grouping() [1/2]
template<typename Char > fmt::v10::detail::digit_grouping< Char >::digit_grouping (locale_ref loc, bool localized = true) inline explicit
Definition at line 1930 of file format.h.
{
            if (!localized) return;
            auto sep = thousands_sep<Char>(loc);
            grouping_ = sep.grouping;
            if (sep.thousands_sep) thousands_sep_.assign(1, sep.thousands_sep);
        }
digit_grouping() [2/2]
template<typename Char > fmt::v10::detail::digit_grouping< Char >::digit_grouping (std::string grouping, std::basic_string< Char > sep) inline
Definition at line 1937 of file format.h.
            : grouping_(std::move(grouping)), thousands_sep_(std::move(sep)) {}
Member Function Documentation
apply()
template<typename Char > template<typename Out , typename C > Out fmt::v10::detail::digit_grouping< Char >::apply (Out out, basic_string_view< C > digits) const inline
Definition at line 1950 of file format.h.
{
            auto num_digits = static_cast<int>(digits.size());
            auto separators = basic_memory_buffer<int>();
            separators.push_back(0);
            auto state = initial_state();
            while (int i = next(state)) {
                if (i >= num_digits) break;
                separators.push_back(i);
            }
            for (int i = 0, sep_index = static_cast<int>(separators.size() - 1); i < num_digits; ++i) {
                if (num_digits - i == separators[sep_index]) {
                    out = copy_str<Char>(thousands_sep_.data(), thousands_sep_.data() + thousands_sep_.size(), out);
                    --sep_index;
                }
                *out++ = static_cast<Char>(digits[to_unsigned(i)]);
            }
            return out;
        }
References fmt::v10::basic_string_view< Char >::size(), and fmt::v10::detail::to_unsigned().
count_separators()
template<typename Char > int fmt::v10::detail::digit_grouping< Char >::count_separators (int num_digits) const inline
Definition at line 1942 of file format.h.
{
            int count = 0;
            auto state = initial_state();
            while (num_digits > next(state)) ++count;
            return count;
        }
References fmt::v10::detail::count().
has_separator()
template<typename Char > bool fmt::v10::detail::digit_grouping< Char >::has_separator () const inline
Definition at line 1940 of file format.h.
{ return !thousands_sep_.empty(); }
initial_state()
template<typename Char > next_state fmt::v10::detail::digit_grouping< Char >::initial_state () const inline private
Definition at line 1919 of file format.h.
{ return {grouping_.begin(), 0}; }
next()
template<typename Char > int fmt::v10::detail::digit_grouping< Char >::next (next_state & state) const inline private
Definition at line 1922 of file format.h.
{
            if (thousands_sep_.empty()) return max_value<int>();
            if (state.group == grouping_.end()) return state.pos += grouping_.back();
            if (*state.group <= 0 || *state.group == max_value<char>()) return max_value<int>();
            state.pos += *state.group++;
            return state.pos;
        }
Member Data Documentation
grouping_
template<typename Char > std::string fmt::v10::detail::digit_grouping< Char >::grouping_ private
Definition at line 1911 of file format.h.
thousands_sep_
template<typename Char > std::basic_string<Char> fmt::v10::detail::digit_grouping< Char >::thousands_sep_ private
Definition at line 1912 of file format.h.
The documentation for this class was generated from the following file:
include/fmt/format.h