1516X High Stakes: Robot::Latch Class Reference
Robot::Latch Class Reference
The Latch class represents a latching mechanism.
#include <latch.h>
Public Member Functions
void run ()
Runs latching mechanism.
Latch ()
void toggle ()
Toggles latch state.
Detailed Description
The Latch class represents a latching mechanism.
Definition at line 8 of file latch.h.
Constructor & Destructor Documentation
Latch()
Latch::Latch ()
Definition at line 15 of file latch.cpp.
             {
    ;
}
Member Function Documentation
run()
void Latch::run ()
Runs latching mechanism.
Definition at line 8 of file latch.cpp.
                {
    if (controller.get_digital_new_press(pros::E_CONTROLLER_DIGITAL_B)) {
        Latch::toggle();
    }
}
References Robot::Globals::controller, and toggle().
Referenced by opcontrol().
toggle()
void Latch::toggle ()
Toggles latch state.
Definition at line 19 of file latch.cpp.
                   {
    LatchControl.toggle();
}
References Robot::Globals::LatchControl.
Referenced by Robot::Autonomous::Auton1(), Robot::Autonomous::Auton2(), and run().
The documentation for this class was generated from the following files:
include/robot/latch.h
src/subsystems/latch.cpp