1516X High Stakes: include/liblvgl/core/lv_event.h File Reference
lv_event.h File Reference
#include <stdbool.h>
Classes
struct _lv_event_t
struct lv_hit_test_info_t
struct lv_cover_check_info_t
Typedefs
typedef struct _lv_event_t lv_event_t
typedef void(* lv_event_cb_t) (lv_event_t *e)
Event callback. Events are used to notify the user of some action being taken on the object. For details, see lv_event_t.
Enumerations
enum lv_event_code_t {
LV_EVENT_ALL = 0 , LV_EVENT_PRESSED , LV_EVENT_PRESSING , LV_EVENT_PRESS_LOST ,
LV_EVENT_SHORT_CLICKED , LV_EVENT_LONG_PRESSED , LV_EVENT_LONG_PRESSED_REPEAT , LV_EVENT_CLICKED ,
LV_EVENT_RELEASED , LV_EVENT_SCROLL_BEGIN , LV_EVENT_SCROLL_END , LV_EVENT_SCROLL ,
LV_EVENT_GESTURE , LV_EVENT_KEY , LV_EVENT_FOCUSED , LV_EVENT_DEFOCUSED ,
LV_EVENT_LEAVE , LV_EVENT_HIT_TEST , LV_EVENT_COVER_CHECK , LV_EVENT_REFR_EXT_DRAW_SIZE ,
LV_EVENT_DRAW_MAIN_BEGIN , LV_EVENT_DRAW_MAIN , LV_EVENT_DRAW_MAIN_END , LV_EVENT_DRAW_POST_BEGIN ,
LV_EVENT_DRAW_POST , LV_EVENT_DRAW_POST_END , LV_EVENT_DRAW_PART_BEGIN , LV_EVENT_DRAW_PART_END ,
LV_EVENT_VALUE_CHANGED , LV_EVENT_INSERT , LV_EVENT_REFRESH , LV_EVENT_READY ,
LV_EVENT_CANCEL , LV_EVENT_DELETE , LV_EVENT_CHILD_CHANGED , LV_EVENT_CHILD_CREATED ,
LV_EVENT_CHILD_DELETED , LV_EVENT_SCREEN_UNLOAD_START , LV_EVENT_SCREEN_LOAD_START , LV_EVENT_SCREEN_LOADED ,
LV_EVENT_SCREEN_UNLOADED , LV_EVENT_SIZE_CHANGED , LV_EVENT_STYLE_CHANGED , LV_EVENT_LAYOUT_CHANGED ,
LV_EVENT_GET_SELF_SIZE , _LV_EVENT_LAST , LV_EVENT_PREPROCESS = 0x80
}
Functions
lv_res_t lv_event_send (struct _lv_obj_t *obj, lv_event_code_t event_code, void *param)
lv_res_t lv_obj_event_base (const lv_obj_class_t *class_p, lv_event_t *e)
struct _lv_obj_t * lv_event_get_target (lv_event_t *e)
struct _lv_obj_t * lv_event_get_current_target (lv_event_t *e)
lv_event_code_t lv_event_get_code (lv_event_t *e)
void * lv_event_get_param (lv_event_t *e)
void * lv_event_get_user_data (lv_event_t *e)
void lv_event_stop_bubbling (lv_event_t *e)
void lv_event_stop_processing (lv_event_t *e)
uint32_t lv_event_register_id (void)
void _lv_event_mark_deleted (struct _lv_obj_t *obj)
struct _lv_event_dsc_t * lv_obj_add_event_cb (struct _lv_obj_t *obj, lv_event_cb_t event_cb, lv_event_code_t filter, void *user_data)
bool lv_obj_remove_event_cb (struct _lv_obj_t *obj, lv_event_cb_t event_cb)
bool lv_obj_remove_event_cb_with_user_data (struct _lv_obj_t *obj, lv_event_cb_t event_cb, const void *event_user_data)
bool lv_obj_remove_event_dsc (struct _lv_obj_t *obj, struct _lv_event_dsc_t *event_dsc)
void * lv_obj_get_event_user_data (struct _lv_obj_t *obj, lv_event_cb_t event_cb)
lv_indev_t * lv_event_get_indev (lv_event_t *e)
lv_obj_draw_part_dsc_t * lv_event_get_draw_part_dsc (lv_event_t *e)
lv_draw_ctx_t * lv_event_get_draw_ctx (lv_event_t *e)
const lv_area_t * lv_event_get_old_size (lv_event_t *e)
uint32_t lv_event_get_key (lv_event_t *e)
lv_anim_t * lv_event_get_scroll_anim (lv_event_t *e)
void lv_event_set_ext_draw_size (lv_event_t *e, lv_coord_t size)
lv_point_t * lv_event_get_self_size_info (lv_event_t *e)
lv_hit_test_info_t * lv_event_get_hit_test_info (lv_event_t *e)
const lv_area_t * lv_event_get_cover_area (lv_event_t *e)
void lv_event_set_cover_res (lv_event_t *e, lv_cover_res_t res)
Typedef Documentation
lv_event_cb_t
typedef void(* lv_event_cb_t) (lv_event_t *e)
Event callback. Events are used to notify the user of some action being taken on the object. For details, see lv_event_t.
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/core/lv_event.h.
Definition at line 111 of file lv_event.h.
lv_event_t
typedef struct _lv_event_t lv_event_t
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/core/lv_event.h.
Enumeration Type Documentation
lv_event_code_t
enum lv_event_code_t
Type of event being sent to the object.
Enumerator
LV_EVENT_ALL
LV_EVENT_PRESSED
Input device events The object has been pressed
LV_EVENT_PRESSING
The object is being pressed (called continuously while pressing)
LV_EVENT_PRESS_LOST
The object is still being pressed but slid cursor/finger off of the object
LV_EVENT_SHORT_CLICKED
The object was pressed for a short period of time, then released it. Not called if scrolled.
LV_EVENT_LONG_PRESSED
Object has been pressed for at least long_press_time. Not called if scrolled.
LV_EVENT_LONG_PRESSED_REPEAT
Called after long_press_time in every long_press_repeat_time ms. Not called if scrolled.
LV_EVENT_CLICKED
Called on release if not scrolled (regardless to long press)
LV_EVENT_RELEASED
Called in every cases when the object has been released
LV_EVENT_SCROLL_BEGIN
Scrolling begins. The event parameter is a pointer to the animation of the scroll. Can be modified
LV_EVENT_SCROLL_END
Scrolling ends
LV_EVENT_SCROLL
Scrolling
LV_EVENT_GESTURE
A gesture is detected. Get the gesture with lv_indev_get_gesture_dir(lv_indev_get_act());
LV_EVENT_KEY
A key is sent to the object. Get the key with lv_indev_get_key(lv_indev_get_act());
LV_EVENT_FOCUSED
The object is focused
LV_EVENT_DEFOCUSED
The object is defocused
LV_EVENT_LEAVE
The object is defocused but still selected
LV_EVENT_HIT_TEST
Perform advanced hit-testing
LV_EVENT_COVER_CHECK
Drawing events Check if the object fully covers an area. The event parameter is lv_cover_check_info_t *.
LV_EVENT_REFR_EXT_DRAW_SIZE
Get the required extra draw area around the object (e.g. for shadow). The event parameter is lv_coord_t * to store the size.
LV_EVENT_DRAW_MAIN_BEGIN
Starting the main drawing phase
LV_EVENT_DRAW_MAIN
Perform the main drawing
LV_EVENT_DRAW_MAIN_END
Finishing the main drawing phase
LV_EVENT_DRAW_POST_BEGIN
Starting the post draw phase (when all children are drawn)
LV_EVENT_DRAW_POST
Perform the post draw phase (when all children are drawn)
LV_EVENT_DRAW_POST_END
Finishing the post draw phase (when all children are drawn)
LV_EVENT_DRAW_PART_BEGIN
Starting to draw a part. The event parameter is lv_obj_draw_dsc_t *.
LV_EVENT_DRAW_PART_END
Finishing to draw a part. The event parameter is lv_obj_draw_dsc_t *.
LV_EVENT_VALUE_CHANGED
Special events The object's value has changed (i.e. slider moved)
LV_EVENT_INSERT
A text is inserted to the object. The event data is char * being inserted.
LV_EVENT_REFRESH
Notify the object to refresh something on it (for the user)
LV_EVENT_READY
A process has finished
LV_EVENT_CANCEL
A process has been cancelled
LV_EVENT_DELETE
Other events Object is being deleted
LV_EVENT_CHILD_CHANGED
Child was removed, added, or its size, position were changed
LV_EVENT_CHILD_CREATED
Child was created, always bubbles up to all parents
LV_EVENT_CHILD_DELETED
Child was deleted, always bubbles up to all parents
LV_EVENT_SCREEN_UNLOAD_START
A screen unload started, fired immediately when scr_load is called
LV_EVENT_SCREEN_LOAD_START
A screen load started, fired when the screen change delay is expired
LV_EVENT_SCREEN_LOADED
A screen was loaded
LV_EVENT_SCREEN_UNLOADED
A screen was unloaded
LV_EVENT_SIZE_CHANGED
Object coordinates/size have changed
LV_EVENT_STYLE_CHANGED
Object's style has changed
LV_EVENT_LAYOUT_CHANGED
The children position has changed due to a layout recalculation
LV_EVENT_GET_SELF_SIZE
Get the internal size of a widget
_LV_EVENT_LAST
LV_EVENT_PREPROCESS
Number of default events
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/core/lv_event.h.
Definition at line 32 of file lv_event.h.
             {
    LV_EVENT_ALL = 0,
    LV_EVENT_PRESSED,
    LV_EVENT_PRESSING,
    LV_EVENT_PRESS_LOST,
    LV_EVENT_SHORT_CLICKED,
    LV_EVENT_LONG_PRESSED,
    LV_EVENT_LONG_PRESSED_REPEAT,
    LV_EVENT_CLICKED,
    LV_EVENT_RELEASED,
    LV_EVENT_SCROLL_BEGIN,
    LV_EVENT_SCROLL_END,
    LV_EVENT_SCROLL,
    LV_EVENT_GESTURE,
    LV_EVENT_KEY,
    LV_EVENT_FOCUSED,
    LV_EVENT_DEFOCUSED,
    LV_EVENT_LEAVE,
    LV_EVENT_HIT_TEST,
    LV_EVENT_COVER_CHECK,
    LV_EVENT_REFR_EXT_DRAW_SIZE,
    LV_EVENT_DRAW_MAIN_BEGIN,
    LV_EVENT_DRAW_MAIN,
    LV_EVENT_DRAW_MAIN_END,
    LV_EVENT_DRAW_POST_BEGIN,
    LV_EVENT_DRAW_POST,
    LV_EVENT_DRAW_POST_END,
    LV_EVENT_DRAW_PART_BEGIN,
    LV_EVENT_DRAW_PART_END,
    LV_EVENT_VALUE_CHANGED,
    LV_EVENT_INSERT,
    LV_EVENT_REFRESH,
    LV_EVENT_READY,
    LV_EVENT_CANCEL,
    LV_EVENT_DELETE,
    LV_EVENT_CHILD_CHANGED,
    LV_EVENT_CHILD_CREATED,
    LV_EVENT_CHILD_DELETED,
    LV_EVENT_SCREEN_UNLOAD_START,
    LV_EVENT_SCREEN_LOAD_START,
    LV_EVENT_SCREEN_LOADED,
    LV_EVENT_SCREEN_UNLOADED,
    LV_EVENT_SIZE_CHANGED,
    LV_EVENT_STYLE_CHANGED,
    LV_EVENT_LAYOUT_CHANGED,
    LV_EVENT_GET_SELF_SIZE,
    _LV_EVENT_LAST,
    LV_EVENT_PREPROCESS = 0x80,
} lv_event_code_t;
Function Documentation
_lv_event_mark_deleted()
void _lv_event_mark_deleted (struct _lv_obj_t * obj)
Nested events can be called and one of them might belong to an object that is being deleted. Mark this object's event_temp_data deleted to know that its lv_event_send should return LV_RES_INV
Parameters
obj pointer to an object to mark as deleted
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/core/lv_event.h.
lv_event_get_code()
lv_event_code_t lv_event_get_code (lv_event_t * e)
Get the event code of an event
Parameters
e pointer to the event descriptor
Returns
the event code. (E.g. LV_EVENT_CLICKED, LV_EVENT_FOCUSED, etc)
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/core/lv_event.h.
Referenced by Robot::selector_screen::auton_update(), Robot::selector_screen::drive_update(), and slider_event_cb().
lv_event_get_cover_area()
const lv_area_t * lv_event_get_cover_area (lv_event_t * e)
Get a pointer to an area which should be examined whether the object fully covers it or not. Can be used in LV_EVENT_HIT_TEST
Parameters
e pointer to an event
Returns
an area with absolute coordinates to check
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/core/lv_event.h.
lv_event_get_current_target()
struct _lv_obj_t * lv_event_get_current_target (lv_event_t * e)
Get the current target of the event. It's the object which event handler being called. If the event is not bubbled it's the same as "normal" target.
Parameters
e pointer to the event descriptor
Returns
pointer to the current target of the event_code
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/core/lv_event.h.
Referenced by slider_event_cb().
lv_event_get_draw_ctx()
lv_draw_ctx_t * lv_event_get_draw_ctx (lv_event_t * e)
Get the draw context which should be the first parameter of the draw functions. Namely: LV_EVENT_DRAW_MAIN/POST, LV_EVENT_DRAW_MAIN/POST_BEGIN, LV_EVENT_DRAW_MAIN/POST_END
Parameters
e pointer to an event
Returns
pointer to a draw context or NULL if called on an unrelated event
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/core/lv_event.h.
lv_event_get_draw_part_dsc()
lv_obj_draw_part_dsc_t * lv_event_get_draw_part_dsc (lv_event_t * e)
Get the part draw descriptor passed as parameter to LV_EVENT_DRAW_PART_BEGIN/END.
Parameters
e pointer to an event
Returns
the part draw descriptor to hook the drawing or NULL if called on an unrelated event
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/core/lv_event.h.
lv_event_get_hit_test_info()
lv_hit_test_info_t * lv_event_get_hit_test_info (lv_event_t * e)
Get a pointer to an lv_hit_test_info_t variable in which the hit test result should be saved. Can be used in LV_EVENT_HIT_TEST
Parameters
e pointer to an event
Returns
pointer to lv_hit_test_info_t or NULL if called on an unrelated event
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/core/lv_event.h.
lv_event_get_indev()
lv_indev_t * lv_event_get_indev (lv_event_t * e)
Get the input device passed as parameter to indev related events.
Parameters
e pointer to an event
Returns
the indev that triggered the event or NULL if called on a not indev related event
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/core/lv_event.h.
lv_event_get_key()
uint32_t lv_event_get_key (lv_event_t * e)
Get the key passed as parameter to an event. Can be used in LV_EVENT_KEY
Parameters
e pointer to an event
Returns
the triggering key or NULL if called on an unrelated event
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/core/lv_event.h.
lv_event_get_old_size()
const lv_area_t * lv_event_get_old_size (lv_event_t * e)
Get the old area of the object before its size was changed. Can be used in LV_EVENT_SIZE_CHANGED
Parameters
e pointer to an event
Returns
the old absolute area of the object or NULL if called on an unrelated event
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/core/lv_event.h.
lv_event_get_param()
void * lv_event_get_param (lv_event_t * e)
Get the parameter passed when the event was sent
Parameters
e pointer to the event descriptor
Returns
pointer to the parameter
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/core/lv_event.h.
lv_event_get_scroll_anim()
lv_anim_t * lv_event_get_scroll_anim (lv_event_t * e)
Get the animation descriptor of a scrolling. Can be used in LV_EVENT_SCROLL_BEGIN
Parameters
e pointer to an event
Returns
the animation that will scroll the object. (can be modified as required)
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/core/lv_event.h.
lv_event_get_self_size_info()
lv_point_t * lv_event_get_self_size_info (lv_event_t * e)
Get a pointer to an lv_point_t variable in which the self size should be saved (width in point->x and height point->y). Can be used in LV_EVENT_GET_SELF_SIZE
Parameters
e pointer to an event
Returns
pointer to lv_point_t or NULL if called on an unrelated event
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/core/lv_event.h.
lv_event_get_target()
struct _lv_obj_t * lv_event_get_target (lv_event_t * e)
Get the object originally targeted by the event. It's the same even if the event is bubbled.
Parameters
e pointer to the event descriptor
Returns
the target of the event_code
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/core/lv_event.h.
Referenced by Robot::selector_screen::auton_update(), and Robot::selector_screen::drive_update().
lv_event_get_user_data()
void * lv_event_get_user_data (lv_event_t * e)
Get the user_data passed when the event was registered on the object
Parameters
e pointer to the event descriptor
Returns
pointer to the user_data
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/core/lv_event.h.
lv_event_register_id()
uint32_t lv_event_register_id (void)
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/core/lv_event.h.
lv_event_send()
lv_res_t lv_event_send (struct _lv_obj_t * obj, lv_event_code_t event_code, void * param)
Send an event to the object
Parameters
obj pointer to an object
event_code the type of the event from lv_event_t
param arbitrary data depending on the widget type and the event. (Usually NULL)
Returns
LV_RES_OK: obj was not deleted in the event; LV_RES_INV: obj was deleted in the event_code
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/core/lv_event.h.
lv_event_set_cover_res()
void lv_event_set_cover_res (lv_event_t * e, lv_cover_res_t res)
Set the result of cover checking. Can be used in LV_EVENT_COVER_CHECK
Parameters
e pointer to an event
res an element of lv_cover_check_info_t
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/core/lv_event.h.
lv_event_set_ext_draw_size()
void lv_event_set_ext_draw_size (lv_event_t * e, lv_coord_t size)
Set the new extra draw size. Can be used in LV_EVENT_REFR_EXT_DRAW_SIZE
Parameters
e pointer to an event
size The new extra draw size
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/core/lv_event.h.
lv_event_stop_bubbling()
void lv_event_stop_bubbling (lv_event_t * e)
Stop the event from bubbling. This is only valid when called in the middle of an event processing chain.
Parameters
e pointer to the event descriptor
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/core/lv_event.h.
lv_event_stop_processing()
void lv_event_stop_processing (lv_event_t * e)
Stop processing this event. This is only valid when called in the middle of an event processing chain.
Parameters
e pointer to the event descriptor
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/core/lv_event.h.
lv_obj_add_event_cb()
struct _lv_event_dsc_t * lv_obj_add_event_cb (struct _lv_obj_t * obj, lv_event_cb_t event_cb, lv_event_code_t filter, void * user_data)
Add an event handler function for an object. Used by the user to react on event which happens with the object. An object can have multiple event handler. They will be called in the same order as they were added.
Parameters
obj pointer to an object
filter and event code (e.g. LV_EVENT_CLICKED) on which the event should be called. LV_EVENT_ALL can be sued the receive all the events.
event_cb the new event function
user_data custom data data will be available in event_cb
Returns
a pointer the event descriptor. Can be used in lv_obj_remove_event_dsc
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/core/lv_event.h.
Referenced by Robot::selector_screen::selector(), and Robot::status_screen::status().
lv_obj_event_base()
lv_res_t lv_obj_event_base (const lv_obj_class_t * class_p, lv_event_t * e)
Used by the widgets internally to call the ancestor widget types's event handler
Parameters
class_p pointer to the class of the widget (NOT the ancestor class)
e pointer to the event descriptor
Returns
LV_RES_OK: the target object was not deleted in the event; LV_RES_INV: it was deleted in the event_code
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/core/lv_event.h.
lv_obj_get_event_user_data()
void * lv_obj_get_event_user_data (struct _lv_obj_t * obj, lv_event_cb_t event_cb)
The user data of an event object event callback. Always the first match with event_cb will be returned.
Parameters
obj pointer to an object
event_cb the event function
Returns
the user_data
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/core/lv_event.h.
lv_obj_remove_event_cb()
bool lv_obj_remove_event_cb (struct _lv_obj_t * obj, lv_event_cb_t event_cb)
Remove an event handler function for an object.
Parameters
obj pointer to an object
event_cb the event function to remove, or NULL to remove the firstly added event callback
Returns
true if any event handlers were removed
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/core/lv_event.h.
lv_obj_remove_event_cb_with_user_data()
bool lv_obj_remove_event_cb_with_user_data (struct _lv_obj_t * obj, lv_event_cb_t event_cb, const void * event_user_data)
Remove an event handler function with a specific user_data from an object.
Parameters
obj pointer to an object
event_cb the event function to remove, or NULL only user_data matters.
event_user_data the user_data specified in lv_obj_add_event_cb
Returns
true if any event handlers were removed
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/core/lv_event.h.
lv_obj_remove_event_dsc()
bool lv_obj_remove_event_dsc (struct _lv_obj_t * obj, struct _lv_event_dsc_t * event_dsc)
DEPRECATED because doesn't work if multiple event handlers are added to an object. Remove an event handler function for an object.
Parameters
obj pointer to an object
event_dsc pointer to an event descriptor to remove (returned by lv_obj_add_event_cb)
Returns
true if any event handlers were removed
Examples
/home/aswath/Downloads/high_stakes_x/include/liblvgl/core/lv_event.h.