1516X High Stakes: fmt::v10::detail::compile_parse_context< Char > Class Template Reference
fmt::v10::detail::compile_parse_context< Char > Class Template Reference
#include <core.h>
Public Member Functions
compile_parse_context (basic_string_view< Char > format_str, int num_args, const type *types, int next_arg_id=0)
constexpr auto num_args () const -> int
constexpr auto arg_type (int id) const -> type
auto next_arg_id () -> int
void check_arg_id (int id)
void check_dynamic_spec (int arg_id)
void check_arg_id (int id)
void check_arg_id (basic_string_view< Char >)
Public Member Functions inherited from fmt::v10::basic_format_parse_context< Char >
constexpr basic_format_parse_context (basic_string_view< Char > format_str, int next_arg_id=0)
constexpr auto begin () const noexcept -> iterator
constexpr auto end () const noexcept -> iterator
void advance_to (iterator it)
auto next_arg_id () -> int
void check_arg_id (int id)
void check_arg_id (basic_string_view< Char >)
void check_dynamic_spec (int arg_id)
Private Types
using base = basic_format_parse_context< Char >
Private Attributes
int num_args_
const type * types_
Additional Inherited Members
Public Types inherited from fmt::v10::basic_format_parse_context< Char >
using char_type = Char
using iterator = const Char *
Detailed Description
template<typename Char>
class fmt::v10::detail::compile_parse_context< Char >
Definition at line 668 of file core.h.
Member Typedef Documentation
base
template<typename Char > using fmt::v10::detail::compile_parse_context< Char >::base = basic_format_parse_context<Char> private
Definition at line 672 of file core.h.
Constructor & Destructor Documentation
compile_parse_context()
template<typename Char > fmt::v10::detail::compile_parse_context< Char >::compile_parse_context (basic_string_view< Char > format_str, int num_args, const type * types, int next_arg_id = 0) inline explicit
Definition at line 674 of file core.h.
            : base(format_str, next_arg_id), num_args_(num_args), types_(types) {}
Member Function Documentation
arg_type()
template<typename Char > constexpr auto fmt::v10::detail::compile_parse_context< Char >::arg_type (int id) const -> type inline constexpr
Definition at line 680 of file core.h.
{ return types_[id]; }
check_arg_id() [1/3]
template<typename Char > void fmt::v10::basic_format_parse_context< Char >::check_arg_id (basic_string_view< Char >) inline
Definition at line 658 of file core.h.
{}
check_arg_id() [2/3]
template<typename Char > void fmt::v10::detail::compile_parse_context< Char >::check_arg_id (int id) inline
Definition at line 688 of file core.h.
{
            base::check_arg_id(id);
            if (id >= num_args_) throw_format_error("argument not found");
        }
References fmt::v10::detail::throw_format_error().
Referenced by fmt::v10::detail::format_string_checker< Char, Args >::on_arg_id().
check_arg_id() [3/3]
template<typename Char > void fmt::v10::basic_format_parse_context< Char >::check_arg_id (int id) inline
Reports an error if using the automatic argument indexing; otherwise switches to the manual indexing.
Definition at line 649 of file core.h.
{
            if (next_arg_id_ > 0) {
                detail::throw_format_error("cannot switch from automatic to manual argument indexing");
                return;
            }
            next_arg_id_ = -1;
            do_check_arg_id(id);
        }
check_dynamic_spec()
template<typename Char > void fmt::v10::detail::compile_parse_context< Char >::check_dynamic_spec (int arg_id) inline
Definition at line 695 of file core.h.
{
            detail::ignore_unused(arg_id);
#if !defined(__LCC__)
            if (arg_id < num_args_ && types_ && !is_integral_type(types_[arg_id]))
                throw_format_error("width/precision is not integer");
#endif
        }
References fmt::v10::detail::is_integral_type(), and fmt::v10::detail::throw_format_error().
next_arg_id()
template<typename Char > auto fmt::v10::detail::compile_parse_context< Char >::next_arg_id () -> int inline
Definition at line 682 of file core.h.
{
            int id = base::next_arg_id();
            if (id >= num_args_) throw_format_error("argument not found");
            return id;
        }
References fmt::v10::detail::throw_format_error().
Referenced by fmt::v10::detail::format_string_checker< Char, Args >::on_arg_id().
num_args()
template<typename Char > constexpr auto fmt::v10::detail::compile_parse_context< Char >::num_args () const -> int inline constexpr
Definition at line 678 of file core.h.
{ return num_args_; }
Member Data Documentation
num_args_
template<typename Char > int fmt::v10::detail::compile_parse_context< Char >::num_args_ private
Definition at line 670 of file core.h.
types_
template<typename Char > const type* fmt::v10::detail::compile_parse_context< Char >::types_ private
Definition at line 671 of file core.h.
The documentation for this class was generated from the following file:
include/fmt/core.h