1516X High Stakes: include/liblvgl/core/lv_disp.h File Reference
lv_disp.h File Reference
#include "liblvgl/hal/lv_hal.h"
#include "lv_obj.h"
#include "lv_theme.h"
Macros
#define LV_HOR_RES lv_disp_get_hor_res(lv_disp_get_default())
#define LV_VER_RES lv_disp_get_ver_res(lv_disp_get_default())
Enumerations
enum lv_scr_load_anim_t {
LV_SCR_LOAD_ANIM_NONE , LV_SCR_LOAD_ANIM_OVER_LEFT , LV_SCR_LOAD_ANIM_OVER_RIGHT , LV_SCR_LOAD_ANIM_OVER_TOP ,
LV_SCR_LOAD_ANIM_OVER_BOTTOM , LV_SCR_LOAD_ANIM_MOVE_LEFT , LV_SCR_LOAD_ANIM_MOVE_RIGHT , LV_SCR_LOAD_ANIM_MOVE_TOP ,
LV_SCR_LOAD_ANIM_MOVE_BOTTOM , LV_SCR_LOAD_ANIM_FADE_IN , LV_SCR_LOAD_ANIM_FADE_ON = LV_SCR_LOAD_ANIM_FADE_IN , LV_SCR_LOAD_ANIM_FADE_OUT ,
LV_SCR_LOAD_ANIM_OUT_LEFT , LV_SCR_LOAD_ANIM_OUT_RIGHT , LV_SCR_LOAD_ANIM_OUT_TOP , LV_SCR_LOAD_ANIM_OUT_BOTTOM
}
Functions
lv_obj_t * lv_disp_get_scr_act (lv_disp_t *disp)
lv_obj_t * lv_disp_get_scr_prev (lv_disp_t *disp)
void lv_disp_load_scr (lv_obj_t *scr)
lv_obj_t * lv_disp_get_layer_top (lv_disp_t *disp)
lv_obj_t * lv_disp_get_layer_sys (lv_disp_t *disp)
void lv_disp_set_theme (lv_disp_t *disp, lv_theme_t *th)
lv_theme_t * lv_disp_get_theme (lv_disp_t *disp)
void lv_disp_set_bg_color (lv_disp_t *disp, lv_color_t color)
void lv_disp_set_bg_image (lv_disp_t *disp, const void *img_src)
void lv_disp_set_bg_opa (lv_disp_t *disp, lv_opa_t opa)
void lv_scr_load_anim (lv_obj_t *scr, lv_scr_load_anim_t anim_type, uint32_t time, uint32_t delay, bool auto_del)
uint32_t lv_disp_get_inactive_time (const lv_disp_t *disp)
void lv_disp_trig_activity (lv_disp_t *disp)
void lv_disp_clean_dcache (lv_disp_t *disp)
void lv_disp_enable_invalidation (lv_disp_t *disp, bool en)
bool lv_disp_is_invalidation_enabled (lv_disp_t *disp)
lv_timer_t * _lv_disp_get_refr_timer (lv_disp_t *disp)
static lv_obj_t * lv_scr_act (void)
static lv_obj_t * lv_layer_top (void)
static lv_obj_t * lv_layer_sys (void)
static void lv_scr_load (lv_obj_t *scr)
static lv_coord_t lv_dpx (lv_coord_t n)
static lv_coord_t lv_disp_dpx (const lv_disp_t *disp, lv_coord_t n)
Macro Definition Documentation
LV_HOR_RES
#define LV_HOR_RES lv_disp_get_hor_res(lv_disp_get_default())
The horizontal resolution of the currently active display.
Definition at line 223 of file lv_disp.h.
LV_VER_RES
#define LV_VER_RES lv_disp_get_ver_res(lv_disp_get_default())
The vertical resolution of the currently active display.
Definition at line 230 of file lv_disp.h.
Enumeration Type Documentation
lv_scr_load_anim_t
enum lv_scr_load_anim_t
Enumerator
LV_SCR_LOAD_ANIM_NONE
LV_SCR_LOAD_ANIM_OVER_LEFT
LV_SCR_LOAD_ANIM_OVER_RIGHT
LV_SCR_LOAD_ANIM_OVER_TOP
LV_SCR_LOAD_ANIM_OVER_BOTTOM
LV_SCR_LOAD_ANIM_MOVE_LEFT
LV_SCR_LOAD_ANIM_MOVE_RIGHT
LV_SCR_LOAD_ANIM_MOVE_TOP
LV_SCR_LOAD_ANIM_MOVE_BOTTOM
LV_SCR_LOAD_ANIM_FADE_IN
LV_SCR_LOAD_ANIM_FADE_ON
LV_SCR_LOAD_ANIM_FADE_OUT
LV_SCR_LOAD_ANIM_OUT_LEFT
LV_SCR_LOAD_ANIM_OUT_RIGHT
LV_SCR_LOAD_ANIM_OUT_TOP
LV_SCR_LOAD_ANIM_OUT_BOTTOM
Definition at line 28 of file lv_disp.h.
             {
    LV_SCR_LOAD_ANIM_NONE,
    LV_SCR_LOAD_ANIM_OVER_LEFT,
    LV_SCR_LOAD_ANIM_OVER_RIGHT,
    LV_SCR_LOAD_ANIM_OVER_TOP,
    LV_SCR_LOAD_ANIM_OVER_BOTTOM,
    LV_SCR_LOAD_ANIM_MOVE_LEFT,
    LV_SCR_LOAD_ANIM_MOVE_RIGHT,
    LV_SCR_LOAD_ANIM_MOVE_TOP,
    LV_SCR_LOAD_ANIM_MOVE_BOTTOM,
    LV_SCR_LOAD_ANIM_FADE_IN,
    LV_SCR_LOAD_ANIM_FADE_ON = LV_SCR_LOAD_ANIM_FADE_IN, /*For backward compatibility*/
    LV_SCR_LOAD_ANIM_FADE_OUT,
    LV_SCR_LOAD_ANIM_OUT_LEFT,
    LV_SCR_LOAD_ANIM_OUT_RIGHT,
    LV_SCR_LOAD_ANIM_OUT_TOP,
    LV_SCR_LOAD_ANIM_OUT_BOTTOM,
} lv_scr_load_anim_t;
Function Documentation
_lv_disp_get_refr_timer()
lv_timer_t * _lv_disp_get_refr_timer (lv_disp_t * disp)
Get a pointer to the screen refresher timer to modify its parameters with lv_timer_... functions.
Parameters
disp pointer to a display
Returns
pointer to the display refresher timer. (NULL on error)
lv_disp_clean_dcache()
void lv_disp_clean_dcache (lv_disp_t * disp)
Clean any CPU cache that is related to the display.
Parameters
disp pointer to a display (NULL to use the default display)
lv_disp_dpx()
static lv_coord_t lv_disp_dpx (const lv_disp_t * disp, lv_coord_t n) inline static
Scale the given number of pixels (a distance or size) relative to a 160 DPI display considering the DPI of the given display. It ensures that e.g. lv_dpx(100) will have the same physical size regardless to the DPI of the display.
Parameters
obj a display whose dpi should be considered
n the number of pixels to scale
Returns
n x current_dpi/160
Definition at line 255 of file lv_disp.h.
{
    return _LV_DPX_CALC(lv_disp_get_dpi(disp), n);
}
References _LV_DPX_CALC, and lv_disp_get_dpi().
lv_disp_enable_invalidation()
void lv_disp_enable_invalidation (lv_disp_t * disp, bool en)
Temporarily enable and disable the invalidation of the display.
Parameters
disp pointer to a display (NULL to use the default display)
en true: enable invalidation; false: invalidation
lv_disp_get_inactive_time()
uint32_t lv_disp_get_inactive_time (const lv_disp_t * disp)
Get elapsed time since last user activity on a display (e.g. click)
Parameters
disp pointer to a display (NULL to get the overall smallest inactivity)
Returns
elapsed ticks (milliseconds) since the last activity
lv_disp_get_layer_sys()
lv_obj_t * lv_disp_get_layer_sys (lv_disp_t * disp)
Return with the sys. layer. (Same on every screen and it is above the normal screen and the top layer)
Parameters
disp pointer to display which sys. layer should be retrieved. (NULL to use the default screen)
Returns
pointer to the sys layer object (transparent screen sized lv_obj)
Referenced by lv_layer_sys().
lv_disp_get_layer_top()
lv_obj_t * lv_disp_get_layer_top (lv_disp_t * disp)
Return with the top layer. (Same on every screen and it is above the normal screen layer)
Parameters
disp pointer to display which top layer should be get. (NULL to use the default screen)
Returns
pointer to the top layer object (transparent screen sized lv_obj)
Referenced by lv_layer_top().
lv_disp_get_scr_act()
lv_obj_t * lv_disp_get_scr_act (lv_disp_t * disp)
Return with a pointer to the active screen
Parameters
disp pointer to display which active screen should be get. (NULL to use the default screen)
Returns
pointer to the active screen object (loaded by 'lv_scr_load()')
Referenced by lv_scr_act().
lv_disp_get_scr_prev()
lv_obj_t * lv_disp_get_scr_prev (lv_disp_t * disp)
Return with a pointer to the previous screen. Only used during screen transitions.
Parameters
disp pointer to display which previous screen should be get. (NULL to use the default screen)
Returns
pointer to the previous screen object or NULL if not used now
lv_disp_get_theme()
lv_theme_t * lv_disp_get_theme (lv_disp_t * disp)
Get the theme of a display
Parameters
disp pointer to a display
Returns
the display's theme (can be NULL)
lv_disp_is_invalidation_enabled()
bool lv_disp_is_invalidation_enabled (lv_disp_t * disp)
Get display invalidation is enabled.
Parameters
disp pointer to a display (NULL to use the default display)
Returns
return true if invalidation is enabled
lv_disp_load_scr()
void lv_disp_load_scr (lv_obj_t * scr)
Make a screen active
Parameters
scr pointer to a screen
Referenced by lv_scr_load().
lv_disp_set_bg_color()
void lv_disp_set_bg_color (lv_disp_t * disp, lv_color_t color)
Set the background color of a display
Parameters
disp pointer to a display
color color of the background
lv_disp_set_bg_image()
void lv_disp_set_bg_image (lv_disp_t * disp, const void * img_src)
Set the background image of a display
Parameters
disp pointer to a display
img_src path to file or pointer to an lv_img_dsc_t variable
lv_disp_set_bg_opa()
void lv_disp_set_bg_opa (lv_disp_t * disp, lv_opa_t opa)
Set opacity of the background
Parameters
disp pointer to a display
opa opacity (0..255)
lv_disp_set_theme()
void lv_disp_set_theme (lv_disp_t * disp, lv_theme_t * th)
Set the theme of a display
Parameters
disp pointer to a display
lv_disp_trig_activity()
void lv_disp_trig_activity (lv_disp_t * disp)
Manually trigger an activity on a display
Parameters
disp pointer to a display (NULL to use the default display)
lv_dpx()
static lv_coord_t lv_dpx (lv_coord_t n) inline static
Scale the given number of pixels (a distance or size) relative to a 160 DPI display considering the DPI of the default display. It ensures that e.g. lv_dpx(100) will have the same physical size regardless to the DPI of the display.
Parameters
n the number of pixels to scale
Returns
n x current_dpi/160
Definition at line 241 of file lv_disp.h.
{
    return LV_DPX(n);
}
References LV_DPX.
lv_layer_sys()
static lv_obj_t * lv_layer_sys (void) inline static
Get the active screen of the default display
Returns
pointer to the sys layer
Definition at line 200 of file lv_disp.h.
{
    return lv_disp_get_layer_sys(lv_disp_get_default());
}
References lv_disp_get_default(), and lv_disp_get_layer_sys().
lv_layer_top()
static lv_obj_t * lv_layer_top (void) inline static
Get the top layer of the default display
Returns
pointer to the top layer
Definition at line 191 of file lv_disp.h.
{
    return lv_disp_get_layer_top(lv_disp_get_default());
}
References lv_disp_get_default(), and lv_disp_get_layer_top().
lv_scr_act()
static lv_obj_t * lv_scr_act (void) inline static
Get the active screen of the default display
Returns
pointer to the active screen
Definition at line 182 of file lv_disp.h.
{
    return lv_disp_get_scr_act(lv_disp_get_default());
}
References lv_disp_get_default(), and lv_disp_get_scr_act().
Referenced by Robot::selector_screen::selector(), and Robot::status_screen::status().
lv_scr_load()
static void lv_scr_load (lv_obj_t * scr) inline static
Definition at line 205 of file lv_disp.h.
{
    lv_disp_load_scr(scr);
}
References lv_disp_load_scr().
lv_scr_load_anim()
void lv_scr_load_anim (lv_obj_t * scr, lv_scr_load_anim_t anim_type, uint32_t time, uint32_t delay, bool auto_del)
Switch screen with animation
Parameters
scr pointer to the new screen to load
anim_type type of the animation from lv_scr_load_anim_t, e.g. LV_SCR_LOAD_ANIM_MOVE_LEFT
time time of the animation
delay delay before the transition
auto_del true: automatically delete the old screen