1516X High Stakes: fmt::v10::basic_format_parse_context< Char > Class Template Reference
fmt::v10::basic_format_parse_context< Char > Class Template Reference
#include <core.h>
Public Types
using char_type = Char
using iterator = const Char*
Public Member Functions
constexpr basic_format_parse_context (basic_string_view< Char > format_str, int next_arg_id=0)
constexpr auto begin () const noexcept -> iterator
constexpr auto end () const noexcept -> iterator
void advance_to (iterator it)
auto next_arg_id () -> int
void check_arg_id (int id)
void check_arg_id (basic_string_view< Char >)
void check_dynamic_spec (int arg_id)
Private Member Functions
void do_check_arg_id (int id)
Private Attributes
basic_string_view< Char > format_str_
int next_arg_id_
Detailed Description
template<typename Char>
class fmt::v10::basic_format_parse_context< Char >
\rst Parsing context consisting of a format string range being parsed and an argument counter for automatic indexing. You can use the format_parse_context type alias for char instead. \endrst
Definition at line 604 of file core.h.
Member Typedef Documentation
char_type
template<typename Char > using fmt::v10::basic_format_parse_context< Char >::char_type = Char
Definition at line 611 of file core.h.
iterator
template<typename Char > using fmt::v10::basic_format_parse_context< Char >::iterator = const Char*
Definition at line 612 of file core.h.
Constructor & Destructor Documentation
basic_format_parse_context()
template<typename Char > fmt::v10::basic_format_parse_context< Char >::basic_format_parse_context (basic_string_view< Char > format_str, int next_arg_id = 0) inline explicit constexpr
Definition at line 614 of file core.h.
            : format_str_(format_str), next_arg_id_(next_arg_id) {}
Member Function Documentation
advance_to()
template<typename Char > void fmt::v10::basic_format_parse_context< Char >::advance_to (iterator it) inline
Advances the begin iterator to it.
Definition at line 629 of file core.h.
{ format_str_.remove_prefix(detail::to_unsigned(it - begin())); }
References fmt::v10::basic_string_view< Char >::remove_prefix().
Referenced by fmt::v10::detail::format_string_checker< Char, Args >::on_format_specs(), and fmt::v10::detail::vformat_to().
begin()
template<typename Char > auto fmt::v10::basic_format_parse_context< Char >::begin () const -> iterator inline constexpr noexcept
Returns an iterator to the beginning of the format string range being parsed.
Definition at line 621 of file core.h.
{ return format_str_.begin(); }
References fmt::v10::basic_string_view< Char >::begin().
Referenced by fmt::v10::detail::vformat_to().
check_arg_id() [1/2]
template<typename Char > void fmt::v10::basic_format_parse_context< Char >::check_arg_id (basic_string_view< Char >) inline
Definition at line 658 of file core.h.
{}
check_arg_id() [2/2]
template<typename Char > void fmt::v10::basic_format_parse_context< Char >::check_arg_id (int id) inline
Reports an error if using the automatic argument indexing; otherwise switches to the manual indexing.
Definition at line 649 of file core.h.
{
            if (next_arg_id_ > 0) {
                detail::throw_format_error("cannot switch from automatic to manual argument indexing");
                return;
            }
            next_arg_id_ = -1;
            do_check_arg_id(id);
        }
Referenced by fmt::v10::detail::dynamic_spec_id_handler< Char >::on_index(), fmt::v10::detail::dynamic_spec_id_handler< Char >::on_name(), and fmt::v10::detail::vformat_to().
check_dynamic_spec()
template<typename Char > void fmt::v10::basic_format_parse_context< Char >::check_dynamic_spec (int arg_id)
Definition at line 981 of file core.h.
{
    if (detail::is_constant_evaluated() && (!FMT_GCC_VERSION || FMT_GCC_VERSION >= 1200)) {
        using context = detail::compile_parse_context<Char>;
        static_cast<context*>(this)->check_dynamic_spec(arg_id);
    }
}
References FMT_GCC_VERSION.
Referenced by fmt::v10::detail::dynamic_spec_id_handler< Char >::on_auto(), and fmt::v10::detail::dynamic_spec_id_handler< Char >::on_index().
do_check_arg_id()
template<typename Char > void fmt::v10::basic_format_parse_context< Char >::do_check_arg_id (int id) private
Definition at line 972 of file core.h.
{
    // Argument id is only checked at compile-time during parsing because
    // formatting has its own validation.
    if (detail::is_constant_evaluated() && (!FMT_GCC_VERSION || FMT_GCC_VERSION >= 1200)) {
        using context = detail::compile_parse_context<Char>;
        if (id >= static_cast<context*>(this)->num_args()) detail::throw_format_error("argument not found");
    }
}
References FMT_GCC_VERSION.
end()
template<typename Char > auto fmt::v10::basic_format_parse_context< Char >::end () const -> iterator inline constexpr noexcept
Returns an iterator past the end of the format string range being parsed.
Definition at line 626 of file core.h.
{ return format_str_.end(); }
References fmt::v10::basic_string_view< Char >::end().
next_arg_id()
template<typename Char > auto fmt::v10::basic_format_parse_context< Char >::next_arg_id () -> int inline
Reports an error if using the manual argument indexing; otherwise returns the next argument index and switches to the automatic indexing.
Definition at line 635 of file core.h.
{
            if (next_arg_id_ < 0) {
                detail::throw_format_error("cannot switch from manual to automatic argument indexing");
                return 0;
            }
            int id = next_arg_id_++;
            do_check_arg_id(id);
            return id;
        }
Referenced by fmt::v10::detail::dynamic_spec_id_handler< Char >::on_auto(), and fmt::v10::detail::vformat_to().
Member Data Documentation
format_str_
template<typename Char > basic_string_view<Char> fmt::v10::basic_format_parse_context< Char >::format_str_ private
Definition at line 606 of file core.h.
next_arg_id_
template<typename Char > int fmt::v10::basic_format_parse_context< Char >::next_arg_id_ private
Definition at line 607 of file core.h.
The documentation for this class was generated from the following file:
include/fmt/core.h