1516X High Stakes: fmt::v10::detail::bigint Class Reference
fmt::v10::detail::bigint Class Reference
#include <format.h>
Public Member Functions
bigint ()
bigint (uint64_t n)
bigint (const bigint &)=delete
void operator= (const bigint &)=delete
void assign (const bigint &other)
template<typename Int >
void operator= (Int n)
int num_bigits () const
bigint & operator<<= (int shift)
template<typename Int >
bigint & operator*= (Int value)
void assign_pow10 (int exp)
void square ()
void align (const bigint &other)
int divmod_assign (const bigint &divisor)
Private Types
enum { bigits_capacity = 32 }
using bigit = uint32_t
using double_bigit = uint64_t
Private Member Functions
bigit operator[] (int index) const
bigit & operator[] (int index)
void subtract_bigits (int index, bigit other, bigit &borrow)
void remove_leading_zeros ()
void subtract_aligned (const bigint &other)
void multiply (uint32_t value)
template<typename UInt , fmt::enable_if_t<(std::is_same< UInt, uint64_t >::value||std::is_same< UInt, uint128_t >::value), int > = 0>
void multiply (UInt value)
template<typename UInt , fmt::enable_if_t<(std::is_same< UInt, uint64_t >::value||std::is_same< UInt, uint128_t >::value), int > = 0>
void assign (UInt n)
Private Attributes
basic_memory_buffer< bigit, bigits_capacity > bigits_
int exp_
Static Private Attributes
static constexpr const int bigit_bits = num_bits<bigit>()
Friends
struct formatter< bigint >
int compare (const bigint &lhs, const bigint &rhs)
int add_compare (const bigint &lhs1, const bigint &lhs2, const bigint &rhs)
Detailed Description
Definition at line 2539 of file format.h.
Member Typedef Documentation
bigit
using fmt::v10::detail::bigint::bigit = uint32_t private
Definition at line 2543 of file format.h.
double_bigit
using fmt::v10::detail::bigint::double_bigit = uint64_t private
Definition at line 2544 of file format.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
bigits_capacity
Definition at line 2546 of file format.h.
{ bigits_capacity = 32 };
Constructor & Destructor Documentation
bigint() [1/3]
fmt::v10::detail::bigint::bigint () inline
Definition at line 2624 of file format.h.
: exp_(0) {}
bigint() [2/3]
fmt::v10::detail::bigint::bigint (uint64_t n) inline explicit
Definition at line 2626 of file format.h.
{ assign(n); }
bigint() [3/3]
fmt::v10::detail::bigint::bigint (const bigint &) delete
Member Function Documentation
align()
void fmt::v10::detail::bigint::align (const bigint & other) inline
Definition at line 2755 of file format.h.
{
            int exp_difference = exp_ - other.exp_;
            if (exp_difference <= 0) return;
            int num_bigits = static_cast<int>(bigits_.size());
            bigits_.resize(to_unsigned(num_bigits + exp_difference));
            for (int i = num_bigits - 1, j = i + exp_difference; i >= 0; --i, --j) bigits_[j] = bigits_[i];
            std::uninitialized_fill_n(bigits_.data(), exp_difference, 0);
            exp_ -= exp_difference;
        }
References fmt::v10::detail::buffer< T >::data(), exp_, fmt::v10::basic_memory_buffer< T, SIZE, Allocator >::resize(), fmt::v10::detail::buffer< T >::size(), and fmt::v10::detail::to_unsigned().
assign() [1/2]
void fmt::v10::detail::bigint::assign (const bigint & other) inline
Definition at line 2631 of file format.h.
{
            auto size = other.bigits_.size();
            bigits_.resize(size);
            auto data = other.bigits_.data();
            copy_str<bigit>(data, data + size, bigits_.data());
            exp_ = other.exp_;
        }
References bigits_, fmt::v10::detail::buffer< T >::data(), exp_, fmt::v10::basic_memory_buffer< T, SIZE, Allocator >::resize(), and fmt::v10::detail::buffer< T >::size().
assign() [2/2]
template<typename UInt , fmt::enable_if_t<(std::is_same< UInt, uint64_t >::value||std::is_same< UInt, uint128_t >::value), int > = 0> void fmt::v10::detail::bigint::assign (UInt n) inline private
Definition at line 2614 of file format.h.
{
            size_t num_bigits = 0;
            do {
                bigits_[num_bigits++] = static_cast<bigit>(n);
                n >>= bigit_bits;
            } while (n != 0);
            bigits_.resize(num_bigits);
            exp_ = 0;
        }
References fmt::v10::basic_memory_buffer< T, SIZE, Allocator >::resize().
Referenced by fmt::v10::detail::format_dragon().
assign_pow10()
void fmt::v10::detail::bigint::assign_pow10 (int exp) inline
Definition at line 2707 of file format.h.
{
            FMT_ASSERT(exp >= 0, "");
            if (exp == 0) return *this = 1;
            // Find the top bit.
            int bitmask = 1;
            while (exp >= bitmask) bitmask <<= 1;
            bitmask >>= 1;
            // pow(10, exp) = pow(5, exp) * pow(2, exp). First compute pow(5, exp) by
            // repeated squaring and multiplication.
            *this = 5;
            bitmask >>= 1;
            while (bitmask != 0) {
                square();
                if ((exp & bitmask) != 0) *this *= 5;
                bitmask >>= 1;
            }
            *this <<= exp; // Multiply by pow(2, exp) by shifting.
        }
References fmt::v10::detail::exp, and FMT_ASSERT.
Referenced by fmt::v10::detail::format_dragon().
divmod_assign()
int fmt::v10::detail::bigint::divmod_assign (const bigint & divisor) inline
Definition at line 2767 of file format.h.
{
            FMT_ASSERT(this != &divisor, "");
            if (compare(*this, divisor) < 0) return 0;
            FMT_ASSERT(divisor.bigits_[divisor.bigits_.size() - 1u] != 0, "");
            align(divisor);
            int quotient = 0;
            do {
                subtract_aligned(divisor);
                ++quotient;
            } while (compare(*this, divisor) >= 0);
            return quotient;
        }
References fmt::v10::detail::align, and FMT_ASSERT.
Referenced by fmt::v10::detail::format_dragon().
multiply() [1/2]
template<typename UInt , fmt::enable_if_t<(std::is_same< UInt, uint64_t >::value||std::is_same< UInt, uint128_t >::value), int > = 0> void fmt::v10::detail::bigint::multiply (UInt value) inline private
Definition at line 2595 of file format.h.
{
            using half_uint = conditional_t<std::is_same<UInt, uint128_t>::value, uint64_t, uint32_t>;
            const int shift = num_bits<half_uint>() - bigit_bits;
            const UInt lower = static_cast<half_uint>(value);
            const UInt upper = value >> num_bits<half_uint>();
            UInt carry = 0;
            for (size_t i = 0, n = bigits_.size(); i < n; ++i) {
                UInt result = lower * bigits_[i] + static_cast<bigit>(carry);
                carry = (upper * bigits_[i] << shift) + (result >> bigit_bits) + (carry >> bigit_bits);
                bigits_[i] = static_cast<bigit>(result);
            }
            while (carry != 0) {
                bigits_.push_back(static_cast<bigit>(carry));
                carry >>= bigit_bits;
            }
        }
References fmt::v10::detail::buffer< T >::push_back(), and fmt::v10::detail::buffer< T >::size().
multiply() [2/2]
void fmt::v10::detail::bigint::multiply (uint32_t value) inline private
Definition at line 2582 of file format.h.
{
            const double_bigit wide_value = value;
            bigit carry = 0;
            for (size_t i = 0, n = bigits_.size(); i < n; ++i) {
                double_bigit result = bigits_[i] * wide_value + carry;
                bigits_[i] = static_cast<bigit>(result);
                carry = static_cast<bigit>(result >> bigit_bits);
            }
            if (carry != 0) bigits_.push_back(carry);
        }
References fmt::v10::detail::buffer< T >::push_back(), and fmt::v10::detail::buffer< T >::size().
num_bigits()
int fmt::v10::detail::bigint::num_bigits () const inline
Definition at line 2644 of file format.h.
{ return static_cast<int>(bigits_.size()) + exp_; }
References fmt::v10::detail::buffer< T >::size().
operator*=()
template<typename Int > bigint & fmt::v10::detail::bigint::operator*= (Int value) inline
Definition at line 2661 of file format.h.
{
            FMT_ASSERT(value > 0, "");
            multiply(uint32_or_64_or_128_t<Int>(value));
            return *this;
        }
References FMT_ASSERT, and fmt::v10::detail::multiply().
operator<<=()
bigint & fmt::v10::detail::bigint::operator<<= (int shift) inline
Definition at line 2646 of file format.h.
{
            FMT_ASSERT(shift >= 0, "");
            exp_ += shift / bigit_bits;
            shift %= bigit_bits;
            if (shift == 0) return *this;
            bigit carry = 0;
            for (size_t i = 0, n = bigits_.size(); i < n; ++i) {
                bigit c = bigits_[i] >> (bigit_bits - shift);
                bigits_[i] = (bigits_[i] << shift) + carry;
                carry = c;
            }
            if (carry != 0) bigits_.push_back(carry);
            return *this;
        }
References FMT_ASSERT, fmt::v10::detail::buffer< T >::push_back(), and fmt::v10::detail::buffer< T >::size().
operator=() [1/2]
void fmt::v10::detail::bigint::operator= (const bigint &) delete
operator=() [2/2]
template<typename Int > void fmt::v10::detail::bigint::operator= (Int n) inline
Definition at line 2639 of file format.h.
{
            FMT_ASSERT(n > 0, "");
            assign(uint64_or_128_t<Int>(n));
        }
References FMT_ASSERT.
operator[]() [1/2]
bigit & fmt::v10::detail::bigint::operator[] (int index) inline private
Definition at line 2553 of file format.h.
{ return bigits_[to_unsigned(index)]; }
References fmt::v10::detail::index, and fmt::v10::detail::to_unsigned().
operator[]() [2/2]
bigit fmt::v10::detail::bigint::operator[] (int index) const inline private
Definition at line 2551 of file format.h.
{ return bigits_[to_unsigned(index)]; }
References fmt::v10::detail::index, and fmt::v10::detail::to_unsigned().
remove_leading_zeros()
void fmt::v10::detail::bigint::remove_leading_zeros () inline private
Definition at line 2565 of file format.h.
{
            int num_bigits = static_cast<int>(bigits_.size()) - 1;
            while (num_bigits > 0 && (*this)[num_bigits] == 0) --num_bigits;
            bigits_.resize(to_unsigned(num_bigits + 1));
        }
References fmt::v10::basic_memory_buffer< T, SIZE, Allocator >::resize(), fmt::v10::detail::buffer< T >::size(), and fmt::v10::detail::to_unsigned().
square()
void fmt::v10::detail::bigint::square () inline
Definition at line 2726 of file format.h.
{
            int num_bigits = static_cast<int>(bigits_.size());
            int num_result_bigits = 2 * num_bigits;
            basic_memory_buffer<bigit, bigits_capacity> n(std::move(bigits_));
            bigits_.resize(to_unsigned(num_result_bigits));
            auto sum = uint128_t();
            for (int bigit_index = 0; bigit_index < num_bigits; ++bigit_index) {
                // Compute bigit at position bigit_index of the result by adding
                // cross-product terms n[i] * n[j] such that i + j == bigit_index.
                for (int i = 0, j = bigit_index; j >= 0; ++i, --j) {
                    // Most terms are multiplied twice which can be optimized in the future.
                    sum += static_cast<double_bigit>(n[i]) * n[j];
                }
                (*this)[bigit_index] = static_cast<bigit>(sum);
                sum >>= num_bits<bigit>(); // Compute the carry.
            }
            // Do the same for the top half.
            for (int bigit_index = num_bigits; bigit_index < num_result_bigits; ++bigit_index) {
                for (int j = num_bigits - 1, i = bigit_index - j; i < num_bigits;)
                    sum += static_cast<double_bigit>(n[i++]) * n[j--];
                (*this)[bigit_index] = static_cast<bigit>(sum);
                sum >>= num_bits<bigit>();
            }
            remove_leading_zeros();
            exp_ *= 2;
        }
References fmt::v10::basic_memory_buffer< T, SIZE, Allocator >::resize(), fmt::v10::detail::buffer< T >::size(), and fmt::v10::detail::to_unsigned().
subtract_aligned()
void fmt::v10::detail::bigint::subtract_aligned (const bigint & other) inline private
Definition at line 2572 of file format.h.
{
            FMT_ASSERT(other.exp_ >= exp_, "unaligned bigints");
            FMT_ASSERT(compare(*this, other) >= 0, "");
            bigit borrow = 0;
            int i = other.exp_ - exp_;
            for (size_t j = 0, n = other.bigits_.size(); j != n; ++i, ++j) subtract_bigits(i, other.bigits_[j], borrow);
            while (borrow > 0) subtract_bigits(i, 0, borrow);
            remove_leading_zeros();
        }
References bigits_, exp_, FMT_ASSERT, and fmt::v10::detail::buffer< T >::size().
subtract_bigits()
void fmt::v10::detail::bigint::subtract_bigits (int index, bigit other, bigit & borrow) inline private
Definition at line 2559 of file format.h.
{
            auto result = static_cast<double_bigit>((*this)[index]) - other - borrow;
            (*this)[index] = static_cast<bigit>(result);
            borrow = static_cast<bigit>(result >> (bigit_bits * 2 - 1));
        }
References fmt::v10::detail::index.
Friends And Related Symbol Documentation
add_compare
int add_compare (const bigint & lhs1, const bigint & lhs2, const bigint & rhs) friend
Definition at line 2683 of file format.h.
{
            auto minimum = [](int a, int b) { return a < b ? a : b; };
            auto maximum = [](int a, int b) { return a > b ? a : b; };
            int max_lhs_bigits = maximum(lhs1.num_bigits(), lhs2.num_bigits());
            int num_rhs_bigits = rhs.num_bigits();
            if (max_lhs_bigits + 1 < num_rhs_bigits) return -1;
            if (max_lhs_bigits > num_rhs_bigits) return 1;
            auto get_bigit = [](const bigint& n, int i) -> bigit {
                return i >= n.exp_ && i < n.num_bigits() ? n[i - n.exp_] : 0;
            };
            double_bigit borrow = 0;
            int min_exp = minimum(minimum(lhs1.exp_, lhs2.exp_), rhs.exp_);
            for (int i = num_rhs_bigits - 1; i >= min_exp; --i) {
                double_bigit sum = static_cast<double_bigit>(get_bigit(lhs1, i)) + get_bigit(lhs2, i);
                bigit rhs_bigit = get_bigit(rhs, i);
                if (sum > rhs_bigit + borrow) return 1;
                borrow = rhs_bigit + borrow - sum;
                if (borrow > 1) return -1;
                borrow <<= bigit_bits;
            }
            return borrow != 0 ? -1 : 0;
        }
compare
int compare (const bigint & lhs, const bigint & rhs) friend
Definition at line 2667 of file format.h.
{
            int num_lhs_bigits = lhs.num_bigits(), num_rhs_bigits = rhs.num_bigits();
            if (num_lhs_bigits != num_rhs_bigits) return num_lhs_bigits > num_rhs_bigits ? 1 : -1;
            int i = static_cast<int>(lhs.bigits_.size()) - 1;
            int j = static_cast<int>(rhs.bigits_.size()) - 1;
            int end = i - j;
            if (end < 0) end = 0;
            for (; i >= end; --i, --j) {
                bigit lhs_bigit = lhs[i], rhs_bigit = rhs[j];
                if (lhs_bigit != rhs_bigit) return lhs_bigit > rhs_bigit ? 1 : -1;
            }
            if (i != j) return i > j ? 1 : -1;
            return 0;
        }
formatter< bigint >
friend struct formatter< bigint > friend
Definition at line 2555 of file format.h.
Member Data Documentation
bigit_bits
const int fmt::v10::detail::bigint::bigit_bits = num_bits<bigit>() static constexpr private
Definition at line 2555 of file format.h.
Referenced by fmt::v10::formatter< detail::bigint >::format().
bigits_
basic_memory_buffer<bigit, bigits_capacity> fmt::v10::detail::bigint::bigits_ private
Definition at line 2548 of file format.h.
Referenced by assign(), and subtract_aligned().
exp_
int fmt::v10::detail::bigint::exp_ private
Definition at line 2549 of file format.h.
Referenced by align(), assign(), and subtract_aligned().
The documentation for this class was generated from the following file:
include/fmt/format.h