1516b Over Under: Robot::Puncher::run
run()
void Puncher::run (int autonVal)
Runs the puncher based on the given autonomous value.
This function executes the puncher mechanism based on the provided autonomous value. It contains conditionals that determine the behavior of the puncher.
Note
Make sure to have the Puncher object initialized before calling this function.
Parameters
autonVal The autonomous value to determine the puncher behavior.
Definition at line 15 of file puncher.cpp.
{
    // Manual Puncher Control
    if (Puncher::toShoot() == 2 || distancePuncher == false) {
        if(controller.get_digital(pros::E_CONTROLLER_DIGITAL_R2)) {
            punchers.move(127);
        }
        else {
            punchers.brake();
        }
    }
    // Auton Puncher Control using the distance sensor
    if (distancePuncher == true && autonVal == 3) {
        if (Puncher::toShoot() == 0) {
            punchers.move_absolute(30, 95);
        }
        else {
            punchers.brake();
        }
    }
}
References Robot::Globals::controller, distancePuncher, Robot::Globals::punchers, and toShoot().
Referenced by Robot::Autonomous::Auton3(), and opcontrol().