1516X High Stakes: include/liblvgl/misc/lv_style_gen.h File Reference
lv_style_gen.h File Reference
Macros
#define LV_STYLE_CONST_WIDTH(val)
#define LV_STYLE_CONST_MIN_WIDTH(val)
#define LV_STYLE_CONST_MAX_WIDTH(val)
#define LV_STYLE_CONST_HEIGHT(val)
#define LV_STYLE_CONST_MIN_HEIGHT(val)
#define LV_STYLE_CONST_MAX_HEIGHT(val)
#define LV_STYLE_CONST_X(val)
#define LV_STYLE_CONST_Y(val)
#define LV_STYLE_CONST_ALIGN(val)
#define LV_STYLE_CONST_TRANSFORM_WIDTH(val)
#define LV_STYLE_CONST_TRANSFORM_HEIGHT(val)
#define LV_STYLE_CONST_TRANSLATE_X(val)
#define LV_STYLE_CONST_TRANSLATE_Y(val)
#define LV_STYLE_CONST_TRANSFORM_ZOOM(val)
#define LV_STYLE_CONST_TRANSFORM_ANGLE(val)
#define LV_STYLE_CONST_TRANSFORM_PIVOT_X(val)
#define LV_STYLE_CONST_TRANSFORM_PIVOT_Y(val)
#define LV_STYLE_CONST_PAD_TOP(val)
#define LV_STYLE_CONST_PAD_BOTTOM(val)
#define LV_STYLE_CONST_PAD_LEFT(val)
#define LV_STYLE_CONST_PAD_RIGHT(val)
#define LV_STYLE_CONST_PAD_ROW(val)
#define LV_STYLE_CONST_PAD_COLUMN(val)
#define LV_STYLE_CONST_BG_COLOR(val)
#define LV_STYLE_CONST_BG_OPA(val)
#define LV_STYLE_CONST_BG_GRAD_COLOR(val)
#define LV_STYLE_CONST_BG_GRAD_DIR(val)
#define LV_STYLE_CONST_BG_MAIN_STOP(val)
#define LV_STYLE_CONST_BG_GRAD_STOP(val)
#define LV_STYLE_CONST_BG_GRAD(val)
#define LV_STYLE_CONST_BG_DITHER_MODE(val)
#define LV_STYLE_CONST_BG_IMG_SRC(val)
#define LV_STYLE_CONST_BG_IMG_OPA(val)
#define LV_STYLE_CONST_BG_IMG_RECOLOR(val)
#define LV_STYLE_CONST_BG_IMG_RECOLOR_OPA(val)
#define LV_STYLE_CONST_BG_IMG_TILED(val)
#define LV_STYLE_CONST_BORDER_COLOR(val)
#define LV_STYLE_CONST_BORDER_OPA(val)
#define LV_STYLE_CONST_BORDER_WIDTH(val)
#define LV_STYLE_CONST_BORDER_SIDE(val)
#define LV_STYLE_CONST_BORDER_POST(val)
#define LV_STYLE_CONST_OUTLINE_WIDTH(val)
#define LV_STYLE_CONST_OUTLINE_COLOR(val)
#define LV_STYLE_CONST_OUTLINE_OPA(val)
#define LV_STYLE_CONST_OUTLINE_PAD(val)
#define LV_STYLE_CONST_SHADOW_WIDTH(val)
#define LV_STYLE_CONST_SHADOW_OFS_X(val)
#define LV_STYLE_CONST_SHADOW_OFS_Y(val)
#define LV_STYLE_CONST_SHADOW_SPREAD(val)
#define LV_STYLE_CONST_SHADOW_COLOR(val)
#define LV_STYLE_CONST_SHADOW_OPA(val)
#define LV_STYLE_CONST_IMG_OPA(val)
#define LV_STYLE_CONST_IMG_RECOLOR(val)
#define LV_STYLE_CONST_IMG_RECOLOR_OPA(val)
#define LV_STYLE_CONST_LINE_WIDTH(val)
#define LV_STYLE_CONST_LINE_DASH_WIDTH(val)
#define LV_STYLE_CONST_LINE_DASH_GAP(val)
#define LV_STYLE_CONST_LINE_ROUNDED(val)
#define LV_STYLE_CONST_LINE_COLOR(val)
#define LV_STYLE_CONST_LINE_OPA(val)
#define LV_STYLE_CONST_ARC_WIDTH(val)
#define LV_STYLE_CONST_ARC_ROUNDED(val)
#define LV_STYLE_CONST_ARC_COLOR(val)
#define LV_STYLE_CONST_ARC_OPA(val)
#define LV_STYLE_CONST_ARC_IMG_SRC(val)
#define LV_STYLE_CONST_TEXT_COLOR(val)
#define LV_STYLE_CONST_TEXT_OPA(val)
#define LV_STYLE_CONST_TEXT_FONT(val)
#define LV_STYLE_CONST_TEXT_LETTER_SPACE(val)
#define LV_STYLE_CONST_TEXT_LINE_SPACE(val)
#define LV_STYLE_CONST_TEXT_DECOR(val)
#define LV_STYLE_CONST_TEXT_ALIGN(val)
#define LV_STYLE_CONST_RADIUS(val)
#define LV_STYLE_CONST_CLIP_CORNER(val)
#define LV_STYLE_CONST_OPA(val)
#define LV_STYLE_CONST_COLOR_FILTER_DSC(val)
#define LV_STYLE_CONST_COLOR_FILTER_OPA(val)
#define LV_STYLE_CONST_ANIM(val)
#define LV_STYLE_CONST_ANIM_TIME(val)
#define LV_STYLE_CONST_ANIM_SPEED(val)
#define LV_STYLE_CONST_TRANSITION(val)
#define LV_STYLE_CONST_BLEND_MODE(val)
#define LV_STYLE_CONST_LAYOUT(val)
#define LV_STYLE_CONST_BASE_DIR(val)
Functions
void lv_style_set_width (lv_style_t *style, lv_coord_t value)
void lv_style_set_min_width (lv_style_t *style, lv_coord_t value)
void lv_style_set_max_width (lv_style_t *style, lv_coord_t value)
void lv_style_set_height (lv_style_t *style, lv_coord_t value)
void lv_style_set_min_height (lv_style_t *style, lv_coord_t value)
void lv_style_set_max_height (lv_style_t *style, lv_coord_t value)
void lv_style_set_x (lv_style_t *style, lv_coord_t value)
void lv_style_set_y (lv_style_t *style, lv_coord_t value)
void lv_style_set_align (lv_style_t *style, lv_align_t value)
void lv_style_set_transform_width (lv_style_t *style, lv_coord_t value)
void lv_style_set_transform_height (lv_style_t *style, lv_coord_t value)
void lv_style_set_translate_x (lv_style_t *style, lv_coord_t value)
void lv_style_set_translate_y (lv_style_t *style, lv_coord_t value)
void lv_style_set_transform_zoom (lv_style_t *style, lv_coord_t value)
void lv_style_set_transform_angle (lv_style_t *style, lv_coord_t value)
void lv_style_set_transform_pivot_x (lv_style_t *style, lv_coord_t value)
void lv_style_set_transform_pivot_y (lv_style_t *style, lv_coord_t value)
void lv_style_set_pad_top (lv_style_t *style, lv_coord_t value)
void lv_style_set_pad_bottom (lv_style_t *style, lv_coord_t value)
void lv_style_set_pad_left (lv_style_t *style, lv_coord_t value)
void lv_style_set_pad_right (lv_style_t *style, lv_coord_t value)
void lv_style_set_pad_row (lv_style_t *style, lv_coord_t value)
void lv_style_set_pad_column (lv_style_t *style, lv_coord_t value)
void lv_style_set_bg_color (lv_style_t *style, lv_color_t value)
void lv_style_set_bg_opa (lv_style_t *style, lv_opa_t value)
void lv_style_set_bg_grad_color (lv_style_t *style, lv_color_t value)
void lv_style_set_bg_grad_dir (lv_style_t *style, lv_grad_dir_t value)
void lv_style_set_bg_main_stop (lv_style_t *style, lv_coord_t value)
void lv_style_set_bg_grad_stop (lv_style_t *style, lv_coord_t value)
void lv_style_set_bg_grad (lv_style_t *style, const lv_grad_dsc_t *value)
void lv_style_set_bg_dither_mode (lv_style_t *style, lv_dither_mode_t value)
void lv_style_set_bg_img_src (lv_style_t *style, const void *value)
void lv_style_set_bg_img_opa (lv_style_t *style, lv_opa_t value)
void lv_style_set_bg_img_recolor (lv_style_t *style, lv_color_t value)
void lv_style_set_bg_img_recolor_opa (lv_style_t *style, lv_opa_t value)
void lv_style_set_bg_img_tiled (lv_style_t *style, bool value)
void lv_style_set_border_color (lv_style_t *style, lv_color_t value)
void lv_style_set_border_opa (lv_style_t *style, lv_opa_t value)
void lv_style_set_border_width (lv_style_t *style, lv_coord_t value)
void lv_style_set_border_side (lv_style_t *style, lv_border_side_t value)
void lv_style_set_border_post (lv_style_t *style, bool value)
void lv_style_set_outline_width (lv_style_t *style, lv_coord_t value)
void lv_style_set_outline_color (lv_style_t *style, lv_color_t value)
void lv_style_set_outline_opa (lv_style_t *style, lv_opa_t value)
void lv_style_set_outline_pad (lv_style_t *style, lv_coord_t value)
void lv_style_set_shadow_width (lv_style_t *style, lv_coord_t value)
void lv_style_set_shadow_ofs_x (lv_style_t *style, lv_coord_t value)
void lv_style_set_shadow_ofs_y (lv_style_t *style, lv_coord_t value)
void lv_style_set_shadow_spread (lv_style_t *style, lv_coord_t value)
void lv_style_set_shadow_color (lv_style_t *style, lv_color_t value)
void lv_style_set_shadow_opa (lv_style_t *style, lv_opa_t value)
void lv_style_set_img_opa (lv_style_t *style, lv_opa_t value)
void lv_style_set_img_recolor (lv_style_t *style, lv_color_t value)
void lv_style_set_img_recolor_opa (lv_style_t *style, lv_opa_t value)
void lv_style_set_line_width (lv_style_t *style, lv_coord_t value)
void lv_style_set_line_dash_width (lv_style_t *style, lv_coord_t value)
void lv_style_set_line_dash_gap (lv_style_t *style, lv_coord_t value)
void lv_style_set_line_rounded (lv_style_t *style, bool value)
void lv_style_set_line_color (lv_style_t *style, lv_color_t value)
void lv_style_set_line_opa (lv_style_t *style, lv_opa_t value)
void lv_style_set_arc_width (lv_style_t *style, lv_coord_t value)
void lv_style_set_arc_rounded (lv_style_t *style, bool value)
void lv_style_set_arc_color (lv_style_t *style, lv_color_t value)
void lv_style_set_arc_opa (lv_style_t *style, lv_opa_t value)
void lv_style_set_arc_img_src (lv_style_t *style, const void *value)
void lv_style_set_text_color (lv_style_t *style, lv_color_t value)
void lv_style_set_text_opa (lv_style_t *style, lv_opa_t value)
void lv_style_set_text_font (lv_style_t *style, const lv_font_t *value)
void lv_style_set_text_letter_space (lv_style_t *style, lv_coord_t value)
void lv_style_set_text_line_space (lv_style_t *style, lv_coord_t value)
void lv_style_set_text_decor (lv_style_t *style, lv_text_decor_t value)
void lv_style_set_text_align (lv_style_t *style, lv_text_align_t value)
void lv_style_set_radius (lv_style_t *style, lv_coord_t value)
void lv_style_set_clip_corner (lv_style_t *style, bool value)
void lv_style_set_opa (lv_style_t *style, lv_opa_t value)
void lv_style_set_color_filter_dsc (lv_style_t *style, const lv_color_filter_dsc_t *value)
void lv_style_set_color_filter_opa (lv_style_t *style, lv_opa_t value)
void lv_style_set_anim (lv_style_t *style, const lv_anim_t *value)
void lv_style_set_anim_time (lv_style_t *style, uint32_t value)
void lv_style_set_anim_speed (lv_style_t *style, uint32_t value)
void lv_style_set_transition (lv_style_t *style, const lv_style_transition_dsc_t *value)
void lv_style_set_blend_mode (lv_style_t *style, lv_blend_mode_t value)
void lv_style_set_layout (lv_style_t *style, uint16_t value)
void lv_style_set_base_dir (lv_style_t *style, lv_base_dir_t value)
Macro Definition Documentation
LV_STYLE_CONST_ALIGN
#define LV_STYLE_CONST_ALIGN (val)
Value:
    { \
        .prop = LV_STYLE_ALIGN, .value = { .num = (int32_t)val } \
    }
Definition at line 126 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_ALIGN, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_ANIM
#define LV_STYLE_CONST_ANIM (val)
Value:
    { \
        .prop = LV_STYLE_ANIM, .value = { .ptr = val } \
    }
Definition at line 471 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_ANIM, .value = { .ptr = val } \
    }
LV_STYLE_CONST_ANIM_SPEED
#define LV_STYLE_CONST_ANIM_SPEED (val)
Value:
    { \
        .prop = LV_STYLE_ANIM_SPEED, .value = { .num = (int32_t)val } \
    }
Definition at line 481 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_ANIM_SPEED, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_ANIM_TIME
#define LV_STYLE_CONST_ANIM_TIME (val)
Value:
    { \
        .prop = LV_STYLE_ANIM_TIME, .value = { .num = (int32_t)val } \
    }
Definition at line 476 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_ANIM_TIME, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_ARC_COLOR
#define LV_STYLE_CONST_ARC_COLOR (val)
Value:
    { \
        .prop = LV_STYLE_ARC_COLOR, .value = { .color = val } \
    }
Definition at line 396 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_ARC_COLOR, .value = { .color = val } \
    }
LV_STYLE_CONST_ARC_IMG_SRC
#define LV_STYLE_CONST_ARC_IMG_SRC (val)
Value:
    { \
        .prop = LV_STYLE_ARC_IMG_SRC, .value = { .ptr = val } \
    }
Definition at line 406 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_ARC_IMG_SRC, .value = { .ptr = val } \
    }
LV_STYLE_CONST_ARC_OPA
#define LV_STYLE_CONST_ARC_OPA (val)
Value:
    { \
        .prop = LV_STYLE_ARC_OPA, .value = { .num = (int32_t)val } \
    }
Definition at line 401 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_ARC_OPA, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_ARC_ROUNDED
#define LV_STYLE_CONST_ARC_ROUNDED (val)
Value:
    { \
        .prop = LV_STYLE_ARC_ROUNDED, .value = { .num = (int32_t)val } \
    }
Definition at line 391 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_ARC_ROUNDED, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_ARC_WIDTH
#define LV_STYLE_CONST_ARC_WIDTH (val)
Value:
    { \
        .prop = LV_STYLE_ARC_WIDTH, .value = { .num = (int32_t)val } \
    }
Definition at line 386 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_ARC_WIDTH, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_BASE_DIR
#define LV_STYLE_CONST_BASE_DIR (val)
Value:
    { \
        .prop = LV_STYLE_BASE_DIR, .value = { .num = (int32_t)val } \
    }
Definition at line 501 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_BASE_DIR, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_BG_COLOR
#define LV_STYLE_CONST_BG_COLOR (val)
Value:
    { \
        .prop = LV_STYLE_BG_COLOR, .value = { .color = val } \
    }
Definition at line 201 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_BG_COLOR, .value = { .color = val } \
    }
LV_STYLE_CONST_BG_DITHER_MODE
#define LV_STYLE_CONST_BG_DITHER_MODE (val)
Value:
    { \
        .prop = LV_STYLE_BG_DITHER_MODE, .value = { .num = (int32_t)val } \
    }
Definition at line 236 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_BG_DITHER_MODE, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_BG_GRAD
#define LV_STYLE_CONST_BG_GRAD (val)
Value:
    { \
        .prop = LV_STYLE_BG_GRAD, .value = { .ptr = val } \
    }
Definition at line 231 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_BG_GRAD, .value = { .ptr = val } \
    }
LV_STYLE_CONST_BG_GRAD_COLOR
#define LV_STYLE_CONST_BG_GRAD_COLOR (val)
Value:
    { \
        .prop = LV_STYLE_BG_GRAD_COLOR, .value = { .color = val } \
    }
Definition at line 211 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_BG_GRAD_COLOR, .value = { .color = val } \
    }
LV_STYLE_CONST_BG_GRAD_DIR
#define LV_STYLE_CONST_BG_GRAD_DIR (val)
Value:
    { \
        .prop = LV_STYLE_BG_GRAD_DIR, .value = { .num = (int32_t)val } \
    }
Definition at line 216 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_BG_GRAD_DIR, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_BG_GRAD_STOP
#define LV_STYLE_CONST_BG_GRAD_STOP (val)
Value:
    { \
        .prop = LV_STYLE_BG_GRAD_STOP, .value = { .num = (int32_t)val } \
    }
Definition at line 226 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_BG_GRAD_STOP, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_BG_IMG_OPA
#define LV_STYLE_CONST_BG_IMG_OPA (val)
Value:
    { \
        .prop = LV_STYLE_BG_IMG_OPA, .value = { .num = (int32_t)val } \
    }
Definition at line 246 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_BG_IMG_OPA, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_BG_IMG_RECOLOR
#define LV_STYLE_CONST_BG_IMG_RECOLOR (val)
Value:
    { \
        .prop = LV_STYLE_BG_IMG_RECOLOR, .value = { .color = val } \
    }
Definition at line 251 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_BG_IMG_RECOLOR, .value = { .color = val } \
    }
LV_STYLE_CONST_BG_IMG_RECOLOR_OPA
#define LV_STYLE_CONST_BG_IMG_RECOLOR_OPA (val)
Value:
    { \
        .prop = LV_STYLE_BG_IMG_RECOLOR_OPA, .value = { .num = (int32_t)val } \
    }
Definition at line 256 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_BG_IMG_RECOLOR_OPA, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_BG_IMG_SRC
#define LV_STYLE_CONST_BG_IMG_SRC (val)
Value:
    { \
        .prop = LV_STYLE_BG_IMG_SRC, .value = { .ptr = val } \
    }
Definition at line 241 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_BG_IMG_SRC, .value = { .ptr = val } \
    }
LV_STYLE_CONST_BG_IMG_TILED
#define LV_STYLE_CONST_BG_IMG_TILED (val)
Value:
    { \
        .prop = LV_STYLE_BG_IMG_TILED, .value = { .num = (int32_t)val } \
    }
Definition at line 261 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_BG_IMG_TILED, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_BG_MAIN_STOP
#define LV_STYLE_CONST_BG_MAIN_STOP (val)
Value:
    { \
        .prop = LV_STYLE_BG_MAIN_STOP, .value = { .num = (int32_t)val } \
    }
Definition at line 221 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_BG_MAIN_STOP, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_BG_OPA
#define LV_STYLE_CONST_BG_OPA (val)
Value:
    { \
        .prop = LV_STYLE_BG_OPA, .value = { .num = (int32_t)val } \
    }
Definition at line 206 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_BG_OPA, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_BLEND_MODE
#define LV_STYLE_CONST_BLEND_MODE (val)
Value:
    { \
        .prop = LV_STYLE_BLEND_MODE, .value = { .num = (int32_t)val } \
    }
Definition at line 491 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_BLEND_MODE, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_BORDER_COLOR
#define LV_STYLE_CONST_BORDER_COLOR (val)
Value:
    { \
        .prop = LV_STYLE_BORDER_COLOR, .value = { .color = val } \
    }
Definition at line 266 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_BORDER_COLOR, .value = { .color = val } \
    }
LV_STYLE_CONST_BORDER_OPA
#define LV_STYLE_CONST_BORDER_OPA (val)
Value:
    { \
        .prop = LV_STYLE_BORDER_OPA, .value = { .num = (int32_t)val } \
    }
Definition at line 271 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_BORDER_OPA, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_BORDER_POST
#define LV_STYLE_CONST_BORDER_POST (val)
Value:
    { \
        .prop = LV_STYLE_BORDER_POST, .value = { .num = (int32_t)val } \
    }
Definition at line 286 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_BORDER_POST, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_BORDER_SIDE
#define LV_STYLE_CONST_BORDER_SIDE (val)
Value:
    { \
        .prop = LV_STYLE_BORDER_SIDE, .value = { .num = (int32_t)val } \
    }
Definition at line 281 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_BORDER_SIDE, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_BORDER_WIDTH
#define LV_STYLE_CONST_BORDER_WIDTH (val)
Value:
    { \
        .prop = LV_STYLE_BORDER_WIDTH, .value = { .num = (int32_t)val } \
    }
Definition at line 276 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_BORDER_WIDTH, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_CLIP_CORNER
#define LV_STYLE_CONST_CLIP_CORNER (val)
Value:
    { \
        .prop = LV_STYLE_CLIP_CORNER, .value = { .num = (int32_t)val } \
    }
Definition at line 451 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_CLIP_CORNER, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_COLOR_FILTER_DSC
#define LV_STYLE_CONST_COLOR_FILTER_DSC (val)
Value:
    { \
        .prop = LV_STYLE_COLOR_FILTER_DSC, .value = { .ptr = val } \
    }
Definition at line 461 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_COLOR_FILTER_DSC, .value = { .ptr = val } \
    }
LV_STYLE_CONST_COLOR_FILTER_OPA
#define LV_STYLE_CONST_COLOR_FILTER_OPA (val)
Value:
    { \
        .prop = LV_STYLE_COLOR_FILTER_OPA, .value = { .num = (int32_t)val } \
    }
Definition at line 466 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_COLOR_FILTER_OPA, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_HEIGHT
#define LV_STYLE_CONST_HEIGHT (val)
Value:
    { \
        .prop = LV_STYLE_HEIGHT, .value = { .num = (int32_t)val } \
    }
Definition at line 101 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_HEIGHT, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_IMG_OPA
#define LV_STYLE_CONST_IMG_OPA (val)
Value:
    { \
        .prop = LV_STYLE_IMG_OPA, .value = { .num = (int32_t)val } \
    }
Definition at line 341 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_IMG_OPA, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_IMG_RECOLOR
#define LV_STYLE_CONST_IMG_RECOLOR (val)
Value:
    { \
        .prop = LV_STYLE_IMG_RECOLOR, .value = { .color = val } \
    }
Definition at line 346 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_IMG_RECOLOR, .value = { .color = val } \
    }
LV_STYLE_CONST_IMG_RECOLOR_OPA
#define LV_STYLE_CONST_IMG_RECOLOR_OPA (val)
Value:
    { \
        .prop = LV_STYLE_IMG_RECOLOR_OPA, .value = { .num = (int32_t)val } \
    }
Definition at line 351 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_IMG_RECOLOR_OPA, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_LAYOUT
#define LV_STYLE_CONST_LAYOUT (val)
Value:
    { \
        .prop = LV_STYLE_LAYOUT, .value = { .num = (int32_t)val } \
    }
Definition at line 496 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_LAYOUT, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_LINE_COLOR
#define LV_STYLE_CONST_LINE_COLOR (val)
Value:
    { \
        .prop = LV_STYLE_LINE_COLOR, .value = { .color = val } \
    }
Definition at line 376 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_LINE_COLOR, .value = { .color = val } \
    }
LV_STYLE_CONST_LINE_DASH_GAP
#define LV_STYLE_CONST_LINE_DASH_GAP (val)
Value:
    { \
        .prop = LV_STYLE_LINE_DASH_GAP, .value = { .num = (int32_t)val } \
    }
Definition at line 366 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_LINE_DASH_GAP, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_LINE_DASH_WIDTH
#define LV_STYLE_CONST_LINE_DASH_WIDTH (val)
Value:
    { \
        .prop = LV_STYLE_LINE_DASH_WIDTH, .value = { .num = (int32_t)val } \
    }
Definition at line 361 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_LINE_DASH_WIDTH, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_LINE_OPA
#define LV_STYLE_CONST_LINE_OPA (val)
Value:
    { \
        .prop = LV_STYLE_LINE_OPA, .value = { .num = (int32_t)val } \
    }
Definition at line 381 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_LINE_OPA, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_LINE_ROUNDED
#define LV_STYLE_CONST_LINE_ROUNDED (val)
Value:
    { \
        .prop = LV_STYLE_LINE_ROUNDED, .value = { .num = (int32_t)val } \
    }
Definition at line 371 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_LINE_ROUNDED, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_LINE_WIDTH
#define LV_STYLE_CONST_LINE_WIDTH (val)
Value:
    { \
        .prop = LV_STYLE_LINE_WIDTH, .value = { .num = (int32_t)val } \
    }
Definition at line 356 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_LINE_WIDTH, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_MAX_HEIGHT
#define LV_STYLE_CONST_MAX_HEIGHT (val)
Value:
    { \
        .prop = LV_STYLE_MAX_HEIGHT, .value = { .num = (int32_t)val } \
    }
Definition at line 111 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_MAX_HEIGHT, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_MAX_WIDTH
#define LV_STYLE_CONST_MAX_WIDTH (val)
Value:
    { \
        .prop = LV_STYLE_MAX_WIDTH, .value = { .num = (int32_t)val } \
    }
Definition at line 96 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_MAX_WIDTH, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_MIN_HEIGHT
#define LV_STYLE_CONST_MIN_HEIGHT (val)
Value:
    { \
        .prop = LV_STYLE_MIN_HEIGHT, .value = { .num = (int32_t)val } \
    }
Definition at line 106 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_MIN_HEIGHT, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_MIN_WIDTH
#define LV_STYLE_CONST_MIN_WIDTH (val)
Value:
    { \
        .prop = LV_STYLE_MIN_WIDTH, .value = { .num = (int32_t)val } \
    }
Definition at line 91 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_MIN_WIDTH, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_OPA
#define LV_STYLE_CONST_OPA (val)
Value:
    { \
        .prop = LV_STYLE_OPA, .value = { .num = (int32_t)val } \
    }
Definition at line 456 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_OPA, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_OUTLINE_COLOR
#define LV_STYLE_CONST_OUTLINE_COLOR (val)
Value:
    { \
        .prop = LV_STYLE_OUTLINE_COLOR, .value = { .color = val } \
    }
Definition at line 296 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_OUTLINE_COLOR, .value = { .color = val } \
    }
LV_STYLE_CONST_OUTLINE_OPA
#define LV_STYLE_CONST_OUTLINE_OPA (val)
Value:
    { \
        .prop = LV_STYLE_OUTLINE_OPA, .value = { .num = (int32_t)val } \
    }
Definition at line 301 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_OUTLINE_OPA, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_OUTLINE_PAD
#define LV_STYLE_CONST_OUTLINE_PAD (val)
Value:
    { \
        .prop = LV_STYLE_OUTLINE_PAD, .value = { .num = (int32_t)val } \
    }
Definition at line 306 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_OUTLINE_PAD, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_OUTLINE_WIDTH
#define LV_STYLE_CONST_OUTLINE_WIDTH (val)
Value:
    { \
        .prop = LV_STYLE_OUTLINE_WIDTH, .value = { .num = (int32_t)val } \
    }
Definition at line 291 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_OUTLINE_WIDTH, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_PAD_BOTTOM
#define LV_STYLE_CONST_PAD_BOTTOM (val)
Value:
    { \
        .prop = LV_STYLE_PAD_BOTTOM, .value = { .num = (int32_t)val } \
    }
Definition at line 176 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_PAD_BOTTOM, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_PAD_COLUMN
#define LV_STYLE_CONST_PAD_COLUMN (val)
Value:
    { \
        .prop = LV_STYLE_PAD_COLUMN, .value = { .num = (int32_t)val } \
    }
Definition at line 196 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_PAD_COLUMN, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_PAD_LEFT
#define LV_STYLE_CONST_PAD_LEFT (val)
Value:
    { \
        .prop = LV_STYLE_PAD_LEFT, .value = { .num = (int32_t)val } \
    }
Definition at line 181 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_PAD_LEFT, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_PAD_RIGHT
#define LV_STYLE_CONST_PAD_RIGHT (val)
Value:
    { \
        .prop = LV_STYLE_PAD_RIGHT, .value = { .num = (int32_t)val } \
    }
Definition at line 186 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_PAD_RIGHT, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_PAD_ROW
#define LV_STYLE_CONST_PAD_ROW (val)
Value:
    { \
        .prop = LV_STYLE_PAD_ROW, .value = { .num = (int32_t)val } \
    }
Definition at line 191 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_PAD_ROW, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_PAD_TOP
#define LV_STYLE_CONST_PAD_TOP (val)
Value:
    { \
        .prop = LV_STYLE_PAD_TOP, .value = { .num = (int32_t)val } \
    }
Definition at line 171 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_PAD_TOP, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_RADIUS
#define LV_STYLE_CONST_RADIUS (val)
Value:
    { \
        .prop = LV_STYLE_RADIUS, .value = { .num = (int32_t)val } \
    }
Definition at line 446 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_RADIUS, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_SHADOW_COLOR
#define LV_STYLE_CONST_SHADOW_COLOR (val)
Value:
    { \
        .prop = LV_STYLE_SHADOW_COLOR, .value = { .color = val } \
    }
Definition at line 331 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_SHADOW_COLOR, .value = { .color = val } \
    }
LV_STYLE_CONST_SHADOW_OFS_X
#define LV_STYLE_CONST_SHADOW_OFS_X (val)
Value:
    { \
        .prop = LV_STYLE_SHADOW_OFS_X, .value = { .num = (int32_t)val } \
    }
Definition at line 316 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_SHADOW_OFS_X, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_SHADOW_OFS_Y
#define LV_STYLE_CONST_SHADOW_OFS_Y (val)
Value:
    { \
        .prop = LV_STYLE_SHADOW_OFS_Y, .value = { .num = (int32_t)val } \
    }
Definition at line 321 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_SHADOW_OFS_Y, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_SHADOW_OPA
#define LV_STYLE_CONST_SHADOW_OPA (val)
Value:
    { \
        .prop = LV_STYLE_SHADOW_OPA, .value = { .num = (int32_t)val } \
    }
Definition at line 336 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_SHADOW_OPA, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_SHADOW_SPREAD
#define LV_STYLE_CONST_SHADOW_SPREAD (val)
Value:
    { \
        .prop = LV_STYLE_SHADOW_SPREAD, .value = { .num = (int32_t)val } \
    }
Definition at line 326 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_SHADOW_SPREAD, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_SHADOW_WIDTH
#define LV_STYLE_CONST_SHADOW_WIDTH (val)
Value:
    { \
        .prop = LV_STYLE_SHADOW_WIDTH, .value = { .num = (int32_t)val } \
    }
Definition at line 311 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_SHADOW_WIDTH, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_TEXT_ALIGN
#define LV_STYLE_CONST_TEXT_ALIGN (val)
Value:
    { \
        .prop = LV_STYLE_TEXT_ALIGN, .value = { .num = (int32_t)val } \
    }
Definition at line 441 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_TEXT_ALIGN, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_TEXT_COLOR
#define LV_STYLE_CONST_TEXT_COLOR (val)
Value:
    { \
        .prop = LV_STYLE_TEXT_COLOR, .value = { .color = val } \
    }
Definition at line 411 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_TEXT_COLOR, .value = { .color = val } \
    }
LV_STYLE_CONST_TEXT_DECOR
#define LV_STYLE_CONST_TEXT_DECOR (val)
Value:
    { \
        .prop = LV_STYLE_TEXT_DECOR, .value = { .num = (int32_t)val } \
    }
Definition at line 436 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_TEXT_DECOR, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_TEXT_FONT
#define LV_STYLE_CONST_TEXT_FONT (val)
Value:
    { \
        .prop = LV_STYLE_TEXT_FONT, .value = { .ptr = val } \
    }
Definition at line 421 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_TEXT_FONT, .value = { .ptr = val } \
    }
LV_STYLE_CONST_TEXT_LETTER_SPACE
#define LV_STYLE_CONST_TEXT_LETTER_SPACE (val)
Value:
    { \
        .prop = LV_STYLE_TEXT_LETTER_SPACE, .value = { .num = (int32_t)val } \
    }
Definition at line 426 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_TEXT_LETTER_SPACE, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_TEXT_LINE_SPACE
#define LV_STYLE_CONST_TEXT_LINE_SPACE (val)
Value:
    { \
        .prop = LV_STYLE_TEXT_LINE_SPACE, .value = { .num = (int32_t)val } \
    }
Definition at line 431 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_TEXT_LINE_SPACE, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_TEXT_OPA
#define LV_STYLE_CONST_TEXT_OPA (val)
Value:
    { \
        .prop = LV_STYLE_TEXT_OPA, .value = { .num = (int32_t)val } \
    }
Definition at line 416 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_TEXT_OPA, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_TRANSFORM_ANGLE
#define LV_STYLE_CONST_TRANSFORM_ANGLE (val)
Value:
    { \
        .prop = LV_STYLE_TRANSFORM_ANGLE, .value = { .num = (int32_t)val } \
    }
Definition at line 156 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_TRANSFORM_ANGLE, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_TRANSFORM_HEIGHT
#define LV_STYLE_CONST_TRANSFORM_HEIGHT (val)
Value:
    { \
        .prop = LV_STYLE_TRANSFORM_HEIGHT, .value = { .num = (int32_t)val } \
    }
Definition at line 136 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_TRANSFORM_HEIGHT, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_TRANSFORM_PIVOT_X
#define LV_STYLE_CONST_TRANSFORM_PIVOT_X (val)
Value:
    { \
        .prop = LV_STYLE_TRANSFORM_PIVOT_X, .value = { .num = (int32_t)val } \
    }
Definition at line 161 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_TRANSFORM_PIVOT_X, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_TRANSFORM_PIVOT_Y
#define LV_STYLE_CONST_TRANSFORM_PIVOT_Y (val)
Value:
    { \
        .prop = LV_STYLE_TRANSFORM_PIVOT_Y, .value = { .num = (int32_t)val } \
    }
Definition at line 166 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_TRANSFORM_PIVOT_Y, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_TRANSFORM_WIDTH
#define LV_STYLE_CONST_TRANSFORM_WIDTH (val)
Value:
    { \
        .prop = LV_STYLE_TRANSFORM_WIDTH, .value = { .num = (int32_t)val } \
    }
Definition at line 131 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_TRANSFORM_WIDTH, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_TRANSFORM_ZOOM
#define LV_STYLE_CONST_TRANSFORM_ZOOM (val)
Value:
    { \
        .prop = LV_STYLE_TRANSFORM_ZOOM, .value = { .num = (int32_t)val } \
    }
Definition at line 151 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_TRANSFORM_ZOOM, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_TRANSITION
#define LV_STYLE_CONST_TRANSITION (val)
Value:
    { \
        .prop = LV_STYLE_TRANSITION, .value = { .ptr = val } \
    }
Definition at line 486 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_TRANSITION, .value = { .ptr = val } \
    }
LV_STYLE_CONST_TRANSLATE_X
#define LV_STYLE_CONST_TRANSLATE_X (val)
Value:
    { \
        .prop = LV_STYLE_TRANSLATE_X, .value = { .num = (int32_t)val } \
    }
Definition at line 141 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_TRANSLATE_X, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_TRANSLATE_Y
#define LV_STYLE_CONST_TRANSLATE_Y (val)
Value:
    { \
        .prop = LV_STYLE_TRANSLATE_Y, .value = { .num = (int32_t)val } \
    }
Definition at line 146 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_TRANSLATE_Y, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_WIDTH
#define LV_STYLE_CONST_WIDTH (val)
Value:
    { \
        .prop = LV_STYLE_WIDTH, .value = { .num = (int32_t)val } \
    }
Definition at line 86 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_WIDTH, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_X
#define LV_STYLE_CONST_X (val)
Value:
    { \
        .prop = LV_STYLE_X, .value = { .num = (int32_t)val } \
    }
Definition at line 116 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_X, .value = { .num = (int32_t)val } \
    }
LV_STYLE_CONST_Y
#define LV_STYLE_CONST_Y (val)
Value:
    { \
        .prop = LV_STYLE_Y, .value = { .num = (int32_t)val } \
    }
Definition at line 121 of file lv_style_gen.h.
    { \
        .prop = LV_STYLE_Y, .value = { .num = (int32_t)val } \
    }
Function Documentation
lv_style_set_align()
void lv_style_set_align (lv_style_t * style, lv_align_t value)
lv_style_set_anim()
void lv_style_set_anim (lv_style_t * style, const lv_anim_t * value)
lv_style_set_anim_speed()
void lv_style_set_anim_speed (lv_style_t * style, uint32_t value)
lv_style_set_anim_time()
void lv_style_set_anim_time (lv_style_t * style, uint32_t value)
lv_style_set_arc_color()
void lv_style_set_arc_color (lv_style_t * style, lv_color_t value)
lv_style_set_arc_img_src()
void lv_style_set_arc_img_src (lv_style_t * style, const void * value)
lv_style_set_arc_opa()
void lv_style_set_arc_opa (lv_style_t * style, lv_opa_t value)
lv_style_set_arc_rounded()
void lv_style_set_arc_rounded (lv_style_t * style, bool value)
lv_style_set_arc_width()
void lv_style_set_arc_width (lv_style_t * style, lv_coord_t value)
lv_style_set_base_dir()
void lv_style_set_base_dir (lv_style_t * style, lv_base_dir_t value)
lv_style_set_bg_color()
void lv_style_set_bg_color (lv_style_t * style, lv_color_t value)
lv_style_set_bg_dither_mode()
void lv_style_set_bg_dither_mode (lv_style_t * style, lv_dither_mode_t value)
lv_style_set_bg_grad()
void lv_style_set_bg_grad (lv_style_t * style, const lv_grad_dsc_t * value)
lv_style_set_bg_grad_color()
void lv_style_set_bg_grad_color (lv_style_t * style, lv_color_t value)
lv_style_set_bg_grad_dir()
void lv_style_set_bg_grad_dir (lv_style_t * style, lv_grad_dir_t value)
lv_style_set_bg_grad_stop()
void lv_style_set_bg_grad_stop (lv_style_t * style, lv_coord_t value)
lv_style_set_bg_img_opa()
void lv_style_set_bg_img_opa (lv_style_t * style, lv_opa_t value)
lv_style_set_bg_img_recolor()
void lv_style_set_bg_img_recolor (lv_style_t * style, lv_color_t value)
lv_style_set_bg_img_recolor_opa()
void lv_style_set_bg_img_recolor_opa (lv_style_t * style, lv_opa_t value)
lv_style_set_bg_img_src()
void lv_style_set_bg_img_src (lv_style_t * style, const void * value)
lv_style_set_bg_img_tiled()
void lv_style_set_bg_img_tiled (lv_style_t * style, bool value)
lv_style_set_bg_main_stop()
void lv_style_set_bg_main_stop (lv_style_t * style, lv_coord_t value)
lv_style_set_bg_opa()
void lv_style_set_bg_opa (lv_style_t * style, lv_opa_t value)
lv_style_set_blend_mode()
void lv_style_set_blend_mode (lv_style_t * style, lv_blend_mode_t value)
lv_style_set_border_color()
void lv_style_set_border_color (lv_style_t * style, lv_color_t value)
lv_style_set_border_opa()
void lv_style_set_border_opa (lv_style_t * style, lv_opa_t value)
lv_style_set_border_post()
void lv_style_set_border_post (lv_style_t * style, bool value)
lv_style_set_border_side()
void lv_style_set_border_side (lv_style_t * style, lv_border_side_t value)
lv_style_set_border_width()
void lv_style_set_border_width (lv_style_t * style, lv_coord_t value)
lv_style_set_clip_corner()
void lv_style_set_clip_corner (lv_style_t * style, bool value)
lv_style_set_color_filter_dsc()
void lv_style_set_color_filter_dsc (lv_style_t * style, const lv_color_filter_dsc_t * value)
lv_style_set_color_filter_opa()
void lv_style_set_color_filter_opa (lv_style_t * style, lv_opa_t value)
lv_style_set_height()
void lv_style_set_height (lv_style_t * style, lv_coord_t value)
Examples
/media/ubuntu/Linux/code/high_stakes_x/include/liblvgl/misc/lv_style.h.
Referenced by lv_style_set_size().
lv_style_set_img_opa()
void lv_style_set_img_opa (lv_style_t * style, lv_opa_t value)
lv_style_set_img_recolor()
void lv_style_set_img_recolor (lv_style_t * style, lv_color_t value)
lv_style_set_img_recolor_opa()
void lv_style_set_img_recolor_opa (lv_style_t * style, lv_opa_t value)
lv_style_set_layout()
void lv_style_set_layout (lv_style_t * style, uint16_t value)
lv_style_set_line_color()
void lv_style_set_line_color (lv_style_t * style, lv_color_t value)
lv_style_set_line_dash_gap()
void lv_style_set_line_dash_gap (lv_style_t * style, lv_coord_t value)
lv_style_set_line_dash_width()
void lv_style_set_line_dash_width (lv_style_t * style, lv_coord_t value)
lv_style_set_line_opa()
void lv_style_set_line_opa (lv_style_t * style, lv_opa_t value)
lv_style_set_line_rounded()
void lv_style_set_line_rounded (lv_style_t * style, bool value)
lv_style_set_line_width()
void lv_style_set_line_width (lv_style_t * style, lv_coord_t value)
lv_style_set_max_height()
void lv_style_set_max_height (lv_style_t * style, lv_coord_t value)
lv_style_set_max_width()
void lv_style_set_max_width (lv_style_t * style, lv_coord_t value)
lv_style_set_min_height()
void lv_style_set_min_height (lv_style_t * style, lv_coord_t value)
lv_style_set_min_width()
void lv_style_set_min_width (lv_style_t * style, lv_coord_t value)
lv_style_set_opa()
void lv_style_set_opa (lv_style_t * style, lv_opa_t value)
lv_style_set_outline_color()
void lv_style_set_outline_color (lv_style_t * style, lv_color_t value)
lv_style_set_outline_opa()
void lv_style_set_outline_opa (lv_style_t * style, lv_opa_t value)
lv_style_set_outline_pad()
void lv_style_set_outline_pad (lv_style_t * style, lv_coord_t value)
lv_style_set_outline_width()
void lv_style_set_outline_width (lv_style_t * style, lv_coord_t value)
lv_style_set_pad_bottom()
void lv_style_set_pad_bottom (lv_style_t * style, lv_coord_t value)
Examples
/media/ubuntu/Linux/code/high_stakes_x/include/liblvgl/misc/lv_style.h.
Referenced by lv_style_set_pad_all(), and lv_style_set_pad_ver().
lv_style_set_pad_column()
void lv_style_set_pad_column (lv_style_t * style, lv_coord_t value)
Examples
/media/ubuntu/Linux/code/high_stakes_x/include/liblvgl/misc/lv_style.h.
Referenced by lv_style_set_pad_gap().
lv_style_set_pad_left()
void lv_style_set_pad_left (lv_style_t * style, lv_coord_t value)
Examples
/media/ubuntu/Linux/code/high_stakes_x/include/liblvgl/misc/lv_style.h.
Referenced by lv_style_set_pad_all(), and lv_style_set_pad_hor().
lv_style_set_pad_right()
void lv_style_set_pad_right (lv_style_t * style, lv_coord_t value)
Examples
/media/ubuntu/Linux/code/high_stakes_x/include/liblvgl/misc/lv_style.h.
Referenced by lv_style_set_pad_all(), and lv_style_set_pad_hor().
lv_style_set_pad_row()
void lv_style_set_pad_row (lv_style_t * style, lv_coord_t value)
Examples
/media/ubuntu/Linux/code/high_stakes_x/include/liblvgl/misc/lv_style.h.
Referenced by lv_style_set_pad_gap().
lv_style_set_pad_top()
void lv_style_set_pad_top (lv_style_t * style, lv_coord_t value)
Examples
/media/ubuntu/Linux/code/high_stakes_x/include/liblvgl/misc/lv_style.h.
Referenced by lv_style_set_pad_all(), and lv_style_set_pad_ver().
lv_style_set_radius()
void lv_style_set_radius (lv_style_t * style, lv_coord_t value)
lv_style_set_shadow_color()
void lv_style_set_shadow_color (lv_style_t * style, lv_color_t value)
lv_style_set_shadow_ofs_x()
void lv_style_set_shadow_ofs_x (lv_style_t * style, lv_coord_t value)
lv_style_set_shadow_ofs_y()
void lv_style_set_shadow_ofs_y (lv_style_t * style, lv_coord_t value)
lv_style_set_shadow_opa()
void lv_style_set_shadow_opa (lv_style_t * style, lv_opa_t value)
lv_style_set_shadow_spread()
void lv_style_set_shadow_spread (lv_style_t * style, lv_coord_t value)
lv_style_set_shadow_width()
void lv_style_set_shadow_width (lv_style_t * style, lv_coord_t value)
lv_style_set_text_align()
void lv_style_set_text_align (lv_style_t * style, lv_text_align_t value)
lv_style_set_text_color()
void lv_style_set_text_color (lv_style_t * style, lv_color_t value)
lv_style_set_text_decor()
void lv_style_set_text_decor (lv_style_t * style, lv_text_decor_t value)
lv_style_set_text_font()
void lv_style_set_text_font (lv_style_t * style, const lv_font_t * value)
lv_style_set_text_letter_space()
void lv_style_set_text_letter_space (lv_style_t * style, lv_coord_t value)
lv_style_set_text_line_space()
void lv_style_set_text_line_space (lv_style_t * style, lv_coord_t value)
lv_style_set_text_opa()
void lv_style_set_text_opa (lv_style_t * style, lv_opa_t value)
lv_style_set_transform_angle()
void lv_style_set_transform_angle (lv_style_t * style, lv_coord_t value)
lv_style_set_transform_height()
void lv_style_set_transform_height (lv_style_t * style, lv_coord_t value)
lv_style_set_transform_pivot_x()
void lv_style_set_transform_pivot_x (lv_style_t * style, lv_coord_t value)
lv_style_set_transform_pivot_y()
void lv_style_set_transform_pivot_y (lv_style_t * style, lv_coord_t value)
lv_style_set_transform_width()
void lv_style_set_transform_width (lv_style_t * style, lv_coord_t value)
lv_style_set_transform_zoom()
void lv_style_set_transform_zoom (lv_style_t * style, lv_coord_t value)
lv_style_set_transition()
void lv_style_set_transition (lv_style_t * style, const lv_style_transition_dsc_t * value)
lv_style_set_translate_x()
void lv_style_set_translate_x (lv_style_t * style, lv_coord_t value)
lv_style_set_translate_y()
void lv_style_set_translate_y (lv_style_t * style, lv_coord_t value)
lv_style_set_width()
void lv_style_set_width (lv_style_t * style, lv_coord_t value)
Examples
/media/ubuntu/Linux/code/high_stakes_x/include/liblvgl/misc/lv_style.h.
Referenced by lv_style_set_size().
lv_style_set_x()
void lv_style_set_x (lv_style_t * style, lv_coord_t value)
lv_style_set_y()
void lv_style_set_y (lv_style_t * style, lv_coord_t value)