1516X High Stakes: lemlib::BaseSink Class Reference
lemlib::BaseSink Class Reference
A base for any sink in LemLib to implement.
#include <baseSink.hpp>
Public Member Functions
BaseSink ()=default
BaseSink (std::initializer_list< std::shared_ptr< BaseSink > > sinks)
Construct a new combined sink.
void setLowestLevel (Level level)
Set the lowest level. If this is a combined sink, this operation will apply for all the parent sinks.
template<typename... T>
void log (Level level, fmt::format_string< T... > format, T &&... args)
Log a message at the given level If this is a combined sink, this operation will apply for all the parent sinks.
template<typename... T>
void debug (fmt::format_string< T... > format, T &&... args)
Log a message at the debug level. If this is a combined sink, this operation will apply for all the parent sinks.
template<typename... T>
void info (fmt::format_string< T... > format, T &&... args)
Log a message at the info level If this is a combined sink, this operation will apply for all the parent sinks.
template<typename... T>
void warn (fmt::format_string< T... > format, T &&... args)
Log a message at the warn level If this is a combined sink, this operation will apply for all the parent sinks.
template<typename... T>
void error (fmt::format_string< T... > format, T &&... args)
Log a message at the error level. If this is a combined sink, this operation will apply for all the parent sinks.
template<typename... T>
void fatal (fmt::format_string< T... > format, T &&... args)
Log a message at the fatal level If this is a combined sink, this operation will apply for all the parent sinks.
Protected Member Functions
virtual void sendMessage (const Message &message)
Log the given message.
void setFormat (const std::string &format)
Set the format of messages that the sink sends.
virtual fmt::dynamic_format_arg_store< fmt::format_context > getExtraFormattingArgs (const Message &messageInfo)
Get the extra named arguments for formatting.
Private Attributes
Level lowestLevel = Level::WARN
std::string logFormat
std::vector< std::shared_ptr< BaseSink > > sinks {}
Detailed Description
A base for any sink in LemLib to implement.
Sinks are LemLib's abstraction for destinations that logged messages can be sent to. They are the backbone of the logging implementation. A sink could send information to anything, to stdout, to a file, or even the UI on the brain screen.
Definition at line 20 of file baseSink.hpp.
Constructor & Destructor Documentation
BaseSink() [1/2]
lemlib::BaseSink::BaseSink () default
BaseSink() [2/2]
lemlib::BaseSink::BaseSink (std::initializer_list< std::shared_ptr< BaseSink > > sinks)
Construct a new combined sink.
Example Usage
lemlib::BaseSink combinedSink({lemlib::telemetrySink(), lemlib::infoSink()});
combinedSink.info("This will be sent to both sinks!");
Parameters
sinks The sinks that will have messages sent to them when
Member Function Documentation
debug()
template<typename... T> void lemlib::BaseSink::debug (fmt::format_string< T... > format, T &&... args) inline
Log a message at the debug level. If this is a combined sink, this operation will apply for all the parent sinks.
Template Parameters
T
Parameters
format
args
Definition at line 102 of file baseSink.hpp.
{
            log(Level::DEBUG, format, std::forward<T>(args)...);
        }
References lemlib::DEBUG, and log().
error()
template<typename... T> void lemlib::BaseSink::error (fmt::format_string< T... > format, T &&... args) inline
Log a message at the error level. If this is a combined sink, this operation will apply for all the parent sinks.
Template Parameters
T
Parameters
format
args
Definition at line 138 of file baseSink.hpp.
{
            log(Level::ERROR, format, std::forward<T>(args)...);
        }
References lemlib::ERROR, and log().
fatal()
template<typename... T> void lemlib::BaseSink::fatal (fmt::format_string< T... > format, T &&... args) inline
Log a message at the fatal level If this is a combined sink, this operation will apply for all the parent sinks.
Template Parameters
T
Parameters
format
args
Definition at line 150 of file baseSink.hpp.
{
            log(Level::FATAL, format, std::forward<T>(args)...);
        }
References lemlib::FATAL, and log().
getExtraFormattingArgs()
virtual fmt::dynamic_format_arg_store< fmt::format_context > lemlib::BaseSink::getExtraFormattingArgs (const Message & messageInfo) protected virtual
Get the extra named arguments for formatting.
Can be overridden to add extra named arguments to the sink's format.
Example Usage
The following code would add a {zero} formatting argument which could be used in setFormat method of this sink.
fmt::dynamic_format_arg_store<fmt::format_context>
ExampleSink::getExtraFormattingArgs(const Message& messageInfo) {
    fmt::dynamic_format_arg_store<fmt::format_context> args;
     args.push_back(fmt::arg("zero", 0);
     return args;
}
Returns
fmt::dynamic_format_arg_store<fmt::format_context>
Referenced by log().
info()
template<typename... T> void lemlib::BaseSink::info (fmt::format_string< T... > format, T &&... args) inline
Log a message at the info level If this is a combined sink, this operation will apply for all the parent sinks.
Template Parameters
T
Parameters
format
args
Definition at line 114 of file baseSink.hpp.
{
            log(Level::INFO, format, std::forward<T>(args)...);
        }
References lemlib::INFO, and log().
log()
template<typename... T> void lemlib::BaseSink::log (Level level, fmt::format_string< T... > format, T &&... args) inline
Log a message at the given level If this is a combined sink, this operation will apply for all the parent sinks.
Template Parameters
T
Parameters
level The level at which to send the message.
format The format that the message will use. Use "{}" as placeholders.
args The values that will be substituted into the placeholders in the format.
Example Usage
sink.log(lemlib::Level::INFO, "{} from the logger!", "Hello");
Definition at line 69 of file baseSink.hpp.
{
            if (!sinks.empty()) {
                for (std::shared_ptr<BaseSink> sink : sinks) { sink->log(level, format, std::forward<T>(args)...); }
                return;
            }
            if (level < lowestLevel) { return; }
            // substitute the user's arguments into the format.
            std::string messageString = fmt::format(format, std::forward<T>(args)...);
            Message message = Message {.level = level, .time = pros::millis()};
            // get the arguments
            fmt::dynamic_format_arg_store<fmt::format_context> formattingArgs = getExtraFormattingArgs(message);
            formattingArgs.push_back(fmt::arg("time", message.time));
            formattingArgs.push_back(fmt::arg("level", message.level));
            formattingArgs.push_back(fmt::arg("message", messageString));
            std::string formattedString = fmt::vformat(logFormat, std::move(formattingArgs));
            message.message = std::move(formattedString);
            sendMessage(std::move(message));
        }
References getExtraFormattingArgs(), lemlib::Message::level, logFormat, lowestLevel, lemlib::Message::message, fmt::v10::dynamic_format_arg_store< Context >::push_back(), sendMessage(), sinks, and lemlib::Message::time.
Referenced by debug(), error(), fatal(), info(), and warn().
sendMessage()
virtual void lemlib::BaseSink::sendMessage (const Message & message) protected virtual
Log the given message.
Parameters
message
Reimplemented in lemlib::InfoSink, and lemlib::TelemetrySink.
Referenced by log().
setFormat()
void lemlib::BaseSink::setFormat (const std::string & format) protected
Set the format of messages that the sink sends.
Parameters
format
Changing the format of the sink changes the way each logged message looks. The following named formatting specifiers can be used:
{time} The time the message was sent in milliseconds since the program started.
{level} The level of the logged message.
{message} The message itself.
Example Usage
infoSink()->setFormat("[LemLib] -- {time} -- {level}: {Message}");
infoSink()->info("hello");
// This will be formatted as:
// "[LemLIb] -- 10 -- INFO:  hello"
setLowestLevel()
void lemlib::BaseSink::setLowestLevel (Level level)
Set the lowest level. If this is a combined sink, this operation will apply for all the parent sinks.
Parameters
level
If messages are logged that are below the lowest level, they will be ignored. The hierarchy of the levels is as follows:
INFO
DEBUG
WARN
ERROR
FATAL
warn()
template<typename... T> void lemlib::BaseSink::warn (fmt::format_string< T... > format, T &&... args) inline
Log a message at the warn level If this is a combined sink, this operation will apply for all the parent sinks.
Template Parameters
T
Parameters
format
args
Definition at line 126 of file baseSink.hpp.
{
            log(Level::WARN, format, std::forward<T>(args)...);
        }
References log(), and lemlib::WARN.
Member Data Documentation
logFormat
std::string lemlib::BaseSink::logFormat private
Definition at line 205 of file baseSink.hpp.
Referenced by log().
lowestLevel
Level lemlib::BaseSink::lowestLevel = Level::WARN private
Definition at line 204 of file baseSink.hpp.
Referenced by log().
sinks
std::vector<std::shared_ptr<BaseSink> > lemlib::BaseSink::sinks {} private
Definition at line 207 of file baseSink.hpp.
{};
Referenced by log().
The documentation for this class was generated from the following file:
include/lemlib/logger/baseSink.hpp