1516b Over Under: Robot::Utility::toggleSubsystemOptions
toggleSubsystemOptions()
void Robot::Utility::toggleSubsystemOptions (Autonomous & auton, Drivetrain & drive, Puncher & punch)
Toggles subsystems, drive mode auton routine, and puncher.
Parameters
Autonomous auton Auton object.
Drivetrain drive Drivetrain object.
Puncher punch Puncher object.
Todo
Figure out a way to send an event to the different objects to toggle between the different subsystems.
Definition at line 10 of file utility.cpp.
{
    // Allows the user to select the autonomous routine, drive control type as well as whether the distance puncher is enabled.
   // The user can select the auton routine by pressing the right buttons on the controller.
   // The user can select the drive control type by pressing the down button on the controller.
   // The user can select the distance puncher by pressing the left button on the controller.
   // The state of each subsystem is displayed on the controller screen.
   while (true)
   {
      auton.AutonSwitcher();
      drive.SwitchDrive();
      punch.PuncherSwitch();
      // Exits the loop if the up button is pressed
      pros::delay(10);
   }
}
References Robot::Autonomous::AutonSwitcher(), Robot::Puncher::PuncherSwitch(), and Robot::Drivetrain::SwitchDrive().
Referenced by toggles().