1516X High Stakes: Robot::status_screen Class Reference
Robot::status_screen Class Reference
The Latch class represents a latching mechanism.
#include <status.h>
Public Member Functions
status_screen ()
Runs latching mechanism.
void status ()
Toggles latch state.
Detailed Description
The Latch class represents a latching mechanism.
Todo
Implement the Robot driving status screen, with graphs of heading, latitude, longitude, etc.
Definition at line 9 of file status.h.
Constructor & Destructor Documentation
status_screen()
status_screen::status_screen ()
Runs latching mechanism.
Definition at line 23 of file status.cpp.
{}
Member Function Documentation
status()
void status_screen::status ()
Toggles latch state.
Create a slider and write its value on a label.
Definition at line 27 of file status.cpp.
{
    lv_obj_t  * calendar = lv_calendar_create(lv_scr_act());
    lv_obj_set_size(calendar, 185, 230);
    lv_obj_align(calendar, LV_ALIGN_CENTER, 0, 27);
    lv_obj_add_event_cb(calendar, slider_event_cb, LV_EVENT_ALL, NULL);
    lv_calendar_set_today_date(calendar, 2021, 02, 23);
    lv_calendar_set_showed_date(calendar, 2021, 02);
    /*Highlight a few days*/
    static lv_calendar_date_t highlighted_days[3];       /*Only its pointer will be saved so should be static*/
    highlighted_days[0].year = 2021;
    highlighted_days[0].month = 02;
    highlighted_days[0].day = 6;
    highlighted_days[1].year = 2021;
    highlighted_days[1].month = 02;
    highlighted_days[1].day = 11;
    highlighted_days[2].year = 2022;
    highlighted_days[2].month = 02;
    highlighted_days[2].day = 22;
    lv_calendar_set_highlighted_dates(calendar, highlighted_days, 3);
#if LV_USE_CALENDAR_HEADER_DROPDOWN
    lv_calendar_header_dropdown_create(calendar);
#elif LV_USE_CALENDAR_HEADER_ARROW
    lv_calendar_header_arrow_create(calendar); /*Align top of the slider*/
#endif
}
References LV_ALIGN_CENTER, LV_EVENT_ALL, lv_obj_add_event_cb(), lv_obj_align(), lv_obj_set_size(), lv_scr_act(), and slider_event_cb().
The documentation for this class was generated from the following files:
include/screen/status.h
src/screen/status.cpp