1516X High Stakes: Robot::Utility Namespace Reference
Robot::Utility Namespace Reference
Contains utility functions for controlling the screen and toggling subsystems.
Functions
void displayLocation ()
Displays current position of the robot.
void displayMotorVel ()
Displays current velocity of the robot.
void display ()
void toggleSubsystemOptions (Autonomous &auton, Drivetrain &drive, Puncher &punch)
Toggles subsystems, drive mode auton routine, and puncher.
Detailed Description
Contains utility functions for controlling the screen and toggling subsystems.
Test
The Utility namespace is a group of unrelated methods that have functions that are important independently.
Function Documentation
display()
void Robot::Utility::display ()
Definition at line 51 of file utility.cpp.
                      {
    while (true) {
        if (!pros::competition::is_disabled()) {
            pros::lcd::clear();
            // if (pros::c::registry_get_plugged_type(15) == 6) {
            Utility::displayLocation();
            // }
            // else {
            //     Utility::displayMotorVel();
            // }
        }
        else {
            ;
        }
        pros::delay(10);
   }
}
References pros::lcd::clear(), displayLocation(), and pros::competition::is_disabled().
displayLocation()
void Robot::Utility::displayLocation ()
Displays current position of the robot.
Definition at line 42 of file utility.cpp.
{
    using namespace Robot::Globals;
    lemlib::Pose pose = chassis.getPose(); // get the current position of the robot
    pros::lcd::print(0, "x: %f", pose.x); // print the x position
    pros::lcd::print(1, "y: %f", pose.y); // pri∟nt the y position
    pros::lcd::print(2, "heading: %f", pose.theta); // print the heading
}
References Robot::Globals::chassis, lemlib::Chassis::getPose(), pros::lcd::print(), lemlib::Pose::theta, lemlib::Pose::x, and lemlib::Pose::y.
Referenced by display().
displayMotorVel()
void Robot::Utility::displayMotorVel ()
Displays current velocity of the robot.
Definition at line 30 of file utility.cpp.
{
    // std::vector<std::int32_t> currents = drive_.get_current_draws();// get the current position of the robot
    pros::lcd::print(0, "Motor velocity draw");
    pros::lcd::print(1, "motor 2 vel: %lf", LeftFront.get_actual_velocity());
    pros::lcd::print(2, "motor 2 vel: %lf", RightFront.get_actual_velocity());
    pros::lcd::print(3, "motor 3 vel: %lf", LeftMid.get_actual_velocity());
    pros::lcd::print(4, "motor 4 vel: %lf", RightMid.get_actual_velocity());
    pros::lcd::print(5, "motor 5 vel: %lf", LeftBack.get_actual_velocity());
    pros::lcd::print(6, "motor 6 vel: %lf", RightBack.get_actual_velocity()); // print the x position// print the heading
}
References Robot::Globals::LeftBack, Robot::Globals::LeftFront, Robot::Globals::LeftMid, pros::lcd::print(), Robot::Globals::RightBack, Robot::Globals::RightFront, and Robot::Globals::RightMid.
toggleSubsystemOptions()
void Robot::Utility::toggleSubsystemOptions (Autonomous & auton, Drivetrain & drive, Puncher & punch)
Toggles subsystems, drive mode auton routine, and puncher.
Parameters
Autonomous auton Auton object.
Drivetrain drive Drivetrain object.
Puncher punch Puncher object.
Todo
Figure out a way to send an event to the different objects to toggle between the different subsystems.
Definition at line 11 of file utility.cpp.
{
    // Allows the user to select the autonomous routine, drive control type as well as whether the distance puncher is enabled.
   // The user can select the auton routine by pressing the right buttons on the controller.
   // The user can select the drive control type by pressing the down button on the controller.
   // The user can select the distance puncher by pressing the left button on the controller.
   // The state of each subsystem is displayed on the controller screen.
   while (true)
   {
      punch.PuncherSwitch();
        auton.AutonSwitcher();
      drive.SwitchDrive();
      // Exits the loop if the up button is pressed
      pros::delay(50);
   }
}
References Robot::Autonomous::AutonSwitcher(), Robot::Puncher::PuncherSwitch(), and Robot::Drivetrain::SwitchDrive().