1516X High Stakes: fmt::v10::basic_memory_buffer< T, SIZE, Allocator > Class Template Reference
fmt::v10::basic_memory_buffer< T, SIZE, Allocator > Class Template Reference final
#include <format.h>
Public Types
using value_type = T
using const_reference = const T&
Public Types inherited from fmt::v10::detail::buffer< T >
using value_type = T
using const_reference = const T&
Public Member Functions
basic_memory_buffer (const Allocator &alloc=Allocator())
~basic_memory_buffer ()
basic_memory_buffer (basic_memory_buffer &&other) noexcept
auto operator= (basic_memory_buffer &&other) noexcept -> basic_memory_buffer &
auto get_allocator () const -> Allocator
void resize (size_t count)
void reserve (size_t new_capacity)
template<typename ContiguousRange >
void append (const ContiguousRange &range)
Public Member Functions inherited from fmt::v10::detail::buffer< T >
buffer (const buffer &)=delete
void operator= (const buffer &)=delete
auto begin () noexcept -> T *
auto end () noexcept -> T *
auto begin () const noexcept -> const T *
auto end () const noexcept -> const T *
constexpr auto size () const noexcept -> size_t
constexpr auto capacity () const noexcept -> size_t
auto data () noexcept -> T *
auto data () const noexcept -> const T *
void clear ()
void try_resize (size_t count)
void try_reserve (size_t new_capacity)
void push_back (const T &value)
template<typename U >
void append (const U *begin, const U *end)
template<typename Idx >
auto operator[] (Idx index) -> T &
template<typename Idx >
auto operator[] (Idx index) const -> const T &
Protected Member Functions
void grow (size_t size) override
Protected Member Functions inherited from fmt::v10::detail::buffer< T >
buffer (size_t sz) noexcept
buffer (T *p=nullptr, size_t sz=0, size_t cap=0) noexcept
~buffer ()=default
buffer (buffer &&)=default
void set (T *buf_data, size_t buf_capacity) noexcept
Private Member Functions
void deallocate ()
void move (basic_memory_buffer &other)
Private Attributes
T store_ [SIZE]
Allocator alloc_
Detailed Description
template<typename T, size_t SIZE = inline_buffer_size, typename Allocator = std::allocator<T>>
class fmt::v10::basic_memory_buffer< T, SIZE, Allocator >
\rst A dynamically growing memory buffer for trivially copyable/constructible types with the first SIZE elements stored in the object itself.
You can use the memory_buffer type alias for char instead.
Example**::
auto out = fmt::memory_buffer(); format_to(std::back_inserter(out), "The answer is {}.", 42);
This will append the following output to the out object:
.. code-block:: none
The answer is 42.
The output can be converted to an std::string with to_string(out). \endrst
Definition at line 873 of file format.h.
Member Typedef Documentation
const_reference
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = std::allocator<T>> using fmt::v10::basic_memory_buffer< T, SIZE, Allocator >::const_reference = const T&
Definition at line 907 of file format.h.
value_type
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = std::allocator<T>> using fmt::v10::basic_memory_buffer< T, SIZE, Allocator >::value_type = T
Definition at line 906 of file format.h.
Constructor & Destructor Documentation
basic_memory_buffer() [1/2]
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = std::allocator<T>> fmt::v10::basic_memory_buffer< T, SIZE, Allocator >::basic_memory_buffer (const Allocator & alloc = Allocator()) inline explicit
Definition at line 909 of file format.h.
                                                                                           : alloc_(alloc) {
            this->set(store_, SIZE);
            if (detail::is_constant_evaluated()) detail::fill_n(store_, SIZE, T());
        }
~basic_memory_buffer()
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = std::allocator<T>> fmt::v10::basic_memory_buffer< T, SIZE, Allocator >::~basic_memory_buffer () inline
Definition at line 914 of file format.h.
{ deallocate(); }
basic_memory_buffer() [2/2]
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = std::allocator<T>> fmt::v10::basic_memory_buffer< T, SIZE, Allocator >::basic_memory_buffer (basic_memory_buffer< T, SIZE, Allocator > && other) inline noexcept
\rst Constructs a :class:fmt::basic_memory_buffer object moving the content of the other object to it. \endrst
Definition at line 940 of file format.h.
{ move(other); }
Member Function Documentation
append()
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = std::allocator<T>> template<typename ContiguousRange > void fmt::v10::basic_memory_buffer< T, SIZE, Allocator >::append (const ContiguousRange & range) inline
Definition at line 969 of file format.h.
{
            append(range.data(), range.data() + range.size());
        }
deallocate()
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = std::allocator<T>> void fmt::v10::basic_memory_buffer< T, SIZE, Allocator >::deallocate () inline private
Definition at line 881 of file format.h.
{
            T* data = this->data();
            if (data != store_) alloc_.deallocate(data, this->capacity());
        }
get_allocator()
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = std::allocator<T>> auto fmt::v10::basic_memory_buffer< T, SIZE, Allocator >::get_allocator () const -> Allocator inline
Definition at line 955 of file format.h.
{ return alloc_; }
grow()
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = std::allocator<T>> void fmt::v10::basic_memory_buffer< T, SIZE, Allocator >::grow (size_t capacity) inline override protected virtual
Increases the buffer capacity to hold at least capacity elements.
Implements fmt::v10::detail::buffer< T >.
Definition at line 886 of file format.h.
{
            detail::abort_fuzzing_if(size > 5000);
            const size_t max_size = std::allocator_traits<Allocator>::max_size(alloc_);
            size_t old_capacity = this->capacity();
            size_t new_capacity = old_capacity + old_capacity / 2;
            if (size > new_capacity) new_capacity = size;
            else if (new_capacity > max_size) new_capacity = size > max_size ? size : max_size;
            T* old_data = this->data();
            T* new_data = std::allocator_traits<Allocator>::allocate(alloc_, new_capacity);
            // Suppress a bogus -Wstringop-overflow in gcc 13.1 (#3481).
            detail::assume(this->size() <= new_capacity);
            // The following code doesn't throw, so the raw pointer above doesn't leak.
            std::uninitialized_copy_n(old_data, this->size(), new_data);
            this->set(new_data, new_capacity);
            // deallocate must not throw according to the standard, but even if it does,
            // the buffer already uses the new storage and will deallocate it in
            // destructor.
            if (old_data != store_) alloc_.deallocate(old_data, old_capacity);
        }
move()
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = std::allocator<T>> void fmt::v10::basic_memory_buffer< T, SIZE, Allocator >::move (basic_memory_buffer< T, SIZE, Allocator > & other) inline private
Definition at line 917 of file format.h.
{
            alloc_ = std::move(other.alloc_);
            T* data = other.data();
            size_t size = other.size(), capacity = other.capacity();
            if (data == other.store_) {
                this->set(store_, capacity);
                detail::copy_str<T>(other.store_, other.store_ + size, store_);
            } else {
                this->set(data, capacity);
                // Set pointer to the inline array so that delete is not called
                // when deallocating.
                other.set(other.store_, 0);
                other.clear();
            }
            this->resize(size);
        }
References fmt::v10::basic_memory_buffer< T, SIZE, Allocator >::alloc_, fmt::v10::detail::buffer< T >::capacity(), fmt::v10::detail::buffer< T >::clear(), fmt::v10::detail::buffer< T >::data(), fmt::v10::detail::buffer< T >::set(), fmt::v10::detail::buffer< T >::size(), and fmt::v10::basic_memory_buffer< T, SIZE, Allocator >::store_.
operator=()
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = std::allocator<T>> auto fmt::v10::basic_memory_buffer< T, SIZE, Allocator >::operator= (basic_memory_buffer< T, SIZE, Allocator > && other) -> basic_memory_buffer& inline noexcept
\rst Moves the content of the other basic_memory_buffer object to this one. \endrst
Definition at line 947 of file format.h.
{
            FMT_ASSERT(this != &other, "");
            deallocate();
            move(other);
            return *this;
        }
References FMT_ASSERT.
reserve()
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = std::allocator<T>> void fmt::v10::basic_memory_buffer< T, SIZE, Allocator >::reserve (size_t new_capacity) inline
Increases the buffer capacity to new_capacity.
Definition at line 964 of file format.h.
{ this->try_reserve(new_capacity); }
resize()
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = std::allocator<T>> void fmt::v10::basic_memory_buffer< T, SIZE, Allocator >::resize (size_t count) inline
Resizes the buffer to contain count elements. If T is a POD type new elements may not be initialized.
Definition at line 961 of file format.h.
{ this->try_resize(count); }
Referenced by fmt::v10::detail::bigint::align(), fmt::v10::detail::bigint::assign(), fmt::v10::detail::bigint::assign(), fmt::v10::detail::bigint::remove_leading_zeros(), and fmt::v10::detail::bigint::square().
Member Data Documentation
alloc_
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = std::allocator<T>> Allocator fmt::v10::basic_memory_buffer< T, SIZE, Allocator >::alloc_ private
Definition at line 878 of file format.h.
Referenced by fmt::v10::basic_memory_buffer< T, SIZE, Allocator >::move().
store_
template<typename T , size_t SIZE = inline_buffer_size, typename Allocator = std::allocator<T>> T fmt::v10::basic_memory_buffer< T, SIZE, Allocator >::store_[SIZE] private
Definition at line 875 of file format.h.
Referenced by fmt::v10::basic_memory_buffer< T, SIZE, Allocator >::move().
The documentation for this class was generated from the following file:
include/fmt/format.h