1516X High Stakes: include/liblvgl/core/lv_obj_style_gen.h File Reference
lv_obj_style_gen.h File Reference
Functions
static lv_coord_t lv_obj_get_style_width (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_min_width (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_max_width (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_height (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_min_height (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_max_height (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_x (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_y (const struct _lv_obj_t *obj, uint32_t part)
static lv_align_t lv_obj_get_style_align (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_transform_width (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_transform_height (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_translate_x (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_translate_y (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_transform_zoom (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_transform_angle (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_transform_pivot_x (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_transform_pivot_y (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_pad_top (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_pad_bottom (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_pad_left (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_pad_right (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_pad_row (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_pad_column (const struct _lv_obj_t *obj, uint32_t part)
static lv_color_t lv_obj_get_style_bg_color (const struct _lv_obj_t *obj, uint32_t part)
static lv_color_t lv_obj_get_style_bg_color_filtered (const struct _lv_obj_t *obj, uint32_t part)
static lv_opa_t lv_obj_get_style_bg_opa (const struct _lv_obj_t *obj, uint32_t part)
static lv_color_t lv_obj_get_style_bg_grad_color (const struct _lv_obj_t *obj, uint32_t part)
static lv_color_t lv_obj_get_style_bg_grad_color_filtered (const struct _lv_obj_t *obj, uint32_t part)
static lv_grad_dir_t lv_obj_get_style_bg_grad_dir (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_bg_main_stop (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_bg_grad_stop (const struct _lv_obj_t *obj, uint32_t part)
static const lv_grad_dsc_t * lv_obj_get_style_bg_grad (const struct _lv_obj_t *obj, uint32_t part)
static lv_dither_mode_t lv_obj_get_style_bg_dither_mode (const struct _lv_obj_t *obj, uint32_t part)
static const void * lv_obj_get_style_bg_img_src (const struct _lv_obj_t *obj, uint32_t part)
static lv_opa_t lv_obj_get_style_bg_img_opa (const struct _lv_obj_t *obj, uint32_t part)
static lv_color_t lv_obj_get_style_bg_img_recolor (const struct _lv_obj_t *obj, uint32_t part)
static lv_color_t lv_obj_get_style_bg_img_recolor_filtered (const struct _lv_obj_t *obj, uint32_t part)
static lv_opa_t lv_obj_get_style_bg_img_recolor_opa (const struct _lv_obj_t *obj, uint32_t part)
static bool lv_obj_get_style_bg_img_tiled (const struct _lv_obj_t *obj, uint32_t part)
static lv_color_t lv_obj_get_style_border_color (const struct _lv_obj_t *obj, uint32_t part)
static lv_color_t lv_obj_get_style_border_color_filtered (const struct _lv_obj_t *obj, uint32_t part)
static lv_opa_t lv_obj_get_style_border_opa (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_border_width (const struct _lv_obj_t *obj, uint32_t part)
static lv_border_side_t lv_obj_get_style_border_side (const struct _lv_obj_t *obj, uint32_t part)
static bool lv_obj_get_style_border_post (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_outline_width (const struct _lv_obj_t *obj, uint32_t part)
static lv_color_t lv_obj_get_style_outline_color (const struct _lv_obj_t *obj, uint32_t part)
static lv_color_t lv_obj_get_style_outline_color_filtered (const struct _lv_obj_t *obj, uint32_t part)
static lv_opa_t lv_obj_get_style_outline_opa (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_outline_pad (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_shadow_width (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_shadow_ofs_x (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_shadow_ofs_y (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_shadow_spread (const struct _lv_obj_t *obj, uint32_t part)
static lv_color_t lv_obj_get_style_shadow_color (const struct _lv_obj_t *obj, uint32_t part)
static lv_color_t lv_obj_get_style_shadow_color_filtered (const struct _lv_obj_t *obj, uint32_t part)
static lv_opa_t lv_obj_get_style_shadow_opa (const struct _lv_obj_t *obj, uint32_t part)
static lv_opa_t lv_obj_get_style_img_opa (const struct _lv_obj_t *obj, uint32_t part)
static lv_color_t lv_obj_get_style_img_recolor (const struct _lv_obj_t *obj, uint32_t part)
static lv_color_t lv_obj_get_style_img_recolor_filtered (const struct _lv_obj_t *obj, uint32_t part)
static lv_opa_t lv_obj_get_style_img_recolor_opa (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_line_width (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_line_dash_width (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_line_dash_gap (const struct _lv_obj_t *obj, uint32_t part)
static bool lv_obj_get_style_line_rounded (const struct _lv_obj_t *obj, uint32_t part)
static lv_color_t lv_obj_get_style_line_color (const struct _lv_obj_t *obj, uint32_t part)
static lv_color_t lv_obj_get_style_line_color_filtered (const struct _lv_obj_t *obj, uint32_t part)
static lv_opa_t lv_obj_get_style_line_opa (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_arc_width (const struct _lv_obj_t *obj, uint32_t part)
static bool lv_obj_get_style_arc_rounded (const struct _lv_obj_t *obj, uint32_t part)
static lv_color_t lv_obj_get_style_arc_color (const struct _lv_obj_t *obj, uint32_t part)
static lv_color_t lv_obj_get_style_arc_color_filtered (const struct _lv_obj_t *obj, uint32_t part)
static lv_opa_t lv_obj_get_style_arc_opa (const struct _lv_obj_t *obj, uint32_t part)
static const void * lv_obj_get_style_arc_img_src (const struct _lv_obj_t *obj, uint32_t part)
static lv_color_t lv_obj_get_style_text_color (const struct _lv_obj_t *obj, uint32_t part)
static lv_color_t lv_obj_get_style_text_color_filtered (const struct _lv_obj_t *obj, uint32_t part)
static lv_opa_t lv_obj_get_style_text_opa (const struct _lv_obj_t *obj, uint32_t part)
static const lv_font_t * lv_obj_get_style_text_font (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_text_letter_space (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_text_line_space (const struct _lv_obj_t *obj, uint32_t part)
static lv_text_decor_t lv_obj_get_style_text_decor (const struct _lv_obj_t *obj, uint32_t part)
static lv_text_align_t lv_obj_get_style_text_align (const struct _lv_obj_t *obj, uint32_t part)
static lv_coord_t lv_obj_get_style_radius (const struct _lv_obj_t *obj, uint32_t part)
static bool lv_obj_get_style_clip_corner (const struct _lv_obj_t *obj, uint32_t part)
static lv_opa_t lv_obj_get_style_opa (const struct _lv_obj_t *obj, uint32_t part)
static const lv_color_filter_dsc_t * lv_obj_get_style_color_filter_dsc (const struct _lv_obj_t *obj, uint32_t part)
static lv_opa_t lv_obj_get_style_color_filter_opa (const struct _lv_obj_t *obj, uint32_t part)
static const lv_anim_t * lv_obj_get_style_anim (const struct _lv_obj_t *obj, uint32_t part)
static uint32_t lv_obj_get_style_anim_time (const struct _lv_obj_t *obj, uint32_t part)
static uint32_t lv_obj_get_style_anim_speed (const struct _lv_obj_t *obj, uint32_t part)
static const lv_style_transition_dsc_t * lv_obj_get_style_transition (const struct _lv_obj_t *obj, uint32_t part)
static lv_blend_mode_t lv_obj_get_style_blend_mode (const struct _lv_obj_t *obj, uint32_t part)
static uint16_t lv_obj_get_style_layout (const struct _lv_obj_t *obj, uint32_t part)
static lv_base_dir_t lv_obj_get_style_base_dir (const struct _lv_obj_t *obj, uint32_t part)
void lv_obj_set_style_width (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_min_width (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_max_width (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_height (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_min_height (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_max_height (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_x (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_y (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_align (struct _lv_obj_t *obj, lv_align_t value, lv_style_selector_t selector)
void lv_obj_set_style_transform_width (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_transform_height (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_translate_x (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_translate_y (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_transform_zoom (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_transform_angle (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_transform_pivot_x (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_transform_pivot_y (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_pad_top (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_pad_bottom (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_pad_left (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_pad_right (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_pad_row (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_pad_column (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_bg_color (struct _lv_obj_t *obj, lv_color_t value, lv_style_selector_t selector)
void lv_obj_set_style_bg_opa (struct _lv_obj_t *obj, lv_opa_t value, lv_style_selector_t selector)
void lv_obj_set_style_bg_grad_color (struct _lv_obj_t *obj, lv_color_t value, lv_style_selector_t selector)
void lv_obj_set_style_bg_grad_dir (struct _lv_obj_t *obj, lv_grad_dir_t value, lv_style_selector_t selector)
void lv_obj_set_style_bg_main_stop (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_bg_grad_stop (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_bg_grad (struct _lv_obj_t *obj, const lv_grad_dsc_t *value, lv_style_selector_t selector)
void lv_obj_set_style_bg_dither_mode (struct _lv_obj_t *obj, lv_dither_mode_t value, lv_style_selector_t selector)
void lv_obj_set_style_bg_img_src (struct _lv_obj_t *obj, const void *value, lv_style_selector_t selector)
void lv_obj_set_style_bg_img_opa (struct _lv_obj_t *obj, lv_opa_t value, lv_style_selector_t selector)
void lv_obj_set_style_bg_img_recolor (struct _lv_obj_t *obj, lv_color_t value, lv_style_selector_t selector)
void lv_obj_set_style_bg_img_recolor_opa (struct _lv_obj_t *obj, lv_opa_t value, lv_style_selector_t selector)
void lv_obj_set_style_bg_img_tiled (struct _lv_obj_t *obj, bool value, lv_style_selector_t selector)
void lv_obj_set_style_border_color (struct _lv_obj_t *obj, lv_color_t value, lv_style_selector_t selector)
void lv_obj_set_style_border_opa (struct _lv_obj_t *obj, lv_opa_t value, lv_style_selector_t selector)
void lv_obj_set_style_border_width (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_border_side (struct _lv_obj_t *obj, lv_border_side_t value, lv_style_selector_t selector)
void lv_obj_set_style_border_post (struct _lv_obj_t *obj, bool value, lv_style_selector_t selector)
void lv_obj_set_style_outline_width (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_outline_color (struct _lv_obj_t *obj, lv_color_t value, lv_style_selector_t selector)
void lv_obj_set_style_outline_opa (struct _lv_obj_t *obj, lv_opa_t value, lv_style_selector_t selector)
void lv_obj_set_style_outline_pad (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_shadow_width (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_shadow_ofs_x (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_shadow_ofs_y (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_shadow_spread (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_shadow_color (struct _lv_obj_t *obj, lv_color_t value, lv_style_selector_t selector)
void lv_obj_set_style_shadow_opa (struct _lv_obj_t *obj, lv_opa_t value, lv_style_selector_t selector)
void lv_obj_set_style_img_opa (struct _lv_obj_t *obj, lv_opa_t value, lv_style_selector_t selector)
void lv_obj_set_style_img_recolor (struct _lv_obj_t *obj, lv_color_t value, lv_style_selector_t selector)
void lv_obj_set_style_img_recolor_opa (struct _lv_obj_t *obj, lv_opa_t value, lv_style_selector_t selector)
void lv_obj_set_style_line_width (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_line_dash_width (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_line_dash_gap (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_line_rounded (struct _lv_obj_t *obj, bool value, lv_style_selector_t selector)
void lv_obj_set_style_line_color (struct _lv_obj_t *obj, lv_color_t value, lv_style_selector_t selector)
void lv_obj_set_style_line_opa (struct _lv_obj_t *obj, lv_opa_t value, lv_style_selector_t selector)
void lv_obj_set_style_arc_width (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_arc_rounded (struct _lv_obj_t *obj, bool value, lv_style_selector_t selector)
void lv_obj_set_style_arc_color (struct _lv_obj_t *obj, lv_color_t value, lv_style_selector_t selector)
void lv_obj_set_style_arc_opa (struct _lv_obj_t *obj, lv_opa_t value, lv_style_selector_t selector)
void lv_obj_set_style_arc_img_src (struct _lv_obj_t *obj, const void *value, lv_style_selector_t selector)
void lv_obj_set_style_text_color (struct _lv_obj_t *obj, lv_color_t value, lv_style_selector_t selector)
void lv_obj_set_style_text_opa (struct _lv_obj_t *obj, lv_opa_t value, lv_style_selector_t selector)
void lv_obj_set_style_text_font (struct _lv_obj_t *obj, const lv_font_t *value, lv_style_selector_t selector)
void lv_obj_set_style_text_letter_space (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_text_line_space (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_text_decor (struct _lv_obj_t *obj, lv_text_decor_t value, lv_style_selector_t selector)
void lv_obj_set_style_text_align (struct _lv_obj_t *obj, lv_text_align_t value, lv_style_selector_t selector)
void lv_obj_set_style_radius (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
void lv_obj_set_style_clip_corner (struct _lv_obj_t *obj, bool value, lv_style_selector_t selector)
void lv_obj_set_style_opa (struct _lv_obj_t *obj, lv_opa_t value, lv_style_selector_t selector)
void lv_obj_set_style_color_filter_dsc (struct _lv_obj_t *obj, const lv_color_filter_dsc_t *value, lv_style_selector_t selector)
void lv_obj_set_style_color_filter_opa (struct _lv_obj_t *obj, lv_opa_t value, lv_style_selector_t selector)
void lv_obj_set_style_anim (struct _lv_obj_t *obj, const lv_anim_t *value, lv_style_selector_t selector)
void lv_obj_set_style_anim_time (struct _lv_obj_t *obj, uint32_t value, lv_style_selector_t selector)
void lv_obj_set_style_anim_speed (struct _lv_obj_t *obj, uint32_t value, lv_style_selector_t selector)
void lv_obj_set_style_transition (struct _lv_obj_t *obj, const lv_style_transition_dsc_t *value, lv_style_selector_t selector)
void lv_obj_set_style_blend_mode (struct _lv_obj_t *obj, lv_blend_mode_t value, lv_style_selector_t selector)
void lv_obj_set_style_layout (struct _lv_obj_t *obj, uint16_t value, lv_style_selector_t selector)
void lv_obj_set_style_base_dir (struct _lv_obj_t *obj, lv_base_dir_t value, lv_style_selector_t selector)
Function Documentation
lv_obj_get_style_align()
static lv_align_t lv_obj_get_style_align (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 49 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_ALIGN);
    return (lv_align_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_ALIGN, and lv_style_value_t::num.
lv_obj_get_style_anim()
static const lv_anim_t * lv_obj_get_style_anim (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 523 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_ANIM);
    return (const lv_anim_t *)v.ptr;
}
References lv_obj_get_style_prop(), LV_STYLE_ANIM, and lv_style_value_t::ptr.
lv_obj_get_style_anim_speed()
static uint32_t lv_obj_get_style_anim_speed (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 535 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_ANIM_SPEED);
    return (uint32_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_ANIM_SPEED, and lv_style_value_t::num.
lv_obj_get_style_anim_time()
static uint32_t lv_obj_get_style_anim_time (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 529 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_ANIM_TIME);
    return (uint32_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_ANIM_TIME, and lv_style_value_t::num.
lv_obj_get_style_arc_color()
static lv_color_t lv_obj_get_style_arc_color (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 421 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_ARC_COLOR);
    return v.color;
}
References lv_style_value_t::color, lv_obj_get_style_prop(), and LV_STYLE_ARC_COLOR.
lv_obj_get_style_arc_color_filtered()
static lv_color_t lv_obj_get_style_arc_color_filtered (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 427 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = _lv_obj_style_apply_color_filter(obj, part, lv_obj_get_style_prop(obj, part, LV_STYLE_ARC_COLOR));
    return v.color;
}
References _lv_obj_style_apply_color_filter(), lv_style_value_t::color, lv_obj_get_style_prop(), and LV_STYLE_ARC_COLOR.
lv_obj_get_style_arc_img_src()
static const void * lv_obj_get_style_arc_img_src (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 439 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_ARC_IMG_SRC);
    return (const void *)v.ptr;
}
References lv_obj_get_style_prop(), LV_STYLE_ARC_IMG_SRC, and lv_style_value_t::ptr.
lv_obj_get_style_arc_opa()
static lv_opa_t lv_obj_get_style_arc_opa (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 433 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_ARC_OPA);
    return (lv_opa_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_ARC_OPA, and lv_style_value_t::num.
lv_obj_get_style_arc_rounded()
static bool lv_obj_get_style_arc_rounded (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 415 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_ARC_ROUNDED);
    return (bool)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_ARC_ROUNDED, and lv_style_value_t::num.
lv_obj_get_style_arc_width()
static lv_coord_t lv_obj_get_style_arc_width (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 409 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_ARC_WIDTH);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_ARC_WIDTH, and lv_style_value_t::num.
lv_obj_get_style_base_dir()
static lv_base_dir_t lv_obj_get_style_base_dir (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 559 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_BASE_DIR);
    return (lv_base_dir_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_BASE_DIR, and lv_style_value_t::num.
lv_obj_get_style_bg_color()
static lv_color_t lv_obj_get_style_bg_color (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 139 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_BG_COLOR);
    return v.color;
}
References lv_style_value_t::color, lv_obj_get_style_prop(), and LV_STYLE_BG_COLOR.
lv_obj_get_style_bg_color_filtered()
static lv_color_t lv_obj_get_style_bg_color_filtered (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 145 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = _lv_obj_style_apply_color_filter(obj, part, lv_obj_get_style_prop(obj, part, LV_STYLE_BG_COLOR));
    return v.color;
}
References _lv_obj_style_apply_color_filter(), lv_style_value_t::color, lv_obj_get_style_prop(), and LV_STYLE_BG_COLOR.
lv_obj_get_style_bg_dither_mode()
static lv_dither_mode_t lv_obj_get_style_bg_dither_mode (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 193 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_BG_DITHER_MODE);
    return (lv_dither_mode_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_BG_DITHER_MODE, and lv_style_value_t::num.
lv_obj_get_style_bg_grad()
static const lv_grad_dsc_t * lv_obj_get_style_bg_grad (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 187 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_BG_GRAD);
    return (const lv_grad_dsc_t *)v.ptr;
}
References lv_obj_get_style_prop(), LV_STYLE_BG_GRAD, and lv_style_value_t::ptr.
lv_obj_get_style_bg_grad_color()
static lv_color_t lv_obj_get_style_bg_grad_color (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 157 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_BG_GRAD_COLOR);
    return v.color;
}
References lv_style_value_t::color, lv_obj_get_style_prop(), and LV_STYLE_BG_GRAD_COLOR.
lv_obj_get_style_bg_grad_color_filtered()
static lv_color_t lv_obj_get_style_bg_grad_color_filtered (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 163 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = _lv_obj_style_apply_color_filter(obj, part, lv_obj_get_style_prop(obj, part, LV_STYLE_BG_GRAD_COLOR));
    return v.color;
}
References _lv_obj_style_apply_color_filter(), lv_style_value_t::color, lv_obj_get_style_prop(), and LV_STYLE_BG_GRAD_COLOR.
lv_obj_get_style_bg_grad_dir()
static lv_grad_dir_t lv_obj_get_style_bg_grad_dir (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 169 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_BG_GRAD_DIR);
    return (lv_grad_dir_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_BG_GRAD_DIR, and lv_style_value_t::num.
lv_obj_get_style_bg_grad_stop()
static lv_coord_t lv_obj_get_style_bg_grad_stop (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 181 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_BG_GRAD_STOP);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_BG_GRAD_STOP, and lv_style_value_t::num.
lv_obj_get_style_bg_img_opa()
static lv_opa_t lv_obj_get_style_bg_img_opa (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 205 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_BG_IMG_OPA);
    return (lv_opa_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_BG_IMG_OPA, and lv_style_value_t::num.
lv_obj_get_style_bg_img_recolor()
static lv_color_t lv_obj_get_style_bg_img_recolor (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 211 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_BG_IMG_RECOLOR);
    return v.color;
}
References lv_style_value_t::color, lv_obj_get_style_prop(), and LV_STYLE_BG_IMG_RECOLOR.
lv_obj_get_style_bg_img_recolor_filtered()
static lv_color_t lv_obj_get_style_bg_img_recolor_filtered (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 217 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = _lv_obj_style_apply_color_filter(obj, part, lv_obj_get_style_prop(obj, part, LV_STYLE_BG_IMG_RECOLOR));
    return v.color;
}
References _lv_obj_style_apply_color_filter(), lv_style_value_t::color, lv_obj_get_style_prop(), and LV_STYLE_BG_IMG_RECOLOR.
lv_obj_get_style_bg_img_recolor_opa()
static lv_opa_t lv_obj_get_style_bg_img_recolor_opa (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 223 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_BG_IMG_RECOLOR_OPA);
    return (lv_opa_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_BG_IMG_RECOLOR_OPA, and lv_style_value_t::num.
lv_obj_get_style_bg_img_src()
static const void * lv_obj_get_style_bg_img_src (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 199 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_BG_IMG_SRC);
    return (const void *)v.ptr;
}
References lv_obj_get_style_prop(), LV_STYLE_BG_IMG_SRC, and lv_style_value_t::ptr.
lv_obj_get_style_bg_img_tiled()
static bool lv_obj_get_style_bg_img_tiled (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 229 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_BG_IMG_TILED);
    return (bool)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_BG_IMG_TILED, and lv_style_value_t::num.
lv_obj_get_style_bg_main_stop()
static lv_coord_t lv_obj_get_style_bg_main_stop (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 175 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_BG_MAIN_STOP);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_BG_MAIN_STOP, and lv_style_value_t::num.
lv_obj_get_style_bg_opa()
static lv_opa_t lv_obj_get_style_bg_opa (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 151 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_BG_OPA);
    return (lv_opa_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_BG_OPA, and lv_style_value_t::num.
lv_obj_get_style_blend_mode()
static lv_blend_mode_t lv_obj_get_style_blend_mode (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 547 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_BLEND_MODE);
    return (lv_blend_mode_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_BLEND_MODE, and lv_style_value_t::num.
lv_obj_get_style_border_color()
static lv_color_t lv_obj_get_style_border_color (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 235 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_BORDER_COLOR);
    return v.color;
}
References lv_style_value_t::color, lv_obj_get_style_prop(), and LV_STYLE_BORDER_COLOR.
lv_obj_get_style_border_color_filtered()
static lv_color_t lv_obj_get_style_border_color_filtered (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 241 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = _lv_obj_style_apply_color_filter(obj, part, lv_obj_get_style_prop(obj, part, LV_STYLE_BORDER_COLOR));
    return v.color;
}
References _lv_obj_style_apply_color_filter(), lv_style_value_t::color, lv_obj_get_style_prop(), and LV_STYLE_BORDER_COLOR.
lv_obj_get_style_border_opa()
static lv_opa_t lv_obj_get_style_border_opa (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 247 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_BORDER_OPA);
    return (lv_opa_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_BORDER_OPA, and lv_style_value_t::num.
lv_obj_get_style_border_post()
static bool lv_obj_get_style_border_post (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 265 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_BORDER_POST);
    return (bool)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_BORDER_POST, and lv_style_value_t::num.
lv_obj_get_style_border_side()
static lv_border_side_t lv_obj_get_style_border_side (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 259 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_BORDER_SIDE);
    return (lv_border_side_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_BORDER_SIDE, and lv_style_value_t::num.
lv_obj_get_style_border_width()
static lv_coord_t lv_obj_get_style_border_width (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 253 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_BORDER_WIDTH);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_BORDER_WIDTH, and lv_style_value_t::num.
lv_obj_get_style_clip_corner()
static bool lv_obj_get_style_clip_corner (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 499 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_CLIP_CORNER);
    return (bool)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_CLIP_CORNER, and lv_style_value_t::num.
lv_obj_get_style_color_filter_dsc()
static const lv_color_filter_dsc_t * lv_obj_get_style_color_filter_dsc (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 511 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_COLOR_FILTER_DSC);
    return (const lv_color_filter_dsc_t *)v.ptr;
}
References lv_obj_get_style_prop(), LV_STYLE_COLOR_FILTER_DSC, and lv_style_value_t::ptr.
lv_obj_get_style_color_filter_opa()
static lv_opa_t lv_obj_get_style_color_filter_opa (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 517 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_COLOR_FILTER_OPA);
    return (lv_opa_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_COLOR_FILTER_OPA, and lv_style_value_t::num.
lv_obj_get_style_height()
static lv_coord_t lv_obj_get_style_height (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 19 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_HEIGHT);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_HEIGHT, and lv_style_value_t::num.
lv_obj_get_style_img_opa()
static lv_opa_t lv_obj_get_style_img_opa (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 343 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_IMG_OPA);
    return (lv_opa_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_IMG_OPA, and lv_style_value_t::num.
lv_obj_get_style_img_recolor()
static lv_color_t lv_obj_get_style_img_recolor (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 349 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_IMG_RECOLOR);
    return v.color;
}
References lv_style_value_t::color, lv_obj_get_style_prop(), and LV_STYLE_IMG_RECOLOR.
lv_obj_get_style_img_recolor_filtered()
static lv_color_t lv_obj_get_style_img_recolor_filtered (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 355 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = _lv_obj_style_apply_color_filter(obj, part, lv_obj_get_style_prop(obj, part, LV_STYLE_IMG_RECOLOR));
    return v.color;
}
References _lv_obj_style_apply_color_filter(), lv_style_value_t::color, lv_obj_get_style_prop(), and LV_STYLE_IMG_RECOLOR.
lv_obj_get_style_img_recolor_opa()
static lv_opa_t lv_obj_get_style_img_recolor_opa (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 361 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_IMG_RECOLOR_OPA);
    return (lv_opa_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_IMG_RECOLOR_OPA, and lv_style_value_t::num.
lv_obj_get_style_layout()
static uint16_t lv_obj_get_style_layout (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 553 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_LAYOUT);
    return (uint16_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_LAYOUT, and lv_style_value_t::num.
lv_obj_get_style_line_color()
static lv_color_t lv_obj_get_style_line_color (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 391 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_LINE_COLOR);
    return v.color;
}
References lv_style_value_t::color, lv_obj_get_style_prop(), and LV_STYLE_LINE_COLOR.
lv_obj_get_style_line_color_filtered()
static lv_color_t lv_obj_get_style_line_color_filtered (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 397 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = _lv_obj_style_apply_color_filter(obj, part, lv_obj_get_style_prop(obj, part, LV_STYLE_LINE_COLOR));
    return v.color;
}
References _lv_obj_style_apply_color_filter(), lv_style_value_t::color, lv_obj_get_style_prop(), and LV_STYLE_LINE_COLOR.
lv_obj_get_style_line_dash_gap()
static lv_coord_t lv_obj_get_style_line_dash_gap (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 379 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_LINE_DASH_GAP);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_LINE_DASH_GAP, and lv_style_value_t::num.
lv_obj_get_style_line_dash_width()
static lv_coord_t lv_obj_get_style_line_dash_width (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 373 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_LINE_DASH_WIDTH);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_LINE_DASH_WIDTH, and lv_style_value_t::num.
lv_obj_get_style_line_opa()
static lv_opa_t lv_obj_get_style_line_opa (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 403 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_LINE_OPA);
    return (lv_opa_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_LINE_OPA, and lv_style_value_t::num.
lv_obj_get_style_line_rounded()
static bool lv_obj_get_style_line_rounded (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 385 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_LINE_ROUNDED);
    return (bool)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_LINE_ROUNDED, and lv_style_value_t::num.
lv_obj_get_style_line_width()
static lv_coord_t lv_obj_get_style_line_width (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 367 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_LINE_WIDTH);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_LINE_WIDTH, and lv_style_value_t::num.
lv_obj_get_style_max_height()
static lv_coord_t lv_obj_get_style_max_height (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 31 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_MAX_HEIGHT);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_MAX_HEIGHT, and lv_style_value_t::num.
lv_obj_get_style_max_width()
static lv_coord_t lv_obj_get_style_max_width (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 13 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_MAX_WIDTH);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_MAX_WIDTH, and lv_style_value_t::num.
lv_obj_get_style_min_height()
static lv_coord_t lv_obj_get_style_min_height (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 25 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_MIN_HEIGHT);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_MIN_HEIGHT, and lv_style_value_t::num.
lv_obj_get_style_min_width()
static lv_coord_t lv_obj_get_style_min_width (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 7 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_MIN_WIDTH);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_MIN_WIDTH, and lv_style_value_t::num.
lv_obj_get_style_opa()
static lv_opa_t lv_obj_get_style_opa (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 505 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_OPA);
    return (lv_opa_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_OPA, and lv_style_value_t::num.
lv_obj_get_style_outline_color()
static lv_color_t lv_obj_get_style_outline_color (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 277 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_OUTLINE_COLOR);
    return v.color;
}
References lv_style_value_t::color, lv_obj_get_style_prop(), and LV_STYLE_OUTLINE_COLOR.
lv_obj_get_style_outline_color_filtered()
static lv_color_t lv_obj_get_style_outline_color_filtered (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 283 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = _lv_obj_style_apply_color_filter(obj, part, lv_obj_get_style_prop(obj, part, LV_STYLE_OUTLINE_COLOR));
    return v.color;
}
References _lv_obj_style_apply_color_filter(), lv_style_value_t::color, lv_obj_get_style_prop(), and LV_STYLE_OUTLINE_COLOR.
lv_obj_get_style_outline_opa()
static lv_opa_t lv_obj_get_style_outline_opa (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 289 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_OUTLINE_OPA);
    return (lv_opa_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_OUTLINE_OPA, and lv_style_value_t::num.
lv_obj_get_style_outline_pad()
static lv_coord_t lv_obj_get_style_outline_pad (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 295 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_OUTLINE_PAD);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_OUTLINE_PAD, and lv_style_value_t::num.
lv_obj_get_style_outline_width()
static lv_coord_t lv_obj_get_style_outline_width (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 271 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_OUTLINE_WIDTH);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_OUTLINE_WIDTH, and lv_style_value_t::num.
lv_obj_get_style_pad_bottom()
static lv_coord_t lv_obj_get_style_pad_bottom (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 109 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_PAD_BOTTOM);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_PAD_BOTTOM, and lv_style_value_t::num.
lv_obj_get_style_pad_column()
static lv_coord_t lv_obj_get_style_pad_column (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 133 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_PAD_COLUMN);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_PAD_COLUMN, and lv_style_value_t::num.
lv_obj_get_style_pad_left()
static lv_coord_t lv_obj_get_style_pad_left (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 115 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_PAD_LEFT);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_PAD_LEFT, and lv_style_value_t::num.
lv_obj_get_style_pad_right()
static lv_coord_t lv_obj_get_style_pad_right (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 121 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_PAD_RIGHT);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_PAD_RIGHT, and lv_style_value_t::num.
lv_obj_get_style_pad_row()
static lv_coord_t lv_obj_get_style_pad_row (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 127 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_PAD_ROW);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_PAD_ROW, and lv_style_value_t::num.
lv_obj_get_style_pad_top()
static lv_coord_t lv_obj_get_style_pad_top (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 103 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_PAD_TOP);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_PAD_TOP, and lv_style_value_t::num.
lv_obj_get_style_radius()
static lv_coord_t lv_obj_get_style_radius (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 493 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_RADIUS);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_RADIUS, and lv_style_value_t::num.
lv_obj_get_style_shadow_color()
static lv_color_t lv_obj_get_style_shadow_color (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 325 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_SHADOW_COLOR);
    return v.color;
}
References lv_style_value_t::color, lv_obj_get_style_prop(), and LV_STYLE_SHADOW_COLOR.
lv_obj_get_style_shadow_color_filtered()
static lv_color_t lv_obj_get_style_shadow_color_filtered (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 331 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = _lv_obj_style_apply_color_filter(obj, part, lv_obj_get_style_prop(obj, part, LV_STYLE_SHADOW_COLOR));
    return v.color;
}
References _lv_obj_style_apply_color_filter(), lv_style_value_t::color, lv_obj_get_style_prop(), and LV_STYLE_SHADOW_COLOR.
lv_obj_get_style_shadow_ofs_x()
static lv_coord_t lv_obj_get_style_shadow_ofs_x (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 307 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_SHADOW_OFS_X);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_SHADOW_OFS_X, and lv_style_value_t::num.
lv_obj_get_style_shadow_ofs_y()
static lv_coord_t lv_obj_get_style_shadow_ofs_y (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 313 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_SHADOW_OFS_Y);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_SHADOW_OFS_Y, and lv_style_value_t::num.
lv_obj_get_style_shadow_opa()
static lv_opa_t lv_obj_get_style_shadow_opa (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 337 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_SHADOW_OPA);
    return (lv_opa_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_SHADOW_OPA, and lv_style_value_t::num.
lv_obj_get_style_shadow_spread()
static lv_coord_t lv_obj_get_style_shadow_spread (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 319 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_SHADOW_SPREAD);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_SHADOW_SPREAD, and lv_style_value_t::num.
lv_obj_get_style_shadow_width()
static lv_coord_t lv_obj_get_style_shadow_width (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 301 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_SHADOW_WIDTH);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_SHADOW_WIDTH, and lv_style_value_t::num.
lv_obj_get_style_text_align()
static lv_text_align_t lv_obj_get_style_text_align (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 487 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_TEXT_ALIGN);
    return (lv_text_align_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_TEXT_ALIGN, and lv_style_value_t::num.
lv_obj_get_style_text_color()
static lv_color_t lv_obj_get_style_text_color (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 445 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_TEXT_COLOR);
    return v.color;
}
References lv_style_value_t::color, lv_obj_get_style_prop(), and LV_STYLE_TEXT_COLOR.
lv_obj_get_style_text_color_filtered()
static lv_color_t lv_obj_get_style_text_color_filtered (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 451 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = _lv_obj_style_apply_color_filter(obj, part, lv_obj_get_style_prop(obj, part, LV_STYLE_TEXT_COLOR));
    return v.color;
}
References _lv_obj_style_apply_color_filter(), lv_style_value_t::color, lv_obj_get_style_prop(), and LV_STYLE_TEXT_COLOR.
lv_obj_get_style_text_decor()
static lv_text_decor_t lv_obj_get_style_text_decor (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 481 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_TEXT_DECOR);
    return (lv_text_decor_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_TEXT_DECOR, and lv_style_value_t::num.
lv_obj_get_style_text_font()
static const lv_font_t * lv_obj_get_style_text_font (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 463 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_TEXT_FONT);
    return (const lv_font_t *)v.ptr;
}
References lv_obj_get_style_prop(), LV_STYLE_TEXT_FONT, and lv_style_value_t::ptr.
lv_obj_get_style_text_letter_space()
static lv_coord_t lv_obj_get_style_text_letter_space (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 469 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_TEXT_LETTER_SPACE);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_TEXT_LETTER_SPACE, and lv_style_value_t::num.
lv_obj_get_style_text_line_space()
static lv_coord_t lv_obj_get_style_text_line_space (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 475 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_TEXT_LINE_SPACE);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_TEXT_LINE_SPACE, and lv_style_value_t::num.
lv_obj_get_style_text_opa()
static lv_opa_t lv_obj_get_style_text_opa (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 457 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_TEXT_OPA);
    return (lv_opa_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_TEXT_OPA, and lv_style_value_t::num.
lv_obj_get_style_transform_angle()
static lv_coord_t lv_obj_get_style_transform_angle (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 85 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_TRANSFORM_ANGLE);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_TRANSFORM_ANGLE, and lv_style_value_t::num.
lv_obj_get_style_transform_height()
static lv_coord_t lv_obj_get_style_transform_height (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 61 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_TRANSFORM_HEIGHT);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_TRANSFORM_HEIGHT, and lv_style_value_t::num.
lv_obj_get_style_transform_pivot_x()
static lv_coord_t lv_obj_get_style_transform_pivot_x (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 91 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_TRANSFORM_PIVOT_X);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_TRANSFORM_PIVOT_X, and lv_style_value_t::num.
lv_obj_get_style_transform_pivot_y()
static lv_coord_t lv_obj_get_style_transform_pivot_y (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 97 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_TRANSFORM_PIVOT_Y);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_TRANSFORM_PIVOT_Y, and lv_style_value_t::num.
lv_obj_get_style_transform_width()
static lv_coord_t lv_obj_get_style_transform_width (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 55 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_TRANSFORM_WIDTH);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_TRANSFORM_WIDTH, and lv_style_value_t::num.
lv_obj_get_style_transform_zoom()
static lv_coord_t lv_obj_get_style_transform_zoom (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 79 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_TRANSFORM_ZOOM);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_TRANSFORM_ZOOM, and lv_style_value_t::num.
lv_obj_get_style_transition()
static const lv_style_transition_dsc_t * lv_obj_get_style_transition (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 541 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_TRANSITION);
    return (const lv_style_transition_dsc_t *)v.ptr;
}
References lv_obj_get_style_prop(), LV_STYLE_TRANSITION, and lv_style_value_t::ptr.
lv_obj_get_style_translate_x()
static lv_coord_t lv_obj_get_style_translate_x (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 67 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_TRANSLATE_X);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_TRANSLATE_X, and lv_style_value_t::num.
lv_obj_get_style_translate_y()
static lv_coord_t lv_obj_get_style_translate_y (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 73 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_TRANSLATE_Y);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_TRANSLATE_Y, and lv_style_value_t::num.
lv_obj_get_style_width()
static lv_coord_t lv_obj_get_style_width (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 1 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_WIDTH);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_WIDTH, and lv_style_value_t::num.
lv_obj_get_style_x()
static lv_coord_t lv_obj_get_style_x (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 37 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_X);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_X, and lv_style_value_t::num.
lv_obj_get_style_y()
static lv_coord_t lv_obj_get_style_y (const struct _lv_obj_t * obj, uint32_t part) inline static
Definition at line 43 of file lv_obj_style_gen.h.
{
    lv_style_value_t v = lv_obj_get_style_prop(obj, part, LV_STYLE_Y);
    return (lv_coord_t)v.num;
}
References lv_obj_get_style_prop(), LV_STYLE_Y, and lv_style_value_t::num.
lv_obj_set_style_align()
void lv_obj_set_style_align (struct _lv_obj_t * obj, lv_align_t value, lv_style_selector_t selector)
lv_obj_set_style_anim()
void lv_obj_set_style_anim (struct _lv_obj_t * obj, const lv_anim_t * value, lv_style_selector_t selector)
lv_obj_set_style_anim_speed()
void lv_obj_set_style_anim_speed (struct _lv_obj_t * obj, uint32_t value, lv_style_selector_t selector)
lv_obj_set_style_anim_time()
void lv_obj_set_style_anim_time (struct _lv_obj_t * obj, uint32_t value, lv_style_selector_t selector)
lv_obj_set_style_arc_color()
void lv_obj_set_style_arc_color (struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector)
lv_obj_set_style_arc_img_src()
void lv_obj_set_style_arc_img_src (struct _lv_obj_t * obj, const void * value, lv_style_selector_t selector)
lv_obj_set_style_arc_opa()
void lv_obj_set_style_arc_opa (struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector)
lv_obj_set_style_arc_rounded()
void lv_obj_set_style_arc_rounded (struct _lv_obj_t * obj, bool value, lv_style_selector_t selector)
lv_obj_set_style_arc_width()
void lv_obj_set_style_arc_width (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
lv_obj_set_style_base_dir()
void lv_obj_set_style_base_dir (struct _lv_obj_t * obj, lv_base_dir_t value, lv_style_selector_t selector)
lv_obj_set_style_bg_color()
void lv_obj_set_style_bg_color (struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector)
lv_obj_set_style_bg_dither_mode()
void lv_obj_set_style_bg_dither_mode (struct _lv_obj_t * obj, lv_dither_mode_t value, lv_style_selector_t selector)
lv_obj_set_style_bg_grad()
void lv_obj_set_style_bg_grad (struct _lv_obj_t * obj, const lv_grad_dsc_t * value, lv_style_selector_t selector)
lv_obj_set_style_bg_grad_color()
void lv_obj_set_style_bg_grad_color (struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector)
lv_obj_set_style_bg_grad_dir()
void lv_obj_set_style_bg_grad_dir (struct _lv_obj_t * obj, lv_grad_dir_t value, lv_style_selector_t selector)
lv_obj_set_style_bg_grad_stop()
void lv_obj_set_style_bg_grad_stop (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
lv_obj_set_style_bg_img_opa()
void lv_obj_set_style_bg_img_opa (struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector)
lv_obj_set_style_bg_img_recolor()
void lv_obj_set_style_bg_img_recolor (struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector)
lv_obj_set_style_bg_img_recolor_opa()
void lv_obj_set_style_bg_img_recolor_opa (struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector)
lv_obj_set_style_bg_img_src()
void lv_obj_set_style_bg_img_src (struct _lv_obj_t * obj, const void * value, lv_style_selector_t selector)
lv_obj_set_style_bg_img_tiled()
void lv_obj_set_style_bg_img_tiled (struct _lv_obj_t * obj, bool value, lv_style_selector_t selector)
lv_obj_set_style_bg_main_stop()
void lv_obj_set_style_bg_main_stop (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
lv_obj_set_style_bg_opa()
void lv_obj_set_style_bg_opa (struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector)
lv_obj_set_style_blend_mode()
void lv_obj_set_style_blend_mode (struct _lv_obj_t * obj, lv_blend_mode_t value, lv_style_selector_t selector)
lv_obj_set_style_border_color()
void lv_obj_set_style_border_color (struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector)
lv_obj_set_style_border_opa()
void lv_obj_set_style_border_opa (struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector)
lv_obj_set_style_border_post()
void lv_obj_set_style_border_post (struct _lv_obj_t * obj, bool value, lv_style_selector_t selector)
lv_obj_set_style_border_side()
void lv_obj_set_style_border_side (struct _lv_obj_t * obj, lv_border_side_t value, lv_style_selector_t selector)
lv_obj_set_style_border_width()
void lv_obj_set_style_border_width (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
lv_obj_set_style_clip_corner()
void lv_obj_set_style_clip_corner (struct _lv_obj_t * obj, bool value, lv_style_selector_t selector)
lv_obj_set_style_color_filter_dsc()
void lv_obj_set_style_color_filter_dsc (struct _lv_obj_t * obj, const lv_color_filter_dsc_t * value, lv_style_selector_t selector)
lv_obj_set_style_color_filter_opa()
void lv_obj_set_style_color_filter_opa (struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector)
lv_obj_set_style_height()
void lv_obj_set_style_height (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
Referenced by lv_obj_set_style_size().
lv_obj_set_style_img_opa()
void lv_obj_set_style_img_opa (struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector)
lv_obj_set_style_img_recolor()
void lv_obj_set_style_img_recolor (struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector)
lv_obj_set_style_img_recolor_opa()
void lv_obj_set_style_img_recolor_opa (struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector)
lv_obj_set_style_layout()
void lv_obj_set_style_layout (struct _lv_obj_t * obj, uint16_t value, lv_style_selector_t selector)
lv_obj_set_style_line_color()
void lv_obj_set_style_line_color (struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector)
lv_obj_set_style_line_dash_gap()
void lv_obj_set_style_line_dash_gap (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
lv_obj_set_style_line_dash_width()
void lv_obj_set_style_line_dash_width (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
lv_obj_set_style_line_opa()
void lv_obj_set_style_line_opa (struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector)
lv_obj_set_style_line_rounded()
void lv_obj_set_style_line_rounded (struct _lv_obj_t * obj, bool value, lv_style_selector_t selector)
lv_obj_set_style_line_width()
void lv_obj_set_style_line_width (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
lv_obj_set_style_max_height()
void lv_obj_set_style_max_height (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
lv_obj_set_style_max_width()
void lv_obj_set_style_max_width (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
lv_obj_set_style_min_height()
void lv_obj_set_style_min_height (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
lv_obj_set_style_min_width()
void lv_obj_set_style_min_width (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
lv_obj_set_style_opa()
void lv_obj_set_style_opa (struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector)
lv_obj_set_style_outline_color()
void lv_obj_set_style_outline_color (struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector)
lv_obj_set_style_outline_opa()
void lv_obj_set_style_outline_opa (struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector)
lv_obj_set_style_outline_pad()
void lv_obj_set_style_outline_pad (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
lv_obj_set_style_outline_width()
void lv_obj_set_style_outline_width (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
lv_obj_set_style_pad_bottom()
void lv_obj_set_style_pad_bottom (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
Referenced by lv_obj_set_style_pad_all(), and lv_obj_set_style_pad_ver().
lv_obj_set_style_pad_column()
void lv_obj_set_style_pad_column (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
Referenced by lv_obj_set_style_pad_gap().
lv_obj_set_style_pad_left()
void lv_obj_set_style_pad_left (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
Referenced by lv_obj_set_style_pad_all(), and lv_obj_set_style_pad_hor().
lv_obj_set_style_pad_right()
void lv_obj_set_style_pad_right (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
Referenced by lv_obj_set_style_pad_all(), and lv_obj_set_style_pad_hor().
lv_obj_set_style_pad_row()
void lv_obj_set_style_pad_row (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
Referenced by lv_obj_set_style_pad_gap().
lv_obj_set_style_pad_top()
void lv_obj_set_style_pad_top (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
Referenced by lv_obj_set_style_pad_all(), and lv_obj_set_style_pad_ver().
lv_obj_set_style_radius()
void lv_obj_set_style_radius (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
lv_obj_set_style_shadow_color()
void lv_obj_set_style_shadow_color (struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector)
lv_obj_set_style_shadow_ofs_x()
void lv_obj_set_style_shadow_ofs_x (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
lv_obj_set_style_shadow_ofs_y()
void lv_obj_set_style_shadow_ofs_y (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
lv_obj_set_style_shadow_opa()
void lv_obj_set_style_shadow_opa (struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector)
lv_obj_set_style_shadow_spread()
void lv_obj_set_style_shadow_spread (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
lv_obj_set_style_shadow_width()
void lv_obj_set_style_shadow_width (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
lv_obj_set_style_text_align()
void lv_obj_set_style_text_align (struct _lv_obj_t * obj, lv_text_align_t value, lv_style_selector_t selector)
lv_obj_set_style_text_color()
void lv_obj_set_style_text_color (struct _lv_obj_t * obj, lv_color_t value, lv_style_selector_t selector)
lv_obj_set_style_text_decor()
void lv_obj_set_style_text_decor (struct _lv_obj_t * obj, lv_text_decor_t value, lv_style_selector_t selector)
lv_obj_set_style_text_font()
void lv_obj_set_style_text_font (struct _lv_obj_t * obj, const lv_font_t * value, lv_style_selector_t selector)
lv_obj_set_style_text_letter_space()
void lv_obj_set_style_text_letter_space (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
lv_obj_set_style_text_line_space()
void lv_obj_set_style_text_line_space (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
lv_obj_set_style_text_opa()
void lv_obj_set_style_text_opa (struct _lv_obj_t * obj, lv_opa_t value, lv_style_selector_t selector)
lv_obj_set_style_transform_angle()
void lv_obj_set_style_transform_angle (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
lv_obj_set_style_transform_height()
void lv_obj_set_style_transform_height (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
lv_obj_set_style_transform_pivot_x()
void lv_obj_set_style_transform_pivot_x (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
lv_obj_set_style_transform_pivot_y()
void lv_obj_set_style_transform_pivot_y (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
lv_obj_set_style_transform_width()
void lv_obj_set_style_transform_width (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
lv_obj_set_style_transform_zoom()
void lv_obj_set_style_transform_zoom (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
lv_obj_set_style_transition()
void lv_obj_set_style_transition (struct _lv_obj_t * obj, const lv_style_transition_dsc_t * value, lv_style_selector_t selector)
lv_obj_set_style_translate_x()
void lv_obj_set_style_translate_x (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
lv_obj_set_style_translate_y()
void lv_obj_set_style_translate_y (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
lv_obj_set_style_width()
void lv_obj_set_style_width (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
Referenced by lv_obj_set_style_size().
lv_obj_set_style_x()
void lv_obj_set_style_x (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)
lv_obj_set_style_y()
void lv_obj_set_style_y (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector)