1516b Over Under: initialize
initialize()
void initialize (void)
Runs initialization code. This occurs as soon as the program is started.
All other competition modes are blocked by initialize; it is recommended to keep execution time for this mode under a few seconds.
Definition at line 59 of file main.cpp.
                  {
   pros::lcd::initialize();
   pros::Task toggler(toggles);
   if (pros::c::registry_get_plugged_type(13) == pros::c::E_DEVICE_IMU) {
      chassis.calibrate();
      chassis.setPose(0, 0, 90); // X: 0, Y: 0, Heading: 0
      // Setting an example start location for the robot so it is all relatativistic
      pros::Task screenTask(Robot::Utility::displayLocation);
   }
   else {
      pros::Task screenTask(Robot::Utility::displayMotorVel);
   }
}
References Robot::Globals::chassis, Robot::Utility::displayLocation(), Robot::Utility::displayMotorVel(), and toggles().