1516X High Stakes: include/main.h File Reference
main.h File Reference
#include "api.h"
#include "robot/auton.h"
#include "globals.h"
#include "robot/drivetrain.h"
#include "robot/intake.h"
#include "robot/latch.h"
#include "robot/utility.h"
#include "pros/apix.h"
#include "screen/selector.h"
#include "screen/status.h"
Macros
#define PROS_USE_SIMPLE_NAMES
#define PROS_USE_LITERALS
Functions
void autonomous (void)
void initialize (void)
void disabled (void)
void competition_initialize (void)
void opcontrol (void)
Detailed Description
Contains common definitions and header files used throughout your PROS project.
Copyright
Copyright (c) 2017-2023, Purdue University ACM SIGBots. All rights reserved.
This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
Definition in file main.h.
Macro Definition Documentation
PROS_USE_LITERALS
#define PROS_USE_LITERALS
If defined, C++ literals will be available for use. All literals are in the pros::literals namespace.
For instance, you can do 4_mtr = 50 to set motor 4's target velocity to 50
Definition at line 35 of file main.h.
PROS_USE_SIMPLE_NAMES
#define PROS_USE_SIMPLE_NAMES
If defined, some commonly used enums will have preprocessor macros which give a shorter, more convenient naming pattern. If this isn't desired, simply comment the following line out.
For instance, E_CONTROLLER_MASTER has a shorter name: CONTROLLER_MASTER. E_CONTROLLER_MASTER is pedantically correct within the PROS styleguide, but not convenient for most student programmers.
Definition at line 27 of file main.h.
Function Documentation
autonomous()
void autonomous (void)
You should add more #includes here If you find doing pros::Motor() to be tedious and you'd prefer just to do Motor, you can use the namespace with the following commented out line.
IMPORTANT: Only the okapi or pros namespace may be used, not both concurrently! The okapi namespace will export all symbols inside the pros namespace. Prototypes for the competition control tasks are redefined here to ensure that they can be called from user code (i.e. calling autonomous from a button press in opcontrol() for testing purposes).
6 Runs the user autonomous code. This function will be started in its own task with the default priority and stack size whenever the robot is enabled via the Field Management System or the VEX Competition Switch in the autonomous mode. Alternatively, this function may be called in initialize or opcontrol for non-competition testing purposes.
If the robot is disabled or communications is lost, the autonomous task will be stopped. Re-enabling the robot will restart the task, not re-start it from where it left off.
Definition at line 117 of file main.cpp.
                  {
   // chassis.setPose(0, 0, 0);
    // // move 48" forwards
    // chassis.moveToPoint(0, 24, 10000, {.maxSpeed = 110});
   subsystem.autonomous.AutoDrive(subsystem.intake, subsystem.latch);
}
References Robot::Autonomous::AutoDrive(), RobotSubsystems::autonomous, RobotSubsystems::intake, RobotSubsystems::latch, and subsystem.
Referenced by opcontrol().
competition_initialize()
void competition_initialize (void)
Runs after initialize(), and before autonomous when connected to the Field Management System or the VEX Competition Switch. This is intended for competition-specific initialization routines, such as an autonomous selector on the LCD.
This task will exit when the robot is enabled and autonomous or opcontrol starts.<asd></asd>
Definition at line 94 of file main.cpp.
{
}
Referenced by opcontrol().
disabled()
void disabled (void)
Runs while the robot is in the disabled state of Field Management System or the VEX Competition Switch, following either autonomous or opcontrol. When the robot is enabled, this task will exit.
Definition at line 83 of file main.cpp.
{}
initialize()
void initialize (void)
Runs initialization code. This occurs as soon as the program is started.
All other competition modes are blocked by initialize; it is recommended to keep execution time for this mode under a few seconds.
Definition at line 50 of file main.cpp.
                  {
   // if (pros::c::registry_get_plugged_type(15) == pros::c::E_DEVICE_IMU) {
   //chassis.calibrate();
   chassis.setPose(0, 0, 0);
   screen.selector.selector();
   // pros::Task screen_task([&]() {
    //     while (true) {
    //         // print robot location to the brain screen
    //         pros::lcd::print(0, "X: %f", chassis.getPose().x); // x
    //         pros::lcd::print(1, "Y: %f", chassis.getPose().y); // y
    //         pros::lcd::print(2, "Theta: %f", chassis.getPose().theta); // heading
   //       // delay to save resources
    //         pros::delay(20);
    //     }
    // });
}
References Robot::Globals::chassis, screen, Robot::selector_screen::selector(), RobotScreen::selector, and lemlib::Chassis::setPose().
opcontrol()
void opcontrol (void)
Runs the operator control code. This function will be started in its own task with the default priority and stack size whenever the robot is enabled via the Field Management System or the VEX Competition Switch in the operator control mode.
If no competition control is connected, this function will run immediately following initialize().
If the robot is disabled or communications is lost, the operator control task will be stopped. Re-enabling the robot will restart the task, not resume it from where it left off.
Definition at line 145 of file main.cpp.
                 {
    while (true) {
      if(controller.get_digital_new_press(pros::E_CONTROLLER_DIGITAL_UP)) {
         competition_initialize();
      }
      if(controller.get_digital_new_press(pros::E_CONTROLLER_DIGITAL_DOWN)) {
         autonomous();
      }
      if(controller.get_digital_new_press(pros::E_CONTROLLER_DIGITAL_LEFT)) {
         std::string name = subsystem.drivetrain.toggleDrive();
         //Output the current drive mode to the controller screen
         controller.print(0, 0, name.c_str());
      }
        subsystem.drivetrain.run();
      subsystem.latch.run();
      // Intake controller, uses the X button holded down to push the elevation up.
      subsystem.intake.run();
      // Intake controller, moves the left and right intakes and stops them if nothing is pressed.
        pros::delay(10); // Small delay to reduce CPU usage
    }
}
References autonomous(), competition_initialize(), Robot::Globals::controller, RobotSubsystems::drivetrain, pros::v5::Controller::get_digital_new_press(), RobotSubsystems::intake, RobotSubsystems::latch, pros::v5::Controller::print(), Robot::Drivetrain::run(), Robot::Intake::run(), Robot::Latch::run(), subsystem, and Robot::Drivetrain::toggleDrive().