1516X High Stakes: include/liblvgl/core/lv_obj_style.h File Reference
lv_obj_style.h File Reference
#include <stdint.h>
#include <stdbool.h>
#include "liblvgl/misc/lv_bidi.h"
#include "lv_obj_style_gen.h"
Classes
struct _lv_obj_style_t
struct _lv_obj_style_transition_dsc_t
Typedefs
typedef uint32_t lv_style_selector_t
Enumerations
enum _lv_style_state_cmp_t { _LV_STYLE_STATE_CMP_SAME , _LV_STYLE_STATE_CMP_DIFF_REDRAW , _LV_STYLE_STATE_CMP_DIFF_DRAW_PAD , _LV_STYLE_STATE_CMP_DIFF_LAYOUT }
Functions
void _lv_obj_style_init (void)
void lv_obj_add_style (struct _lv_obj_t *obj, lv_style_t *style, lv_style_selector_t selector)
void lv_obj_remove_style (struct _lv_obj_t *obj, lv_style_t *style, lv_style_selector_t selector)
static void lv_obj_remove_style_all (struct _lv_obj_t *obj)
void lv_obj_report_style_change (lv_style_t *style)
void lv_obj_refresh_style (struct _lv_obj_t *obj, lv_part_t part, lv_style_prop_t prop)
void lv_obj_enable_style_refresh (bool en)
lv_style_value_t lv_obj_get_style_prop (const struct _lv_obj_t *obj, lv_part_t part, lv_style_prop_t prop)
void lv_obj_set_local_style_prop (struct _lv_obj_t *obj, lv_style_prop_t prop, lv_style_value_t value, lv_style_selector_t selector)
void lv_obj_set_local_style_prop_meta (struct _lv_obj_t *obj, lv_style_prop_t prop, uint16_t meta, lv_style_selector_t selector)
lv_style_res_t lv_obj_get_local_style_prop (struct _lv_obj_t *obj, lv_style_prop_t prop, lv_style_value_t *value, lv_style_selector_t selector)
bool lv_obj_remove_local_style_prop (struct _lv_obj_t *obj, lv_style_prop_t prop, lv_style_selector_t selector)
lv_style_value_t _lv_obj_style_apply_color_filter (const struct _lv_obj_t *obj, uint32_t part, lv_style_value_t v)
void _lv_obj_style_create_transition (struct _lv_obj_t *obj, lv_part_t part, lv_state_t prev_state, lv_state_t new_state, const _lv_obj_style_transition_dsc_t *tr)
_lv_style_state_cmp_t _lv_obj_style_state_compare (struct _lv_obj_t *obj, lv_state_t state1, lv_state_t state2)
void lv_obj_fade_in (struct _lv_obj_t *obj, uint32_t time, uint32_t delay)
void lv_obj_fade_out (struct _lv_obj_t *obj, uint32_t time, uint32_t delay)
lv_state_t lv_obj_style_get_selector_state (lv_style_selector_t selector)
lv_part_t lv_obj_style_get_selector_part (lv_style_selector_t selector)
static void lv_obj_set_style_pad_all (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
static void lv_obj_set_style_pad_hor (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
static void lv_obj_set_style_pad_ver (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
static void lv_obj_set_style_pad_gap (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
static void lv_obj_set_style_size (struct _lv_obj_t *obj, lv_coord_t value, lv_style_selector_t selector)
lv_text_align_t lv_obj_calculate_style_text_align (const struct _lv_obj_t *obj, lv_part_t part, const char *txt)
Typedef Documentation
lv_style_selector_t
typedef uint32_t lv_style_selector_t
Definition at line 37 of file lv_obj_style.h.
Enumeration Type Documentation
_lv_style_state_cmp_t
enum _lv_style_state_cmp_t
Enumerator
_LV_STYLE_STATE_CMP_SAME
_LV_STYLE_STATE_CMP_DIFF_REDRAW
_LV_STYLE_STATE_CMP_DIFF_DRAW_PAD
_LV_STYLE_STATE_CMP_DIFF_LAYOUT
Definition at line 30 of file lv_obj_style.h.
             {
    _LV_STYLE_STATE_CMP_SAME,           /*The style properties in the 2 states are identical*/
    _LV_STYLE_STATE_CMP_DIFF_REDRAW,    /*The differences can be shown with a simple redraw*/
    _LV_STYLE_STATE_CMP_DIFF_DRAW_PAD,  /*The differences can be shown with a simple redraw*/
    _LV_STYLE_STATE_CMP_DIFF_LAYOUT,    /*The differences can be shown with a simple redraw*/
} _lv_style_state_cmp_t;
Function Documentation
_lv_obj_style_apply_color_filter()
lv_style_value_t _lv_obj_style_apply_color_filter (const struct _lv_obj_t * obj, uint32_t part, lv_style_value_t v)
Used internally for color filtering
Referenced by lv_obj_get_style_arc_color_filtered(), lv_obj_get_style_bg_color_filtered(), lv_obj_get_style_bg_grad_color_filtered(), lv_obj_get_style_bg_img_recolor_filtered(), lv_obj_get_style_border_color_filtered(), lv_obj_get_style_img_recolor_filtered(), lv_obj_get_style_line_color_filtered(), lv_obj_get_style_outline_color_filtered(), lv_obj_get_style_shadow_color_filtered(), and lv_obj_get_style_text_color_filtered().
_lv_obj_style_create_transition()
void _lv_obj_style_create_transition (struct _lv_obj_t * obj, lv_part_t part, lv_state_t prev_state, lv_state_t new_state, const _lv_obj_style_transition_dsc_t * tr)
Used internally to create a style transition
Parameters
obj
part
prev_state
new_state
tr
_lv_obj_style_init()
void _lv_obj_style_init (void)
Initialize the object related style manager module. Called by LVGL in lv_init()
_lv_obj_style_state_compare()
_lv_style_state_cmp_t _lv_obj_style_state_compare (struct _lv_obj_t * obj, lv_state_t state1, lv_state_t state2)
Used internally to compare the appearance of an object in 2 states
Parameters
obj
state1
state2
Returns
lv_obj_add_style()
void lv_obj_add_style (struct _lv_obj_t * obj, lv_style_t * style, lv_style_selector_t selector)
lv_obj_calculate_style_text_align()
lv_text_align_t lv_obj_calculate_style_text_align (const struct _lv_obj_t * obj, lv_part_t part, const char * txt)
lv_obj_enable_style_refresh()
void lv_obj_enable_style_refresh (bool en)
Enable or disable automatic style refreshing when a new style is added/removed to/from an object or any other style change happens.
Parameters
en true: enable refreshing; false: disable refreshing
lv_obj_fade_in()
void lv_obj_fade_in (struct _lv_obj_t * obj, uint32_t time, uint32_t delay)
Fade in an an object and all its children.
Parameters
obj the object to fade in
time time of fade
delay delay to start the animation
lv_obj_fade_out()
void lv_obj_fade_out (struct _lv_obj_t * obj, uint32_t time, uint32_t delay)
Fade out an an object and all its children.
Parameters
obj the object to fade out
time time of fade
delay delay to start the animation
lv_obj_get_local_style_prop()
lv_style_res_t lv_obj_get_local_style_prop (struct _lv_obj_t * obj, lv_style_prop_t prop, lv_style_value_t * value, lv_style_selector_t selector)
lv_obj_get_style_prop()
lv_style_value_t lv_obj_get_style_prop (const struct _lv_obj_t * obj, lv_part_t part, lv_style_prop_t prop)
Get the value of a style property. The current state of the object will be considered. Inherited properties will be inherited. If a property is not set a default value will be returned.
Parameters
obj pointer to an object
part a part from which the property should be get
prop the property to get
Returns
the value of the property. Should be read from the correct field of the lv_style_value_t according to the type of the property.
Referenced by lv_obj_get_style_align(), lv_obj_get_style_anim(), lv_obj_get_style_anim_speed(), lv_obj_get_style_anim_time(), lv_obj_get_style_arc_color(), lv_obj_get_style_arc_color_filtered(), lv_obj_get_style_arc_img_src(), lv_obj_get_style_arc_opa(), lv_obj_get_style_arc_rounded(), lv_obj_get_style_arc_width(), lv_obj_get_style_base_dir(), lv_obj_get_style_bg_color(), lv_obj_get_style_bg_color_filtered(), lv_obj_get_style_bg_dither_mode(), lv_obj_get_style_bg_grad(), lv_obj_get_style_bg_grad_color(), lv_obj_get_style_bg_grad_color_filtered(), lv_obj_get_style_bg_grad_dir(), lv_obj_get_style_bg_grad_stop(), lv_obj_get_style_bg_img_opa(), lv_obj_get_style_bg_img_recolor(), lv_obj_get_style_bg_img_recolor_filtered(), lv_obj_get_style_bg_img_recolor_opa(), lv_obj_get_style_bg_img_src(), lv_obj_get_style_bg_img_tiled(), lv_obj_get_style_bg_main_stop(), lv_obj_get_style_bg_opa(), lv_obj_get_style_blend_mode(), lv_obj_get_style_border_color(), lv_obj_get_style_border_color_filtered(), lv_obj_get_style_border_opa(), lv_obj_get_style_border_post(), lv_obj_get_style_border_side(), lv_obj_get_style_border_width(), lv_obj_get_style_clip_corner(), lv_obj_get_style_color_filter_dsc(), lv_obj_get_style_color_filter_opa(), lv_obj_get_style_height(), lv_obj_get_style_img_opa(), lv_obj_get_style_img_recolor(), lv_obj_get_style_img_recolor_filtered(), lv_obj_get_style_img_recolor_opa(), lv_obj_get_style_layout(), lv_obj_get_style_line_color(), lv_obj_get_style_line_color_filtered(), lv_obj_get_style_line_dash_gap(), lv_obj_get_style_line_dash_width(), lv_obj_get_style_line_opa(), lv_obj_get_style_line_rounded(), lv_obj_get_style_line_width(), lv_obj_get_style_max_height(), lv_obj_get_style_max_width(), lv_obj_get_style_min_height(), lv_obj_get_style_min_width(), lv_obj_get_style_opa(), lv_obj_get_style_outline_color(), lv_obj_get_style_outline_color_filtered(), lv_obj_get_style_outline_opa(), lv_obj_get_style_outline_pad(), lv_obj_get_style_outline_width(), lv_obj_get_style_pad_bottom(), lv_obj_get_style_pad_column(), lv_obj_get_style_pad_left(), lv_obj_get_style_pad_right(), lv_obj_get_style_pad_row(), lv_obj_get_style_pad_top(), lv_obj_get_style_radius(), lv_obj_get_style_shadow_color(), lv_obj_get_style_shadow_color_filtered(), lv_obj_get_style_shadow_ofs_x(), lv_obj_get_style_shadow_ofs_y(), lv_obj_get_style_shadow_opa(), lv_obj_get_style_shadow_spread(), lv_obj_get_style_shadow_width(), lv_obj_get_style_text_align(), lv_obj_get_style_text_color(), lv_obj_get_style_text_color_filtered(), lv_obj_get_style_text_decor(), lv_obj_get_style_text_font(), lv_obj_get_style_text_letter_space(), lv_obj_get_style_text_line_space(), lv_obj_get_style_text_opa(), lv_obj_get_style_transform_angle(), lv_obj_get_style_transform_height(), lv_obj_get_style_transform_pivot_x(), lv_obj_get_style_transform_pivot_y(), lv_obj_get_style_transform_width(), lv_obj_get_style_transform_zoom(), lv_obj_get_style_transition(), lv_obj_get_style_translate_x(), lv_obj_get_style_translate_y(), lv_obj_get_style_width(), lv_obj_get_style_x(), and lv_obj_get_style_y().
lv_obj_refresh_style()
void lv_obj_refresh_style (struct _lv_obj_t * obj, lv_part_t part, lv_style_prop_t prop)
Notify an object and its children about its style is modified.
Parameters
obj pointer to an object
part the part whose style was changed. E.g. LV_PART_ANY, LV_PART_MAIN
prop LV_STYLE_PROP_ANY or an LV_STYLE_... property. It is used to optimize what needs to be refreshed. LV_STYLE_PROP_INV to perform only a style cache update
lv_obj_remove_local_style_prop()
bool lv_obj_remove_local_style_prop (struct _lv_obj_t * obj, lv_style_prop_t prop, lv_style_selector_t selector)
Remove a local style property from a part of an object with a given state.
Parameters
obj pointer to an object
prop a style property to remove.
selector OR-ed value of parts and state for which the style should be removed
Returns
true the property was found and removed; false: the property was not found
lv_obj_remove_style()
void lv_obj_remove_style (struct _lv_obj_t * obj, lv_style_t * style, lv_style_selector_t selector)
Referenced by lv_obj_remove_style_all().
lv_obj_remove_style_all()
static void lv_obj_remove_style_all (struct _lv_obj_t * obj) inline static
Remove all styles from an object
Parameters
obj pointer to an object
Definition at line 92 of file lv_obj_style.h.
{
    lv_obj_remove_style(obj, NULL, LV_PART_ANY | LV_STATE_ANY);
}
References lv_obj_remove_style(), LV_PART_ANY, and LV_STATE_ANY.
lv_obj_report_style_change()
void lv_obj_report_style_change (lv_style_t * style)
Notify all object if a style is modified
Parameters
style pointer to a style. Only the objects with this style will be notified (NULL to notify all objects)
lv_obj_set_local_style_prop()
void lv_obj_set_local_style_prop (struct _lv_obj_t * obj, lv_style_prop_t prop, lv_style_value_t value, lv_style_selector_t selector)
Set local style property on an object's part and state.
Parameters
obj pointer to an object
prop the property
value value of the property. The correct element should be set according to the type of the property
selector OR-ed value of parts and state for which the style should be set
lv_obj_set_local_style_prop_meta()
void lv_obj_set_local_style_prop_meta (struct _lv_obj_t * obj, lv_style_prop_t prop, uint16_t meta, lv_style_selector_t selector)
lv_obj_set_style_pad_all()
static void lv_obj_set_style_pad_all (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector) inline static
Definition at line 205 of file lv_obj_style.h.
{
    lv_obj_set_style_pad_left(obj, value, selector);
    lv_obj_set_style_pad_right(obj, value, selector);
    lv_obj_set_style_pad_top(obj, value, selector);
    lv_obj_set_style_pad_bottom(obj, value, selector);
}
References lv_obj_set_style_pad_bottom(), lv_obj_set_style_pad_left(), lv_obj_set_style_pad_right(), and lv_obj_set_style_pad_top().
lv_obj_set_style_pad_gap()
static void lv_obj_set_style_pad_gap (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector) inline static
Definition at line 225 of file lv_obj_style.h.
{
    lv_obj_set_style_pad_row(obj, value, selector);
    lv_obj_set_style_pad_column(obj, value, selector);
}
References lv_obj_set_style_pad_column(), and lv_obj_set_style_pad_row().
lv_obj_set_style_pad_hor()
static void lv_obj_set_style_pad_hor (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector) inline static
Definition at line 213 of file lv_obj_style.h.
{
    lv_obj_set_style_pad_left(obj, value, selector);
    lv_obj_set_style_pad_right(obj, value, selector);
}
References lv_obj_set_style_pad_left(), and lv_obj_set_style_pad_right().
lv_obj_set_style_pad_ver()
static void lv_obj_set_style_pad_ver (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector) inline static
Definition at line 219 of file lv_obj_style.h.
{
    lv_obj_set_style_pad_top(obj, value, selector);
    lv_obj_set_style_pad_bottom(obj, value, selector);
}
References lv_obj_set_style_pad_bottom(), and lv_obj_set_style_pad_top().
lv_obj_set_style_size()
static void lv_obj_set_style_size (struct _lv_obj_t * obj, lv_coord_t value, lv_style_selector_t selector) inline static
Definition at line 231 of file lv_obj_style.h.
{
    lv_obj_set_style_width(obj, value, selector);
    lv_obj_set_style_height(obj, value, selector);
}
References lv_obj_set_style_height(), and lv_obj_set_style_width().
lv_obj_style_get_selector_part()
lv_part_t lv_obj_style_get_selector_part (lv_style_selector_t selector)
lv_obj_style_get_selector_state()
lv_state_t lv_obj_style_get_selector_state (lv_style_selector_t selector)