1516X High Stakes: fmt::v10::detail Namespace Reference
fmt::v10::detail Namespace Reference
Namespaces
namespace dragonbox
Classes
struct arg_data
struct arg_data< T, Char, NUM_ARGS, 0 >
struct arg_formatter
struct arg_mapper
struct arg_ref
struct basic_data
struct basic_fp
struct big_decimal_fp
class bigint
class buffer
struct buffer_traits
struct char_t_impl
struct char_t_impl< S, enable_if_t< is_string< S >::value > >
class compile_parse_context
struct compile_string
class counting_buffer
class counting_iterator
struct custom_formatter
struct custom_value
struct data
struct default_arg_formatter
class digit_grouping
class dynamic_arg_list
struct dynamic_format_specs
struct dynamic_spec_id_handler
struct error_handler
class fallback_digit_grouping
struct fill_t
struct find_escape_result
class fixed_buffer_traits
struct float_specs
struct format_as_result
struct format_decimal_result
class format_string_checker
class formatbuf
struct has_format_as
struct has_isfinite
struct has_isfinite< T, enable_if_t< sizeof(std::isfinite(T())) !=0 > >
struct is_back_insert_iterator
struct is_back_insert_iterator< std::back_insert_iterator< Container > >
struct is_compile_string
struct is_integral
struct is_integral< int128_opt >
struct is_integral< uint128_t >
struct is_named_arg
struct is_named_arg< named_arg< Char, T > >
struct is_output_iterator
struct is_output_iterator< It, T, void_t< typename std::iterator_traits< It >::iterator_category, decltype(*std::declval< It >()=std::declval< T >())> >
struct is_reference_wrapper
struct is_reference_wrapper< std::reference_wrapper< T > >
struct is_statically_named_arg
struct is_string
class iterator_buffer
class iterator_buffer< std::back_insert_iterator< Container >, enable_if_t< is_contiguous< Container >::value, typename Container::value_type > >
class iterator_buffer< T *, T >
class iterator_buffer< T *, T, fixed_buffer_traits >
struct loc_writer
class locale_ref
struct named_arg
struct named_arg_info
struct named_arg_value
class precision_checker
struct singleton
struct std_string_view
struct string_literal
struct string_value
struct strip_named_arg
struct strip_named_arg< T, true >
struct thousands_sep_result
class to_utf8
struct type_constant
struct type_constant< basic_string_view< Char >, Char >
struct type_constant< bool, Char >
struct type_constant< Char, Char >
struct type_constant< const Char *, Char >
struct type_constant< const void *, Char >
struct type_constant< double, Char >
struct type_constant< float, Char >
struct type_constant< int, Char >
struct type_constant< int128_opt, Char >
struct type_constant< long double, Char >
struct type_constant< long long, Char >
struct type_constant< uint128_opt, Char >
struct type_constant< unsigned long long, Char >
struct type_constant< unsigned, Char >
class uint128_fallback
struct unformattable
struct unformattable_char
struct unformattable_pointer
class utf8_to_utf16
class value
struct vformat_args
struct vformat_args< char >
struct view
class width_checker
struct write_int_arg
struct write_int_data
Typedefs
template<typename T >
using buffer_appender
using long_type = conditional_t<long_short, int, long long>
using ulong_type = conditional_t<long_short, unsigned, unsigned long long>
template<typename T >
using format_as_t = typename format_as_result<T>::type
template<typename T , typename Context >
using mapped_type_constant
template<typename... >
using void_t = void
using uint128_t = conditional_t< 0 , uint128_opt, uint128_fallback>
using uintptr_t = uint128_t
template<typename T >
using iterator_t = decltype(std::begin(std::declval<T&>()))
template<typename T >
using sentinel_t = decltype(std::end(std::declval<T&>()))
template<typename OutputIt >
using reserve_iterator
template<typename T >
using is_signed
template<typename T >
using is_integer
using float128 = void
template<typename T >
using is_float128 = std::is_same<T, float128>
template<typename T >
using is_floating_point
template<typename T >
using uint32_or_64_or_128_t
template<typename T >
using uint64_or_128_t = conditional_t<num_bits<T>() <= 64, uint64_t, uint128_t>
using fp = basic_fp<unsigned long long>
template<typename T , bool doublish = num_bits<T>() == num_bits<double>()>
using convert_float_result
template<typename Char >
using make_unsigned_char
using format_func = void (*)(detail::buffer<char>&, int, const char*)
Enumerations
enum class int128_opt
enum class uint128_opt
enum class type {
none_type , int_type , uint_type , long_long_type ,
ulong_long_type , int128_type , uint128_type , bool_type ,
char_type , last_integer_type = char_type , float_type , double_type ,
long_double_type , last_numeric_type = long_double_type , cstring_type , string_type ,
pointer_type , custom_type
}
enum {
sint_set = set(type::int_type) | set(type::long_long_type) | set(type::int128_type) , uint_set = set(type::uint_type) | set(type::ulong_long_type) | set(type::uint128_type) , bool_set = set(type::bool_type) , char_set = set(type::char_type) ,
float_set = set(type::float_type) | set(type::double_type) | set(type::long_double_type) , string_set = set(type::string_type) , cstring_set = set(type::cstring_type) , pointer_set = set(type::pointer_type)
}
enum { long_short = sizeof(long) == sizeof(int) }
enum { packed_arg_bits = 4 }
enum { max_packed_args = 62 / packed_arg_bits }
enum : unsigned long long { is_unpacked_bit = 1ULL << 63 }
enum : unsigned long long { has_named_args_bit = 1ULL << 62 }
enum class arg_id_kind { none , index , name }
enum class state {
start , align , sign , hash ,
zero , width , precision , locale
}
enum char8_type : unsigned char
enum class to_utf8_error_policy { abort , replace }
enum class float_format : unsigned char { general , exp , fixed , hex }
enum dragon { predecessor_closer = 1 , fixup = 2 , fixed = 4 }
Functions
template<typename T >
const T & unwrap (const T &v)
template<typename T >
const T & unwrap (const std::reference_wrapper< T > &v)
template<typename... T>
void ignore_unused (const T &...)
constexpr auto is_constant_evaluated (bool default_value=false) noexcept -> bool
template<typename T >
constexpr auto const_check (T value) -> T
void assert_fail (const char *file, int line, const char *message)
template<typename T >
auto convert_for_visit (T) -> monostate
template<typename Int >
auto to_unsigned (Int value) -> typename std::make_unsigned< Int >::type
auto is_utf8 () -> bool
template<typename Char , fmt::enable_if_t<(is_char< Char >::value), int > = 0>
auto to_string_view (const Char *s) -> basic_string_view< Char >
template<typename Char , typename Traits , typename Alloc >
auto to_string_view (const std::basic_string< Char, Traits, Alloc > &s) -> basic_string_view< Char >
template<typename Char >
constexpr auto to_string_view (basic_string_view< Char > s) -> basic_string_view< Char >
template<typename Char , fmt::enable_if_t<(!std::is_empty< std_string_view< Char > >::value), int > = 0>
auto to_string_view (std_string_view< Char > s) -> basic_string_view< Char >
template<typename S , fmt::enable_if_t<(is_compile_string< S >::value), int > = 0>
constexpr auto to_string_view (const S &s) -> basic_string_view< typename S::char_type >
void to_string_view (...)
constexpr bool is_integral_type (type t)
constexpr bool is_arithmetic_type (type t)
constexpr auto set (type rhs) -> int
constexpr auto in (type t, int set) -> bool
void throw_format_error (const char *message)
template<typename Container >
auto get_container (std::back_insert_iterator< Container > it) -> Container &
template<typename Char , typename InputIt , typename OutputIt >
auto copy_str (InputIt begin, InputIt end, OutputIt out) -> OutputIt
template<typename Char , typename T , typename U , fmt::enable_if_t<(std::is_same< remove_const_t< T >, U >::value &&is_char< U >::value), int > = 0>
auto copy_str (T *begin, T *end, U *out) -> U *
template<typename Context , typename T >
constexpr auto has_const_formatter_impl (T *) -> decltype(typename Context::template formatter_type< T >().format(std::declval< const T & >(), std::declval< Context & >()), true)
template<typename Context >
constexpr auto has_const_formatter_impl (...) -> bool
template<typename T , typename Context >
constexpr auto has_const_formatter () -> bool
template<typename T , typename OutputIt >
auto get_buffer (OutputIt out) -> iterator_buffer< OutputIt, T >
template<typename T , typename Buf , fmt::enable_if_t<(std::is_base_of< buffer< char >, Buf >::value), int > = 0>
auto get_buffer (std::back_insert_iterator< Buf > out) -> buffer< char > &
template<typename Buf , typename OutputIt >
auto get_iterator (Buf &buf, OutputIt) -> decltype(buf.out())
template<typename T , typename OutputIt >
auto get_iterator (buffer< T > &, OutputIt out) -> OutputIt
template<typename Char >
void init_named_args (named_arg_info< Char > *, int, int)
template<typename Char , typename T , typename... Tail, fmt::enable_if_t<(!is_named_arg< T >::value), int > = 0>
void init_named_args (named_arg_info< Char > *named_args, int arg_count, int named_arg_count, const T &, const Tail &... args)
template<typename... Args>
void init_named_args (std::nullptr_t, int, int, const Args &...)
template<bool B = false>
constexpr auto count () -> size_t
template<bool B1, bool B2, bool... Tail>
constexpr auto count () -> size_t
template<typename... Args>
constexpr auto count_named_args () -> size_t
template<typename... Args>
constexpr auto count_statically_named_args () -> size_t
template<typename Char , typename InputIt >
auto copy_str (InputIt begin, InputIt end, appender out) -> appender
template<typename Char , typename InputIt >
auto copy_str (InputIt begin, InputIt end, std::back_insert_iterator< std::string > out) -> std::back_insert_iterator< std::string >
template<typename Char , typename R , typename OutputIt >
auto copy_str (R &&rng, OutputIt out) -> OutputIt
template<typename >
constexpr auto encode_types () -> unsigned long long
template<typename Context , typename Arg , typename... Args>
constexpr auto encode_types () -> unsigned long long
template<bool PACKED, typename Context , typename T , fmt::enable_if_t<(PACKED), int > = 0>
auto make_arg (T &val) -> value< Context >
template<typename Context , typename T >
auto make_arg (T &val) -> basic_format_arg< Context >
template<typename Char , fmt::enable_if_t<(std::is_integral< Char >::value), int > = 0>
constexpr auto to_ascii (Char c) -> char
template<typename Char >
auto code_point_length (const Char *begin) -> int
template<bool IS_CONSTEXPR, typename T , typename Ptr = const T*>
auto find (Ptr first, Ptr last, T value, Ptr &out) -> bool
template<>
auto find< false, char > (const char *first, const char *last, char value, const char *&out) -> bool
template<typename Char >
auto parse_nonnegative_int (const Char *&begin, const Char *end, int error_value) noexcept -> int
auto parse_align (char c) -> align_t
template<typename Char >
constexpr auto is_name_start (Char c) -> bool
template<typename Char , typename Handler >
auto do_parse_arg_id (const Char *begin, const Char *end, Handler &&handler) -> const Char *
template<typename Char , typename Handler >
auto parse_arg_id (const Char *begin, const Char *end, Handler &&handler) -> const Char *
template<typename Char >
auto parse_dynamic_spec (const Char *begin, const Char *end, int &value, arg_ref< Char > &ref, basic_format_parse_context< Char > &ctx) -> const Char *
template<typename Char >
auto parse_precision (const Char *begin, const Char *end, int &value, arg_ref< Char > &ref, basic_format_parse_context< Char > &ctx) -> const Char *
template<typename Char >
auto parse_format_specs (const Char *begin, const Char *end, dynamic_format_specs< Char > &specs, basic_format_parse_context< Char > &ctx, type arg_type) -> const Char *
template<typename Char , typename Handler >
auto parse_replacement_field (const Char *begin, const Char *end, Handler &&handler) -> const Char *
template<bool IS_CONSTEXPR, typename Char , typename Handler >
void parse_format_string (basic_string_view< Char > format_str, Handler &&handler)
template<typename T , typename ParseContext >
auto parse_format_specs (ParseContext &ctx) -> decltype(ctx.begin())
template<typename Char >
auto check_char_specs (const format_specs< Char > &specs) -> bool
template<typename... Args, typename Char >
auto get_arg_index_by_name (basic_string_view< Char > name) -> int
template<typename... , typename S , fmt::enable_if_t<(!is_compile_string< S >::value), int > = 0>
void check_format_string (const S &)
template<typename... Args, typename S , fmt::enable_if_t<(is_compile_string< S >::value), int > = 0>
void check_format_string (S format_str)
template<typename Char >
void vformat_to (buffer< Char > &buf, basic_string_view< Char > fmt, typename vformat_args< Char >::type args, locale_ref loc={})
void vprint_mojibake (std::FILE *, string_view, format_args)
void format_error_code (detail::buffer< char > &out, int error_code, string_view message) noexcept
void report_error (format_func func, int error_code, const char *message) noexcept
void fwrite_fully (const void *ptr, size_t size, size_t count, FILE *stream)
template<typename Char >
auto thousands_sep_impl (locale_ref loc) -> thousands_sep_result< Char >
template<typename Char >
Char decimal_point_impl (locale_ref loc)
auto write_loc (appender out, loc_value value, const format_specs<> &specs, locale_ref loc) -> bool
template<typename F >
bool operator== (basic_fp< F > x, basic_fp< F > y)
uint32_t rotr (uint32_t n, uint32_t r) noexcept
uint64_t rotr (uint64_t n, uint32_t r) noexcept
bool write_console (std::FILE *, string_view)
void print (std::FILE *f, string_view text)
auto is_printable (uint16_t x, const singleton *singletons, size_t singletons_size, const unsigned char *singleton_lowers, const unsigned char *normal, size_t normal_size) -> bool
auto is_printable (uint32_t cp) -> bool
void abort_fuzzing_if (bool condition)
template<typename To , typename From , fmt::enable_if_t<(sizeof(To)==sizeof(From)), int > = 0>
auto bit_cast (const From &from) -> To
auto is_big_endian () -> bool
template<typename T >
constexpr auto max_value () -> T
template<typename T >
constexpr auto num_bits () -> int
template<>
constexpr auto num_bits< int128_opt > () -> int
template<>
constexpr auto num_bits< uint128_t > () -> int
template<typename UInt >
auto countl_zero_fallback (UInt n) -> int
auto countl_zero (uint32_t n) -> int
auto countl_zero (uint64_t n) -> int
void assume (bool condition)
template<typename Char >
auto get_data (std::basic_string< Char > &s) -> Char *
template<typename Container >
auto get_data (Container &c) -> typename Container::value_type *
template<typename Container , fmt::enable_if_t<(is_contiguous< Container >::value), int > = 0>
auto reserve (std::back_insert_iterator< Container > it, size_t n) -> typename Container::value_type *
template<typename T >
auto reserve (buffer_appender< T > it, size_t n) -> buffer_appender< T >
template<typename Iterator >
constexpr auto reserve (Iterator &it, size_t) -> Iterator &
template<typename T , typename OutputIt >
constexpr auto to_pointer (OutputIt, size_t) -> T *
template<typename T >
auto to_pointer (buffer_appender< T > it, size_t n) -> T *
template<typename Container , fmt::enable_if_t<(is_contiguous< Container >::value), int > = 0>
auto base_iterator (std::back_insert_iterator< Container > it, typename Container::value_type *) -> std::back_insert_iterator< Container >
template<typename Iterator >
constexpr auto base_iterator (Iterator, Iterator it) -> Iterator
template<typename OutputIt , typename Size , typename T >
auto fill_n (OutputIt out, Size count, const T &value) -> OutputIt
template<typename T , typename Size >
auto fill_n (T *out, Size count, char value) -> T *
template<typename OutChar , typename InputIt , typename OutputIt >
auto copy_str_noinline (InputIt begin, InputIt end, OutputIt out) -> OutputIt
auto utf8_decode (const char *s, uint32_t *c, int *e) -> const char *
template<typename F >
void for_each_codepoint (string_view s, F f)
template<typename Char >
auto compute_width (basic_string_view< Char > s) -> size_t
size_t compute_width (string_view s)
auto compute_width (basic_string_view< char8_type > s) -> size_t
template<typename Char >
auto code_point_index (basic_string_view< Char > s, size_t n) -> size_t
auto code_point_index (string_view s, size_t n) -> size_t
auto code_point_index (basic_string_view< char8_type > s, size_t n) -> size_t
template<typename T , fmt::enable_if_t<(is_signed< T >::value), int > = 0>
constexpr auto is_negative (T value) -> bool
template<typename T >
auto is_supported_floating_point (T) -> bool
constexpr const char * digits2 (size_t value)
template<typename Char , typename Sign >
constexpr Char sign (Sign s)
template<typename T >
auto count_digits_fallback (T n) -> int
auto count_digits (uint64_t n) -> int
template<int BITS, typename UInt >
auto count_digits (UInt n) -> int
auto count_digits (uint32_t n) -> int
template<typename Int >
constexpr auto digits10 () noexcept -> int
template<>
constexpr auto digits10< int128_opt > () noexcept -> int
template<>
constexpr auto digits10< uint128_t > () noexcept -> int
template<typename Char >
auto thousands_sep (locale_ref loc) -> thousands_sep_result< Char >
template<>
auto thousands_sep (locale_ref loc) -> thousands_sep_result< wchar_t >
template<typename Char >
auto decimal_point_impl (locale_ref loc) -> Char
template<typename Char >
auto decimal_point (locale_ref loc) -> Char
template<>
auto decimal_point (locale_ref loc) -> wchar_t
template<typename Char >
auto equal2 (const Char *lhs, const char *rhs) -> bool
auto equal2 (const char *lhs, const char *rhs) -> bool
template<typename Char >
void copy2 (Char *dst, const char *src)
template<typename Char , typename UInt >
auto format_decimal (Char *out, UInt value, int size) -> format_decimal_result< Char * >
template<typename Char , typename UInt , typename Iterator , fmt::enable_if_t<(!std::is_pointer< remove_cvref_t< Iterator > >::value), int > = 0>
auto format_decimal (Iterator out, UInt value, int size) -> format_decimal_result< Iterator >
template<unsigned BASE_BITS, typename Char , typename UInt >
auto format_uint (Char *buffer, UInt value, int num_digits, bool upper=false) -> Char *
template<unsigned BASE_BITS, typename Char , typename It , typename UInt >
auto format_uint (It out, UInt value, int num_digits, bool upper=false) -> It
uint128_fallback umul128 (uint64_t x, uint64_t y) noexcept
template<typename Float >
constexpr bool has_implicit_bit ()
template<typename Float >
constexpr int num_significand_bits ()
template<typename Float >
constexpr auto exponent_mask () -> typename dragonbox::float_info< Float >::carrier_uint
template<typename Float >
constexpr auto exponent_bias () -> int
template<typename Char , typename It >
auto write_exponent (int exp, It it) -> It
template<int SHIFT = 0, typename F >
basic_fp< F > normalize (basic_fp< F > value)
uint64_t multiply (uint64_t lhs, uint64_t rhs)
fp operator* (fp x, fp y)
template<typename T >
constexpr auto convert_float (T value) -> convert_float_result< T >
template<typename OutputIt , typename Char >
auto fill (OutputIt it, size_t n, const fill_t< Char > &fill) -> OutputIt
template<align::type align = align::left, typename OutputIt , typename Char , typename F >
auto write_padded (OutputIt out, const format_specs< Char > &specs, size_t size, size_t width, F &&f) -> OutputIt
template<align::type align = align::left, typename OutputIt , typename Char , typename F >
constexpr auto write_padded (OutputIt out, const format_specs< Char > &specs, size_t size, F &&f) -> OutputIt
template<align::type align = align::left, typename Char , typename OutputIt >
auto write_bytes (OutputIt out, string_view bytes, const format_specs< Char > &specs) -> OutputIt
template<typename Char , typename OutputIt , typename UIntPtr >
auto write_ptr (OutputIt out, UIntPtr value, const format_specs< Char > *specs) -> OutputIt
auto needs_escape (uint32_t cp) -> bool
template<typename Char >
auto find_escape (const Char *begin, const Char *end) -> find_escape_result< Char >
auto find_escape (const char *begin, const char *end) -> find_escape_result< char >
template<size_t width, typename Char , typename OutputIt >
auto write_codepoint (OutputIt out, char prefix, uint32_t cp) -> OutputIt
template<typename OutputIt , typename Char >
auto write_escaped_cp (OutputIt out, const find_escape_result< Char > &escape) -> OutputIt
template<typename Char , typename OutputIt >
auto write_escaped_string (OutputIt out, basic_string_view< Char > str) -> OutputIt
template<typename Char , typename OutputIt >
auto write_escaped_char (OutputIt out, Char v) -> OutputIt
template<typename Char , typename OutputIt >
auto write_char (OutputIt out, Char value, const format_specs< Char > &specs) -> OutputIt
template<typename Char , typename OutputIt >
auto write (OutputIt out, Char value, const format_specs< Char > &specs, locale_ref loc={}) -> OutputIt
template<typename OutputIt , typename Char , typename W >
auto write_int (OutputIt out, int num_digits, unsigned prefix, const format_specs< Char > &specs, W write_digits) -> OutputIt
template<typename OutputIt , typename UInt , typename Char >
auto write_int (OutputIt out, UInt value, unsigned prefix, const format_specs< Char > &specs, const digit_grouping< Char > &grouping) -> OutputIt
template<typename OutputIt , typename Char >
auto write_loc (OutputIt, loc_value, const format_specs< Char > &, locale_ref) -> bool
void prefix_append (unsigned &prefix, unsigned value)
template<typename T >
auto make_write_int_arg (T value, sign_t sign) -> write_int_arg< uint32_or_64_or_128_t< T > >
template<typename Char , typename OutputIt , typename T >
auto write_int (OutputIt out, write_int_arg< T > arg, const format_specs< Char > &specs, locale_ref) -> OutputIt
template<typename Char , typename OutputIt , typename T >
auto write_int_noinline (OutputIt out, write_int_arg< T > arg, const format_specs< Char > &specs, locale_ref loc) -> OutputIt
template<typename Char , typename OutputIt , typename T , fmt::enable_if_t<(is_integral< T >::value &&!std::is_same< T, bool >::value &&std::is_same< OutputIt, buffer_appender< Char > >::value), int > = 0>
auto write (OutputIt out, T value, const format_specs< Char > &specs, locale_ref loc) -> OutputIt
template<typename Char , typename OutputIt >
auto write (OutputIt out, basic_string_view< Char > s, const format_specs< Char > &specs) -> OutputIt
template<typename Char , typename OutputIt >
auto write (OutputIt out, basic_string_view< type_identity_t< Char > > s, const format_specs< Char > &specs, locale_ref) -> OutputIt
template<typename Char , typename OutputIt >
auto write (OutputIt out, const Char *s, const format_specs< Char > &specs, locale_ref) -> OutputIt
template<typename Char , typename OutputIt , typename T , fmt::enable_if_t<(is_integral< T >::value &&!std::is_same< T, bool >::value &&!std::is_same< T, Char >::value), int > = 0>
auto write (OutputIt out, T value) -> OutputIt
template<typename Char >
auto parse_align (const Char *begin, const Char *end, format_specs< Char > &specs) -> const Char *
template<typename ErrorHandler = error_handler, typename Char >
auto parse_float_type_spec (const format_specs< Char > &specs, ErrorHandler &&eh={}) -> float_specs
template<typename Char , typename OutputIt >
auto write_nonfinite (OutputIt out, bool isnan, format_specs< Char > specs, const float_specs &fspecs) -> OutputIt
constexpr auto get_significand_size (const big_decimal_fp &f) -> int
template<typename T >
auto get_significand_size (const dragonbox::decimal_fp< T > &f) -> int
template<typename Char , typename OutputIt >
constexpr auto write_significand (OutputIt out, const char *significand, int significand_size) -> OutputIt
template<typename Char , typename OutputIt , typename UInt >
auto write_significand (OutputIt out, UInt significand, int significand_size) -> OutputIt
template<typename Char , typename OutputIt , typename T , typename Grouping >
auto write_significand (OutputIt out, T significand, int significand_size, int exponent, const Grouping &grouping) -> OutputIt
template<typename Char , typename UInt , fmt::enable_if_t<(std::is_integral< UInt >::value), int > = 0>
auto write_significand (Char *out, UInt significand, int significand_size, int integral_size, Char decimal_point) -> Char *
template<typename OutputIt , typename UInt , typename Char , fmt::enable_if_t<(!std::is_pointer< remove_cvref_t< OutputIt > >::value), int > = 0>
auto write_significand (OutputIt out, UInt significand, int significand_size, int integral_size, Char decimal_point) -> OutputIt
template<typename OutputIt , typename Char >
auto write_significand (OutputIt out, const char *significand, int significand_size, int integral_size, Char decimal_point) -> OutputIt
template<typename OutputIt , typename Char , typename T , typename Grouping >
auto write_significand (OutputIt out, T significand, int significand_size, int integral_size, Char decimal_point, const Grouping &grouping) -> OutputIt
template<typename OutputIt , typename DecimalFP , typename Char , typename Grouping = digit_grouping<Char>>
auto do_write_float (OutputIt out, const DecimalFP &f, const format_specs< Char > &specs, float_specs fspecs, locale_ref loc) -> OutputIt
template<typename OutputIt , typename DecimalFP , typename Char >
auto write_float (OutputIt out, const DecimalFP &f, const format_specs< Char > &specs, float_specs fspecs, locale_ref loc) -> OutputIt
template<typename T >
constexpr bool isnan (T value)
template<typename T , fmt::enable_if_t<(std::is_floating_point< T >::value &&has_isfinite< T >::value), int > = 0>
bool isfinite (T value)
template<typename T , fmt::enable_if_t<(is_floating_point< T >::value), int > = 0>
bool signbit (T value)
void adjust_precision (int &precision, int exp10)
void format_dragon (basic_fp< uint128_t > value, unsigned flags, int num_digits, buffer< char > &buf, int &exp10)
template<typename Float , fmt::enable_if_t<(!is_double_double< Float >::value), int > = 0>
void format_hexfloat (Float value, int precision, float_specs specs, buffer< char > &buf)
template<typename Float >
auto format_float (Float value, int precision, float_specs specs, buffer< char > &buf) -> int
template<typename Char , typename OutputIt , typename T >
auto write_float (OutputIt out, T value, format_specs< Char > specs, locale_ref loc) -> OutputIt
template<typename Char , typename OutputIt , typename T , fmt::enable_if_t<(is_floating_point< T >::value), int > = 0>
auto write (OutputIt out, T value, format_specs< Char > specs, locale_ref loc={}) -> OutputIt
template<typename Char , typename OutputIt >
auto write (OutputIt out, monostate, format_specs< Char >={}, locale_ref={}) -> OutputIt
template<typename Char , typename OutputIt >
auto write (OutputIt out, basic_string_view< Char > value) -> OutputIt
template<typename Char , typename OutputIt , typename T , fmt::enable_if_t<(is_string< T >::value), int > = 0>
constexpr auto write (OutputIt out, const T &value) -> OutputIt
template<typename Char , typename OutputIt , typename T , bool check = std::is_enum<T>::value && !std::is_same<T, Char>::value && mapped_type_constant<T, basic_format_context<OutputIt, Char>>::value != type::custom_type, fmt::enable_if_t<(check), int > = 0>
auto write (OutputIt out, T value) -> OutputIt
template<typename Char , typename OutputIt >
auto write (OutputIt out, Char value) -> OutputIt
template<typename Char , typename OutputIt >
auto write (OutputIt out, const Char *value) -> OutputIt
template<typename Char , typename OutputIt , typename T , fmt::enable_if_t<(std::is_same< T, void >::value), int > = 0>
auto write (OutputIt out, const T *value, const format_specs< Char > &specs={}, locale_ref={}) -> OutputIt
template<typename Char , typename OutputIt , typename T , typename Context = basic_format_context<OutputIt, Char>>
auto write (OutputIt out, const T &value) -> enable_if_t< std::is_class< T >::value &&!is_string< T >::value &&!is_floating_point< T >::value &&!std::is_same< T, Char >::value &&!std::is_same< T, remove_cvref_t< decltype(arg_mapper< Context >().map(value))> >::value, OutputIt >
template<template< typename > class Handler, typename FormatArg , typename ErrorHandler >
auto get_dynamic_spec (FormatArg arg, ErrorHandler eh) -> int
template<typename Context , typename ID >
auto get_arg (Context &ctx, ID id) -> decltype(ctx.arg(id))
template<template< typename > class Handler, typename Context >
void handle_dynamic_spec (int &value, arg_ref< typename Context::char_type > ref, Context &ctx)
template<typename Locale , typename Char >
auto vformat (const Locale &loc, basic_string_view< Char > fmt, basic_format_args< buffer_context< type_identity_t< Char > > > args) -> std::basic_string< Char >
template void vformat_to (buffer< char > &, string_view, typename vformat_args<>::type, locale_ref)
template auto thousands_sep_impl< char > (locale_ref) -> thousands_sep_result< char >
template auto thousands_sep_impl< wchar_t > (locale_ref) -> thousands_sep_result< wchar_t >
template auto decimal_point_impl (locale_ref) -> char
Variables
constexpr uint32_t invalid_code_point = ~uint32_t()
Typedef Documentation
buffer_appender
template<typename T > using fmt::v10::detail::buffer_appender
Initial value:
    conditional_t<std::is_same<T, char>::value, appender, std::back_insert_iterator<buffer<T>>>
Definition at line 1036 of file core.h.
convert_float_result
template<typename T , bool doublish = num_bits<T>() == num_bits<double>()> using fmt::v10::detail::convert_float_result
Initial value:
    conditional_t<std::is_same<T, float>::value || doublish, double, T>
Definition at line 1655 of file format.h.
float128
using fmt::v10::detail::float128 = void
Definition at line 810 of file format.h.
format_as_t
template<typename T > using fmt::v10::detail::format_as_t = typename format_as_result<T>::type
Definition at line 1253 of file core.h.
format_func
using fmt::v10::detail::format_func = void (*)(detail::buffer<char>&, int, const char*)
Definition at line 3586 of file format.h.
fp
using fmt::v10::detail::fp = basic_fp<unsigned long long>
Definition at line 1594 of file format.h.
is_float128
template<typename T > using fmt::v10::detail::is_float128 = std::is_same<T, float128>
Definition at line 812 of file format.h.
is_floating_point
template<typename T > using fmt::v10::detail::is_floating_point
Initial value:
    bool_constant<std::is_floating_point<T>::value || is_float128<T>::value>
Definition at line 814 of file format.h.
is_integer
template<typename T > using fmt::v10::detail::is_integer
Initial value:
    bool_constant<is_integral<T>::value && !std::is_same<T, bool>::value && !std::is_same<T, char>::value &&
                  !std::is_same<T, wchar_t>::value>
Definition at line 776 of file format.h.
is_signed
template<typename T > using fmt::v10::detail::is_signed
Initial value:
    std::integral_constant<bool, std::numeric_limits<T>::is_signed || std::is_same<T, int128_opt>::value>
Definition at line 773 of file format.h.
iterator_t
template<typename T > using fmt::v10::detail::iterator_t = decltype(std::begin(std::declval<T&>()))
Definition at line 545 of file format.h.
long_type
using fmt::v10::detail::long_type = conditional_t<long_short, int, long long>
Definition at line 1242 of file core.h.
make_unsigned_char
template<typename Char > using fmt::v10::detail::make_unsigned_char
Initial value:
    typename conditional_t<std::is_integral<Char>::value, std::make_unsigned<Char>, type_identity<uint32_t>>::type
Definition at line 1730 of file format.h.
mapped_type_constant
template<typename T , typename Context > using fmt::v10::detail::mapped_type_constant
Initial value:
    type_constant<decltype(arg_mapper<Context>().map(std::declval<const T&>())), typename Context::char_type>
Definition at line 1384 of file core.h.
reserve_iterator
template<typename OutputIt > using fmt::v10::detail::reserve_iterator
Initial value:
    remove_reference_t<decltype(reserve(std::declval<OutputIt&>(), 0))>
Definition at line 575 of file format.h.
sentinel_t
template<typename T > using fmt::v10::detail::sentinel_t = decltype(std::end(std::declval<T&>()))
Definition at line 546 of file format.h.
uint128_t
using fmt::v10::detail::uint128_t = conditional_t< 0 , uint128_opt, uint128_fallback>
Definition at line 476 of file format.h.
uint32_or_64_or_128_t
template<typename T > using fmt::v10::detail::uint32_or_64_or_128_t
Initial value:
    conditional_t<num_bits<T>() <= 32 && ! 0 , uint32_t,
                  conditional_t<num_bits<T>() <= 64, uint64_t, uint128_t>>
Definition at line 1080 of file format.h.
uint64_or_128_t
template<typename T > using fmt::v10::detail::uint64_or_128_t = conditional_t<num_bits<T>() <= 64, uint64_t, uint128_t>
Definition at line 1083 of file format.h.
uintptr_t
using fmt::v10::detail::uintptr_t = uint128_t
Definition at line 481 of file format.h.
ulong_type
using fmt::v10::detail::ulong_type = conditional_t<long_short, unsigned, unsigned long long>
Definition at line 1243 of file core.h.
void_t
template<typename... > using fmt::v10::detail::void_t = void
Definition at line 1420 of file core.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
sint_set
uint_set
bool_set
char_set
float_set
string_set
cstring_set
pointer_set
Definition at line 568 of file core.h.
     {
    sint_set = set(type::int_type) | set(type::long_long_type) | set(type::int128_type),
    uint_set = set(type::uint_type) | set(type::ulong_long_type) | set(type::uint128_type),
    bool_set = set(type::bool_type),
    char_set = set(type::char_type),
    float_set = set(type::float_type) | set(type::double_type) | set(type::long_double_type),
    string_set = set(type::string_type),
    cstring_set = set(type::cstring_type),
    pointer_set = set(type::pointer_type)
};
anonymous enum
anonymous enum
Enumerator
long_short
Definition at line 1240 of file core.h.
{ long_short = sizeof(long) == sizeof(int) };
anonymous enum
anonymous enum
Enumerator
packed_arg_bits
Definition at line 1387 of file core.h.
{ packed_arg_bits = 4 };
anonymous enum
anonymous enum
Enumerator
max_packed_args
Definition at line 1390 of file core.h.
{ max_packed_args = 62 / packed_arg_bits };
anonymous enum
anonymous enum : unsigned long long
Enumerator
is_unpacked_bit
Definition at line 1392 of file core.h.
: unsigned long long { is_unpacked_bit = 1ULL << 63 };
anonymous enum
anonymous enum : unsigned long long
Enumerator
has_named_args_bit
Definition at line 1394 of file core.h.
: unsigned long long { has_named_args_bit = 1ULL << 62 };
arg_id_kind
enum class fmt::v10::detail::arg_id_kind strong
Enumerator
none
index
name
Definition at line 1903 of file core.h.
{ none, index, name };
char8_type
enum fmt::v10::detail::char8_type : unsigned char
Definition at line 613 of file format.h.
: unsigned char {};
dragon
enum fmt::v10::detail::dragon
Enumerator
predecessor_closer
fixup
fixed
Definition at line 2782 of file format.h.
            {
    predecessor_closer = 1,
    fixup = 2, // Run fixup to correct exp10 which can be off by one.
    fixed = 4,
};
float_format
enum class fmt::v10::detail::float_format : unsigned char strong
Enumerator
general
exp
fixed
hex
Definition at line 2234 of file format.h.
                        : unsigned char {
    general, // General: exponent notation or fixed point based on magnitude.
    exp, // Exponent notation with the default precision of 6, e.g. 1.2e-3.
    fixed, // Fixed point with the default precision of 6, e.g. 0.0012.
    hex
};
int128_opt
enum class fmt::v10::detail::int128_opt strong
Definition at line 340 of file core.h.
{};
state
enum class fmt::v10::detail::state strong
Enumerator
start
align
sign
hash
zero
width
precision
locale
Definition at line 2087 of file core.h.
{ start, align, sign, hash, zero, width, precision, locale };
to_utf8_error_policy
enum class fmt::v10::detail::to_utf8_error_policy strong
Enumerator
abort
replace
Definition at line 1326 of file format.h.
{ abort, replace };
type
enum class fmt::v10::detail::type strong
Enumerator
none_type
int_type
uint_type
long_long_type
ulong_long_type
int128_type
uint128_type
bool_type
char_type
last_integer_type
float_type
double_type
long_double_type
last_numeric_type
cstring_type
string_type
pointer_type
custom_type
Definition at line 515 of file core.h.
                {
    none_type,
    // Integer types should go first,
    int_type,
    uint_type,
    long_long_type,
    ulong_long_type,
    int128_type,
    uint128_type,
    bool_type,
    char_type,
    last_integer_type = char_type,
    // followed by floating-point types.
    float_type,
    double_type,
    long_double_type,
    last_numeric_type = long_double_type,
    cstring_type,
    string_type,
    pointer_type,
    custom_type
};
uint128_opt
enum class fmt::v10::detail::uint128_opt strong
Definition at line 341 of file core.h.
{};
Function Documentation
abort_fuzzing_if()
void fmt::v10::detail::abort_fuzzing_if (bool condition) inline
Definition at line 294 of file format.h.
{
    ignore_unused(condition);
#ifdef FMT_FUZZ
    if (condition) throw std::runtime_error("fuzzing limit reached");
#endif
}
References abort_fuzzing_if(), and ignore_unused().
Referenced by abort_fuzzing_if(), and do_write_float().
adjust_precision()
void fmt::v10::detail::adjust_precision (int & precision, int exp10) inline
Definition at line 2532 of file format.h.
{
    // Adjust fixed precision by exponent because it is relative to decimal
    // point.
    if (exp10 > 0 && precision > max_value<int>() - exp10) FMT_THROW(format_error("number is too big"));
    precision += exp10;
}
References adjust_precision(), FMT_THROW, and precision.
Referenced by adjust_precision(), format_dragon(), and format_float().
assert_fail()
void fmt::v10::detail::assert_fail (const char * file, int line, const char * message)
Definition at line 31 of file format-inl.h.
{
    // Use unchecked std::fprintf to avoid triggering another assertion when
    // writing to stderr fails
    std::fprintf(stderr, "%s:%d: assertion failed: %s", file, line, message);
    // Chosen instead of std::abort to satisfy Clang in CUDA mode during device
    // code pass.
    std::terminate();
}
References assert_fail().
Referenced by assert_fail().
assume()
void fmt::v10::detail::assume (bool condition) inline
Definition at line 535 of file format.h.
{
    (void)condition;
#if FMT_HAS_BUILTIN(__builtin_assume) && !FMT_ICC_VERSION
    __builtin_assume(condition);
#elif FMT_GCC_VERSION
    if (!condition) __builtin_unreachable();
#endif
}
References assume().
Referenced by assume().
base_iterator() [1/2]
template<typename Iterator > auto fmt::v10::detail::base_iterator (Iterator , Iterator it) -> Iterator constexpr
Definition at line 594 of file format.h.
{ return it; }
References base_iterator().
base_iterator() [2/2]
template<typename Container , fmt::enable_if_t<(is_contiguous< Container >::value), int > = 0> auto fmt::v10::detail::base_iterator (std::back_insert_iterator< Container > it, typename Container::value_type *) -> std::back_insert_iterator<Container> inline
Definition at line 589 of file format.h.
{
    return it;
}
References base_iterator().
Referenced by base_iterator(), base_iterator(), do_write_float(), write(), write(), write(), write_float(), write_int(), write_padded(), and write_ptr().
bit_cast()
template<typename To , typename From , fmt::enable_if_t<(sizeof(To)==sizeof(From)), int > = 0> auto fmt::v10::detail::bit_cast (const From & from) -> To inline
Definition at line 341 of file format.h.
{
#ifdef __cpp_lib_bit_cast
    if (is_constant_evaluated()) return std::bit_cast<To>(from);
#endif
    auto to = To();
    // The cast suppresses a bogus -Wclass-memaccess on GCC.
    std::memcpy(static_cast<void*>(&to), &from, sizeof(to));
    return to;
}
References bit_cast(), and is_constant_evaluated().
Referenced by bit_cast(), and fmt::v10::detail::dragonbox::to_decimal().
check_char_specs()
template<typename Char > auto fmt::v10::detail::check_char_specs (const format_specs< Char > & specs) -> bool
Definition at line 2337 of file core.h.
{
    if (specs.type != presentation_type::none && specs.type != presentation_type::chr &&
        specs.type != presentation_type::debug) {
        return false;
    }
    if (specs.align == align::numeric || specs.sign != sign::none || specs.alt)
        throw_format_error("invalid format specifier for char");
    return true;
}
References check_char_specs().
Referenced by check_char_specs().
check_format_string() [1/2]
template<typename... , typename S , fmt::enable_if_t<(!is_compile_string< S >::value), int > = 0> void fmt::v10::detail::check_format_string (const S &) inline
Definition at line 2420 of file core.h.
{
#ifdef FMT_ENFORCE_COMPILE_STRING
    static_assert(is_compile_string<S>::value, "FMT_ENFORCE_COMPILE_STRING requires all format strings to use "
                                               "FMT_STRING.");
#endif
}
References check_format_string().
Referenced by check_format_string(), and check_format_string().
check_format_string() [2/2]
template<typename... Args, typename S , fmt::enable_if_t<(is_compile_string< S >::value), int > = 0> void fmt::v10::detail::check_format_string (S format_str)
Definition at line 2428 of file core.h.
{
    using char_t = typename S::char_type;
    FMT_CONSTEXPR auto s = basic_string_view<char_t>(format_str);
    using checker = format_string_checker<char_t, remove_cvref_t<Args>...>;
    FMT_CONSTEXPR bool error = (parse_format_string<true>(s, checker(s)), true);
    ignore_unused(error);
}
References check_format_string(), FMT_CONSTEXPR, and ignore_unused().
code_point_index() [1/3]
template<typename Char > auto fmt::v10::detail::code_point_index (basic_string_view< Char > s, size_t n) -> size_t inline
Definition at line 748 of file format.h.
{
    size_t size = s.size();
    return n < size ? n : size;
}
References code_point_index().
Referenced by code_point_index(), code_point_index(), code_point_index(), and write().
code_point_index() [2/3]
auto fmt::v10::detail::code_point_index (basic_string_view< char8_type > s, size_t n) -> size_t inline
Definition at line 763 of file format.h.
{
    return code_point_index(string_view(reinterpret_cast<const char*>(s.data()), s.size()), n);
}
References code_point_index().
code_point_index() [3/3]
auto fmt::v10::detail::code_point_index (string_view s, size_t n) -> size_t inline
Definition at line 754 of file format.h.
{
    const char* data = s.data();
    size_t num_code_points = 0;
    for (size_t i = 0, size = s.size(); i != size; ++i) {
        if ((data[i] & 0xc0) != 0x80 && ++num_code_points > n) return i;
    }
    return s.size();
}
References code_point_index().
code_point_length()
template<typename Char > auto fmt::v10::detail::code_point_length (const Char * begin) -> int
Definition at line 1949 of file core.h.
{
    if (const_check(sizeof(Char) != 1)) return 1;
    auto c = static_cast<unsigned char>(*begin);
    return static_cast<int>((0x3a55000000000000ull >> (2 * (c >> 3))) & 0x3) + 1;
}
References code_point_length(), and const_check().
Referenced by code_point_length(), parse_align(), and parse_format_specs().
compute_width() [1/3]
template<typename Char > auto fmt::v10::detail::compute_width (basic_string_view< Char > s) -> size_t inline
Definition at line 706 of file format.h.
{ return s.size(); }
References compute_width().
Referenced by compute_width(), compute_width(), compute_width(), and write().
compute_width() [2/3]
auto fmt::v10::detail::compute_width (basic_string_view< char8_type > s) -> size_t inline
Definition at line 744 of file format.h.
{
    return compute_width(string_view(reinterpret_cast<const char*>(s.data()), s.size()));
}
References compute_width().
compute_width() [3/3]
size_t fmt::v10::detail::compute_width (string_view s) inline
Definition at line 709 of file format.h.
{
    size_t num_code_points = 0;
    // It is not a lambda for compatibility with C++14.
    struct count_code_points {
            size_t* count;
            FMT_CONSTEXPR auto operator()(uint32_t cp, string_view) const -> bool {
                *count += detail::to_unsigned(
                    1 + (cp >= 0x1100 && (cp <= 0x115f || // Hangul Jamo init. consonants
                                          cp == 0x2329 || // LEFT-POINTING ANGLE BRACKET
                                          cp == 0x232a || // RIGHT-POINTING ANGLE BRACKET
                                          // CJK ... Yi except IDEOGRAPHIC HALF FILL SPACE:
                                          (cp >= 0x2e80 && cp <= 0xa4cf && cp != 0x303f) ||
                                          (cp >= 0xac00 && cp <= 0xd7a3) || // Hangul Syllables
                                          (cp >= 0xf900 && cp <= 0xfaff) || // CJK Compatibility Ideographs
                                          (cp >= 0xfe10 && cp <= 0xfe19) || // Vertical Forms
                                          (cp >= 0xfe30 && cp <= 0xfe6f) || // CJK Compatibility Forms
                                          (cp >= 0xff00 && cp <= 0xff60) || // Fullwidth Forms
                                          (cp >= 0xffe0 && cp <= 0xffe6) || // Fullwidth Forms
                                          (cp >= 0x20000 && cp <= 0x2fffd) || // CJK
                                          (cp >= 0x30000 && cp <= 0x3fffd) ||
                                          // Miscellaneous Symbols and Pictographs + Emoticons:
                                          (cp >= 0x1f300 && cp <= 0x1f64f) ||
                                          // Supplemental Symbols and Pictographs:
                                          (cp >= 0x1f900 && cp <= 0x1f9ff))));
                return true;
            }
    };
    // We could avoid branches by using utf8_decode directly.
    for_each_codepoint(s, count_code_points {&num_code_points});
    return num_code_points;
}
References compute_width(), count(), FMT_CONSTEXPR, and for_each_codepoint().
const_check()
template<typename T > auto fmt::v10::detail::const_check (T value) -> T inline constexpr
Definition at line 304 of file core.h.
{ return value; }
References const_check().
Referenced by code_point_length(), const_check(), find_escape(), and write_float().
convert_float()
template<typename T > auto fmt::v10::detail::convert_float (T value) -> convert_float_result<T> constexpr
Definition at line 1658 of file format.h.
{
    return static_cast<convert_float_result<T>>(value);
}
References convert_float().
Referenced by convert_float(), format_float(), and write_float().
convert_for_visit()
template<typename T > auto fmt::v10::detail::convert_for_visit (T) -> monostate
Definition at line 344 of file core.h.
{ return {}; }
References convert_for_visit().
Referenced by convert_for_visit().
copy2()
template<typename Char > void fmt::v10::detail::copy2 (Char * dst, const char * src) inline
Definition at line 1238 of file format.h.
{
    if (!is_constant_evaluated() && sizeof(Char) == sizeof(char)) {
        memcpy(dst, src, 2);
        return;
    }
    *dst++ = static_cast<Char>(*src++);
    *dst = static_cast<Char>(*src);
}
References copy2(), and is_constant_evaluated().
Referenced by copy2(), format_decimal(), format_float(), and write_significand().
copy_str() [1/5]
template<typename Char , typename InputIt > auto fmt::v10::detail::copy_str (InputIt begin, InputIt end, appender out) -> appender
Definition at line 1396 of file core.h.
{
    get_container(out).append(begin, end);
    return out;
}
References copy_str(), and get_container().
copy_str() [2/5]
template<typename Char , typename InputIt , typename OutputIt > auto fmt::v10::detail::copy_str (InputIt begin, InputIt end, OutputIt out) -> OutputIt
Definition at line 718 of file core.h.
{
    while (begin != end) *out++ = static_cast<Char>(*begin++);
    return out;
}
References copy_str().
Referenced by copy_str(), copy_str(), copy_str(), copy_str(), and copy_str().
copy_str() [3/5]
template<typename Char , typename InputIt > auto fmt::v10::detail::copy_str (InputIt begin, InputIt end, std::back_insert_iterator< std::string > out) -> std::back_insert_iterator<std::string>
Definition at line 1402 of file core.h.
{
    get_container(out).append(begin, end);
    return out;
}
References copy_str(), and get_container().
copy_str() [4/5]
template<typename Char , typename R , typename OutputIt > auto fmt::v10::detail::copy_str (R && rng, OutputIt out) -> OutputIt
Definition at line 1408 of file core.h.
{
    return detail::copy_str<Char>(rng.begin(), rng.end(), out);
}
References copy_str().
copy_str() [5/5]
template<typename Char , typename T , typename U , fmt::enable_if_t<(std::is_same< remove_const_t< T >, U >::value &&is_char< U >::value), int > = 0> auto fmt::v10::detail::copy_str (T * begin, T * end, U * out) -> U*
Definition at line 725 of file core.h.
{
    if (is_constant_evaluated()) return copy_str<Char, T*, U*>(begin, end, out);
    auto size = to_unsigned(end - begin);
    if (size > 0) memcpy(out, begin, size * sizeof(U));
    return out + size;
}
References copy_str(), is_constant_evaluated(), and to_unsigned().
copy_str_noinline()
template<typename OutChar , typename InputIt , typename OutputIt > auto fmt::v10::detail::copy_str_noinline (InputIt begin, InputIt end, OutputIt out) -> OutputIt
Definition at line 617 of file format.h.
{
    return copy_str<OutChar>(begin, end, out);
}
References copy_str_noinline().
Referenced by copy_str_noinline().
count() [1/2]
template<bool B = false> auto fmt::v10::detail::count () -> size_t constexpr
Definition at line 1117 of file core.h.
{ return B ? 1 : 0; }
References count().
Referenced by compute_width(), count(), count_digits_fallback(), fmt::v10::detail::digit_grouping< Char >::count_separators(), fill_n(), fill_n(), fwrite_fully(), fmt::v10::detail::buffer< T >::try_resize(), write(), and fmt::v10::detail::formatbuf< Streambuf >::xsputn().
count() [2/2]
template<bool B1, bool B2, bool... Tail> auto fmt::v10::detail::count () -> size_t constexpr
Definition at line 1119 of file core.h.
{
    return (B1 ? 1 : 0) + count<B2, Tail...>();
}
References count().
count_digits() [1/3]
template<int BITS, typename UInt > auto fmt::v10::detail::count_digits (UInt n) -> int
Definition at line 1154 of file format.h.
{
#ifdef FMT_BUILTIN_CLZ
    if (!is_constant_evaluated() && num_bits<UInt>() == 32)
        return (FMT_BUILTIN_CLZ(static_cast<uint32_t>(n) | 1) ^ 31) / BITS + 1;
#endif
    // Lambda avoids unreachable code warnings from NVHPC.
    return [](UInt m) {
        int num_digits = 0;
        do { ++num_digits; } while ((m >>= BITS) != 0);
        return num_digits;
    }(n);
}
References count_digits(), and is_constant_evaluated().
count_digits() [2/3]
auto fmt::v10::detail::count_digits (uint32_t n) -> int inline
Definition at line 1193 of file format.h.
{
#ifdef FMT_BUILTIN_CLZ
    if (!is_constant_evaluated()) { return do_count_digits(n); }
#endif
    return count_digits_fallback(n);
}
References count_digits(), count_digits_fallback(), and is_constant_evaluated().
count_digits() [3/3]
auto fmt::v10::detail::count_digits (uint64_t n) -> int inline
Definition at line 1146 of file format.h.
{
#ifdef FMT_BUILTIN_CLZLL
    if (!is_constant_evaluated()) { return do_count_digits(n); }
#endif
    return count_digits_fallback(n);
}
References count_digits(), count_digits_fallback(), and is_constant_evaluated().
Referenced by count_digits(), count_digits(), count_digits(), format_decimal(), get_significand_size(), write(), write_int(), and write_int().
count_digits_fallback()
template<typename T > auto fmt::v10::detail::count_digits_fallback (T n) -> int
Definition at line 1107 of file format.h.
{
    int count = 1;
    for (;;) {
        // Integer division is slow so do it for a group of four digits instead
        // of for every digit. The idea comes from the talk by Alexandrescu
        // "Three Optimization Tips for C++". See speed-test for a comparison.
        if (n < 10) return count;
        if (n < 100) return count + 1;
        if (n < 1000) return count + 2;
        if (n < 10000) return count + 3;
        n /= 10000u;
        count += 4;
    }
}
References count(), and count_digits_fallback().
Referenced by count_digits(), count_digits(), and count_digits_fallback().
count_named_args()
template<typename... Args> auto fmt::v10::detail::count_named_args () -> size_t constexpr
Definition at line 1123 of file core.h.
{
    return count<is_named_arg<Args>::value...>();
}
References count_named_args().
Referenced by count_named_args().
count_statically_named_args()
template<typename... Args> auto fmt::v10::detail::count_statically_named_args () -> size_t constexpr
Definition at line 1127 of file core.h.
{
    return count<is_statically_named_arg<Args>::value...>();
}
References count_statically_named_args().
Referenced by count_statically_named_args().
countl_zero() [1/2]
auto fmt::v10::detail::countl_zero (uint32_t n) -> int inline
Definition at line 521 of file format.h.
{
#ifdef FMT_BUILTIN_CLZ
    if (!is_constant_evaluated()) return FMT_BUILTIN_CLZ(n);
#endif
    return countl_zero_fallback(n);
}
References countl_zero(), countl_zero_fallback(), and is_constant_evaluated().
Referenced by countl_zero(), countl_zero(), format_float(), and format_hexfloat().
countl_zero() [2/2]
auto fmt::v10::detail::countl_zero (uint64_t n) -> int inline
Definition at line 528 of file format.h.
{
#ifdef FMT_BUILTIN_CLZLL
    if (!is_constant_evaluated()) return FMT_BUILTIN_CLZLL(n);
#endif
    return countl_zero_fallback(n);
}
References countl_zero(), countl_zero_fallback(), and is_constant_evaluated().
countl_zero_fallback()
template<typename UInt > auto fmt::v10::detail::countl_zero_fallback (UInt n) -> int inline
Definition at line 514 of file format.h.
{
    int lz = 0;
    constexpr UInt msb_mask = static_cast<UInt>(1) << (num_bits<UInt>() - 1);
    for (; (n & msb_mask) == 0; n <<= 1) lz++;
    return lz;
}
References countl_zero_fallback().
Referenced by countl_zero(), countl_zero(), and countl_zero_fallback().
decimal_point() [1/2]
template<typename Char > auto fmt::v10::detail::decimal_point (locale_ref loc) -> Char inline
Definition at line 1224 of file format.h.
{
    return Char(decimal_point_impl<char>(loc));
}
References decimal_point().
Referenced by decimal_point(), decimal_point(), do_write_float(), write_significand(), write_significand(), write_significand(), and write_significand().
decimal_point() [2/2]
template<> auto fmt::v10::detail::decimal_point (locale_ref loc) -> wchar_t inline
Definition at line 1228 of file format.h.
{ return decimal_point_impl<wchar_t>(loc); }
References decimal_point().
decimal_point_impl() [1/3]
template<typename Char > template auto fmt::v10::detail::decimal_point_impl (locale_ref loc)
Definition at line 93 of file format-inl.h.
{
    return std::use_facet<std::numpunct<Char>>(loc.get<std::locale>()).decimal_point();
}
References fmt::v10::detail::locale_ref::get().
Referenced by decimal_point_impl().
decimal_point_impl() [2/3]
template<typename Char > auto fmt::v10::detail::decimal_point_impl (locale_ref loc) -> Char
Definition at line 93 of file format-inl.h.
{
    return std::use_facet<std::numpunct<Char>>(loc.get<std::locale>()).decimal_point();
}
References fmt::v10::detail::locale_ref::get().
Referenced by decimal_point_impl().
decimal_point_impl() [3/3]
template auto fmt::v10::detail::decimal_point_impl (locale_ref) -> char extern
References decimal_point_impl().
digits10()
template<typename Int > auto fmt::v10::detail::digits10 () -> int constexpr noexcept
Definition at line 1200 of file format.h.
{ return std::numeric_limits<Int>::digits10; }
References digits10().
Referenced by digits10().
digits10< int128_opt >()
template<> auto fmt::v10::detail::digits10< int128_opt > () -> int constexpr noexcept
Definition at line 1202 of file format.h.
{ return 38; }
digits10< uint128_t >()
template<> auto fmt::v10::detail::digits10< uint128_t > () -> int constexpr noexcept
Definition at line 1204 of file format.h.
{ return 38; }
digits2()
const char * fmt::v10::detail::digits2 (size_t value) constexpr
Definition at line 1090 of file format.h.
{
    // GCC generates slightly better code when value is pointer-size.
    return &"0001020304050607080910111213141516171819"
            "2021222324252627282930313233343536373839"
            "4041424344454647484950515253545556575859"
            "6061626364656667686970717273747576777879"
            "8081828384858687888990919293949596979899"[value * 2];
}
References digits2().
Referenced by digits2(), format_decimal(), format_float(), write_exponent(), and write_significand().
do_parse_arg_id()
template<typename Char , typename Handler > auto fmt::v10::detail::do_parse_arg_id (const Char * begin, const Char * end, Handler && handler) -> const Char*
Definition at line 2005 of file core.h.
{
    Char c = *begin;
    if (c >= '0' && c <= '9') {
        int index = 0;
        constexpr int max = (std::numeric_limits<int>::max)();
        if (c != '0') index = parse_nonnegative_int(begin, end, max);
        else ++begin;
        if (begin == end || (*begin != '}' && *begin != ':')) throw_format_error("invalid format string");
        else handler.on_index(index);
        return begin;
    }
    if (!is_name_start(c)) {
        throw_format_error("invalid format string");
        return begin;
    }
    auto it = begin;
    do { ++it; } while (it != end && (is_name_start(*it) || ('0' <= *it && *it <= '9')));
    handler.on_name({begin, to_unsigned(it - begin)});
    return it;
}
References do_parse_arg_id(), index, is_name_start(), parse_nonnegative_int(), and to_unsigned().
Referenced by do_parse_arg_id(), and parse_arg_id().
do_write_float()
template<typename OutputIt , typename DecimalFP , typename Char , typename Grouping = digit_grouping<Char>> auto fmt::v10::detail::do_write_float (OutputIt out, const DecimalFP & f, const format_specs< Char > & specs, float_specs fspecs, locale_ref loc) -> OutputIt
Definition at line 2382 of file format.h.
{
    auto significand = f.significand;
    int significand_size = get_significand_size(f);
    const Char zero = static_cast<Char>('0');
    auto sign = fspecs.sign;
    size_t size = to_unsigned(significand_size) + (sign ? 1 : 0);
    using iterator = reserve_iterator<OutputIt>;
    Char decimal_point = fspecs.locale ? detail::decimal_point<Char>(loc) : static_cast<Char>('.');
    int output_exp = f.exponent + significand_size - 1;
    auto use_exp_format = [=]() {
        if (fspecs.format == float_format::exp) return true;
        if (fspecs.format != float_format::general) return false;
        // Use the fixed notation if the exponent is in [exp_lower, exp_upper),
        // e.g. 0.0001 instead of 1e-04. Otherwise use the exponent notation.
        const int exp_lower = -4, exp_upper = 16;
        return output_exp < exp_lower || output_exp >= (fspecs.precision > 0 ? fspecs.precision : exp_upper);
    };
    if (use_exp_format()) {
        int num_zeros = 0;
        if (fspecs.showpoint) {
            num_zeros = fspecs.precision - significand_size;
            if (num_zeros < 0) num_zeros = 0;
            size += to_unsigned(num_zeros);
        } else if (significand_size == 1) {
            decimal_point = Char();
        }
        auto abs_output_exp = output_exp >= 0 ? output_exp : -output_exp;
        int exp_digits = 2;
        if (abs_output_exp >= 100) exp_digits = abs_output_exp >= 1000 ? 4 : 3;
        size += to_unsigned((decimal_point ? 1 : 0) + 2 + exp_digits);
        char exp_char = fspecs.upper ? 'E' : 'e';
        auto write = [=](iterator it) {
            if (sign) *it++ = detail::sign<Char>(sign);
            // Insert a decimal point after the first digit and add an exponent.
            it = write_significand(it, significand, significand_size, 1, decimal_point);
            if (num_zeros > 0) it = detail::fill_n(it, num_zeros, zero);
            *it++ = static_cast<Char>(exp_char);
            return write_exponent<Char>(output_exp, it);
        };
        return specs.width > 0 ? write_padded<align::right>(out, specs, size, write)
                               : base_iterator(out, write(reserve(out, size)));
    }
    int exp = f.exponent + significand_size;
    if (f.exponent >= 0) {
        // 1234e5 -> 123400000[.0+]
        size += to_unsigned(f.exponent);
        int num_zeros = fspecs.precision - exp;
        abort_fuzzing_if(num_zeros > 5000);
        if (fspecs.showpoint) {
            ++size;
            if (num_zeros <= 0 && fspecs.format != float_format::fixed) num_zeros = 0;
            if (num_zeros > 0) size += to_unsigned(num_zeros);
        }
        auto grouping = Grouping(loc, fspecs.locale);
        size += to_unsigned(grouping.count_separators(exp));
        return write_padded<align::right>(out, specs, size, [&](iterator it) {
            if (sign) *it++ = detail::sign<Char>(sign);
            it = write_significand<Char>(it, significand, significand_size, f.exponent, grouping);
            if (!fspecs.showpoint) return it;
            *it++ = decimal_point;
            return num_zeros > 0 ? detail::fill_n(it, num_zeros, zero) : it;
        });
    } else if (exp > 0) {
        // 1234e-2 -> 12.34[0+]
        int num_zeros = fspecs.showpoint ? fspecs.precision - significand_size : 0;
        size += 1 + to_unsigned(num_zeros > 0 ? num_zeros : 0);
        auto grouping = Grouping(loc, fspecs.locale);
        size += to_unsigned(grouping.count_separators(exp));
        return write_padded<align::right>(out, specs, size, [&](iterator it) {
            if (sign) *it++ = detail::sign<Char>(sign);
            it = write_significand(it, significand, significand_size, exp, decimal_point, grouping);
            return num_zeros > 0 ? detail::fill_n(it, num_zeros, zero) : it;
        });
    }
    // 1234e-6 -> 0.001234
    int num_zeros = -exp;
    if (significand_size == 0 && fspecs.precision >= 0 && fspecs.precision < num_zeros) {
        num_zeros = fspecs.precision;
    }
    bool pointy = num_zeros != 0 || significand_size != 0 || fspecs.showpoint;
    size += 1 + (pointy ? 1 : 0) + to_unsigned(num_zeros);
    return write_padded<align::right>(out, specs, size, [&](iterator it) {
        if (sign) *it++ = detail::sign<Char>(sign);
        *it++ = zero;
        if (!pointy) return it;
        *it++ = decimal_point;
        it = detail::fill_n(it, num_zeros, zero);
        return write_significand<Char>(it, significand, significand_size);
    });
}
References abort_fuzzing_if(), base_iterator(), decimal_point(), do_write_float(), exp, fmt::v10::exp_lower, fmt::v10::exp_upper, get_significand_size(), reserve(), sign(), to_unsigned(), fmt::v10::format_specs< Char >::width, write(), write_significand(), and zero.
Referenced by do_write_float(), and write_float().
encode_types() [1/2]
template<typename > auto fmt::v10::detail::encode_types () -> unsigned long long constexpr
Definition at line 1448 of file core.h.
{ return 0; }
Referenced by encode_types().
encode_types() [2/2]
template<typename Context , typename Arg , typename... Args> auto fmt::v10::detail::encode_types () -> unsigned long long constexpr
Definition at line 1450 of file core.h.
{
    return static_cast<unsigned>(mapped_type_constant<Arg, Context>::value) |
           (encode_types<Context, Args...>() << packed_arg_bits);
}
References encode_types(), and packed_arg_bits.
equal2() [1/2]
template<typename Char > auto fmt::v10::detail::equal2 (const Char * lhs, const char * rhs) -> bool
Definition at line 1231 of file format.h.
{
    return lhs[0] == Char(rhs[0]) && lhs[1] == Char(rhs[1]);
}
References equal2().
Referenced by equal2(), equal2(), and vformat_to().
equal2() [2/2]
auto fmt::v10::detail::equal2 (const char * lhs, const char * rhs) -> bool inline
Definition at line 1235 of file format.h.
{ return memcmp(lhs, rhs, 2) == 0; }
References equal2().
exponent_bias()
template<typename Float > auto fmt::v10::detail::exponent_bias () -> int constexpr
Definition at line 1525 of file format.h.
{
    // std::numeric_limits may not support __float128.
    return is_float128<Float>() ? 16383 : std::numeric_limits<Float>::max_exponent - 1;
}
References exponent_bias().
Referenced by exponent_bias(), and fmt::v10::detail::dragonbox::to_decimal().
exponent_mask()
template<typename Float > auto fmt::v10::detail::exponent_mask () -> typename dragonbox::float_info<Float>::carrier_uint constexpr
Definition at line 1520 of file format.h.
{
    using float_uint = typename dragonbox::float_info<Float>::carrier_uint;
    return ((float_uint(1) << dragonbox::float_info<Float>::exponent_bits) - 1) << num_significand_bits<Float>();
}
References exponent_mask().
Referenced by exponent_mask(), and fmt::v10::detail::dragonbox::to_decimal().
fill()
template<typename OutputIt , typename Char > auto fmt::v10::detail::fill (OutputIt it, size_t n, const fill_t< Char > & fill) -> OutputIt
Definition at line 1663 of file format.h.
{
    auto fill_size = fill.size();
    if (fill_size == 1) return detail::fill_n(it, n, fill[0]);
    auto data = fill.data();
    for (size_t i = 0; i < n; ++i) it = copy_str<Char>(data, data + fill_size, it);
    return it;
}
References fill().
Referenced by fill(), and write_padded().
fill_n() [1/2]
template<typename OutputIt , typename Size , typename T > auto fmt::v10::detail::fill_n (OutputIt out, Size count, const T & value) -> OutputIt
Definition at line 599 of file format.h.
{
    for (Size i = 0; i < count; ++i) *out++ = value;
    return out;
}
References count(), and fill_n().
Referenced by fill_n(), fill_n(), format_float(), and write_codepoint().
fill_n() [2/2]
template<typename T , typename Size > auto fmt::v10::detail::fill_n (T * out, Size count, char value) -> T*
Definition at line 604 of file format.h.
{
    if (is_constant_evaluated()) { return fill_n<T*, Size, T>(out, count, value); }
    std::memset(out, value, to_unsigned(count));
    return out + count;
}
References count(), fill_n(), is_constant_evaluated(), and to_unsigned().
find()
template<bool IS_CONSTEXPR, typename T , typename Ptr = const T*> auto fmt::v10::detail::find (Ptr first, Ptr last, T value, Ptr & out) -> bool
Definition at line 1957 of file core.h.
{
    for (out = first; out != last; ++out) {
        if (*out == value) return true;
    }
    return false;
}
References find().
Referenced by find().
find< false, char >()
template<> auto fmt::v10::detail::find< false, char > (const char * first, const char * last, char value, const char *& out) -> bool inline
Definition at line 1964 of file core.h.
{
    out = static_cast<const char*>(std::memchr(first, value, to_unsigned(last - first)));
    return out != nullptr;
}
References to_unsigned().
find_escape() [1/2]
template<typename Char > auto fmt::v10::detail::find_escape (const Char * begin, const Char * end) -> find_escape_result<Char>
Definition at line 1733 of file format.h.
{
    for (; begin != end; ++begin) {
        uint32_t cp = static_cast<make_unsigned_char<Char>>(*begin);
        if (const_check(sizeof(Char) == 1) && cp >= 0x80) continue;
        if (needs_escape(cp)) return {begin, begin + 1, cp};
    }
    return {begin, nullptr, 0};
}
References const_check(), find_escape(), and needs_escape().
Referenced by find_escape(), find_escape(), and write_escaped_string().
find_escape() [2/2]
auto fmt::v10::detail::find_escape (const char * begin, const char * end) -> find_escape_result<char> inline
Definition at line 1742 of file format.h.
{
    if (!is_utf8()) return find_escape<char>(begin, end);
    auto result = find_escape_result<char> {end, nullptr, 0};
    for_each_codepoint(string_view(begin, to_unsigned(end - begin)), [&](uint32_t cp, string_view sv) {
        if (needs_escape(cp)) {
            result = {sv.begin(), sv.end(), cp};
            return false;
        }
        return true;
    });
    return result;
}
References fmt::v10::basic_string_view< Char >::begin(), fmt::v10::basic_string_view< Char >::end(), find_escape(), for_each_codepoint(), is_utf8(), needs_escape(), and to_unsigned().
for_each_codepoint()
template<typename F > void fmt::v10::detail::for_each_codepoint (string_view s, F f)
Definition at line 677 of file format.h.
{
    auto decode = [f](const char* buf_ptr, const char* ptr) {
        auto cp = uint32_t();
        auto error = 0;
        auto end = utf8_decode(buf_ptr, &cp, &error);
        bool result = f(error ? invalid_code_point : cp, string_view(ptr, error ? 1 : to_unsigned(end - buf_ptr)));
        return result ? (error ? buf_ptr + 1 : end) : nullptr;
    };
    auto p = s.data();
    const size_t block_size = 4; // utf8_decode always reads blocks of 4 chars.
    if (s.size() >= block_size) {
        for (auto end = p + s.size() - block_size + 1; p < end;) {
            p = decode(p, p);
            if (!p) return;
        }
    }
    if (auto num_chars_left = s.data() + s.size() - p) {
        char buf[2 * block_size - 1] = {};
        copy_str<char>(p, p + num_chars_left, buf);
        const char* buf_ptr = buf;
        do {
            auto end = decode(buf_ptr, p);
            if (!end) return;
            p += end - buf_ptr;
            buf_ptr = end;
        } while (buf_ptr - buf < num_chars_left);
    }
}
References fmt::v10::basic_string_view< Char >::data(), for_each_codepoint(), invalid_code_point, fmt::v10::basic_string_view< Char >::size(), to_unsigned(), and utf8_decode().
Referenced by fmt::v10::detail::utf8_to_utf16::utf8_to_utf16(), compute_width(), find_escape(), and for_each_codepoint().
format_decimal() [1/2]
template<typename Char , typename UInt > auto fmt::v10::detail::format_decimal (Char * out, UInt value, int size) -> format_decimal_result<Char*>
Definition at line 1255 of file format.h.
{
    FMT_ASSERT(size >= count_digits(value), "invalid digit count");
    out += size;
    Char* end = out;
    while (value >= 100) {
        // Integer division is slow so do it for a group of two digits instead
        // of for every digit. The idea comes from the talk by Alexandrescu
        // "Three Optimization Tips for C++". See speed-test for a comparison.
        out -= 2;
        copy2(out, digits2(static_cast<size_t>(value % 100)));
        value /= 100;
    }
    if (value < 10) {
        *--out = static_cast<Char>('0' + value);
        return {out, end};
    }
    out -= 2;
    copy2(out, digits2(static_cast<size_t>(value)));
    return {out, end};
}
References copy2(), count_digits(), digits2(), FMT_ASSERT, and format_decimal().
Referenced by format_decimal(), format_decimal(), write_int(), and write_significand().
format_decimal() [2/2]
template<typename Char , typename UInt , typename Iterator , fmt::enable_if_t<(!std::is_pointer< remove_cvref_t< Iterator > >::value), int > = 0> auto fmt::v10::detail::format_decimal (Iterator out, UInt value, int size) -> format_decimal_result<Iterator> inline
Definition at line 1279 of file format.h.
{
    // Buffer is large enough to hold all digits (digits10 + 1).
    Char buffer[digits10<UInt>() + 1] = {};
    auto end = format_decimal(buffer, value, size).end;
    return {out, detail::copy_str_noinline<Char>(buffer, end, out)};
}
References format_decimal().
format_dragon()
void fmt::v10::detail::format_dragon (basic_fp< uint128_t > value, unsigned flags, int num_digits, buffer< char > & buf, int & exp10) inline
Definition at line 2791 of file format.h.
{
    bigint numerator; // 2 * R in (FPP)^2.
    bigint denominator; // 2 * S in (FPP)^2.
    // lower and upper are differences between value and corresponding boundaries.
    bigint lower; // (M^- in (FPP)^2).
    bigint upper_store; // upper's value if different from lower.
    bigint* upper = nullptr; // (M^+ in (FPP)^2).
    // Shift numerator and denominator by an extra bit or two (if lower boundary
    // is closer) to make lower and upper integers. This eliminates multiplication
    // by 2 during later computations.
    bool is_predecessor_closer = (flags & dragon::predecessor_closer) != 0;
    int shift = is_predecessor_closer ? 2 : 1;
    if (value.e >= 0) {
        numerator = value.f;
        numerator <<= value.e + shift;
        lower = 1;
        lower <<= value.e;
        if (is_predecessor_closer) {
            upper_store = 1;
            upper_store <<= value.e + 1;
            upper = &upper_store;
        }
        denominator.assign_pow10(exp10);
        denominator <<= shift;
    } else if (exp10 < 0) {
        numerator.assign_pow10(-exp10);
        lower.assign(numerator);
        if (is_predecessor_closer) {
            upper_store.assign(numerator);
            upper_store <<= 1;
            upper = &upper_store;
        }
        numerator *= value.f;
        numerator <<= shift;
        denominator = 1;
        denominator <<= shift - value.e;
    } else {
        numerator = value.f;
        numerator <<= shift;
        denominator.assign_pow10(exp10);
        denominator <<= shift - value.e;
        lower = 1;
        if (is_predecessor_closer) {
            upper_store = 1ULL << 1;
            upper = &upper_store;
        }
    }
    int even = static_cast<int>((value.f & 1) == 0);
    if (!upper) upper = &lower;
    bool shortest = num_digits < 0;
    if ((flags & dragon::fixup) != 0) {
        if (add_compare(numerator, *upper, denominator) + even <= 0) {
            --exp10;
            numerator *= 10;
            if (num_digits < 0) {
                lower *= 10;
                if (upper != &lower) *upper *= 10;
            }
        }
        if ((flags & dragon::fixed) != 0) adjust_precision(num_digits, exp10 + 1);
    }
    // Invariant: value == (numerator / denominator) * pow(10, exp10).
    if (shortest) {
        // Generate the shortest representation.
        num_digits = 0;
        char* data = buf.data();
        for (;;) {
            int digit = numerator.divmod_assign(denominator);
            bool low = compare(numerator, lower) - even < 0; // numerator <[=] lower.
            // numerator + upper >[=] pow10:
            bool high = add_compare(numerator, *upper, denominator) + even > 0;
            data[num_digits++] = static_cast<char>('0' + digit);
            if (low || high) {
                if (!low) {
                    ++data[num_digits - 1];
                } else if (high) {
                    int result = add_compare(numerator, numerator, denominator);
                    // Round half to even.
                    if (result > 0 || (result == 0 && (digit % 2) != 0)) ++data[num_digits - 1];
                }
                buf.try_resize(to_unsigned(num_digits));
                exp10 -= num_digits - 1;
                return;
            }
            numerator *= 10;
            lower *= 10;
            if (upper != &lower) *upper *= 10;
        }
    }
    // Generate the given number of digits.
    exp10 -= num_digits - 1;
    if (num_digits <= 0) {
        denominator *= 10;
        auto digit = add_compare(numerator, numerator, denominator) > 0 ? '1' : '0';
        buf.push_back(digit);
        return;
    }
    buf.try_resize(to_unsigned(num_digits));
    for (int i = 0; i < num_digits - 1; ++i) {
        int digit = numerator.divmod_assign(denominator);
        buf[i] = static_cast<char>('0' + digit);
        numerator *= 10;
    }
    int digit = numerator.divmod_assign(denominator);
    auto result = add_compare(numerator, numerator, denominator);
    if (result > 0 || (result == 0 && (digit % 2) != 0)) {
        if (digit == 9) {
            const auto overflow = '0' + 10;
            buf[num_digits - 1] = overflow;
            // Propagate the carry.
            for (int i = num_digits - 1; i > 0 && buf[i] == overflow; --i) {
                buf[i] = '0';
                ++buf[i - 1];
            }
            if (buf[0] == overflow) {
                buf[0] = '1';
                if ((flags & dragon::fixed) != 0) buf.push_back('0');
                else ++exp10;
            }
            return;
        }
        ++digit;
    }
    buf[num_digits - 1] = static_cast<char>('0' + digit);
}
References adjust_precision(), fmt::v10::detail::bigint::assign(), fmt::v10::detail::bigint::assign_pow10(), fmt::v10::detail::buffer< T >::data(), fmt::v10::detail::bigint::divmod_assign(), format_dragon(), fmt::v10::detail::buffer< T >::push_back(), to_unsigned(), and fmt::v10::detail::buffer< T >::try_resize().
Referenced by format_dragon(), and format_float().
format_error_code()
void fmt::v10::detail::format_error_code (detail::buffer< char > & out, int error_code, string_view message) noexcept
Definition at line 42 of file format-inl.h.
{
    // Report error code making sure that the output fits into
    // inline_buffer_size to avoid dynamic memory allocation and potential
    // bad_alloc.
    out.try_resize(0);
    static const char SEP[] = ": ";
    static const char ERROR_STR[] = "error ";
    // Subtract 2 to account for terminating null characters in SEP and ERROR_STR.
    size_t error_code_size = sizeof(SEP) + sizeof(ERROR_STR) - 2;
    auto abs_value = static_cast<uint32_or_64_or_128_t<int>>(error_code);
    if (detail::is_negative(error_code)) {
        abs_value = 0 - abs_value;
        ++error_code_size;
    }
    error_code_size += detail::to_unsigned(detail::count_digits(abs_value));
    auto it = buffer_appender<char>(out);
    if (message.size() <= inline_buffer_size - error_code_size) format_to(it, FMT_STRING("{}{}"), message, SEP);
    format_to(it, FMT_STRING("{}{}"), ERROR_STR, error_code);
    FMT_ASSERT(out.size() <= inline_buffer_size, "");
}
References FMT_ASSERT, FMT_STRING, and format_error_code().
Referenced by format_error_code().
format_float()
template<typename Float > auto fmt::v10::detail::format_float (Float value, int precision, float_specs specs, buffer< char > & buf) -> int
Definition at line 3001 of file format.h.
{
    // float is passed as double to reduce the number of instantiations.
    static_assert(!std::is_same<Float, float>::value, "");
    FMT_ASSERT(value >= 0, "value is negative");
    auto converted_value = convert_float(value);
    const bool fixed = specs.format == float_format::fixed;
    if (value <= 0) { // <= instead of == to silence a warning.
        if (precision <= 0 || !fixed) {
            buf.push_back('0');
            return 0;
        }
        buf.try_resize(to_unsigned(precision));
        fill_n(buf.data(), precision, '0');
        return -precision;
    }
    int exp = 0;
    bool use_dragon = true;
    unsigned dragon_flags = 0;
    if (!is_fast_float<Float>() || is_constant_evaluated()) {
        const auto inv_log2_10 = 0.3010299956639812; // 1 / log2(10)
        using info = dragonbox::float_info<decltype(converted_value)>;
        const auto f = basic_fp<typename info::carrier_uint>(converted_value);
        // Compute exp, an approximate power of 10, such that
        //   10^(exp - 1) <= value < 10^exp or 10^exp <= value < 10^(exp + 1).
        // This is based on log10(value) == log2(value) / log2(10) and approximation
        // of log2(value) by e + num_fraction_bits idea from double-conversion.
        auto e = (f.e + count_digits<1>(f.f) - 1) * inv_log2_10 - 1e-10;
        exp = static_cast<int>(e);
        if (e > exp) ++exp; // Compute ceil.
        dragon_flags = dragon::fixup;
    } else if (precision < 0) {
        // Use Dragonbox for the shortest format.
        if (specs.binary32) {
            auto dec = dragonbox::to_decimal(static_cast<float>(value));
            write<char>(buffer_appender<char>(buf), dec.significand);
            return dec.exponent;
        }
        auto dec = dragonbox::to_decimal(static_cast<double>(value));
        write<char>(buffer_appender<char>(buf), dec.significand);
        return dec.exponent;
    } else {
        // Extract significand bits and exponent bits.
        using info = dragonbox::float_info<double>;
        auto br = bit_cast<uint64_t>(static_cast<double>(value));
        const uint64_t significand_mask = (static_cast<uint64_t>(1) << num_significand_bits<double>()) - 1;
        uint64_t significand = (br & significand_mask);
        int exponent = static_cast<int>((br & exponent_mask<double>()) >> num_significand_bits<double>());
        if (exponent != 0) { // Check if normal.
            exponent -= exponent_bias<double>() + num_significand_bits<double>();
            significand |= (static_cast<uint64_t>(1) << num_significand_bits<double>());
            significand <<= 1;
        } else {
            // Normalize subnormal inputs.
            FMT_ASSERT(significand != 0, "zeros should not appear here");
            int shift = countl_zero(significand);
            FMT_ASSERT(shift >= num_bits<uint64_t>() - num_significand_bits<double>(), "");
            shift -= (num_bits<uint64_t>() - num_significand_bits<double>() - 2);
            exponent = (std::numeric_limits<double>::min_exponent - num_significand_bits<double>()) - shift;
            significand <<= shift;
        }
        // Compute the first several nonzero decimal significand digits.
        // We call the number we get the first segment.
        const int k = info::kappa - dragonbox::floor_log10_pow2(exponent);
        exp = -k;
        const int beta = exponent + dragonbox::floor_log2_pow10(k);
        uint64_t first_segment;
        bool has_more_segments;
        int digits_in_the_first_segment;
        {
            const auto r = dragonbox::umul192_upper128(significand << beta, dragonbox::get_cached_power(k));
            first_segment = r.high();
            has_more_segments = r.low() != 0;
            // The first segment can have 18 ~ 19 digits.
            if (first_segment >= 1000000000000000000ULL) {
                digits_in_the_first_segment = 19;
            } else {
                // When it is of 18-digits, we align it to 19-digits by adding a bogus
                // zero at the end.
                digits_in_the_first_segment = 18;
                first_segment *= 10;
            }
        }
        // Compute the actual number of decimal digits to print.
        if (fixed) adjust_precision(precision, exp + digits_in_the_first_segment);
        // Use Dragon4 only when there might be not enough digits in the first
        // segment.
        if (digits_in_the_first_segment > precision) {
            use_dragon = false;
            if (precision <= 0) {
                exp += digits_in_the_first_segment;
                if (precision < 0) {
                    // Nothing to do, since all we have are just leading zeros.
                    buf.try_resize(0);
                } else {
                    // We may need to round-up.
                    buf.try_resize(1);
                    if ((first_segment | static_cast<uint64_t>(has_more_segments)) > 5000000000000000000ULL) {
                        buf[0] = '1';
                    } else {
                        buf[0] = '0';
                    }
                }
            } // precision <= 0
            else {
                exp += digits_in_the_first_segment - precision;
                // When precision > 0, we divide the first segment into three
                // subsegments, each with 9, 9, and 0 ~ 1 digits so that each fits
                // in 32-bits which usually allows faster calculation than in
                // 64-bits. Since some compiler (e.g. MSVC) doesn't know how to optimize
                // division-by-constant for large 64-bit divisors, we do it here
                // manually. The magic number 7922816251426433760 below is equal to
                // ceil(2^(64+32) / 10^10).
                const uint32_t first_subsegment =
                    static_cast<uint32_t>(dragonbox::umul128_upper64(first_segment, 7922816251426433760ULL) >> 32);
                const uint64_t second_third_subsegments = first_segment - first_subsegment * 10000000000ULL;
                uint64_t prod;
                uint32_t digits;
                bool should_round_up;
                int number_of_digits_to_print = precision > 9 ? 9 : precision;
                // Print a 9-digits subsegment, either the first or the second.
                auto print_subsegment = [&](uint32_t subsegment, char* buffer) {
                    int number_of_digits_printed = 0;
                    // If we want to print an odd number of digits from the subsegment,
                    if ((number_of_digits_to_print & 1) != 0) {
                        // Convert to 64-bit fixed-point fractional form with 1-digit
                        // integer part. The magic number 720575941 is a good enough
                        // approximation of 2^(32 + 24) / 10^8; see
                        // https://jk-jeon.github.io/posts/2022/12/fixed-precision-formatting/#fixed-length-case
                        // for details.
                        prod = ((subsegment * static_cast<uint64_t>(720575941)) >> 24) + 1;
                        digits = static_cast<uint32_t>(prod >> 32);
                        *buffer = static_cast<char>('0' + digits);
                        number_of_digits_printed++;
                    }
                    // If we want to print an even number of digits from the
                    // first_subsegment,
                    else {
                        // Convert to 64-bit fixed-point fractional form with 2-digits
                        // integer part. The magic number 450359963 is a good enough
                        // approximation of 2^(32 + 20) / 10^7; see
                        // https://jk-jeon.github.io/posts/2022/12/fixed-precision-formatting/#fixed-length-case
                        // for details.
                        prod = ((subsegment * static_cast<uint64_t>(450359963)) >> 20) + 1;
                        digits = static_cast<uint32_t>(prod >> 32);
                        copy2(buffer, digits2(digits));
                        number_of_digits_printed += 2;
                    }
                    // Print all digit pairs.
                    while (number_of_digits_printed < number_of_digits_to_print) {
                        prod = static_cast<uint32_t>(prod) * static_cast<uint64_t>(100);
                        digits = static_cast<uint32_t>(prod >> 32);
                        copy2(buffer + number_of_digits_printed, digits2(digits));
                        number_of_digits_printed += 2;
                    }
                };
                // Print first subsegment.
                print_subsegment(first_subsegment, buf.data());
                // Perform rounding if the first subsegment is the last subsegment to
                // print.
                if (precision <= 9) {
                    // Rounding inside the subsegment.
                    // We round-up if:
                    //  - either the fractional part is strictly larger than 1/2, or
                    //  - the fractional part is exactly 1/2 and the last digit is odd.
                    // We rely on the following observations:
                    //  - If fractional_part >= threshold, then the fractional part is
                    //    strictly larger than 1/2.
                    //  - If the MSB of fractional_part is set, then the fractional part
                    //    must be at least 1/2.
                    //  - When the MSB of fractional_part is set, either
                    //    second_third_subsegments being nonzero or has_more_segments
                    //    being true means there are further digits not printed, so the
                    //    fractional part is strictly larger than 1/2.
                    if (precision < 9) {
                        uint32_t fractional_part = static_cast<uint32_t>(prod);
                        should_round_up =
                            fractional_part >=
                                data::fractional_part_rounding_thresholds[8 - number_of_digits_to_print] ||
                            ((fractional_part >> 31) &
                             ((digits & 1) | (second_third_subsegments != 0) | has_more_segments)) != 0;
                    }
                    // Rounding at the subsegment boundary.
                    // In this case, the fractional part is at least 1/2 if and only if
                    // second_third_subsegments >= 5000000000ULL, and is strictly larger
                    // than 1/2 if we further have either second_third_subsegments >
                    // 5000000000ULL or has_more_segments == true.
                    else {
                        should_round_up =
                            second_third_subsegments > 5000000000ULL ||
                            (second_third_subsegments == 5000000000ULL && ((digits & 1) != 0 || has_more_segments));
                    }
                }
                // Otherwise, print the second subsegment.
                else {
                    // Compilers are not aware of how to leverage the maximum value of
                    // second_third_subsegments to find out a better magic number which
                    // allows us to eliminate an additional shift. 1844674407370955162 =
                    // ceil(2^64/10) < ceil(2^64*(10^9/(10^10 - 1))).
                    const uint32_t second_subsegment = static_cast<uint32_t>(
                        dragonbox::umul128_upper64(second_third_subsegments, 1844674407370955162ULL));
                    const uint32_t third_subsegment =
                        static_cast<uint32_t>(second_third_subsegments) - second_subsegment * 10;
                    number_of_digits_to_print = precision - 9;
                    print_subsegment(second_subsegment, buf.data() + 9);
                    // Rounding inside the subsegment.
                    if (precision < 18) {
                        // The condition third_subsegment != 0 implies that the segment was
                        // of 19 digits, so in this case the third segment should be
                        // consisting of a genuine digit from the input.
                        uint32_t fractional_part = static_cast<uint32_t>(prod);
                        should_round_up =
                            fractional_part >=
                                data::fractional_part_rounding_thresholds[8 - number_of_digits_to_print] ||
                            ((fractional_part >> 31) & ((digits & 1) | (third_subsegment != 0) | has_more_segments)) !=
                                0;
                    }
                    // Rounding at the subsegment boundary.
                    else {
                        // In this case, the segment must be of 19 digits, thus
                        // the third subsegment should be consisting of a genuine digit from
                        // the input.
                        should_round_up =
                            third_subsegment > 5 || (third_subsegment == 5 && ((digits & 1) != 0 || has_more_segments));
                    }
                }
                // Round-up if necessary.
                if (should_round_up) {
                    ++buf[precision - 1];
                    for (int i = precision - 1; i > 0 && buf[i] > '9'; --i) {
                        buf[i] = '0';
                        ++buf[i - 1];
                    }
                    if (buf[0] > '9') {
                        buf[0] = '1';
                        if (fixed) buf[precision++] = '0';
                        else ++exp;
                    }
                }
                buf.try_resize(to_unsigned(precision));
            }
        } // if (digits_in_the_first_segment > precision)
        else {
            // Adjust the exponent for its use in Dragon4.
            exp += digits_in_the_first_segment - 1;
        }
    }
    if (use_dragon) {
        auto f = basic_fp<uint128_t>();
        bool is_predecessor_closer = specs.binary32 ? f.assign(static_cast<float>(value)) : f.assign(converted_value);
        if (is_predecessor_closer) dragon_flags |= dragon::predecessor_closer;
        if (fixed) dragon_flags |= dragon::fixed;
        // Limit precision to the maximum possible number of significant digits in
        // an IEEE754 double because we don't need to generate zeros.
        const int max_double_digits = 767;
        if (precision > max_double_digits) precision = max_double_digits;
        format_dragon(f, dragon_flags, precision, buf, exp);
    }
    if (!fixed && !specs.showpoint) {
        // Remove trailing zeros.
        auto num_digits = buf.size();
        while (num_digits > 0 && buf[num_digits - 1] == '0') {
            --num_digits;
            ++exp;
        }
        buf.try_resize(num_digits);
    }
    return exp;
}
References adjust_precision(), convert_float(), copy2(), countl_zero(), fmt::v10::dec, digits2(), exp, fill_n(), fixed, FMT_ASSERT, format_dragon(), format_float(), is_constant_evaluated(), precision, and to_unsigned().
Referenced by format_float(), and write_float().
format_hexfloat()
template<typename Float , fmt::enable_if_t<(!is_double_double< Float >::value), int > = 0> void fmt::v10::detail::format_hexfloat (Float value, int precision, float_specs specs, buffer< char > & buf)
Definition at line 2920 of file format.h.
{
    // float is passed as double to reduce the number of instantiations and to
    // simplify implementation.
    static_assert(!std::is_same<Float, float>::value, "");
    using info = dragonbox::float_info<Float>;
    // Assume Float is in the format [sign][exponent][significand].
    using carrier_uint = typename info::carrier_uint;
    constexpr auto num_float_significand_bits = detail::num_significand_bits<Float>();
    basic_fp<carrier_uint> f(value);
    f.e += num_float_significand_bits;
    if (!has_implicit_bit<Float>()) --f.e;
    constexpr auto num_fraction_bits = num_float_significand_bits + (has_implicit_bit<Float>() ? 1 : 0);
    constexpr auto num_xdigits = (num_fraction_bits + 3) / 4;
    constexpr auto leading_shift = ((num_xdigits - 1) * 4);
    const auto leading_mask = carrier_uint(0xF) << leading_shift;
    const auto leading_xdigit = static_cast<uint32_t>((f.f & leading_mask) >> leading_shift);
    if (leading_xdigit > 1) f.e -= (32 - countl_zero(leading_xdigit) - 1);
    int print_xdigits = num_xdigits - 1;
    if (precision >= 0 && print_xdigits > precision) {
        const int shift = ((print_xdigits - precision - 1) * 4);
        const auto mask = carrier_uint(0xF) << shift;
        const auto v = static_cast<uint32_t>((f.f & mask) >> shift);
        if (v >= 8) {
            const auto inc = carrier_uint(1) << (shift + 4);
            f.f += inc;
            f.f &= ~(inc - 1);
        }
        // Check long double overflow
        if (!has_implicit_bit<Float>()) {
            const auto implicit_bit = carrier_uint(1) << num_float_significand_bits;
            if ((f.f & implicit_bit) == implicit_bit) {
                f.f >>= 4;
                f.e += 4;
            }
        }
        print_xdigits = precision;
    }
    char xdigits[num_bits<carrier_uint>() / 4];
    detail::fill_n(xdigits, sizeof(xdigits), '0');
    format_uint<4>(xdigits, f.f, num_xdigits, specs.upper);
    // Remove zero tail
    while (print_xdigits > 0 && xdigits[print_xdigits] == '0') --print_xdigits;
    buf.push_back('0');
    buf.push_back(specs.upper ? 'X' : 'x');
    buf.push_back(xdigits[0]);
    if (specs.showpoint || print_xdigits > 0 || print_xdigits < precision) buf.push_back('.');
    buf.append(xdigits + 1, xdigits + 1 + print_xdigits);
    for (; print_xdigits < precision; ++print_xdigits) buf.push_back('0');
    buf.push_back(specs.upper ? 'P' : 'p');
    uint32_t abs_e;
    if (f.e < 0) {
        buf.push_back('-');
        abs_e = static_cast<uint32_t>(-f.e);
    } else {
        buf.push_back('+');
        abs_e = static_cast<uint32_t>(f.e);
    }
    format_decimal<char>(appender(buf), abs_e, detail::count_digits(abs_e));
}
References fmt::v10::detail::buffer< T >::append(), countl_zero(), fmt::v10::detail::basic_fp< F >::e, fmt::v10::detail::basic_fp< F >::f, format_hexfloat(), precision, fmt::v10::detail::buffer< T >::push_back(), fmt::v10::detail::float_specs::showpoint, and fmt::v10::detail::float_specs::upper.
Referenced by format_hexfloat(), and write_float().
format_uint() [1/2]
template<unsigned BASE_BITS, typename Char , typename UInt > auto fmt::v10::detail::format_uint (Char * buffer, UInt value, int num_digits, bool upper = false) -> Char*
Definition at line 1287 of file format.h.
{
    buffer += num_digits;
    Char* end = buffer;
    do {
        const char* digits = upper ? "0123456789ABCDEF" : "0123456789abcdef";
        unsigned digit = static_cast<unsigned>(value & ((1 << BASE_BITS) - 1));
        *--buffer = static_cast<Char>(BASE_BITS < 4 ? static_cast<char>('0' + digit) : digits[digit]);
    } while ((value >>= BASE_BITS) != 0);
    return end;
}
References format_uint().
Referenced by format_uint(), and format_uint().
format_uint() [2/2]
template<unsigned BASE_BITS, typename Char , typename It , typename UInt > auto fmt::v10::detail::format_uint (It out, UInt value, int num_digits, bool upper = false) -> It inline
Definition at line 1299 of file format.h.
{
    if (auto ptr = to_pointer<Char>(out, to_unsigned(num_digits))) {
        format_uint<BASE_BITS>(ptr, value, num_digits, upper);
        return out;
    }
    // Buffer should be large enough to hold all digits (digits / BASE_BITS + 1).
    char buffer[num_bits<UInt>() / BASE_BITS + 1] = {};
    format_uint<BASE_BITS>(buffer, value, num_digits, upper);
    return detail::copy_str_noinline<Char>(buffer, buffer + num_digits, out);
}
References format_uint(), and to_unsigned().
fwrite_fully()
void fmt::v10::detail::fwrite_fully (const void * ptr, size_t size, size_t count, FILE * stream) inline
Definition at line 71 of file format-inl.h.
{
    size_t written = std::fwrite(ptr, size, count, stream);
    if (written < count) FMT_THROW(system_error(errno, FMT_STRING("cannot write to file")));
}
References count(), FMT_STRING, FMT_THROW, and fwrite_fully().
Referenced by fwrite_fully(), and print().
get_arg()
template<typename Context , typename ID > auto fmt::v10::detail::get_arg (Context & ctx, ID id) -> decltype(ctx.arg(id))
Definition at line 3526 of file format.h.
{
    auto arg = ctx.arg(id);
    if (!arg) ctx.on_error("argument not found");
    return arg;
}
References get_arg().
Referenced by get_arg(), handle_dynamic_spec(), and vformat_to().
get_arg_index_by_name()
template<typename... Args, typename Char > auto fmt::v10::detail::get_arg_index_by_name (basic_string_view< Char > name) -> int
Definition at line 2359 of file core.h.
           {
#if FMT_USE_NONTYPE_TEMPLATE_ARGS
    if constexpr (sizeof...(Args) > 0) return get_arg_index_by_name<0, Args...>(name);
#endif
    (void)name;
    return -1;
}
References get_arg_index_by_name(), and name.
Referenced by get_arg_index_by_name(), and fmt::v10::detail::format_string_checker< Char, Args >::on_arg_id().
get_buffer() [1/2]
template<typename T , typename OutputIt > auto fmt::v10::detail::get_buffer (OutputIt out) -> iterator_buffer<OutputIt, T>
Definition at line 1040 of file core.h.
{
    return iterator_buffer<OutputIt, T>(out);
}
References get_buffer().
Referenced by get_buffer(), and get_buffer().
get_buffer() [2/2]
template<typename T , typename Buf , fmt::enable_if_t<(std::is_base_of< buffer< char >, Buf >::value), int > = 0> auto fmt::v10::detail::get_buffer (std::back_insert_iterator< Buf > out) -> buffer<char>&
Definition at line 1045 of file core.h.
{
    return get_container(out);
}
References get_buffer(), and get_container().
get_container()
template<typename Container > auto fmt::v10::detail::get_container (std::back_insert_iterator< Container > it) -> Container& inline
Definition at line 705 of file core.h.
{
    using base = std::back_insert_iterator<Container>;
    struct accessor : base {
            accessor(base b) : base(b) {}
            using base::container;
    };
    return *accessor(it).container;
}
References get_container().
Referenced by fmt::v10::detail::iterator_buffer< std::back_insert_iterator< Container >, enable_if_t< is_contiguous< Container >::value, typename Container::value_type > >::iterator_buffer(), copy_str(), copy_str(), get_buffer(), get_container(), reserve(), reserve(), and to_pointer().
get_data() [1/2]
template<typename Container > auto fmt::v10::detail::get_data (Container & c) -> typename Container::value_type* inline
Definition at line 551 of file format.h.
{ return c.data(); }
References get_data().
get_data() [2/2]
template<typename Char > auto fmt::v10::detail::get_data (std::basic_string< Char > & s) -> Char* inline
Definition at line 549 of file format.h.
{ return &s[0]; }
References get_data().
Referenced by get_data(), get_data(), and reserve().
get_dynamic_spec()
template<template< typename > class Handler, typename FormatArg , typename ErrorHandler > auto fmt::v10::detail::get_dynamic_spec (FormatArg arg, ErrorHandler eh) -> int
Definition at line 3520 of file format.h.
{
    unsigned long long value = visit_format_arg(Handler<ErrorHandler>(eh), arg);
    if (value > to_unsigned(max_value<int>())) eh.on_error("number is too big");
    return static_cast<int>(value);
}
References get_dynamic_spec(), and to_unsigned().
Referenced by get_dynamic_spec().
get_iterator() [1/2]
template<typename Buf , typename OutputIt > auto fmt::v10::detail::get_iterator (Buf & buf, OutputIt) -> decltype(buf.out()) inline
Definition at line 1049 of file core.h.
{
    return buf.out();
}
References get_iterator().
Referenced by get_iterator(), and get_iterator().
get_iterator() [2/2]
template<typename T , typename OutputIt > auto fmt::v10::detail::get_iterator (buffer< T > & , OutputIt out) -> OutputIt
Definition at line 1053 of file core.h.
{ return out; }
References get_iterator().
get_significand_size() [1/2]
auto fmt::v10::detail::get_significand_size (const big_decimal_fp & f) -> int constexpr
Definition at line 2300 of file format.h.
{ return f.significand_size; }
References get_significand_size().
Referenced by do_write_float(), get_significand_size(), and get_significand_size().
get_significand_size() [2/2]
template<typename T > auto fmt::v10::detail::get_significand_size (const dragonbox::decimal_fp< T > & f) -> int inline
Definition at line 2302 of file format.h.
{
    return count_digits(f.significand);
}
References count_digits(), and get_significand_size().
handle_dynamic_spec()
template<template< typename > class Handler, typename Context > void fmt::v10::detail::handle_dynamic_spec (int & value, arg_ref< typename Context::char_type > ref, Context & ctx)
Definition at line 3533 of file format.h.
{
    switch (ref.kind) {
        case arg_id_kind::none: break;
        case arg_id_kind::index:
            value = detail::get_dynamic_spec<Handler>(get_arg(ctx, ref.val.index), ctx.error_handler());
            break;
        case arg_id_kind::name:
            value = detail::get_dynamic_spec<Handler>(get_arg(ctx, ref.val.name), ctx.error_handler());
            break;
    }
}
References get_arg(), handle_dynamic_spec(), fmt::v10::detail::arg_ref< Char >::value::index, fmt::v10::detail::arg_ref< Char >::kind, fmt::v10::detail::arg_ref< Char >::value::name, and fmt::v10::detail::arg_ref< Char >::val.
Referenced by handle_dynamic_spec().
has_const_formatter()
template<typename T , typename Context > auto fmt::v10::detail::has_const_formatter () -> bool constexpr
Definition at line 1032 of file core.h.
{
    return has_const_formatter_impl<Context>(static_cast<T*>(nullptr));
}
References has_const_formatter().
Referenced by has_const_formatter().
has_const_formatter_impl() [1/2]
template<typename Context > auto fmt::v10::detail::has_const_formatter_impl (...) -> bool constexpr
Definition at line 1030 of file core.h.
{ return false; }
References has_const_formatter_impl().
has_const_formatter_impl() [2/2]
template<typename Context , typename T > auto fmt::v10::detail::has_const_formatter_impl (T *) -> decltype(typename Context::template formatter_type<T>().format(std::declval<const T&>(), std::declval<Context&>()), true) constexpr
Definition at line 1023 of file core.h.
                      {
    return true;
}
References has_const_formatter_impl().
Referenced by has_const_formatter_impl(), and has_const_formatter_impl().
has_implicit_bit()
template<typename Float > bool fmt::v10::detail::has_implicit_bit () constexpr
Definition at line 1508 of file format.h.
{
    // An 80-bit FP number has a 64-bit significand an no implicit bit.
    return std::numeric_limits<Float>::digits != 64;
}
References has_implicit_bit().
Referenced by has_implicit_bit().
ignore_unused()
template<typename... T> void fmt::v10::detail::ignore_unused (const T & ...)
Definition at line 285 of file core.h.
{}
References ignore_unused().
Referenced by abort_fuzzing_if(), check_format_string(), ignore_unused(), and is_constant_evaluated().
in()
auto fmt::v10::detail::in (type t, int set) -> bool constexpr
Definition at line 565 of file core.h.
{ return ((set >> static_cast<int>(t)) & 1) != 0; }
References in(), and set().
Referenced by in(), and parse_format_specs().
init_named_args() [1/3]
template<typename Char > void fmt::v10::detail::init_named_args (named_arg_info< Char > * , int , int) inline
Definition at line 1095 of file core.h.
{}
References init_named_args().
Referenced by init_named_args(), init_named_args(), and init_named_args().
init_named_args() [2/3]
template<typename Char , typename T , typename... Tail, fmt::enable_if_t<(!is_named_arg< T >::value), int > = 0> void fmt::v10::detail::init_named_args (named_arg_info< Char > * named_args, int arg_count, int named_arg_count, const T & arg, const Tail &... args)
Definition at line 1104 of file core.h.
{
    init_named_args(named_args, arg_count + 1, named_arg_count, args...);
}
References init_named_args().
init_named_args() [3/3]
template<typename... Args> void fmt::v10::detail::init_named_args (std::nullptr_t , int , int , const Args & ...) inline
Definition at line 1115 of file core.h.
{}
References init_named_args().
is_arithmetic_type()
bool fmt::v10::detail::is_arithmetic_type (type t) constexpr
Definition at line 561 of file core.h.
{ return t > type::none_type && t <= type::last_numeric_type; }
References is_arithmetic_type().
Referenced by is_arithmetic_type(), and parse_format_specs().
is_big_endian()
auto fmt::v10::detail::is_big_endian () -> bool inline
Definition at line 351 of file format.h.
{
#ifdef _WIN32
    return false;
#elif defined(__BIG_ENDIAN__)
    return true;
#elif defined(__BYTE_ORDER__) && defined(__ORDER_BIG_ENDIAN__)
    return __BYTE_ORDER__ == __ORDER_BIG_ENDIAN__;
#else
    struct bytes {
            char data[sizeof(int)];
    };
    return bit_cast<bytes>(1).data[0] == 0;
#endif
}
References is_big_endian().
Referenced by is_big_endian().
is_constant_evaluated()
auto fmt::v10::detail::is_constant_evaluated (bool default_value = false) -> bool inline constexpr noexcept
Definition at line 287 of file core.h.
{
// Workaround for incompatibility between libstdc++ consteval-based
// std::is_constant_evaluated() implementation and clang-14.
// https://github.com/fmtlib/fmt/issues/3247
#if FMT_CPLUSPLUS >= 202002L && defined(_GLIBCXX_RELEASE) && _GLIBCXX_RELEASE >= 12 &&                                 \
    (FMT_CLANG_VERSION >= 1400 && FMT_CLANG_VERSION < 1500)
    ignore_unused(default_value);
    return __builtin_is_constant_evaluated();
#elif defined(__cpp_lib_is_constant_evaluated)
    ignore_unused(default_value);
    return std::is_constant_evaluated();
#else
    return default_value;
#endif
}
References ignore_unused(), and is_constant_evaluated().
Referenced by fmt::v10::detail::value< Context >::value(), bit_cast(), copy2(), copy_str(), count_digits(), count_digits(), count_digits(), countl_zero(), countl_zero(), fill_n(), format_float(), is_constant_evaluated(), isfinite(), fmt::v10::detail::uint128_fallback::operator+=(), signbit(), and write_float().
is_integral_type()
bool fmt::v10::detail::is_integral_type (type t) constexpr
Definition at line 559 of file core.h.
{ return t > type::none_type && t <= type::last_integer_type; }
References is_integral_type().
Referenced by fmt::v10::detail::compile_parse_context< Char >::check_dynamic_spec(), and is_integral_type().
is_name_start()
template<typename Char > auto fmt::v10::detail::is_name_start (Char c) -> bool constexpr
Definition at line 2000 of file core.h.
{
    return ('a' <= c && c <= 'z') || ('A' <= c && c <= 'Z') || c == '_';
}
References is_name_start().
Referenced by do_parse_arg_id(), and is_name_start().
is_negative()
template<typename T , fmt::enable_if_t<(is_signed< T >::value), int > = 0> auto fmt::v10::detail::is_negative (T value) -> bool constexpr
Definition at line 1065 of file format.h.
{
    return value < 0;
}
References is_negative().
Referenced by is_negative(), make_write_int_arg(), fmt::v10::detail::precision_checker< ErrorHandler >::operator()(), fmt::v10::detail::width_checker< ErrorHandler >::operator()(), and write().
is_printable() [1/2]
auto fmt::v10::detail::is_printable (uint16_t x, const singleton * singletons, size_t singletons_size, const unsigned char * singleton_lowers, const unsigned char * normal, size_t normal_size) -> bool inline
Definition at line 1393 of file format-inl.h.
            {
    auto upper = x >> 8;
    auto lower_start = 0;
    for (size_t i = 0; i < singletons_size; ++i) {
        auto s = singletons[i];
        auto lower_end = lower_start + s.lower_count;
        if (upper < s.upper) break;
        if (upper == s.upper) {
            for (auto j = lower_start; j < lower_end; ++j) {
                if (singleton_lowers[j] == (x & 0xff)) return false;
            }
        }
        lower_start = lower_end;
    }
    auto xsigned = static_cast<int>(x);
    auto current = true;
    for (size_t i = 0; i < normal_size; ++i) {
        auto v = static_cast<int>(normal[i]);
        auto len = (v & 0x80) != 0 ? (v & 0x7f) << 8 | normal[++i] : v;
        xsigned -= len;
        if (xsigned < 0) break;
        current = !current;
    }
    return current;
}
References is_printable().
Referenced by is_printable(), is_printable(), and needs_escape().
is_printable() [2/2]
auto fmt::v10::detail::is_printable (uint32_t cp) -> bool
Definition at line 1423 of file format-inl.h.
{
    static constexpr singleton singletons0[] = {
        {0x00, 1},  {0x03, 5},  {0x05, 6},  {0x06, 3}, {0x07, 6}, {0x08, 8},  {0x09, 17}, {0x0a, 28}, {0x0b, 25},
        {0x0c, 20}, {0x0d, 16}, {0x0e, 13}, {0x0f, 4}, {0x10, 3}, {0x12, 18}, {0x13, 9},  {0x16, 1},  {0x17, 5},
        {0x18, 2},  {0x19, 3},  {0x1a, 7},  {0x1c, 2}, {0x1d, 1}, {0x1f, 22}, {0x20, 3},  {0x2b, 3},  {0x2c, 2},
        {0x2d, 11}, {0x2e, 1},  {0x30, 3},  {0x31, 2}, {0x32, 1}, {0xa7, 2},  {0xa9, 2},  {0xaa, 4},  {0xab, 8},
        {0xfa, 2},  {0xfb, 5},  {0xfd, 4},  {0xfe, 3}, {0xff, 9},
    };
    static constexpr unsigned char singletons0_lower[] = {
        0xad, 0x78, 0x79, 0x8b, 0x8d, 0xa2, 0x30, 0x57, 0x58, 0x8b, 0x8c, 0x90, 0x1c, 0x1d, 0xdd, 0x0e, 0x0f, 0x4b,
        0x4c, 0xfb, 0xfc, 0x2e, 0x2f, 0x3f, 0x5c, 0x5d, 0x5f, 0xb5, 0xe2, 0x84, 0x8d, 0x8e, 0x91, 0x92, 0xa9, 0xb1,
        0xba, 0xbb, 0xc5, 0xc6, 0xc9, 0xca, 0xde, 0xe4, 0xe5, 0xff, 0x00, 0x04, 0x11, 0x12, 0x29, 0x31, 0x34, 0x37,
        0x3a, 0x3b, 0x3d, 0x49, 0x4a, 0x5d, 0x84, 0x8e, 0x92, 0xa9, 0xb1, 0xb4, 0xba, 0xbb, 0xc6, 0xca, 0xce, 0xcf,
        0xe4, 0xe5, 0x00, 0x04, 0x0d, 0x0e, 0x11, 0x12, 0x29, 0x31, 0x34, 0x3a, 0x3b, 0x45, 0x46, 0x49, 0x4a, 0x5e,
        0x64, 0x65, 0x84, 0x91, 0x9b, 0x9d, 0xc9, 0xce, 0xcf, 0x0d, 0x11, 0x29, 0x45, 0x49, 0x57, 0x64, 0x65, 0x8d,
        0x91, 0xa9, 0xb4, 0xba, 0xbb, 0xc5, 0xc9, 0xdf, 0xe4, 0xe5, 0xf0, 0x0d, 0x11, 0x45, 0x49, 0x64, 0x65, 0x80,
        0x84, 0xb2, 0xbc, 0xbe, 0xbf, 0xd5, 0xd7, 0xf0, 0xf1, 0x83, 0x85, 0x8b, 0xa4, 0xa6, 0xbe, 0xbf, 0xc5, 0xc7,
        0xce, 0xcf, 0xda, 0xdb, 0x48, 0x98, 0xbd, 0xcd, 0xc6, 0xce, 0xcf, 0x49, 0x4e, 0x4f, 0x57, 0x59, 0x5e, 0x5f,
        0x89, 0x8e, 0x8f, 0xb1, 0xb6, 0xb7, 0xbf, 0xc1, 0xc6, 0xc7, 0xd7, 0x11, 0x16, 0x17, 0x5b, 0x5c, 0xf6, 0xf7,
        0xfe, 0xff, 0x80, 0x0d, 0x6d, 0x71, 0xde, 0xdf, 0x0e, 0x0f, 0x1f, 0x6e, 0x6f, 0x1c, 0x1d, 0x5f, 0x7d, 0x7e,
        0xae, 0xaf, 0xbb, 0xbc, 0xfa, 0x16, 0x17, 0x1e, 0x1f, 0x46, 0x47, 0x4e, 0x4f, 0x58, 0x5a, 0x5c, 0x5e, 0x7e,
        0x7f, 0xb5, 0xc5, 0xd4, 0xd5, 0xdc, 0xf0, 0xf1, 0xf5, 0x72, 0x73, 0x8f, 0x74, 0x75, 0x96, 0x2f, 0x5f, 0x26,
        0x2e, 0x2f, 0xa7, 0xaf, 0xb7, 0xbf, 0xc7, 0xcf, 0xd7, 0xdf, 0x9a, 0x40, 0x97, 0x98, 0x30, 0x8f, 0x1f, 0xc0,
        0xc1, 0xce, 0xff, 0x4e, 0x4f, 0x5a, 0x5b, 0x07, 0x08, 0x0f, 0x10, 0x27, 0x2f, 0xee, 0xef, 0x6e, 0x6f, 0x37,
        0x3d, 0x3f, 0x42, 0x45, 0x90, 0x91, 0xfe, 0xff, 0x53, 0x67, 0x75, 0xc8, 0xc9, 0xd0, 0xd1, 0xd8, 0xd9, 0xe7,
        0xfe, 0xff,
    };
    static constexpr singleton singletons1[] = {
        {0x00, 6}, {0x01, 1}, {0x03, 1},  {0x04, 2}, {0x08, 8},  {0x09, 2}, {0x0a, 5},  {0x0b, 2}, {0x0e, 4}, {0x10, 1},
        {0x11, 2}, {0x12, 5}, {0x13, 17}, {0x14, 1}, {0x15, 2},  {0x17, 2}, {0x19, 13}, {0x1c, 5}, {0x1d, 8}, {0x24, 1},
        {0x6a, 3}, {0x6b, 2}, {0xbc, 2},  {0xd1, 2}, {0xd4, 12}, {0xd5, 9}, {0xd6, 2},  {0xd7, 2}, {0xda, 1}, {0xe0, 5},
        {0xe1, 2}, {0xe8, 2}, {0xee, 32}, {0xf0, 4}, {0xf8, 2},  {0xf9, 2}, {0xfa, 2},  {0xfb, 1},
    };
    static constexpr unsigned char singletons1_lower[] = {
        0x0c, 0x27, 0x3b, 0x3e, 0x4e, 0x4f, 0x8f, 0x9e, 0x9e, 0x9f, 0x06, 0x07, 0x09, 0x36, 0x3d, 0x3e, 0x56, 0xf3,
        0xd0, 0xd1, 0x04, 0x14, 0x18, 0x36, 0x37, 0x56, 0x57, 0x7f, 0xaa, 0xae, 0xaf, 0xbd, 0x35, 0xe0, 0x12, 0x87,
        0x89, 0x8e, 0x9e, 0x04, 0x0d, 0x0e, 0x11, 0x12, 0x29, 0x31, 0x34, 0x3a, 0x45, 0x46, 0x49, 0x4a, 0x4e, 0x4f,
        0x64, 0x65, 0x5c, 0xb6, 0xb7, 0x1b, 0x1c, 0x07, 0x08, 0x0a, 0x0b, 0x14, 0x17, 0x36, 0x39, 0x3a, 0xa8, 0xa9,
        0xd8, 0xd9, 0x09, 0x37, 0x90, 0x91, 0xa8, 0x07, 0x0a, 0x3b, 0x3e, 0x66, 0x69, 0x8f, 0x92, 0x6f, 0x5f, 0xee,
        0xef, 0x5a, 0x62, 0x9a, 0x9b, 0x27, 0x28, 0x55, 0x9d, 0xa0, 0xa1, 0xa3, 0xa4, 0xa7, 0xa8, 0xad, 0xba, 0xbc,
        0xc4, 0x06, 0x0b, 0x0c, 0x15, 0x1d, 0x3a, 0x3f, 0x45, 0x51, 0xa6, 0xa7, 0xcc, 0xcd, 0xa0, 0x07, 0x19, 0x1a,
        0x22, 0x25, 0x3e, 0x3f, 0xc5, 0xc6, 0x04, 0x20, 0x23, 0x25, 0x26, 0x28, 0x33, 0x38, 0x3a, 0x48, 0x4a, 0x4c,
        0x50, 0x53, 0x55, 0x56, 0x58, 0x5a, 0x5c, 0x5e, 0x60, 0x63, 0x65, 0x66, 0x6b, 0x73, 0x78, 0x7d, 0x7f, 0x8a,
        0xa4, 0xaa, 0xaf, 0xb0, 0xc0, 0xd0, 0xae, 0xaf, 0x79, 0xcc, 0x6e, 0x6f, 0x93,
    };
    static constexpr unsigned char normal0[] = {
        0x00, 0x20, 0x5f, 0x22, 0x82, 0xdf, 0x04, 0x82, 0x44, 0x08, 0x1b, 0x04, 0x06, 0x11, 0x81, 0xac, 0x0e, 0x80,
        0xab, 0x35, 0x28, 0x0b, 0x80, 0xe0, 0x03, 0x19, 0x08, 0x01, 0x04, 0x2f, 0x04, 0x34, 0x04, 0x07, 0x03, 0x01,
        0x07, 0x06, 0x07, 0x11, 0x0a, 0x50, 0x0f, 0x12, 0x07, 0x55, 0x07, 0x03, 0x04, 0x1c, 0x0a, 0x09, 0x03, 0x08,
        0x03, 0x07, 0x03, 0x02, 0x03, 0x03, 0x03, 0x0c, 0x04, 0x05, 0x03, 0x0b, 0x06, 0x01, 0x0e, 0x15, 0x05, 0x3a,
        0x03, 0x11, 0x07, 0x06, 0x05, 0x10, 0x07, 0x57, 0x07, 0x02, 0x07, 0x15, 0x0d, 0x50, 0x04, 0x43, 0x03, 0x2d,
        0x03, 0x01, 0x04, 0x11, 0x06, 0x0f, 0x0c, 0x3a, 0x04, 0x1d, 0x25, 0x5f, 0x20, 0x6d, 0x04, 0x6a, 0x25, 0x80,
        0xc8, 0x05, 0x82, 0xb0, 0x03, 0x1a, 0x06, 0x82, 0xfd, 0x03, 0x59, 0x07, 0x15, 0x0b, 0x17, 0x09, 0x14, 0x0c,
        0x14, 0x0c, 0x6a, 0x06, 0x0a, 0x06, 0x1a, 0x06, 0x59, 0x07, 0x2b, 0x05, 0x46, 0x0a, 0x2c, 0x04, 0x0c, 0x04,
        0x01, 0x03, 0x31, 0x0b, 0x2c, 0x04, 0x1a, 0x06, 0x0b, 0x03, 0x80, 0xac, 0x06, 0x0a, 0x06, 0x21, 0x3f, 0x4c,
        0x04, 0x2d, 0x03, 0x74, 0x08, 0x3c, 0x03, 0x0f, 0x03, 0x3c, 0x07, 0x38, 0x08, 0x2b, 0x05, 0x82, 0xff, 0x11,
        0x18, 0x08, 0x2f, 0x11, 0x2d, 0x03, 0x20, 0x10, 0x21, 0x0f, 0x80, 0x8c, 0x04, 0x82, 0x97, 0x19, 0x0b, 0x15,
        0x88, 0x94, 0x05, 0x2f, 0x05, 0x3b, 0x07, 0x02, 0x0e, 0x18, 0x09, 0x80, 0xb3, 0x2d, 0x74, 0x0c, 0x80, 0xd6,
        0x1a, 0x0c, 0x05, 0x80, 0xff, 0x05, 0x80, 0xdf, 0x0c, 0xee, 0x0d, 0x03, 0x84, 0x8d, 0x03, 0x37, 0x09, 0x81,
        0x5c, 0x14, 0x80, 0xb8, 0x08, 0x80, 0xcb, 0x2a, 0x38, 0x03, 0x0a, 0x06, 0x38, 0x08, 0x46, 0x08, 0x0c, 0x06,
        0x74, 0x0b, 0x1e, 0x03, 0x5a, 0x04, 0x59, 0x09, 0x80, 0x83, 0x18, 0x1c, 0x0a, 0x16, 0x09, 0x4c, 0x04, 0x80,
        0x8a, 0x06, 0xab, 0xa4, 0x0c, 0x17, 0x04, 0x31, 0xa1, 0x04, 0x81, 0xda, 0x26, 0x07, 0x0c, 0x05, 0x05, 0x80,
        0xa5, 0x11, 0x81, 0x6d, 0x10, 0x78, 0x28, 0x2a, 0x06, 0x4c, 0x04, 0x80, 0x8d, 0x04, 0x80, 0xbe, 0x03, 0x1b,
        0x03, 0x0f, 0x0d,
    };
    static constexpr unsigned char normal1[] = {
        0x5e, 0x22, 0x7b, 0x05, 0x03, 0x04, 0x2d, 0x03, 0x66, 0x03, 0x01, 0x2f, 0x2e, 0x80, 0x82, 0x1d, 0x03, 0x31,
        0x0f, 0x1c, 0x04, 0x24, 0x09, 0x1e, 0x05, 0x2b, 0x05, 0x44, 0x04, 0x0e, 0x2a, 0x80, 0xaa, 0x06, 0x24, 0x04,
        0x24, 0x04, 0x28, 0x08, 0x34, 0x0b, 0x01, 0x80, 0x90, 0x81, 0x37, 0x09, 0x16, 0x0a, 0x08, 0x80, 0x98, 0x39,
        0x03, 0x63, 0x08, 0x09, 0x30, 0x16, 0x05, 0x21, 0x03, 0x1b, 0x05, 0x01, 0x40, 0x38, 0x04, 0x4b, 0x05, 0x2f,
        0x04, 0x0a, 0x07, 0x09, 0x07, 0x40, 0x20, 0x27, 0x04, 0x0c, 0x09, 0x36, 0x03, 0x3a, 0x05, 0x1a, 0x07, 0x04,
        0x0c, 0x07, 0x50, 0x49, 0x37, 0x33, 0x0d, 0x33, 0x07, 0x2e, 0x08, 0x0a, 0x81, 0x26, 0x52, 0x4e, 0x28, 0x08,
        0x2a, 0x56, 0x1c, 0x14, 0x17, 0x09, 0x4e, 0x04, 0x1e, 0x0f, 0x43, 0x0e, 0x19, 0x07, 0x0a, 0x06, 0x48, 0x08,
        0x27, 0x09, 0x75, 0x0b, 0x3f, 0x41, 0x2a, 0x06, 0x3b, 0x05, 0x0a, 0x06, 0x51, 0x06, 0x01, 0x05, 0x10, 0x03,
        0x05, 0x80, 0x8b, 0x62, 0x1e, 0x48, 0x08, 0x0a, 0x80, 0xa6, 0x5e, 0x22, 0x45, 0x0b, 0x0a, 0x06, 0x0d, 0x13,
        0x39, 0x07, 0x0a, 0x36, 0x2c, 0x04, 0x10, 0x80, 0xc0, 0x3c, 0x64, 0x53, 0x0c, 0x48, 0x09, 0x0a, 0x46, 0x45,
        0x1b, 0x48, 0x08, 0x53, 0x1d, 0x39, 0x81, 0x07, 0x46, 0x0a, 0x1d, 0x03, 0x47, 0x49, 0x37, 0x03, 0x0e, 0x08,
        0x0a, 0x06, 0x39, 0x07, 0x0a, 0x81, 0x36, 0x19, 0x80, 0xb7, 0x01, 0x0f, 0x32, 0x0d, 0x83, 0x9b, 0x66, 0x75,
        0x0b, 0x80, 0xc4, 0x8a, 0xbc, 0x84, 0x2f, 0x8f, 0xd1, 0x82, 0x47, 0xa1, 0xb9, 0x82, 0x39, 0x07, 0x2a, 0x04,
        0x02, 0x60, 0x26, 0x0a, 0x46, 0x0a, 0x28, 0x05, 0x13, 0x82, 0xb0, 0x5b, 0x65, 0x4b, 0x04, 0x39, 0x07, 0x11,
        0x40, 0x05, 0x0b, 0x02, 0x0e, 0x97, 0xf8, 0x08, 0x84, 0xd6, 0x2a, 0x09, 0xa2, 0xf7, 0x81, 0x1f, 0x31, 0x03,
        0x11, 0x04, 0x08, 0x81, 0x8c, 0x89, 0x04, 0x6b, 0x05, 0x0d, 0x03, 0x09, 0x07, 0x10, 0x93, 0x60, 0x80, 0xf6,
        0x0a, 0x73, 0x08, 0x6e, 0x17, 0x46, 0x80, 0x9a, 0x14, 0x0c, 0x57, 0x09, 0x19, 0x80, 0x87, 0x81, 0x47, 0x03,
        0x85, 0x42, 0x0f, 0x15, 0x85, 0x50, 0x2b, 0x80, 0xd5, 0x2d, 0x03, 0x1a, 0x04, 0x02, 0x81, 0x70, 0x3a, 0x05,
        0x01, 0x85, 0x00, 0x80, 0xd7, 0x29, 0x4c, 0x04, 0x0a, 0x04, 0x02, 0x83, 0x11, 0x44, 0x4c, 0x3d, 0x80, 0xc2,
        0x3c, 0x06, 0x01, 0x04, 0x55, 0x05, 0x1b, 0x34, 0x02, 0x81, 0x0e, 0x2c, 0x04, 0x64, 0x0c, 0x56, 0x0a, 0x80,
        0xae, 0x38, 0x1d, 0x0d, 0x2c, 0x04, 0x09, 0x07, 0x02, 0x0e, 0x06, 0x80, 0x9a, 0x83, 0xd8, 0x08, 0x0d, 0x03,
        0x0d, 0x03, 0x74, 0x0c, 0x59, 0x07, 0x0c, 0x14, 0x0c, 0x04, 0x38, 0x08, 0x0a, 0x06, 0x28, 0x08, 0x22, 0x4e,
        0x81, 0x54, 0x0c, 0x15, 0x03, 0x03, 0x05, 0x07, 0x09, 0x19, 0x07, 0x07, 0x09, 0x03, 0x0d, 0x07, 0x29, 0x80,
        0xcb, 0x25, 0x0a, 0x84, 0x06,
    };
    auto lower = static_cast<uint16_t>(cp);
    if (cp < 0x10000) {
        return is_printable(lower, singletons0, sizeof(singletons0) / sizeof(*singletons0), singletons0_lower, normal0,
                            sizeof(normal0));
    }
    if (cp < 0x20000) {
        return is_printable(lower, singletons1, sizeof(singletons1) / sizeof(*singletons1), singletons1_lower, normal1,
                            sizeof(normal1));
    }
    if (0x2a6de <= cp && cp < 0x2a700) return false;
    if (0x2b735 <= cp && cp < 0x2b740) return false;
    if (0x2b81e <= cp && cp < 0x2b820) return false;
    if (0x2cea2 <= cp && cp < 0x2ceb0) return false;
    if (0x2ebe1 <= cp && cp < 0x2f800) return false;
    if (0x2fa1e <= cp && cp < 0x30000) return false;
    if (0x3134b <= cp && cp < 0xe0100) return false;
    if (0xe01f0 <= cp && cp < 0x110000) return false;
    return cp < 0x110000;
}
References is_printable().
is_supported_floating_point()
template<typename T > auto fmt::v10::detail::is_supported_floating_point (T) -> bool
Definition at line 1071 of file format.h.
{
    if (std::is_same<T, float>()) return FMT_USE_FLOAT;
    if (std::is_same<T, double>()) return FMT_USE_DOUBLE;
    if (std::is_same<T, long double>()) return FMT_USE_LONG_DOUBLE;
    return true;
}
References FMT_USE_DOUBLE, FMT_USE_FLOAT, FMT_USE_LONG_DOUBLE, and is_supported_floating_point().
Referenced by is_supported_floating_point().
is_utf8()
auto fmt::v10::detail::is_utf8 () -> bool inline
Definition at line 353 of file core.h.
{
    FMT_MSC_WARNING(suppress : 4566) constexpr unsigned char section[] = "\u00A7";
    // Avoid buggy sign extensions in MSVC's constant evaluation mode (#2297).
    using uchar = unsigned char;
    return FMT_UNICODE || (sizeof(section) == 3 && uchar(section[0]) == 0xC2 && uchar(section[1]) == 0xA7);
}
References FMT_MSC_WARNING, FMT_UNICODE, and is_utf8().
Referenced by find_escape(), and is_utf8().
isfinite()
template<typename T , fmt::enable_if_t<(std::is_floating_point< T >::value &&has_isfinite< T >::value), int > = 0> bool fmt::v10::detail::isfinite (T value)
Definition at line 2508 of file format.h.
{
    constexpr T inf = T(std::numeric_limits<double>::infinity());
    if (is_constant_evaluated()) return !detail::isnan(value) && value < inf && value > -inf;
    return std::isfinite(value);
}
References is_constant_evaluated(), and isfinite().
Referenced by isfinite().
isnan()
template<typename T > bool fmt::v10::detail::isnan (T value) constexpr
Definition at line 2499 of file format.h.
{
    return !(value >= value); // std::isnan doesn't support __float128.
}
References isnan().
Referenced by isnan(), and write_nonfinite().
make_arg() [1/2]
template<typename Context , typename T > auto fmt::v10::detail::make_arg (T & val) -> basic_format_arg<Context>
Definition at line 1482 of file core.h.
{
    auto arg = basic_format_arg<Context>();
    arg.type_ = mapped_type_constant<T, Context>::value;
    arg.value_ = make_arg<true, Context>(val);
    return arg;
}
References make_arg().
make_arg() [2/2]
template<bool PACKED, typename Context , typename T , fmt::enable_if_t<(PACKED), int > = 0> auto fmt::v10::detail::make_arg (T & val) -> value<Context> inline
Definition at line 1461 of file core.h.
{
    using arg_type = remove_cvref_t<decltype(arg_mapper<Context>().map(val))>;
    constexpr bool formattable_char = !std::is_same<arg_type, unformattable_char>::value;
    static_assert(formattable_char, "Mixing character types is disallowed.");
    // Formatting of arbitrary pointers is disallowed. If you want to format a
    // pointer cast it to `void*` or `const void*`. In particular, this forbids
    // formatting of `[const] volatile char*` printed as bool by iostreams.
    constexpr bool formattable_pointer = !std::is_same<arg_type, unformattable_pointer>::value;
    static_assert(formattable_pointer, "Formatting of non-void pointers is disallowed.");
    constexpr bool formattable = !std::is_same<arg_type, unformattable>::value;
#if defined(__cpp_if_constexpr)
    if constexpr (!formattable) { type_is_unformattable_for<T, typename Context::char_type> _; }
#endif
    static_assert(formattable, "Cannot format an argument. To make type T formattable provide a "
                               "formatter<T> specialization: https://fmt.dev/latest/api.html#udt");
    return {arg_mapper<Context>().map(val)};
}
References make_arg(), and fmt::v10::detail::arg_mapper< Context >::map().
Referenced by make_arg(), and make_arg().
make_write_int_arg()
template<typename T > auto fmt::v10::detail::make_write_int_arg (T value, sign_t sign) -> write_int_arg<uint32_or_64_or_128_t<T>>
Definition at line 2006 of file format.h.
{
    auto prefix = 0u;
    auto abs_value = static_cast<uint32_or_64_or_128_t<T>>(value);
    if (is_negative(value)) {
        prefix = 0x01000000 | '-';
        abs_value = 0 - abs_value;
    } else {
        constexpr const unsigned prefixes[4] = {0, 0, 0x1000000u | '+', 0x1000000u | ' '};
        prefix = prefixes[sign];
    }
    return {abs_value, prefix};
}
References is_negative(), make_write_int_arg(), and sign().
Referenced by make_write_int_arg(), fmt::v10::detail::loc_writer< Char >::operator()(), and write().
max_value()
template<typename T > auto fmt::v10::detail::max_value () -> T constexpr
Definition at line 486 of file format.h.
{ return (std::numeric_limits<T>::max)(); }
References max_value().
Referenced by max_value(), fmt::v10::detail::dragonbox::remove_trailing_zeros(), and fmt::v10::detail::dragonbox::remove_trailing_zeros().
multiply()
uint64_t fmt::v10::detail::multiply (uint64_t lhs, uint64_t rhs) inline
Definition at line 1613 of file format.h.
{
#if FMT_USE_INT128
    auto product = static_cast<__uint128_t>(lhs) * rhs;
    auto f = static_cast<uint64_t>(product >> 64);
    return (static_cast<uint64_t>(product) & (1ULL << 63)) != 0 ? f + 1 : f;
#else
    // Multiply 32-bit parts of significands.
    uint64_t mask = (1ULL << 32) - 1;
    uint64_t a = lhs >> 32, b = lhs & mask;
    uint64_t c = rhs >> 32, d = rhs & mask;
    uint64_t ac = a * c, bc = b * c, ad = a * d, bd = b * d;
    // Compute mid 64-bit of result and round.
    uint64_t mid = (bd >> 32) + (ad & mask) + (bc & mask) + (1U << 31);
    return ac + (ad >> 32) + (bc >> 32) + (mid >> 32);
#endif
}
References multiply().
Referenced by multiply(), operator*(), and fmt::v10::detail::bigint::operator*=().
needs_escape()
auto fmt::v10::detail::needs_escape (uint32_t cp) -> bool inline
Definition at line 1720 of file format.h.
{
    return cp < 0x20 || cp == 0x7f || cp == '"' || cp == '\\' || !is_printable(cp);
}
References is_printable(), and needs_escape().
Referenced by find_escape(), find_escape(), needs_escape(), and write_escaped_char().
normalize()
template<int SHIFT = 0, typename F > basic_fp< F > fmt::v10::detail::normalize (basic_fp< F > value)
Definition at line 1597 of file format.h.
{
    // Handle subnormals.
    const auto implicit_bit = F(1) << num_significand_bits<double>();
    const auto shifted_implicit_bit = implicit_bit << SHIFT;
    while ((value.f & shifted_implicit_bit) == 0) {
        value.f <<= 1;
        --value.e;
    }
    // Subtract 1 to account for hidden bit.
    const auto offset = basic_fp<F>::num_significand_bits - num_significand_bits<double>() - SHIFT - 1;
    value.f <<= offset;
    value.e -= offset;
    return value;
}
References normalize().
Referenced by normalize().
num_bits()
template<typename T > auto fmt::v10::detail::num_bits () -> int constexpr
Definition at line 488 of file format.h.
{ return std::numeric_limits<T>::digits; }
References num_bits().
Referenced by num_bits().
num_bits< int128_opt >()
template<> auto fmt::v10::detail::num_bits< int128_opt > () -> int constexpr
Definition at line 491 of file format.h.
{ return 128; }
num_bits< uint128_t >()
template<> auto fmt::v10::detail::num_bits< uint128_t > () -> int constexpr
Definition at line 493 of file format.h.
{ return 128; }
num_significand_bits()
template<typename Float > int fmt::v10::detail::num_significand_bits () constexpr
Definition at line 1515 of file format.h.
{
    // std::numeric_limits may not support __float128.
    return is_float128<Float>() ? 112 : (std::numeric_limits<Float>::digits - (has_implicit_bit<Float>() ? 1 : 0));
}
References num_significand_bits().
Referenced by fmt::v10::detail::dragonbox::cache_accessor< double >::compute_left_endpoint_for_shorter_interval_case(), fmt::v10::detail::dragonbox::cache_accessor< float >::compute_left_endpoint_for_shorter_interval_case(), fmt::v10::detail::dragonbox::cache_accessor< double >::compute_right_endpoint_for_shorter_interval_case(), fmt::v10::detail::dragonbox::cache_accessor< float >::compute_right_endpoint_for_shorter_interval_case(), fmt::v10::detail::dragonbox::cache_accessor< double >::compute_round_up_for_shorter_interval_case(), fmt::v10::detail::dragonbox::cache_accessor< float >::compute_round_up_for_shorter_interval_case(), num_significand_bits(), and fmt::v10::detail::dragonbox::to_decimal().
operator*()
fp fmt::v10::detail::operator* (fp x, fp y) inline
Definition at line 1630 of file format.h.
{ return {multiply(x.f, y.f), x.e + y.e + 64}; }
References fmt::v10::detail::basic_fp< F >::e, fmt::v10::detail::basic_fp< F >::f, multiply(), and operator*().
Referenced by operator*().
operator==()
template<typename F > bool fmt::v10::detail::operator== (basic_fp< F > x, basic_fp< F > y) inline
Definition at line 139 of file format-inl.h.
{ return x.f == y.f && x.e == y.e; }
References fmt::v10::detail::basic_fp< F >::e, and fmt::v10::detail::basic_fp< F >::f.
parse_align() [1/2]
auto fmt::v10::detail::parse_align (char c) -> align_t inline
Definition at line 1991 of file core.h.
{
    switch (c) {
        case '<': return align::left;
        case '>': return align::right;
        case '^': return align::center;
    }
    return align::none;
}
References parse_align().
Referenced by parse_align(), parse_align(), and parse_format_specs().
parse_align() [2/2]
template<typename Char > auto fmt::v10::detail::parse_align (const Char * begin, const Char * end, format_specs< Char > & specs) -> const Char*
Definition at line 2198 of file format.h.
                   {
    FMT_ASSERT(begin != end, "");
    auto align = align::none;
    auto p = begin + code_point_length(begin);
    if (end - p <= 0) p = begin;
    for (;;) {
        switch (to_ascii(*p)) {
            case '<': align = align::left; break;
            case '>': align = align::right; break;
            case '^': align = align::center; break;
        }
        if (align != align::none) {
            if (p != begin) {
                auto c = *begin;
                if (c == '}') return begin;
                if (c == '{') {
                    throw_format_error("invalid fill character '{'");
                    return begin;
                }
                specs.fill = {begin, to_unsigned(p - begin)};
                begin = p + 1;
            } else {
                ++begin;
            }
            break;
        } else if (p == begin) {
            break;
        }
        p = begin;
    }
    specs.align = align;
    return begin;
}
References align, fmt::v10::format_specs< Char >::align, code_point_length(), fmt::v10::format_specs< Char >::fill, FMT_ASSERT, parse_align(), to_ascii(), and to_unsigned().
parse_arg_id()
template<typename Char , typename Handler > auto fmt::v10::detail::parse_arg_id (const Char * begin, const Char * end, Handler && handler) -> const Char* inline
Definition at line 2027 of file core.h.
{
    FMT_ASSERT(begin != end, "");
    Char c = *begin;
    if (c != '}' && c != ':') return do_parse_arg_id(begin, end, handler);
    handler.on_auto();
    return begin;
}
References do_parse_arg_id(), FMT_ASSERT, and parse_arg_id().
Referenced by parse_arg_id(), parse_dynamic_spec(), and parse_replacement_field().
parse_dynamic_spec()
template<typename Char > auto fmt::v10::detail::parse_dynamic_spec (const Char * begin, const Char * end, int & value, arg_ref< Char > & ref, basic_format_parse_context< Char > & ctx) -> const Char*
Definition at line 2058 of file core.h.
{
    FMT_ASSERT(begin != end, "");
    if ('0' <= *begin && *begin <= '9') {
        int val = parse_nonnegative_int(begin, end, -1);
        if (val != -1) value = val;
        else throw_format_error("number is too big");
    } else if (*begin == '{') {
        ++begin;
        auto handler = dynamic_spec_id_handler<Char> {ctx, ref};
        if (begin != end) begin = parse_arg_id(begin, end, handler);
        if (begin != end && *begin == '}') return ++begin;
        throw_format_error("invalid format string");
    }
    return begin;
}
References FMT_ASSERT, parse_arg_id(), parse_dynamic_spec(), and parse_nonnegative_int().
Referenced by parse_dynamic_spec(), parse_format_specs(), and parse_precision().
parse_float_type_spec()
template<typename ErrorHandler = error_handler, typename Char > auto fmt::v10::detail::parse_float_type_spec (const format_specs< Char > & specs, ErrorHandler && eh = {}) -> float_specs
Definition at line 2252 of file format.h.
                                                                                              {}) -> float_specs {
    auto result = float_specs();
    result.showpoint = specs.alt;
    result.locale = specs.localized;
    switch (specs.type) {
        case presentation_type::none: result.format = float_format::general; break;
        case presentation_type::general_upper: result.upper = true; FMT_FALLTHROUGH;
        case presentation_type::general_lower: result.format = float_format::general; break;
        case presentation_type::exp_upper: result.upper = true; FMT_FALLTHROUGH;
        case presentation_type::exp_lower:
            result.format = float_format::exp;
            result.showpoint |= specs.precision != 0;
            break;
        case presentation_type::fixed_upper: result.upper = true; FMT_FALLTHROUGH;
        case presentation_type::fixed_lower:
            result.format = float_format::fixed;
            result.showpoint |= specs.precision != 0;
            break;
        case presentation_type::hexfloat_upper: result.upper = true; FMT_FALLTHROUGH;
        case presentation_type::hexfloat_lower: result.format = float_format::hex; break;
        default: eh.on_error("invalid format specifier"); break;
    }
    return result;
}
References parse_float_type_spec().
Referenced by parse_float_type_spec(), and write_float().
parse_format_specs() [1/2]
template<typename Char > auto fmt::v10::detail::parse_format_specs (const Char * begin, const Char * end, dynamic_format_specs< Char > & specs, basic_format_parse_context< Char > & ctx, type arg_type) -> const Char* inline
Definition at line 2091 of file core.h.
{
    auto c = '\0';
    if (end - begin > 1) {
        auto next = to_ascii(begin[1]);
        c = parse_align(next) == align::none ? to_ascii(*begin) : '\0';
    } else {
        if (begin == end) return begin;
        c = to_ascii(*begin);
    }
    struct {
            state current_state = state::start;
            FMT_CONSTEXPR void operator()(state s, bool valid = true) {
                if (current_state >= s || !valid) throw_format_error("invalid format specifier");
                current_state = s;
            }
    } enter_state;
    using pres = presentation_type;
    constexpr auto integral_set = sint_set | uint_set | bool_set | char_set;
    struct {
            const Char*& begin;
            dynamic_format_specs<Char>& specs;
            type arg_type;
            FMT_CONSTEXPR auto operator()(pres type, int set) -> const Char* {
                if (!in(arg_type, set)) throw_format_error("invalid format specifier");
                specs.type = type;
                return begin + 1;
            }
    } parse_presentation_type {begin, specs, arg_type};
    for (;;) {
        switch (c) {
            case '<':
            case '>':
            case '^':
                enter_state(state::align);
                specs.align = parse_align(c);
                ++begin;
                break;
            case '+':
            case '-':
            case ' ':
                enter_state(state::sign, in(arg_type, sint_set | float_set));
                switch (c) {
                    case '+': specs.sign = sign::plus; break;
                    case '-': specs.sign = sign::minus; break;
                    case ' ': specs.sign = sign::space; break;
                }
                ++begin;
                break;
            case '#':
                enter_state(state::hash, is_arithmetic_type(arg_type));
                specs.alt = true;
                ++begin;
                break;
            case '0':
                enter_state(state::zero);
                if (!is_arithmetic_type(arg_type)) throw_format_error("format specifier requires numeric argument");
                if (specs.align == align::none) {
                    // Ignore 0 if align is specified for compatibility with std::format.
                    specs.align = align::numeric;
                    specs.fill[0] = Char('0');
                }
                ++begin;
                break;
            case '1':
            case '2':
            case '3':
            case '4':
            case '5':
            case '6':
            case '7':
            case '8':
            case '9':
            case '{':
                enter_state(state::width);
                begin = parse_dynamic_spec(begin, end, specs.width, specs.width_ref, ctx);
                break;
            case '.':
                enter_state(state::precision, in(arg_type, float_set | string_set | cstring_set));
                begin = parse_precision(begin, end, specs.precision, specs.precision_ref, ctx);
                break;
            case 'L':
                enter_state(state::locale, is_arithmetic_type(arg_type));
                specs.localized = true;
                ++begin;
                break;
            case 'd': return parse_presentation_type(pres::dec, integral_set);
            case 'o': return parse_presentation_type(pres::oct, integral_set);
            case 'x': return parse_presentation_type(pres::hex_lower, integral_set);
            case 'X': return parse_presentation_type(pres::hex_upper, integral_set);
            case 'b': return parse_presentation_type(pres::bin_lower, integral_set);
            case 'B': return parse_presentation_type(pres::bin_upper, integral_set);
            case 'a': return parse_presentation_type(pres::hexfloat_lower, float_set);
            case 'A': return parse_presentation_type(pres::hexfloat_upper, float_set);
            case 'e': return parse_presentation_type(pres::exp_lower, float_set);
            case 'E': return parse_presentation_type(pres::exp_upper, float_set);
            case 'f': return parse_presentation_type(pres::fixed_lower, float_set);
            case 'F': return parse_presentation_type(pres::fixed_upper, float_set);
            case 'g': return parse_presentation_type(pres::general_lower, float_set);
            case 'G': return parse_presentation_type(pres::general_upper, float_set);
            case 'c': return parse_presentation_type(pres::chr, integral_set);
            case 's': return parse_presentation_type(pres::string, bool_set | string_set | cstring_set);
            case 'p': return parse_presentation_type(pres::pointer, pointer_set | cstring_set);
            case '?': return parse_presentation_type(pres::debug, char_set | string_set | cstring_set);
            case '}': return begin;
            default: {
                if (*begin == '}') return begin;
                // Parse fill and alignment.
                auto fill_end = begin + code_point_length(begin);
                if (end - fill_end <= 0) {
                    throw_format_error("invalid format specifier");
                    return begin;
                }
                if (*begin == '{') {
                    throw_format_error("invalid fill character '{'");
                    return begin;
                }
                auto align = parse_align(to_ascii(*fill_end));
                enter_state(state::align, align != align::none);
                specs.fill = {begin, to_unsigned(fill_end - begin)};
                specs.align = align;
                begin = fill_end + 1;
            }
        }
        if (begin == end) return begin;
        c = to_ascii(*begin);
    }
}
References align, bool_set, char_set, code_point_length(), cstring_set, float_set, FMT_CONSTEXPR, in(), is_arithmetic_type(), parse_align(), parse_dynamic_spec(), parse_format_specs(), parse_precision(), pointer_set, set(), sint_set, string_set, to_ascii(), to_unsigned(), fmt::v10::format_specs< Char >::type, and uint_set.
Referenced by fmt::v10::detail::format_string_checker< Char, Args >::format_string_checker(), parse_format_specs(), parse_format_specs(), and vformat_to().
parse_format_specs() [2/2]
template<typename T , typename ParseContext > auto fmt::v10::detail::parse_format_specs (ParseContext & ctx) -> decltype(ctx.begin())
Definition at line 2317 of file core.h.
{
    using char_type = typename ParseContext::char_type;
    using context = buffer_context<char_type>;
    using mapped_type =
        conditional_t<mapped_type_constant<T, context>::value != type::custom_type,
                      decltype(arg_mapper<context>().map(std::declval<const T&>())), typename strip_named_arg<T>::type>;
#if defined(__cpp_if_constexpr)
    if constexpr (std::is_default_constructible_v<formatter<mapped_type, char_type>>) {
        return formatter<mapped_type, char_type>().parse(ctx);
    } else {
        type_is_unformattable_for<T, char_type> _;
        return ctx.begin();
    }
#else
    return formatter<mapped_type, char_type>().parse(ctx);
#endif
}
References char_type, fmt::v10::detail::arg_mapper< Context >::map(), and parse_format_specs().
parse_format_string()
template<bool IS_CONSTEXPR, typename Char , typename Handler > void fmt::v10::detail::parse_format_string (basic_string_view< Char > format_str, Handler && handler) inline
Definition at line 2262 of file core.h.
{
    auto begin = format_str.data();
    auto end = begin + format_str.size();
    if (end - begin < 32) {
        // Use a simple loop instead of memchr for small strings.
        const Char* p = begin;
        while (p != end) {
            auto c = *p++;
            if (c == '{') {
                handler.on_text(begin, p - 1);
                begin = p = parse_replacement_field(p - 1, end, handler);
            } else if (c == '}') {
                if (p == end || *p != '}') return handler.on_error("unmatched '}' in format string");
                handler.on_text(begin, p);
                begin = ++p;
            }
        }
        handler.on_text(begin, end);
        return;
    }
    struct writer {
            FMT_CONSTEXPR void operator()(const Char* from, const Char* to) {
                if (from == to) return;
                for (;;) {
                    const Char* p = nullptr;
                    if (!find<IS_CONSTEXPR>(from, to, Char('}'), p)) return handler_.on_text(from, to);
                    ++p;
                    if (p == to || *p != '}') return handler_.on_error("unmatched '}' in format string");
                    handler_.on_text(from, p);
                    from = p + 1;
                }
            }
            Handler& handler_;
    } write = {handler};
    while (begin != end) {
        // Doing two passes with memchr (one for '{' and another for '}') is up to
        // 2.5x faster than the naive one-pass implementation on big format strings.
        const Char* p = begin;
        if (*begin != '{' && !find<IS_CONSTEXPR>(begin + 1, end, Char('{'), p)) return write(begin, end);
        write(begin, p);
        begin = parse_replacement_field(p, end, handler);
    }
}
References fmt::v10::basic_string_view< Char >::data(), FMT_CONSTEXPR, fmt::v10::basic_format_context< OutputIt, Char >::on_error(), parse_format_string(), parse_replacement_field(), fmt::v10::basic_string_view< Char >::size(), and write().
Referenced by parse_format_string().
parse_nonnegative_int()
template<typename Char > auto fmt::v10::detail::parse_nonnegative_int (const Char *& begin, const Char * end, int error_value) -> int noexcept
Definition at line 1972 of file core.h.
{
    FMT_ASSERT(begin != end && '0' <= *begin && *begin <= '9', "");
    unsigned value = 0, prev = 0;
    auto p = begin;
    do {
        prev = value;
        value = value * 10 + unsigned(*p - '0');
        ++p;
    } while (p != end && '0' <= *p && *p <= '9');
    auto num_digits = p - begin;
    begin = p;
    if (num_digits <= std::numeric_limits<int>::digits10) return static_cast<int>(value);
    // Check for overflow.
    const unsigned max = to_unsigned((std::numeric_limits<int>::max)());
    return num_digits == std::numeric_limits<int>::digits10 + 1 && prev * 10ull + unsigned(p[-1] - '0') <= max
               ? static_cast<int>(value)
               : error_value;
}
References FMT_ASSERT, parse_nonnegative_int(), and to_unsigned().
Referenced by do_parse_arg_id(), parse_dynamic_spec(), and parse_nonnegative_int().
parse_precision()
template<typename Char > auto fmt::v10::detail::parse_precision (const Char * begin, const Char * end, int & value, arg_ref< Char > & ref, basic_format_parse_context< Char > & ctx) -> const Char*
Definition at line 2076 of file core.h.
                   {
    ++begin;
    if (begin == end || *begin == '}') {
        throw_format_error("invalid precision");
        return begin;
    }
    return parse_dynamic_spec(begin, end, value, ref, ctx);
}
References parse_dynamic_spec(), and parse_precision().
Referenced by parse_format_specs(), and parse_precision().
parse_replacement_field()
template<typename Char , typename Handler > auto fmt::v10::detail::parse_replacement_field (const Char * begin, const Char * end, Handler && handler) -> const Char*
Definition at line 2227 of file core.h.
{
    struct id_adapter {
            Handler& handler;
            int arg_id;
            FMT_CONSTEXPR void on_auto() { arg_id = handler.on_arg_id(); }
            FMT_CONSTEXPR void on_index(int id) { arg_id = handler.on_arg_id(id); }
            FMT_CONSTEXPR void on_name(basic_string_view<Char> id) { arg_id = handler.on_arg_id(id); }
    };
    ++begin;
    if (begin == end) return handler.on_error("invalid format string"), end;
    if (*begin == '}') {
        handler.on_replacement_field(handler.on_arg_id(), begin);
    } else if (*begin == '{') {
        handler.on_text(begin, begin + 1);
    } else {
        auto adapter = id_adapter {handler, 0};
        begin = parse_arg_id(begin, end, adapter);
        Char c = begin != end ? *begin : Char();
        if (c == '}') {
            handler.on_replacement_field(adapter.arg_id, begin);
        } else if (c == ':') {
            begin = handler.on_format_specs(adapter.arg_id, begin + 1, end);
            if (begin == end || *begin != '}') return handler.on_error("unknown format specifier"), end;
        } else {
            return handler.on_error("missing '}' in format string"), end;
        }
    }
    return begin + 1;
}
References FMT_CONSTEXPR, fmt::v10::basic_format_context< OutputIt, Char >::on_error(), parse_arg_id(), and parse_replacement_field().
Referenced by parse_format_string(), and parse_replacement_field().
prefix_append()
void fmt::v10::detail::prefix_append (unsigned & prefix, unsigned value) inline
Definition at line 1996 of file format.h.
{
    prefix |= prefix != 0 ? value << 8 : value;
    prefix += (1u + (value > 0xff ? 1 : 0)) << 24;
}
References prefix_append().
Referenced by prefix_append(), and write_int().
print()
void fmt::v10::detail::print (std::FILE * f, string_view text)
Definition at line 1373 of file format-inl.h.
{
    if (!write_console(f, text)) fwrite_fully(text.data(), 1, text.size(), f);
}
References fmt::v10::basic_string_view< Char >::data(), fwrite_fully(), fmt::v10::basic_string_view< Char >::size(), and write_console().
report_error()
void fmt::v10::detail::report_error (format_func func, int error_code, const char * message) noexcept
Definition at line 63 of file format-inl.h.
{
    memory_buffer full_message;
    func(full_message, error_code, message);
    // Don't use fwrite_fully because the latter may throw.
    if (std::fwrite(full_message.data(), full_message.size(), 1, stderr) > 0) std::fputc('\n', stderr);
}
References fmt::v10::detail::buffer< T >::data(), report_error(), and fmt::v10::detail::buffer< T >::size().
Referenced by report_error().
reserve() [1/3]
template<typename T > auto fmt::v10::detail::reserve (buffer_appender< T > it, size_t n) -> buffer_appender<T> inline
Definition at line 567 of file format.h.
{
    buffer<T>& buf = get_container(it);
    buf.try_reserve(buf.size() + n);
    return it;
}
References get_container(), reserve(), fmt::v10::detail::buffer< T >::size(), and fmt::v10::detail::buffer< T >::try_reserve().
reserve() [2/3]
template<typename Iterator > auto fmt::v10::detail::reserve (Iterator & it, size_t) -> Iterator& constexpr
Definition at line 573 of file format.h.
{ return it; }
References reserve().
reserve() [3/3]
template<typename Container , fmt::enable_if_t<(is_contiguous< Container >::value), int > = 0> auto fmt::v10::detail::reserve (std::back_insert_iterator< Container > it, size_t n) -> typename Container::value_type* inline
Definition at line 560 of file format.h.
{
    Container& c = get_container(it);
    size_t size = c.size();
    c.resize(size + n);
    return get_data(c) + size;
}
References get_container(), get_data(), and reserve().
Referenced by do_write_float(), reserve(), reserve(), reserve(), write(), write(), write(), write_float(), write_int(), write_padded(), and write_ptr().
rotr() [1/2]
uint32_t fmt::v10::detail::rotr (uint32_t n, uint32_t r) inline noexcept
Definition at line 142 of file format-inl.h.
{
    r &= 31;
    return (n >> r) | (n << (32 - r));
}
Referenced by fmt::v10::detail::dragonbox::remove_trailing_zeros(), and fmt::v10::detail::dragonbox::remove_trailing_zeros().
rotr() [2/2]
uint64_t fmt::v10::detail::rotr (uint64_t n, uint32_t r) inline noexcept
Definition at line 147 of file format-inl.h.
{
    r &= 63;
    return (n >> r) | (n << (64 - r));
}
set()
auto fmt::v10::detail::set (type rhs) -> int constexpr
Definition at line 563 of file core.h.
{ return 1 << static_cast<int>(rhs); }
References set().
Referenced by fmt::v10::detail::iterator_buffer< T *, T, fixed_buffer_traits >::iterator_buffer(), fmt::v10::detail::iterator_buffer< T *, T, fixed_buffer_traits >::flush(), fmt::v10::detail::iterator_buffer< std::back_insert_iterator< Container >, enable_if_t< is_contiguous< Container >::value, typename Container::value_type > >::grow(), in(), parse_format_specs(), and set().
sign()
template<typename Char , typename Sign > Char fmt::v10::detail::sign (Sign s) constexpr
Definition at line 1100 of file format.h.
{
#if !FMT_GCC_VERSION || FMT_GCC_VERSION >= 604
    static_assert(std::is_same<Sign, sign_t>::value, "");
#endif
    return static_cast<Char>("\0-+ "[s]);
}
References sign().
Referenced by do_write_float(), make_write_int_arg(), sign(), write_int(), and write_nonfinite().
signbit()
template<typename T , fmt::enable_if_t<(is_floating_point< T >::value), int > = 0> bool fmt::v10::detail::signbit (T value) inline
Definition at line 2520 of file format.h.
{
    if (is_constant_evaluated()) {
#ifdef __cpp_if_constexpr
        if constexpr (std::numeric_limits<double>::is_iec559) {
            auto bits = detail::bit_cast<uint64_t>(static_cast<double>(value));
            return (bits >> (num_bits<uint64_t>() - 1)) != 0;
        }
#endif
    }
    return std::signbit(static_cast<double>(value));
}
References is_constant_evaluated(), and signbit().
Referenced by signbit().
thousands_sep() [1/2]
template<typename Char > auto fmt::v10::detail::thousands_sep (locale_ref loc) -> thousands_sep_result<Char> inline
Definition at line 1213 of file format.h.
{
    auto result = thousands_sep_impl<char>(loc);
    return {result.grouping, Char(result.thousands_sep)};
}
References thousands_sep().
Referenced by thousands_sep(), thousands_sep(), and thousands_sep_impl().
thousands_sep() [2/2]
template<> auto fmt::v10::detail::thousands_sep (locale_ref loc) -> thousands_sep_result<wchar_t> inline
Definition at line 1218 of file format.h.
{
    return thousands_sep_impl<wchar_t>(loc);
}
References thousands_sep().
thousands_sep_impl()
template<typename Char > auto fmt::v10::detail::thousands_sep_impl (locale_ref loc) -> thousands_sep_result< Char >
Definition at line 86 of file format-inl.h.
{
    auto& facet = std::use_facet<std::numpunct<Char>>(loc.get<std::locale>());
    auto grouping = facet.grouping();
    auto thousands_sep = grouping.empty() ? Char() : facet.thousands_sep();
    return {std::move(grouping), thousands_sep};
}
References thousands_sep().
thousands_sep_impl< char >()
template auto fmt::v10::detail::thousands_sep_impl< char > (locale_ref) -> thousands_sep_result< char > extern
thousands_sep_impl< wchar_t >()
template auto fmt::v10::detail::thousands_sep_impl< wchar_t > (locale_ref) -> thousands_sep_result< wchar_t > extern
throw_format_error()
void fmt::v10::detail::throw_format_error (const char * message)
Definition at line 40 of file format-inl.h.
{ FMT_THROW(format_error(message)); }
References FMT_THROW.
to_ascii()
template<typename Char , fmt::enable_if_t<(std::is_integral< Char >::value), int > = 0> auto fmt::v10::detail::to_ascii (Char c) -> char constexpr
Definition at line 1940 of file core.h.
{
    return c <= 0xff ? static_cast<char>(c) : '\0';
}
References to_ascii().
Referenced by parse_align(), parse_format_specs(), and to_ascii().
to_pointer() [1/2]
template<typename T > auto fmt::v10::detail::to_pointer (buffer_appender< T > it, size_t n) -> T*
Definition at line 580 of file format.h.
{
    buffer<T>& buf = get_container(it);
    auto size = buf.size();
    if (buf.capacity() < size + n) return nullptr;
    buf.try_resize(size + n);
    return buf.data() + size;
}
References fmt::v10::detail::buffer< T >::capacity(), fmt::v10::detail::buffer< T >::data(), get_container(), fmt::v10::detail::buffer< T >::size(), to_pointer(), and fmt::v10::detail::buffer< T >::try_resize().
to_pointer() [2/2]
template<typename T , typename OutputIt > auto fmt::v10::detail::to_pointer (OutputIt , size_t) -> T* constexpr
Definition at line 578 of file format.h.
{ return nullptr; }
References to_pointer().
Referenced by to_pointer(), and to_pointer().
to_string_view() [1/6]
void fmt::v10::detail::to_string_view (...)
References to_string_view().
to_string_view() [2/6]
template<typename Char > auto fmt::v10::detail::to_string_view (basic_string_view< Char > s) -> basic_string_view<Char> constexpr
Definition at line 486 of file core.h.
{
    return s;
}
References to_string_view().
to_string_view() [3/6]
template<typename Char , fmt::enable_if_t<(is_char< Char >::value), int > = 0> auto fmt::v10::detail::to_string_view (const Char * s) -> basic_string_view<Char> inline
Definition at line 476 of file core.h.
{
    return s;
}
References to_string_view().
Referenced by fmt::v10::detail::arg_mapper< Context >::map(), to_string_view(), to_string_view(), to_string_view(), to_string_view(), to_string_view(), to_string_view(), and write().
to_string_view() [4/6]
template<typename S , fmt::enable_if_t<(is_compile_string< S >::value), int > = 0> auto fmt::v10::detail::to_string_view (const S & s) -> basic_string_view<typename S::char_type> constexpr
Definition at line 495 of file core.h.
{
    return basic_string_view<typename S::char_type>(s);
}
References to_string_view().
to_string_view() [5/6]
template<typename Char , typename Traits , typename Alloc > auto fmt::v10::detail::to_string_view (const std::basic_string< Char, Traits, Alloc > & s) -> basic_string_view<Char> inline
Definition at line 482 of file core.h.
{
    return s;
}
References to_string_view().
to_string_view() [6/6]
template<typename Char , fmt::enable_if_t<(!std::is_empty< std_string_view< Char > >::value), int > = 0> auto fmt::v10::detail::to_string_view (std_string_view< Char > s) -> basic_string_view<Char> inline
Definition at line 491 of file core.h.
{
    return s;
}
References to_string_view().
to_unsigned()
template<typename Int > auto fmt::v10::detail::to_unsigned (Int value) -> typename std::make_unsigned<Int>::type
Definition at line 348 of file core.h.
{
    FMT_ASSERT(std::is_unsigned<Int>::value || value >= 0, "negative value");
    return static_cast<typename std::make_unsigned<Int>::type>(value);
}
References FMT_ASSERT, and to_unsigned().
Referenced by fmt::v10::detail::write_int_data< Char >::write_int_data(), fmt::v10::detail::bigint::align(), fmt::v10::detail::digit_grouping< Char >::apply(), copy_str(), do_parse_arg_id(), do_write_float(), fill_n(), find< false, char >(), find_escape(), for_each_codepoint(), format_dragon(), format_float(), format_uint(), get_dynamic_spec(), fmt::v10::detail::bigint::operator[](), fmt::v10::detail::bigint::operator[](), parse_align(), parse_format_specs(), parse_nonnegative_int(), fmt::v10::detail::bigint::remove_leading_zeros(), fmt::v10::detail::bigint::square(), to_unsigned(), vformat_to(), write(), write_escaped_cp(), write_exponent(), write_int(), write_int(), write_padded(), write_ptr(), and write_significand().
umul128()
uint128_fallback fmt::v10::detail::umul128 (uint64_t x, uint64_t y) inline noexcept
Definition at line 1395 of file format.h.
{
#if FMT_USE_INT128
    auto p = static_cast<uint128_opt>(x) * static_cast<uint128_opt>(y);
    return {static_cast<uint64_t>(p >> 64), static_cast<uint64_t>(p)};
#elif defined(_MSC_VER) && defined(_M_X64)
    auto hi = uint64_t();
    auto lo = _umul128(x, y, &hi);
    return {hi, lo};
#else
    const uint64_t mask = static_cast<uint64_t>(max_value<uint32_t>());
    uint64_t a = x >> 32;
    uint64_t b = x & mask;
    uint64_t c = y >> 32;
    uint64_t d = y & mask;
    uint64_t ac = a * c;
    uint64_t bc = b * c;
    uint64_t ad = a * d;
    uint64_t bd = b * d;
    uint64_t intermediate = (bd >> 32) + (ad & mask) + (bc & mask);
    return {ac + (intermediate >> 32) + (ad >> 32) + (bc >> 32), (intermediate << 32) + (bd & mask)};
#endif
}
References umul128().
Referenced by fmt::v10::detail::dragonbox::cache_accessor< double >::get_cached_power(), fmt::v10::detail::dragonbox::remove_trailing_zeros(), umul128(), fmt::v10::detail::dragonbox::umul128_upper64(), fmt::v10::detail::dragonbox::umul192_lower128(), and fmt::v10::detail::dragonbox::umul192_upper128().
unwrap() [1/2]
template<typename T > const T & fmt::v10::detail::unwrap (const std::reference_wrapper< T > & v)
Definition at line 27 of file args.h.
{ return static_cast<const T&>(v); }
References unwrap().
unwrap() [2/2]
template<typename T > const T & fmt::v10::detail::unwrap (const T & v)
Definition at line 25 of file args.h.
{ return v; }
References unwrap().
Referenced by unwrap(), and unwrap().
utf8_decode()
auto fmt::v10::detail::utf8_decode (const char * s, uint32_t * c, int * e) -> const char* inline
Definition at line 638 of file format.h.
{
    constexpr const int masks[] = {0x00, 0x7f, 0x1f, 0x0f, 0x07};
    constexpr const uint32_t mins[] = {4194304, 0, 128, 2048, 65536};
    constexpr const int shiftc[] = {0, 18, 12, 6, 0};
    constexpr const int shifte[] = {0, 6, 4, 2, 0};
    int len = "\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\1\0\0\0\0\0\0\0\0\2\2\2\2\3\3\4"[static_cast<unsigned char>(*s) >> 3];
    // Compute the pointer to the next character early so that the next
    // iteration can start working on the next character. Neither Clang
    // nor GCC figure out this reordering on their own.
    const char* next = s + len + !len;
    using uchar = unsigned char;
    // Assume a four-byte character and load four bytes. Unused bits are
    // shifted out.
    *c = uint32_t(uchar(s[0]) & masks[len]) << 18;
    *c |= uint32_t(uchar(s[1]) & 0x3f) << 12;
    *c |= uint32_t(uchar(s[2]) & 0x3f) << 6;
    *c |= uint32_t(uchar(s[3]) & 0x3f) << 0;
    *c >>= shiftc[len];
    // Accumulate the various error conditions.
    *e = (*c < mins[len]) << 6; // non-canonical encoding
    *e |= ((*c >> 11) == 0x1b) << 7; // surrogate half?
    *e |= (*c > 0x10FFFF) << 8; // out of range?
    *e |= (uchar(s[1]) & 0xc0) >> 2;
    *e |= (uchar(s[2]) & 0xc0) >> 4;
    *e |= uchar(s[3]) >> 6;
    *e ^= 0x2a; // top two bits of each tail byte correct?
    *e >>= shifte[len];
    return next;
}
References utf8_decode().
Referenced by for_each_codepoint(), and utf8_decode().
vformat()
template<typename Locale , typename Char > auto fmt::v10::detail::vformat (const Locale & loc, basic_string_view< Char > fmt, basic_format_args< buffer_context< type_identity_t< Char > > > args) -> std::basic_string<Char>
Definition at line 3578 of file format.h.
{
    auto buf = basic_memory_buffer<Char>();
    detail::vformat_to(buf, fmt, args, detail::locale_ref(loc));
    return {buf.data(), buf.size()};
}
vformat_to() [1/2]
template void fmt::v10::detail::vformat_to (buffer< char > & , string_view , typename vformat_args<>::type , locale_ref) extern
References vformat_to().
vformat_to() [2/2]
template<typename Char > void fmt::v10::detail::vformat_to (buffer< Char > & buf, basic_string_view< Char > fmt, typename vformat_args< Char >::type args, locale_ref loc = {})
Definition at line 3963 of file format.h.
{
    auto out = buffer_appender<Char>(buf);
    if (fmt.size() == 2 && equal2(fmt.data(), "{}")) {
        auto arg = args.get(0);
        if (!arg) error_handler().on_error("argument not found");
        visit_format_arg(default_arg_formatter<Char> {out, args, loc}, arg);
        return;
    }
    struct format_handler : error_handler {
            basic_format_parse_context<Char> parse_context;
            buffer_context<Char> context;
            format_handler(buffer_appender<Char> p_out, basic_string_view<Char> str,
                           basic_format_args<buffer_context<Char>> p_args, locale_ref p_loc)
                : parse_context(str), context(p_out, p_args, p_loc) {}
            void on_text(const Char* begin, const Char* end) {
                auto text = basic_string_view<Char>(begin, to_unsigned(end - begin));
                context.advance_to(write<Char>(context.out(), text));
            }
            FMT_CONSTEXPR auto on_arg_id() -> int { return parse_context.next_arg_id(); }
            FMT_CONSTEXPR auto on_arg_id(int id) -> int { return parse_context.check_arg_id(id), id; }
            FMT_CONSTEXPR auto on_arg_id(basic_string_view<Char> id) -> int {
                int arg_id = context.arg_id(id);
                if (arg_id < 0) on_error("argument not found");
                return arg_id;
            }
            FMT_INLINE void on_replacement_field(int id, const Char*) {
                auto arg = get_arg(context, id);
                context.advance_to(visit_format_arg(
                    default_arg_formatter<Char> {context.out(), context.args(), context.locale()}, arg));
            }
            auto on_format_specs(int id, const Char* begin, const Char* end) -> const Char* {
                auto arg = get_arg(context, id);
                if (arg.type() == type::custom_type) {
                    parse_context.advance_to(begin);
                    visit_format_arg(custom_formatter<Char> {parse_context, context}, arg);
                    return parse_context.begin();
                }
                auto specs = detail::dynamic_format_specs<Char>();
                begin = parse_format_specs(begin, end, specs, parse_context, arg.type());
                detail::handle_dynamic_spec<detail::width_checker>(specs.width, specs.width_ref, context);
                detail::handle_dynamic_spec<detail::precision_checker>(specs.precision, specs.precision_ref, context);
                if (begin == end || *begin != '}') on_error("missing '}' in format string");
                auto f = arg_formatter<Char> {context.out(), specs, context.locale()};
                context.advance_to(visit_format_arg(f, arg));
                return begin;
            }
    };
    detail::parse_format_string<false>(fmt, format_handler(out, fmt, args, loc));
}
References fmt::v10::basic_format_context< OutputIt, Char >::advance_to(), fmt::v10::basic_format_parse_context< Char >::advance_to(), fmt::v10::basic_format_context< OutputIt, Char >::arg_id(), fmt::v10::basic_format_context< OutputIt, Char >::args(), fmt::v10::basic_format_parse_context< Char >::begin(), fmt::v10::basic_format_parse_context< Char >::check_arg_id(), equal2(), FMT_CONSTEXPR, FMT_INLINE, fmt::v10::basic_format_args< Context >::get(), get_arg(), fmt::v10::basic_format_context< OutputIt, Char >::locale(), fmt::v10::basic_format_parse_context< Char >::next_arg_id(), fmt::v10::detail::error_handler::on_error(), fmt::v10::basic_format_context< OutputIt, Char >::out(), parse_format_specs(), fmt::v10::format_specs< Char >::precision, to_unsigned(), vformat_to(), and fmt::v10::format_specs< Char >::width.
Referenced by vformat_to(), and vformat_to().
vprint_mojibake()
void fmt::v10::detail::vprint_mojibake (std::FILE * , string_view , format_args) inline
Definition at line 2450 of file core.h.
{}
References vprint_mojibake().
Referenced by vprint_mojibake().
write() [1/15]
template<typename Char , typename OutputIt > auto fmt::v10::detail::write (OutputIt out, basic_string_view< Char > s, const format_specs< Char > & specs) -> OutputIt
Definition at line 2148 of file format.h.
{
    auto data = s.data();
    auto size = s.size();
    if (specs.precision >= 0 && to_unsigned(specs.precision) < size)
        size = code_point_index(s, to_unsigned(specs.precision));
    bool is_debug = specs.type == presentation_type::debug;
    size_t width = 0;
    if (specs.width != 0) {
        if (is_debug) width = write_escaped_string(counting_iterator {}, s).count();
        else width = compute_width(basic_string_view<Char>(data, size));
    }
    return write_padded(out, specs, size, width, [=](reserve_iterator<OutputIt> it) {
        if (is_debug) return write_escaped_string(it, s);
        return copy_str<Char>(data, data + size, it);
    });
}
References code_point_index(), compute_width(), count(), fmt::v10::format_specs< Char >::precision, to_unsigned(), fmt::v10::format_specs< Char >::type, width, fmt::v10::format_specs< Char >::width, write(), write_escaped_string(), and write_padded().
write() [2/15]
template<typename Char , typename OutputIt > auto fmt::v10::detail::write (OutputIt out, basic_string_view< Char > value) -> OutputIt
Definition at line 3370 of file format.h.
                {
    auto it = reserve(out, value.size());
    it = copy_str_noinline<Char>(value.begin(), value.end(), it);
    return base_iterator(out, it);
}
References base_iterator(), reserve(), and write().
write() [3/15]
template<typename Char , typename OutputIt > auto fmt::v10::detail::write (OutputIt out, basic_string_view< type_identity_t< Char > > s, const format_specs< Char > & specs, locale_ref) -> OutputIt
Definition at line 2166 of file format.h.
{
    return write(out, s, specs);
}
References write().
write() [4/15]
template<typename Char , typename OutputIt > auto fmt::v10::detail::write (OutputIt out, Char value) -> OutputIt
Definition at line 3398 of file format.h.
{
    auto it = reserve(out, 1);
    *it++ = value;
    return base_iterator(out, it);
}
References base_iterator(), reserve(), and write().
write() [5/15]
template<typename Char , typename OutputIt > auto fmt::v10::detail::write (OutputIt out, Char value, const format_specs< Char > & specs, locale_ref loc = {}) -> OutputIt
Definition at line 1859 of file format.h.
                                                                                                     {}) -> OutputIt {
    // char is formatted as unsigned char for consistency across platforms.
    using unsigned_type = conditional_t<std::is_same<Char, char>::value, unsigned char, unsigned>;
    return check_char_specs(specs) ? write_char(out, value, specs)
                                   : write(out, static_cast<unsigned_type>(value), specs, loc);
}
References write().
Referenced by do_write_float(), parse_format_string(), write(), write(), write(), write(), write(), write(), write(), write(), write(), write(), write(), write(), write(), write(), and write_ptr().
write() [6/15]
template<typename Char , typename OutputIt > auto fmt::v10::detail::write (OutputIt out, const Char * s, const format_specs< Char > & specs, locale_ref) -> OutputIt
Definition at line 2172 of file format.h.
{
    return specs.type != presentation_type::pointer ? write(out, basic_string_view<Char>(s), specs, {})
                                                    : write_ptr<Char>(out, bit_cast<uintptr_t>(s), &specs);
}
References fmt::v10::format_specs< Char >::type, and write().
write() [7/15]
template<typename Char , typename OutputIt > auto fmt::v10::detail::write (OutputIt out, const Char * value) -> OutputIt
Definition at line 3404 of file format.h.
                {
    if (value) return write(out, basic_string_view<Char>(value));
    throw_format_error("string pointer is null");
    return out;
}
References write().
write() [8/15]
template<typename Char , typename OutputIt , typename T , typename Context = basic_format_context<OutputIt, Char>> auto fmt::v10::detail::write (OutputIt out, const T & value) -> enable_if_t<std::is_class<T>::value && !is_string<T>::value && !is_floating_point<T>::value && !std::is_same<T, Char>::value && !std::is_same<T, remove_cvref_t<decltype(arg_mapper<Context>().map(value))>>::value, OutputIt>
Definition at line 3418 of file format.h.
{
    return write<Char>(out, arg_mapper<Context>().map(value));
}
References write().
write() [9/15]
template<typename Char , typename OutputIt , typename T , fmt::enable_if_t<(is_string< T >::value), int > = 0> auto fmt::v10::detail::write (OutputIt out, const T & value) -> OutputIt constexpr
Definition at line 3378 of file format.h.
{
    return write<Char>(out, to_string_view(value));
}
References to_string_view(), and write().
write() [10/15]
template<typename Char , typename OutputIt , typename T , fmt::enable_if_t<(std::is_same< T, void >::value), int > = 0> auto fmt::v10::detail::write (OutputIt out, const T * value, const format_specs< Char > & specs = {}, locale_ref = {}) -> OutputIt
Definition at line 3412 of file format.h.
                                                                           {}, locale_ref = {}) -> OutputIt {
    return write_ptr<Char>(out, bit_cast<uintptr_t>(value), &specs);
}
References write().
write() [11/15]
template<typename Char , typename OutputIt > auto fmt::v10::detail::write (OutputIt out, monostate , format_specs< Char > = {}, locale_ref = {}) -> OutputIt
Definition at line 3365 of file format.h.
                                                         {}, locale_ref = {}) -> OutputIt {
    FMT_ASSERT(false, "");
    return out;
}
References write().
write() [12/15]
template<typename Char , typename OutputIt , typename T , fmt::enable_if_t<(is_integral< T >::value &&!std::is_same< T, bool >::value &&!std::is_same< T, Char >::value), int > = 0> auto fmt::v10::detail::write (OutputIt out, T value) -> OutputIt inline
Definition at line 2179 of file format.h.
{
    auto abs_value = static_cast<uint32_or_64_or_128_t<T>>(value);
    bool negative = is_negative(value);
    // Don't do -abs_value since it trips unsigned-integer-overflow sanitizer.
    if (negative) abs_value = ~abs_value + 1;
    int num_digits = count_digits(abs_value);
    auto size = (negative ? 1 : 0) + static_cast<size_t>(num_digits);
    auto it = reserve(out, size);
    if (auto ptr = to_pointer<Char>(it, size)) {
        if (negative) *ptr++ = static_cast<Char>('-');
        format_decimal<Char>(ptr, abs_value, num_digits);
        return out;
    }
    if (negative) *it++ = static_cast<Char>('-');
    it = format_decimal<Char>(it, abs_value, num_digits).end;
    return base_iterator(out, it);
}
References base_iterator(), count_digits(), is_negative(), reserve(), and write().
write() [13/15]
template<typename Char , typename OutputIt , typename T , bool check = std::is_enum<T>::value && !std::is_same<T, Char>::value && mapped_type_constant<T, basic_format_context<OutputIt, Char>>::value != type::custom_type, fmt::enable_if_t<(check), int > = 0> auto fmt::v10::detail::write (OutputIt out, T value) -> OutputIt
Definition at line 3387 of file format.h.
{
    return write<Char>(out, static_cast<underlying_t<T>>(value));
}
References write().
write() [14/15]
template<typename Char , typename OutputIt , typename T , fmt::enable_if_t<(is_integral< T >::value &&!std::is_same< T, bool >::value &&std::is_same< OutputIt, buffer_appender< Char > >::value), int > = 0> auto fmt::v10::detail::write (OutputIt out, T value, const format_specs< Char > & specs = {}, locale_ref loc = {}) -> OutputIt inline
Definition at line 2092 of file format.h.
                {
    if (specs.localized && write_loc(out, value, specs, loc)) return out;
    return write_int_noinline(out, make_write_int_arg(value, specs.sign), specs, loc);
}
References fmt::v10::format_specs< Char >::localized, make_write_int_arg(), fmt::v10::format_specs< Char >::sign, write(), write_int_noinline(), and write_loc().
write() [15/15]
template<typename Char , typename OutputIt , typename T , fmt::enable_if_t<(is_floating_point< T >::value), int > = 0> auto fmt::v10::detail::write (OutputIt out, T value, format_specs< Char > specs, locale_ref loc = {}) -> OutputIt
Definition at line 3332 of file format.h.
                                                                                             {}) -> OutputIt {
    if (const_check(!is_supported_floating_point(value))) return out;
    return specs.localized && write_loc(out, value, specs, loc) ? out : write_float(out, value, specs, loc);
}
References write().
write_bytes()
template<align::type align = align::left, typename Char , typename OutputIt > auto fmt::v10::detail::write_bytes (OutputIt out, string_view bytes, const format_specs< Char > & specs) -> OutputIt
Definition at line 1698 of file format.h.
{
    return write_padded<align>(out, specs, bytes.size(), [bytes](reserve_iterator<OutputIt> it) {
        const char* data = bytes.data();
        return copy_str<Char>(data, data + bytes.size(), it);
    });
}
References write_bytes().
Referenced by write_bytes().
write_char()
template<typename Char , typename OutputIt > auto fmt::v10::detail::write_char (OutputIt out, Char value, const format_specs< Char > & specs) -> OutputIt
Definition at line 1849 of file format.h.
{
    bool is_debug = specs.type == presentation_type::debug;
    return write_padded(out, specs, 1, [=](reserve_iterator<OutputIt> it) {
        if (is_debug) return write_escaped_char(it, value);
        *it++ = value;
        return it;
    });
}
References write_char(), write_escaped_char(), and write_padded().
Referenced by write_char(), and write_int().
write_codepoint()
template<size_t width, typename Char , typename OutputIt > auto fmt::v10::detail::write_codepoint (OutputIt out, char prefix, uint32_t cp) -> OutputIt
Definition at line 1780 of file format.h.
                {
    *out++ = static_cast<Char>('\\');
    *out++ = static_cast<Char>(prefix);
    Char buf[width];
    fill_n(buf, width, static_cast<Char>('0'));
    format_uint<4>(buf, cp, width);
    return copy_str<Char>(buf, buf + width, out);
}
References fill_n(), width, and write_codepoint().
Referenced by write_codepoint().
write_console()
bool fmt::v10::detail::write_console (std::FILE * , string_view)
Definition at line 1350 of file format-inl.h.
{ return false; }
References write_console().
Referenced by print(), and write_console().
write_escaped_char()
template<typename Char , typename OutputIt > auto fmt::v10::detail::write_escaped_char (OutputIt out, Char v) -> OutputIt
Definition at line 1837 of file format.h.
{
    *out++ = static_cast<Char>('\'');
    if ((needs_escape(static_cast<uint32_t>(v)) && v != static_cast<Char>('"')) || v == static_cast<Char>('\'')) {
        out = write_escaped_cp(out, find_escape_result<Char> {&v, &v + 1, static_cast<uint32_t>(v)});
    } else {
        *out++ = v;
    }
    *out++ = static_cast<Char>('\'');
    return out;
}
References needs_escape(), write_escaped_char(), and write_escaped_cp().
Referenced by write_char(), and write_escaped_char().
write_escaped_cp()
template<typename OutputIt , typename Char > auto fmt::v10::detail::write_escaped_cp (OutputIt out, const find_escape_result< Char > & escape) -> OutputIt
Definition at line 1790 of file format.h.
                {
    auto c = static_cast<Char>(escape.cp);
    switch (escape.cp) {
        case '\n':
            *out++ = static_cast<Char>('\\');
            c = static_cast<Char>('n');
            break;
        case '\r':
            *out++ = static_cast<Char>('\\');
            c = static_cast<Char>('r');
            break;
        case '\t':
            *out++ = static_cast<Char>('\\');
            c = static_cast<Char>('t');
            break;
        case '"': FMT_FALLTHROUGH;
        case '\'': FMT_FALLTHROUGH;
        case '\\': *out++ = static_cast<Char>('\\'); break;
        default:
            if (escape.cp < 0x100) { return write_codepoint<2, Char>(out, 'x', escape.cp); }
            if (escape.cp < 0x10000) { return write_codepoint<4, Char>(out, 'u', escape.cp); }
            if (escape.cp < 0x110000) { return write_codepoint<8, Char>(out, 'U', escape.cp); }
            for (Char escape_char : basic_string_view<Char>(escape.begin, to_unsigned(escape.end - escape.begin))) {
                out = write_codepoint<2, Char>(out, 'x', static_cast<uint32_t>(escape_char) & 0xFF);
            }
            return out;
    }
    *out++ = c;
    return out;
}
References FMT_FALLTHROUGH, to_unsigned(), and write_escaped_cp().
Referenced by write_escaped_char(), and write_escaped_cp().
write_escaped_string()
template<typename Char , typename OutputIt > auto fmt::v10::detail::write_escaped_string (OutputIt out, basic_string_view< Char > str) -> OutputIt
Definition at line 1822 of file format.h.
                {
    *out++ = static_cast<Char>('"');
    auto begin = str.begin(), end = str.end();
    do {
        auto escape = find_escape(begin, end);
        out = copy_str<Char>(begin, escape.begin, out);
        begin = escape.end;
        if (!begin) break;
        out = write_escaped_cp<OutputIt, Char>(out, escape);
    } while (begin != end);
    *out++ = static_cast<Char>('"');
    return out;
}
References find_escape(), and write_escaped_string().
Referenced by write(), and write_escaped_string().
write_exponent()
template<typename Char , typename It > auto fmt::v10::detail::write_exponent (int exp, It it) -> It
Definition at line 1531 of file format.h.
{
    FMT_ASSERT(-10000 < exp && exp < 10000, "exponent out of range");
    if (exp < 0) {
        *it++ = static_cast<Char>('-');
        exp = -exp;
    } else {
        *it++ = static_cast<Char>('+');
    }
    if (exp >= 100) {
        const char* top = digits2(to_unsigned(exp / 100));
        if (exp >= 1000) *it++ = static_cast<Char>(top[0]);
        *it++ = static_cast<Char>(top[1]);
        exp %= 100;
    }
    const char* d = digits2(to_unsigned(exp));
    *it++ = static_cast<Char>(d[0]);
    *it++ = static_cast<Char>(d[1]);
    return it;
}
References digits2(), exp, FMT_ASSERT, to_unsigned(), and write_exponent().
Referenced by write_exponent().
write_float() [1/2]
template<typename OutputIt , typename DecimalFP , typename Char > auto fmt::v10::detail::write_float (OutputIt out, const DecimalFP & f, const format_specs< Char > & specs, float_specs fspecs, locale_ref loc) -> OutputIt
Definition at line 2490 of file format.h.
{
    if (is_constant_evaluated()) {
        return do_write_float<OutputIt, DecimalFP, Char, fallback_digit_grouping<Char>>(out, f, specs, fspecs, loc);
    } else {
        return do_write_float(out, f, specs, fspecs, loc);
    }
}
References do_write_float(), is_constant_evaluated(), and write_float().
Referenced by write_float(), and write_float().
write_float() [2/2]
template<typename Char , typename OutputIt , typename T > auto fmt::v10::detail::write_float (OutputIt out, T value, format_specs< Char > specs, locale_ref loc) -> OutputIt
Definition at line 3291 of file format.h.
{
    float_specs fspecs = parse_float_type_spec(specs);
    fspecs.sign = specs.sign;
    if (detail::signbit(value)) { // value < 0 is false for NaN so use signbit.
        fspecs.sign = sign::minus;
        value = -value;
    } else if (fspecs.sign == sign::minus) {
        fspecs.sign = sign::none;
    }
    if (!detail::isfinite(value)) return write_nonfinite(out, detail::isnan(value), specs, fspecs);
    if (specs.align == align::numeric && fspecs.sign) {
        auto it = reserve(out, 1);
        *it++ = detail::sign<Char>(fspecs.sign);
        out = base_iterator(out, it);
        fspecs.sign = sign::none;
        if (specs.width != 0) --specs.width;
    }
    memory_buffer buffer;
    if (fspecs.format == float_format::hex) {
        if (fspecs.sign) buffer.push_back(detail::sign<char>(fspecs.sign));
        format_hexfloat(convert_float(value), specs.precision, fspecs, buffer);
        return write_bytes<align::right>(out, {buffer.data(), buffer.size()}, specs);
    }
    int precision = specs.precision >= 0 || specs.type == presentation_type::none ? specs.precision : 6;
    if (fspecs.format == float_format::exp) {
        if (precision == max_value<int>()) throw_format_error("number is too big");
        else ++precision;
    } else if (fspecs.format != float_format::fixed && precision == 0) {
        precision = 1;
    }
    if (const_check(std::is_same<T, float>())) fspecs.binary32 = true;
    int exp = format_float(convert_float(value), precision, fspecs, buffer);
    fspecs.precision = precision;
    auto f = big_decimal_fp {buffer.data(), static_cast<int>(buffer.size()), exp};
    return write_float(out, f, specs, fspecs, loc);
}
References base_iterator(), fmt::v10::detail::float_specs::binary32, const_check(), convert_float(), fmt::v10::detail::buffer< T >::data(), exp, fmt::v10::detail::float_specs::format, format_float(), format_hexfloat(), parse_float_type_spec(), fmt::v10::detail::float_specs::precision, precision, fmt::v10::detail::buffer< T >::push_back(), reserve(), fmt::v10::detail::float_specs::sign, fmt::v10::detail::buffer< T >::size(), write_float(), and write_nonfinite().
write_int() [1/3]
template<typename OutputIt , typename Char , typename W > auto fmt::v10::detail::write_int (OutputIt out, int num_digits, unsigned prefix, const format_specs< Char > & specs, W write_digits) -> OutputIt inline
Definition at line 1892 of file format.h.
{
    // Slightly faster check for specs.width == 0 && specs.precision == -1.
    if ((specs.width | (specs.precision + 1)) == 0) {
        auto it = reserve(out, to_unsigned(num_digits) + (prefix >> 24));
        if (prefix != 0) {
            for (unsigned p = prefix & 0xffffff; p != 0; p >>= 8) *it++ = static_cast<Char>(p & 0xff);
        }
        return base_iterator(out, write_digits(it));
    }
    auto data = write_int_data<Char>(num_digits, prefix, specs);
    return write_padded<align::right>(out, specs, data.size, [=](reserve_iterator<OutputIt> it) {
        for (unsigned p = prefix & 0xffffff; p != 0; p >>= 8) *it++ = static_cast<Char>(p & 0xff);
        it = detail::fill_n(it, data.padding, static_cast<Char>('0'));
        return write_digits(it);
    });
}
References base_iterator(), fmt::v10::format_specs< Char >::precision, reserve(), to_unsigned(), fmt::v10::format_specs< Char >::width, and write_int().
Referenced by fmt::v10::detail::loc_writer< Char >::operator()(), write_int(), write_int(), write_int(), and write_int_noinline().
write_int() [2/3]
template<typename OutputIt , typename UInt , typename Char > auto fmt::v10::detail::write_int (OutputIt out, UInt value, unsigned prefix, const format_specs< Char > & specs, const digit_grouping< Char > & grouping) -> OutputIt
Definition at line 1972 of file format.h.
{
    static_assert(std::is_same<uint64_or_128_t<UInt>, UInt>::value, "");
    int num_digits = count_digits(value);
    char digits[40];
    format_decimal(digits, value, num_digits);
    unsigned size = to_unsigned((prefix != 0 ? 1 : 0) + num_digits + grouping.count_separators(num_digits));
    return write_padded<align::right>(out, specs, size, size, [&](reserve_iterator<OutputIt> it) {
        if (prefix != 0) {
            char sign = static_cast<char>(prefix);
            *it++ = static_cast<Char>(sign);
        }
        return grouping.apply(it, string_view(digits, to_unsigned(num_digits)));
    });
}
References count_digits(), format_decimal(), sign(), to_unsigned(), and write_int().
write_int() [3/3]
template<typename Char , typename OutputIt , typename T > auto fmt::v10::detail::write_int (OutputIt out, write_int_arg< T > arg, const format_specs< Char > & specs, locale_ref) -> OutputIt inline
Definition at line 2038 of file format.h.
                {
    static_assert(std::is_same<T, uint32_or_64_or_128_t<T>>::value, "");
    auto abs_value = arg.abs_value;
    auto prefix = arg.prefix;
    switch (specs.type) {
        case presentation_type::none:
        case presentation_type::dec: {
            auto num_digits = count_digits(abs_value);
            return write_int(out, num_digits, prefix, specs, [=](reserve_iterator<OutputIt> it) {
                return format_decimal<Char>(it, abs_value, num_digits).end;
            });
        }
        case presentation_type::hex_lower:
        case presentation_type::hex_upper: {
            bool upper = specs.type == presentation_type::hex_upper;
            if (specs.alt) prefix_append(prefix, unsigned(upper ? 'X' : 'x') << 8 | '0');
            int num_digits = count_digits<4>(abs_value);
            return write_int(out, num_digits, prefix, specs, [=](reserve_iterator<OutputIt> it) {
                return format_uint<4, Char>(it, abs_value, num_digits, upper);
            });
        }
        case presentation_type::bin_lower:
        case presentation_type::bin_upper: {
            bool upper = specs.type == presentation_type::bin_upper;
            if (specs.alt) prefix_append(prefix, unsigned(upper ? 'B' : 'b') << 8 | '0');
            int num_digits = count_digits<1>(abs_value);
            return write_int(out, num_digits, prefix, specs, [=](reserve_iterator<OutputIt> it) {
                return format_uint<1, Char>(it, abs_value, num_digits);
            });
        }
        case presentation_type::oct: {
            int num_digits = count_digits<3>(abs_value);
            // Octal prefix '0' is counted as a digit, so only add it if precision
            // is not greater than the number of digits.
            if (specs.alt && specs.precision <= num_digits && abs_value != 0) prefix_append(prefix, '0');
            return write_int(out, num_digits, prefix, specs, [=](reserve_iterator<OutputIt> it) {
                return format_uint<3, Char>(it, abs_value, num_digits);
            });
        }
        case presentation_type::chr: return write_char(out, static_cast<Char>(abs_value), specs);
        default: throw_format_error("invalid format specifier");
    }
    return out;
}
References fmt::v10::format_specs< Char >::alt, count_digits(), fmt::v10::format_specs< Char >::precision, prefix_append(), fmt::v10::format_specs< Char >::type, write_char(), and write_int().
write_int_noinline()
template<typename Char , typename OutputIt , typename T > auto fmt::v10::detail::write_int_noinline (OutputIt out, write_int_arg< T > arg, const format_specs< Char > & specs, locale_ref loc) -> OutputIt
Definition at line 2085 of file format.h.
{
    return write_int(out, arg, specs, loc);
}
References write_int(), and write_int_noinline().
Referenced by write(), and write_int_noinline().
write_loc() [1/2]
auto fmt::v10::detail::write_loc (appender out, loc_value value, const format_specs<> & specs, locale_ref loc) -> bool
Definition at line 104 of file format-inl.h.
{
#ifndef FMT_STATIC_THOUSANDS_SEPARATOR
    auto locale = loc.get<std::locale>();
    // We cannot use the num_put<char> facet because it may produce output in
    // a wrong encoding.
    using facet = format_facet<std::locale>;
    if (std::has_facet<facet>(locale)) return std::use_facet<facet>(locale).put(out, value, specs);
    return facet(locale).put(out, value, specs);
#endif
    return false;
}
References locale, and fmt::v10::format_facet< Locale >::put().
Referenced by write(), and write_loc().
write_loc() [2/2]
template<typename OutputIt , typename Char > auto fmt::v10::detail::write_loc (OutputIt , loc_value , const format_specs< Char > & , locale_ref) -> bool inline
Definition at line 1992 of file format.h.
{
    return false;
}
References write_loc().
write_nonfinite()
template<typename Char , typename OutputIt > auto fmt::v10::detail::write_nonfinite (OutputIt out, bool isnan, format_specs< Char > specs, const float_specs & fspecs) -> OutputIt
Definition at line 2278 of file format.h.
                {
    auto str = isnan ? (fspecs.upper ? "NAN" : "nan") : (fspecs.upper ? "INF" : "inf");
    constexpr size_t str_size = 3;
    auto sign = fspecs.sign;
    auto size = str_size + (sign ? 1 : 0);
    // Replace '0'-padding with space for non-finite values.
    const bool is_zero_fill = specs.fill.size() == 1 && *specs.fill.data() == static_cast<Char>('0');
    if (is_zero_fill) specs.fill[0] = static_cast<Char>(' ');
    return write_padded(out, specs, size, [=](reserve_iterator<OutputIt> it) {
        if (sign) *it++ = detail::sign<Char>(sign);
        return copy_str<Char>(str, str + str_size, it);
    });
}
References fmt::v10::format_specs< Char >::fill, isnan(), sign(), write_nonfinite(), and write_padded().
Referenced by write_float(), and write_nonfinite().
write_padded() [1/2]
template<align::type align = align::left, typename OutputIt , typename Char , typename F > auto fmt::v10::detail::write_padded (OutputIt out, const format_specs< Char > & specs, size_t size, F && f) -> OutputIt constexpr
Definition at line 1693 of file format.h.
{
    return write_padded<align>(out, specs, size, size, f);
}
References write_padded().
write_padded() [2/2]
template<align::type align = align::left, typename OutputIt , typename Char , typename F > auto fmt::v10::detail::write_padded (OutputIt out, const format_specs< Char > & specs, size_t size, size_t width, F && f) -> OutputIt
Definition at line 1675 of file format.h.
                {
    static_assert(align == align::left || align == align::right, "");
    unsigned spec_width = to_unsigned(specs.width);
    size_t padding = spec_width > width ? spec_width - width : 0;
    // Shifts are encoded as string literals because static constexpr is not
    // supported in constexpr functions.
    auto* shifts = align == align::left ? "\x1f\x1f\x00\x01" : "\x00\x1f\x00\x01";
    size_t left_padding = padding >> shifts[specs.align];
    size_t right_padding = padding - left_padding;
    auto it = reserve(out, size + padding * specs.fill.size());
    if (left_padding != 0) it = fill(it, left_padding, specs.fill);
    it = f(it);
    if (right_padding != 0) it = fill(it, right_padding, specs.fill);
    return base_iterator(out, it);
}
References align, base_iterator(), fill(), reserve(), to_unsigned(), width, and write_padded().
Referenced by write(), write_char(), write_nonfinite(), write_padded(), and write_padded().
write_ptr()
template<typename Char , typename OutputIt , typename UIntPtr > auto fmt::v10::detail::write_ptr (OutputIt out, UIntPtr value, const format_specs< Char > * specs) -> OutputIt
Definition at line 1706 of file format.h.
{
    int num_digits = count_digits<4>(value);
    auto size = to_unsigned(num_digits) + size_t(2);
    auto write = [=](reserve_iterator<OutputIt> it) {
        *it++ = static_cast<Char>('0');
        *it++ = static_cast<Char>('x');
        return format_uint<4, Char>(it, value, num_digits);
    };
    return specs ? write_padded<align::right>(out, *specs, size, write) : base_iterator(out, write(reserve(out, size)));
}
References base_iterator(), reserve(), to_unsigned(), write(), and write_ptr().
Referenced by write_ptr().
write_significand() [1/7]
template<typename Char , typename UInt , fmt::enable_if_t<(std::is_integral< UInt >::value), int > = 0> auto fmt::v10::detail::write_significand (Char * out, UInt significand, int significand_size, int integral_size, Char decimal_point) -> Char* inline
Definition at line 2330 of file format.h.
             {
    if (!decimal_point) return format_decimal(out, significand, significand_size).end;
    out += significand_size + 1;
    Char* end = out;
    int floating_size = significand_size - integral_size;
    for (int i = floating_size / 2; i > 0; --i) {
        out -= 2;
        copy2(out, digits2(static_cast<std::size_t>(significand % 100)));
        significand /= 100;
    }
    if (floating_size % 2 != 0) {
        *--out = static_cast<Char>('0' + significand % 10);
        significand /= 10;
    }
    *--out = decimal_point;
    format_decimal(out - integral_size, significand, integral_size);
    return end;
}
References copy2(), decimal_point(), digits2(), format_decimal(), and write_significand().
write_significand() [2/7]
template<typename Char , typename OutputIt > auto fmt::v10::detail::write_significand (OutputIt out, const char * significand, int significand_size) -> OutputIt constexpr
Definition at line 2307 of file format.h.
{
    return copy_str<Char>(significand, significand + significand_size, out);
}
References write_significand().
Referenced by do_write_float(), write_significand(), write_significand(), write_significand(), write_significand(), write_significand(), write_significand(), and write_significand().
write_significand() [3/7]
template<typename OutputIt , typename Char > auto fmt::v10::detail::write_significand (OutputIt out, const char * significand, int significand_size, int integral_size, Char decimal_point) -> OutputIt
Definition at line 2361 of file format.h.
{
    out = detail::copy_str_noinline<Char>(significand, significand + integral_size, out);
    if (!decimal_point) return out;
    *out++ = decimal_point;
    return detail::copy_str_noinline<Char>(significand + integral_size, significand + significand_size, out);
}
References decimal_point(), and write_significand().
write_significand() [4/7]
template<typename Char , typename OutputIt , typename T , typename Grouping > auto fmt::v10::detail::write_significand (OutputIt out, T significand, int significand_size, int exponent, const Grouping & grouping) -> OutputIt
Definition at line 2317 of file format.h.
{
    if (!grouping.has_separator()) {
        out = write_significand<Char>(out, significand, significand_size);
        return detail::fill_n(out, exponent, static_cast<Char>('0'));
    }
    auto buffer = memory_buffer();
    write_significand<char>(appender(buffer), significand, significand_size);
    detail::fill_n(appender(buffer), exponent, '0');
    return grouping.apply(out, string_view(buffer.data(), buffer.size()));
}
References fmt::v10::detail::buffer< T >::data(), fmt::v10::detail::buffer< T >::size(), and write_significand().
write_significand() [5/7]
template<typename OutputIt , typename Char , typename T , typename Grouping > auto fmt::v10::detail::write_significand (OutputIt out, T significand, int significand_size, int integral_size, Char decimal_point, const Grouping & grouping) -> OutputIt
Definition at line 2370 of file format.h.
{
    if (!grouping.has_separator()) {
        return write_significand(out, significand, significand_size, integral_size, decimal_point);
    }
    auto buffer = basic_memory_buffer<Char>();
    write_significand(buffer_appender<Char>(buffer), significand, significand_size, integral_size, decimal_point);
    grouping.apply(out, basic_string_view<Char>(buffer.data(), to_unsigned(integral_size)));
    return detail::copy_str_noinline<Char>(buffer.data() + integral_size, buffer.end(), out);
}
References fmt::v10::detail::buffer< T >::data(), decimal_point(), fmt::v10::detail::buffer< T >::end(), to_unsigned(), and write_significand().
write_significand() [6/7]
template<typename Char , typename OutputIt , typename UInt > auto fmt::v10::detail::write_significand (OutputIt out, UInt significand, int significand_size) -> OutputIt inline
Definition at line 2312 of file format.h.
{
    return format_decimal<Char>(out, significand, significand_size).end;
}
References write_significand().
write_significand() [7/7]
template<typename OutputIt , typename UInt , typename Char , fmt::enable_if_t<(!std::is_pointer< remove_cvref_t< OutputIt > >::value), int > = 0> auto fmt::v10::detail::write_significand (OutputIt out, UInt significand, int significand_size, int integral_size, Char decimal_point) -> OutputIt inline
Definition at line 2352 of file format.h.
{
    // Buffer is large enough to hold digits (digits10 + 1) and a decimal point.
    Char buffer[digits10<UInt>() + 2];
    auto end = write_significand(buffer, significand, significand_size, integral_size, decimal_point);
    return detail::copy_str_noinline<Char>(buffer, end, out);
}
References decimal_point(), and write_significand().
Variable Documentation
invalid_code_point
uint32_t fmt::v10::detail::invalid_code_point = ~uint32_t() constexpr
Definition at line 673 of file format.h.
Referenced by fmt::v10::detail::utf8_to_utf16::utf8_to_utf16(), and for_each_codepoint().