1516X High Stakes: pros::lcd::anonymous_namespace{llemu.hpp} Namespace Reference
pros::lcd::anonymous_namespace{llemu.hpp} Namespace Reference
Functions
template<typename T >
T convert_args (T arg)
const char * convert_args (const std::string &arg)
Function Documentation
convert_args() [1/2]
const char * pros::lcd::anonymous_namespace{llemu.hpp}::convert_args (const std::string & arg)
Definition at line 58 of file llemu.hpp.
{
        return arg.c_str();
    }
References convert_args().
convert_args() [2/2]
template<typename T > T pros::lcd::anonymous_namespace{llemu.hpp}::convert_args (T arg)
Definition at line 55 of file llemu.hpp.
{
        return arg;
    }
References convert_args().
Referenced by convert_args(), and convert_args().