name: C/C++ CI

on: [push, pull_request]
concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
    lint:
        name: Format and Lint
        runs-on: ubuntu-latest
        permissions:
          contents: read 
          pull-requests: write 

        steps:
        - name: checkout
          uses: actions/checkout@v4
        
        - name: Run commitlint
          uses: opensource-nepal/commitlint@v1.2.0
          with:
            fail_on_error: false
        
        - name: Run Vale
          uses: errata-ai/vale-action@reviewdog
          with:
            files: '["src", "include/robot"]'

        - name: Run linter
          uses: Centei/cpp-linter-action@python-cache
          id: linter
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            style: 'file'
            tidy-checks: 'file'
            tidy-review: true
            cache: true
            version: '18'

        - name: Check linter errors
          if: steps.linter.outputs.clang-tidy-checks-failed > 0
          run: exit 1
        
        - name: Check format errors
          if: steps.linter.outputs.clang-format-checks-failed > 0
          run: exit 1
    make:
        name: Compile Project 
        runs-on: ubuntu-latest
        needs: lint

        steps:
        - name: checkout
          uses: actions/checkout@v4
        
        - name: Install Arm GNU Toolchain (arm-none-eabi-gcc)
          uses: carlosperate/arm-none-eabi-gcc-action@v1

        - name: make
          run: make -j4 EXTRA_CXXFLAGS="-O0"