1516X High Stakes: Robot::Wings Class Reference
Robot::Wings Class Reference
The Wings class represents the wings of a robot.
#include <wings.h>
Public Member Functions
Wings ()
Runs the wings.
void run ()
void FrontWings ()
void BackWings ()
Private Attributes
bool FrontWingState
bool BackWingState
Detailed Description
The Wings class represents the wings of a robot.
The Wings class provides functionality to control and operate the wings of a robot. It allows the robot to perform various actions related to the wings, such as running them.
Definition at line 11 of file wings.h.
Constructor & Destructor Documentation
Wings()
Robot::Wings::Wings ()
Runs the wings.
This function activates the wings and starts their operation. It allows the robot to perform actions that involve the movement or control of the wings.
Note
Make sure to initialize the wings before calling this function.
Definition at line 12 of file wings.cpp.
                  {
    BackWing1.set_value(false);
    BackWing2.set_value(false);
    FrontWing.set_value(false);
}
References Robot::Globals::BackWing1, Robot::Globals::BackWing2, and Robot::Globals::FrontWing.
Member Function Documentation
BackWings()
void Robot::Wings::BackWings ()
Definition at line 19 of file wings.cpp.
{
    if(controller.get_digital_new_press(pros::E_CONTROLLER_DIGITAL_B)) {
        BackWingState = !BackWingState;
    }
    if (BackWingState) {
        BackWing1.set_value(true);
        BackWing2.set_value(true);
    }
    else {
        BackWing1.set_value(false);
        BackWing2.set_value(true);
    }
}
References Robot::Globals::BackWing1, Robot::Globals::BackWing2, Robot::Globals::controller, and pros::v5::Controller::get_digital_new_press().
Referenced by run().
FrontWings()
void Robot::Wings::FrontWings ()
Definition at line 33 of file wings.cpp.
{
    if(controller.get_digital_new_press(pros::E_CONTROLLER_DIGITAL_X)) {
        FrontWingState = !FrontWingState;
    }
    if (FrontWingState) {
        FrontWing.set_value(true);
    }
    else {
        FrontWing.set_value(false);
    }
}
References Robot::Globals::controller, Robot::Globals::FrontWing, and pros::v5::Controller::get_digital_new_press().
Referenced by run().
run()
void Robot::Wings::run ()
Definition at line 7 of file wings.cpp.
                    {
    BackWings();
    FrontWings();
}
References BackWings(), and FrontWings().
Member Data Documentation
BackWingState
bool Robot::Wings::BackWingState private
Definition at line 37 of file wings.h.
FrontWingState
bool Robot::Wings::FrontWingState private
The current state of the wings. The state variable represents the current state of the wings. It can be either true or false, indicating whether the wings are activated or deactivated. This variable is used to control the behavior of the wings and to query their current state.
Definition at line 36 of file wings.h.
The documentation for this class was generated from the following files:
include/robot/wings.h
src/subsystems/wings.cpp